objects/Account.object
<CustomObject>
    <fields>
        <fullName>ClientNumber__c</fullName>
        <externalId>true</externalId>
        <label>Client #</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>ActiveMilitary__c</fullName>
        <description>HUD-Defined Activity Military?</description>
        <label>Active Military</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ActiveMilitary</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ClientCaseClosedDate__c</fullName>
        <description>Date the case is closed</description>
        <label>Client Case Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ClientCaseStatus__c</fullName>
        <defaultValue>(&quot;In Progress&quot;)</defaultValue>
        <description>In Progress: Open Case that is in progress and HUD reportable

Closed - Incomplete: Case closed without meeting the original outcome, HUD reportable

Closed - Service Complete: Case closed with meeting the original outcome, HUD reportable

On Hold: Case temporarily paused due to external factors or client request</description>
        <inlineHelpText>[1] In Progress: Case pending

[2] Closed - Incomplete: Didn’t meet original outcome

[3] Closed - Complete: Met the outcome

[4] On Hold: Case temporarily paused</inlineHelpText>
        <label>Client Case Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Closed - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Closed - Complete</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                    <isActive>false</isActive>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <isActive>false</isActive>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <isActive>false</isActive>
                    <label>Prospect</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClientNumber__c</fullName>
        <description>Client Number pulled from Household</description>
        <formula>Household__r.ClientNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <description>HUD-Defined Ethnicity</description>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>FormalPartneringOrgProvidedService__c</fullName>
        <inlineHelpText>A formal partner can be a NeighborWorks Network Organization or non-network organization that has a formal Memorandum of Understanding (MOU). Sending a client to a lender is not considered a formal partnership and does not require the MOU.</inlineHelpText>
        <label>Formal Partnering Org Provided Service</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>HUD-Defined Gender</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>HUD-Defined Number in Household</description>
        <inlineHelpText>Total number of people living in the same household as the primary client</inlineHelpText>
        <label>Household Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Household__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Primary Client&apos;s Household</description>
        <label>Household</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NWOProvidedCounselingEducation__c</fullName>
        <label>NWO Provided Counseling/Education</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NWOProvidedLendingServices__c</fullName>
        <label>NWO Provided Lending Services</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NWORole__c</fullName>
        <label>NWO Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NWO Constructs New Unit for New Home Owner</fullName>
                </value>
                <value>
                    <fullName>NWO Sells a Unit it Had Purchased (with or without rehab) to New Home Owner</fullName>
                </value>
                <value>
                    <fullName>Directly provides Self-Help Housing for New Home Owner</fullName>
                </value>
                <value>
                    <fullName>Plays Intermediary role in providing Self-Help Housing for New Home Owner</fullName>
                </value>
                <value>
                    <fullName>Counselor and/or Broker/Lender ONLY for New Home Owner</fullName>
                </value>
                <value>
                    <fullName>NWO Provides Services to an Existing Home Owner</fullName>
                </value>
                <value>
                    <fullName>Foreclosure Mitigation Counseling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PrimaryClient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProvideRealEstateAgentServices__c</fullName>
        <inlineHelpText>Did your organization provide Real Estate Agent Services (listing agent and/or buyer&apos;s agent)?</inlineHelpText>
        <label>Provide Real Estate Agent Services?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>NWORole__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <description>HUD-Defined Race</description>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RehabConstCostNotincinPrice__c</fullName>
        <label>Rehab/Const Cost Not inc in Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RehabConstrCostsincinPrice__c</fullName>
        <label>Rehab/Constr Costs inc in Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ServicesProvidedToExistingHomeOwner__c</fullName>
        <label>Services Provided to Existing Home Owner</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>NWORole__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Rehab</fullName>
                </value>
                <value>
                    <fullName>Refinance not foreclosure</fullName>
                </value>
                <value>
                    <fullName>Reverse mortgage</fullName>
                </value>
                <value>
                    <fullName>Replacement</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Veteran__c</fullName>
        <description>HUD-Defined Veteran</description>
        <label>Veteran</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Veteran</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>X1stTimeHomeBuyer__c</fullName>
        <description>HUD-Defined 1st Time Homebuyer</description>
        <inlineHelpText>Must not have owned a home within the last 3 years.</inlineHelpText>
        <label>1st Time Home Buyer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>X1stTimeHomeBuyer</valueSetName>
        </valueSet>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <recordTypes>
        <fullName>FinancialCapabilityCounseling</fullName>
        <active>true</active>
        <label>Financial Capability Counseling</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ActiveMilitary__c</fullName>
        <description>Yes, No, Not Applicable</description>
        <label>Active Military</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ActiveMilitary</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Age__c</fullName>
        <formula>YEAR(TODAY()) - YEAR(Birthdate) - IF(MONTH(TODAY()) * 100 + DAY(TODAY()) &lt; MONTH(Birthdate) * 100 + DAY(Birthdate), 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <description>Client’s self-identified ethnicity, used in 9902 reporting</description>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Male, Female, Other/Non-Conforming</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>Number of people in the household</description>
        <inlineHelpText>Total number of people living in the same household</inlineHelpText>
        <label>Household Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <description>Which HUD 9902-recognized race category the contact belongs to.</description>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Veteran__c</fullName>
        <description>Yes, No, Not Applicable</description>
        <label>Veteran</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Veteran</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>X1stTimeHomeBuyer__c</fullName>
        <description>Yes, No</description>
        <inlineHelpText>Must not have owned a home within the last 3 years.</inlineHelpText>
        <label>1st Time Home Buyer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>X1stTimeHomeBuyer</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Grant__c.object
<CustomObject>
    <fields>
        <fullName>ClientCase__c</fullName>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Grant</label>
    <nameField>
        <displayFormat>G- {YYYY}/{MM} - {0000}</displayFormat>
        <label>Grant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/ActiveMilitary.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>Not available</fullName>
    </customValue>
    <masterLabel>Active Military?</masterLabel>
</GlobalValueSet>

globalValueSets/Ethnicity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Not Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Ethnicity</description>
    <masterLabel>Ethnicity</masterLabel>
</GlobalValueSet>

globalValueSets/Gender.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <customValue>
        <fullName>Other/Non-conforming</fullName>
    </customValue>
    <description>Gender</description>
    <masterLabel>Gender</masterLabel>
</GlobalValueSet>

globalValueSets/Race.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>American Indian/Alaskan Native</fullName>
    </customValue>
    <customValue>
        <fullName>Asian</fullName>
    </customValue>
    <customValue>
        <fullName>Black or African American</fullName>
    </customValue>
    <customValue>
        <fullName>Native Hawaiian or Other Pacific Islander</fullName>
    </customValue>
    <customValue>
        <fullName>White</fullName>
    </customValue>
    <customValue>
        <fullName>More than one race</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Race</description>
    <masterLabel>Race</masterLabel>
</GlobalValueSet>

globalValueSets/Veteran.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>Not available</fullName>
    </customValue>
    <masterLabel>Veteran?</masterLabel>
</GlobalValueSet>

globalValueSets/X1stTimeHomeBuyer.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>Not available</fullName>
    </customValue>
    <masterLabel>1st Time Home Buyer?</masterLabel>
</GlobalValueSet>

classes/NWQRClientsReportControllerTest.cls
@isTest
public class NWQRClientsReportControllerTest {
    //test
    @testSetup
    static void setupTestData() {
        TestDataFactory.createAutomationBypassCS(true);
        string NWC2NameSpace = Utility.getNwc2NameSpace();
        string objectName = NWC2NameSpace + 'ClientCase__c';

        // Create test data for the ClientCase__c object
        RecordType rt = [SELECT Id FROM RecordType WHERE DeveloperName = 'FinancialCapabilityCounseling' AND SObjectType =: objectName  LIMIT 1];

        Account acc = TestDataFactory.createAccounts(1, false)[0];
        acc.ClientNumber__c = '1234';
        insert acc;
        Contact con = TestDataFactory.createContacts(acc.Id, 1, true)[0];
        ClientCase__c case1 = TestDataFactory.createClientCases(1,false)[0];
		case1.ClientCaseClosedDate__c = Date.today().addDays(-1);       
      	case1.ClientCaseClosedDate__c = Date.today().addDays(-1);
        case1.ClientCaseStatus__c = 'Closed - Complete';
        case1.Household__c = acc.Id;
        case1.PrimaryClient__c = con.Id;
        case1.NWORole__c = 'NWO Constructs New Unit for New Home Owner';
        case1.ServicesProvidedToExistingHomeOwner__c = 'Not Applicable';
        case1.NWOProvidedLendingServices__c = 'Yes';
        case1.NWOProvidedCounselingEducation__c = 'Yes';
        case1.FormalPartneringOrgProvidedService__c = 'Yes';
        case1.ProvideRealEstateAgentServices__c = 'Yes';
        case1.Age__c = 10;
        case1.Gender__c = 'Male';
        case1.Race__c = 'Asian';
        case1.Ethnicity__c = 'Hispanic';
        case1.X1stTimeHomeBuyer__c = 'Yes';
        case1.Veteran__c = 'Yes';
        case1.RehabConstCostNotIncInPrice__c = 1000;
        case1.RehabConstrCostsincinPrice__c = 1000;
        case1.ActiveMilitary__c = 'Yes';
        case1.HouseholdSize__c = 2;
        case1.CounselingTermination__c = 'Completed';
        insert case1;
        Grant__c grant = new Grant__c();
        grant.FundingType__c = 'CDBG';
        grant.FundingSource__c = 'Government (Federal/State/Local)';
        grant.ClientCase__c = case1.Id;
        grant.FundingAmount__c = 100;
        grant.Grantor__c = 'test';
        grant.StatusType__c = 'Approved';
        insert grant;
    }

    @isTest
    static void testgetOrsClientsUniqueList() {
        // Set test dates
        Date qtrStartDate = Date.today().addMonths(-3);
        Date qtrEndDate = Date.today();

        Test.startTest();

        // Call the method to test
        map<string,list<NWQRClientsReportController.OrsReportWrapper>> result = NWQRClientsReportController.getOrsClientsUniqueList(qtrStartDate, qtrEndDate);
        //NWQRClientsReportController.getReportData(qtrStartDate, qtrEndDate);
        Test.stopTest();
		System.debug('### result : '+result.size()); 
        System.assertNotEquals(null, result);
    }
}