objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <label>Household</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ActiveMilitary__c</fullName>
        <description>Yes, No, Not Applicable</description>
        <label>Active Military</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ActiveMilitary</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ColoniasResidence__c</fullName>
        <label>Colonias Residence</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CurrentResidence__c</fullName>
        <description>Own, Rent, Others</description>
        <label>Current Residence</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CurrentResidenceContact</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DisabledStatus__c</fullName>
        <label>Disabled Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <description>Pre-defined list</description>
        <label>Education</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Education</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EnglishProficiency__c</fullName>
        <description>Reflects overall level of English proficiency within the same household as the contact.</description>
        <inlineHelpText>English Proficiency of the primary client</inlineHelpText>
        <label>English Proficiency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Limited_English_Proficiency_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <description>Client’s self-identified ethnicity, used in 9902 reporting</description>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EvaluateHUDAMI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EvaluateHUDAMI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FarmWorker__c</fullName>
        <label>Farm Worker</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HouseholdMonthlyIncome1__c</fullName>
        <label>Household Monthly Income</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>Number of people in the household</description>
        <inlineHelpText>Total number of people living in the same household</inlineHelpText>
        <label>Household Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HouseholdType__c</fullName>
        <label>Household Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MaritalStatus__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>HouseholdTypeHeadofHousehold</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MaritalStatus__c</fullName>
        <description>Pre-defined  list</description>
        <label>Marital Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MaritalStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>NumberOfDependents__c</fullName>
        <label>Number of Dependents</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PreferredLanguage__c</fullName>
        <description>Client’s preferred language</description>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English (US)</label>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>ASL</fullName>
                </value>
                <value>
                    <fullName>Cambodian</fullName>
                </value>
                <value>
                    <fullName>Cantonese</fullName>
                </value>
                <value>
                    <fullName>Chinese Mandarin</fullName>
                </value>
                <value>
                    <fullName>Creole</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Goboligok</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hmong</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latin</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
                <value>
                    <fullName>Portuuguese</fullName>
                </value>
                <value>
                    <fullName>Russian</fullName>
                </value>
                <value>
                    <fullName>Swahili</fullName>
                </value>
                <value>
                    <fullName>Turkish</fullName>
                </value>
                <value>
                    <fullName>Ukrainian</fullName>
                </value>
                <value>
                    <fullName>Urdu</fullName>
                </value>
                <value>
                    <fullName>Vietnamese</fullName>
                </value>
                <value>
                    <fullName>Yiddish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <description>Which HUD 9902-recognized race category the contact belongs to.</description>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RuralAreaStatus__c</fullName>
        <description>Whether or not this contact resides in a rural area as defined by HUD.</description>
        <label>Rural Area Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Rural_Area_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Veteran__c</fullName>
        <description>Yes, No, Not Applicable</description>
        <label>Veteran</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Veteran</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>isInvalidZip__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isInvalidZip</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Intake__c.object
<CustomObject>
    <description>To capture and store initial information about clients/prospects during the intake process including New Intake, New Education Only, and New Emergency Triage.</description>
    <fields>
        <fullName>ActiveMilitary__c</fullName>
        <label>Active Military</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>Not available</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ColoniasResidence__c</fullName>
        <label>Colonias Residence</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CurrentResidence__c</fullName>
        <label>Current Residence</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CurrentResidenceClientCase</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DisabledStatus__c</fullName>
        <label>Disabled Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Education</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EnglishProficiency__c</fullName>
        <description>HUD-Defined English Proficiency</description>
        <inlineHelpText>English Proficiency of the primary client</inlineHelpText>
        <label>English Proficiency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Limited_English_Proficiency_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EvaluateHUDAMI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EvaluateHUDAMI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FarmWorker__c</fullName>
        <label>Farm Worker</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <label>Household Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HouseholdType__c</fullName>
        <label>Household Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MaritalStatus__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>HouseholdTypeHeadofHousehold</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MaritalStatus__c</fullName>
        <label>Marital Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MaritalStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>NumberofDependents__c</fullName>
        <label>Number of Dependents</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RuralAreaStatus__c</fullName>
        <label>Rural Area Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Rural_Area_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Veteran__c</fullName>
        <label>Veteran</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Veteran</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>isInvalidZip__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isInvalidZip</label>
        <type>Checkbox</type>
    </fields>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Intake</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/ActiveMilitary.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>Not available</fullName>
    </customValue>
    <masterLabel>Active Military?</masterLabel>
</GlobalValueSet>

globalValueSets/CurrentResidenceClientCase.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Own</fullName>
    </customValue>
    <customValue>
        <fullName>Rent</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>Current Residence Client Case</masterLabel>
</GlobalValueSet>

globalValueSets/CurrentResidenceContact.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Own</fullName>
    </customValue>
    <customValue>
        <fullName>Rent</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>Current Residence Contact</masterLabel>
</GlobalValueSet>

globalValueSets/Education.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Elementary/Primary</fullName>
    </customValue>
    <customValue>
        <fullName>Junior High School</fullName>
    </customValue>
    <customValue>
        <fullName>High School/GED</fullName>
    </customValue>
    <customValue>
        <fullName>Junior College</fullName>
    </customValue>
    <customValue>
        <fullName>University</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate School</fullName>
    </customValue>
    <customValue>
        <fullName>Vocational</fullName>
    </customValue>
    <customValue>
        <fullName>College</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>High School</fullName>
        <isActive>false</isActive>
        <label>High School</label>
    </customValue>
    <customValue>
        <fullName>Elementary</fullName>
        <isActive>false</isActive>
        <label>Elementary</label>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
        <isActive>false</isActive>
        <label>Unknown</label>
    </customValue>
    <description>Education</description>
    <masterLabel>Education</masterLabel>
</GlobalValueSet>

globalValueSets/Ethnicity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Not Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Ethnicity</description>
    <masterLabel>Ethnicity</masterLabel>
</GlobalValueSet>

globalValueSets/HouseholdTypeHeadofHousehold.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Single adult</fullName>
    </customValue>
    <customValue>
        <fullName>Female-headed single parent household</fullName>
    </customValue>
    <customValue>
        <fullName>Male-headed single parent household</fullName>
    </customValue>
    <customValue>
        <fullName>Married without dependents</fullName>
    </customValue>
    <customValue>
        <fullName>Married with dependents</fullName>
    </customValue>
    <customValue>
        <fullName>Two or more unrelated Adults</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Married with children</fullName>
        <isActive>false</isActive>
        <label>Married with children</label>
    </customValue>
    <customValue>
        <fullName>Male-headed single parent household/Head of Household</fullName>
        <isActive>false</isActive>
        <label>Male-headed single parent household/Head of Household</label>
    </customValue>
    <customValue>
        <fullName>Female-headed single parent household/Head of Household</fullName>
        <isActive>false</isActive>
        <label>Female-headed single parent household/Head of Household</label>
    </customValue>
    <customValue>
        <fullName>Domestic partnership</fullName>
        <isActive>false</isActive>
        <label>Domestic partnership</label>
    </customValue>
    <customValue>
        <fullName>Married without children</fullName>
        <isActive>false</isActive>
        <label>Married without children</label>
    </customValue>
    <masterLabel>Household Type/Head of Household</masterLabel>
</GlobalValueSet>

globalValueSets/Limited_English_Proficiency_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Limited English Proficient</fullName>
    </customValue>
    <customValue>
        <fullName>Not Limited English Proficient</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Limited English Proficiency Status</description>
    <masterLabel>Limited English Proficiency Status</masterLabel>
</GlobalValueSet>

globalValueSets/MaritalStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Married</fullName>
    </customValue>
    <customValue>
        <fullName>Single</fullName>
    </customValue>
    <customValue>
        <fullName>Divorced</fullName>
    </customValue>
    <customValue>
        <fullName>Separated</fullName>
    </customValue>
    <customValue>
        <fullName>Widowed</fullName>
    </customValue>
    <customValue>
        <fullName>Choose not to respond</fullName>
    </customValue>
    <customValue>
        <fullName>Legally Separated</fullName>
        <isActive>false</isActive>
        <label>Legally Separated</label>
    </customValue>
    <masterLabel>Marital Status</masterLabel>
</GlobalValueSet>

globalValueSets/Race.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>American Indian/Alaskan Native</fullName>
    </customValue>
    <customValue>
        <fullName>Asian</fullName>
    </customValue>
    <customValue>
        <fullName>Black or African American</fullName>
    </customValue>
    <customValue>
        <fullName>Native Hawaiian or Other Pacific Islander</fullName>
    </customValue>
    <customValue>
        <fullName>White</fullName>
    </customValue>
    <customValue>
        <fullName>More than one race</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Race</description>
    <masterLabel>Race</masterLabel>
</GlobalValueSet>

globalValueSets/Rural_Area_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Lives in a rural area</fullName>
    </customValue>
    <customValue>
        <fullName>Does not live in a rural area</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Rural Area Status</description>
    <masterLabel>Rural Area Status</masterLabel>
</GlobalValueSet>

globalValueSets/Veteran.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>Not available</fullName>
    </customValue>
    <masterLabel>Veteran?</masterLabel>
</GlobalValueSet>

classes/HUDValidationControllerTest.cls
@IsTest
public class HUDValidationControllerTest {
	@TestSetup
    static void makeData(){
        List<Account> portalAccounts = TestDataFactory.createAccounts(1, false);
        insert portalAccounts;
        
        List<Contact> contacts = TestDataFactory.createContacts(portalAccounts[0].Id, 3, false);
        contacts[0].AccountId = portalAccounts[0].Id;
        contacts[0].LastName = 'Con 1';
        
        contacts[1].LastName = 'Con 2';
        contacts[1].MailingCity = 'JP';
        contacts[1].MailingStateCode = 'CA';
        contacts[1].MailingCountryCode = 'US';
        contacts[1].MailingPostalCode = '12345';
        contacts[1].MaritalStatus__c = 'Single';
        //contacts[1].Education__c = 'None';
        contacts[1].FarmWorker__c = 'NO';
        contacts[1].ColoniasResidence__c = 'NO';
        contacts[1].DisabledStatus__c = 'No';
        contacts[1].NumberOfDependents__c = 1;
        contacts[1].PreferredLanguage__c = 'Hindi';
        contacts[1].isInvalidZip__c = false;
        contacts[1].EvaluateHUDAMI__c = false;
        
        contacts[2].LastName = 'Con 3';
        contacts[2].Race__c = 'American Indian/Alaskan Native';
        contacts[2].Ethnicity__c = 'Hispanic';
        contacts[2].MaritalStatus__c = 'Single';
        //contacts[2].HouseholdType__c = 'Female-headed single parent household';
        contacts[2].HouseholdSize__c = 1;
        contacts[2].ActiveMilitary__c = 'No';
        contacts[2].Veteran__c = 'No';
        contacts[2].RuralAreaStatus__c = 'Lives in a rural area';
        contacts[2].EnglishProficiency__c = 'Limited English Proficient';
        contacts[2].HouseholdMonthlyIncome1__c = 12345;
        contacts[2].CurrentResidence__c = 'Own';
        
        
        insert contacts;
        
        List<Intake__c> intake = TestDataFactory.createIntakes(contacts[0], portalAccounts[0].Id, 1, true);
        
    }
    
    @isTest
    public static void testGetValidationErrors1(){        
        
        List<Contact> contacts = [SELECT Id, AccountId FROM Contact where LastName = 'Con 1' limit 1];
        
        
         
        	Test.startTest();
        
        	String result = HUDValidationController.getValidationErrors('contact', contacts[0].Id);
            System.assertNotEquals(NULL, result);
        
        Test.stopTest();
        //System.assertEquals(true, isReset);
    }
    
    @isTest
    public static void testGetValidationErrors2(){        
        
        List<Contact> contacts = [SELECT Id, AccountId FROM Contact where LastName = 'Con 2' limit 1];
        
        
         
        	Test.startTest();
        
        	String result = HUDValidationController.getValidationErrors('contact', contacts[0].Id);
            System.assertNotEquals(NULL, result);
        
        Test.stopTest();
        //System.assertEquals(true, isReset);
    }
    
    @isTest
    public static void testGetValidationErrors3(){        
        
        List<Contact> contacts = [SELECT Id, AccountId FROM Contact where LastName = 'Con 3' limit 1];
        
        
         
        	Test.startTest();
        
        	String result = HUDValidationController.getValidationErrors('contact', contacts[0].Id);
            System.assertNotEquals(NULL, result);
        
        Test.stopTest();
        //System.assertEquals(true, isReset);
    }
    
    @isTest
    public static void testGetValidationErrors4(){        
        
        List<Intake__c> intake = [SELECT Id FROM Intake__c limit 1];
        
        
         
        	Test.startTest();
        
        	String result = HUDValidationController.getValidationErrors('Intake__c', intake[0].Id);
            System.assertNotEquals(NULL, result);
        
        Test.stopTest();
        //System.assertEquals(true, isReset);
    }
}