objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <label>Household</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>ClientCaseStatus__c</fullName>
        <defaultValue>(&quot;In Progress&quot;)</defaultValue>
        <description>In Progress: Open Case that is in progress and HUD reportable

Closed - Incomplete: Case closed without meeting the original outcome, HUD reportable

Closed - Service Complete: Case closed with meeting the original outcome, HUD reportable

On Hold: Case temporarily paused due to external factors or client request</description>
        <inlineHelpText>[1] In Progress: Case pending

[2] Closed - Incomplete: Didn’t meet original outcome

[3] Closed - Complete: Met the outcome

[4] On Hold: Case temporarily paused</inlineHelpText>
        <label>Client Case Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Closed - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Closed - Complete</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                    <isActive>false</isActive>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <isActive>false</isActive>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <isActive>false</isActive>
                    <label>Prospect</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HouseholdMonthlyIncome1__c</fullName>
        <label>Household Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>HUD-Defined Number in Household</description>
        <inlineHelpText>Total number of people living in the same household as the primary client</inlineHelpText>
        <label>Household Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MetropolitanStatisticalArea__c</fullName>
        <label>Metropolitan Statistical Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>HouseholdMonthlyIncome1__c</fullName>
        <label>Household Monthly Income</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>Number of people in the household</description>
        <inlineHelpText>Total number of people living in the same household</inlineHelpText>
        <label>Household Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MetropolitanStatisticalArea__c</fullName>
        <label>Metropolitan Statistical Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/HUDAMIData__c.object
<CustomObject>
    <description>To store data related to Area Median Income (AMI) for various regions, including details such as area names, county names, FIPS codes, and HUD-specific identifiers for HUD AMI calculations.</description>
    <fields>
        <fullName>Areaname__c</fullName>
        <description>HUD Income Limit Area Name</description>
        <label>Area name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CountyName__c</fullName>
        <description>HUD Income Limit - Official County Name</description>
        <label>County Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MedianFamilyIncome__c</fullName>
        <description>Median Family Income (MFI) for area</description>
        <label>Median Family Income</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TownName__c</fullName>
        <description>Town Name for Income Limit purposes</description>
        <label>Town Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zipcode__c</fullName>
        <label>Zipcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p1__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 1 Persons in Household</description>
        <label>il30 p1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p2__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 2 Persons in Household</description>
        <label>il30 p2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p3__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 3 Persons in Household</description>
        <label>il30 p3</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p4__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 4 Persons in Household</description>
        <label>il30 p4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p1__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 1 Persons in Household</description>
        <label>il50 p1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p2__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 2 Persons in Household</description>
        <label>il50 p2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p3__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 3 Persons in Household</description>
        <label>il50 p3</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p4__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 4 Persons in Household</description>
        <label>il50 p4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p1__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 1 Persons in Household</description>
        <label>il80 p1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p2__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 2 Persons in Household</description>
        <label>il80 p2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p3__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 3 Persons in Household</description>
        <label>il80 p3</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p4__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 4 Persons in Household</description>
        <label>il80 p4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il_metro_name__c</fullName>
        <label>Metro Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>HUD AMI Data</label>
    <nameField>
        <label>HUD AMI Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HUD AMI Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Intake__c.object
<CustomObject>
    <description>To capture and store initial information about clients/prospects during the intake process including New Intake, New Education Only, and New Emergency Triage.</description>
    <fields>
        <fullName>HouseholdMonthlyIncome__c</fullName>
        <label>Household Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <label>Household Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MetropolitanStatisticalArea__c</fullName>
        <label>Metropolitan Statistical Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Intake</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HUDAmiLookupControllerTest.cls
@isTest
public class HUDAmiLookupControllerTest {
    static string NWC2NameSpace = Utility.getNwc2NameSpace();
    @testSetup
    static void setupTestData() {
        
        Account acc = TestDataFactory.createAccounts(1, false)[0];
        Contact contactRecord = TestDataFactory.createContacts(acc.Id, 1, false)[0];
        contactRecord.FirstName = 'Test';
        contactRecord.LastName = 'Test';
        contactRecord.Email = 'tommy@dummy.com';
        contactRecord.HouseholdSize__c = 9;
        contactRecord.MailingPostalCode = '12345';
        contactRecord.HouseholdMonthlyIncome1__c = 4000;
        contactRecord.MetropolitanStatisticalArea__c = 'Some MSA';
        insert contactRecord;
        
        Intake__c intakeRecord = TestDataFactory.createIntakes(contactRecord, acc.Id, 1, false)[0];
        intakeRecord.HouseholdSize__c = 9;
        intakeRecord.Address__PostalCode__s = '12345';
        intakeRecord.HouseholdMonthlyIncome__c = 4000;
        intakeRecord.MetropolitanStatisticalArea__c = 'Some MSA';
        insert intakeRecord;
        
        ClientCase__c clientCaseRecord = TestDataFactory.createClientCases(1, false)[0];
        clientCaseRecord.HouseholdSize__c = 9;
        clientCaseRecord.Address__PostalCode__s = '12345';
        clientCaseRecord.HouseholdMonthlyIncome1__c = 4000;
        clientCaseRecord.MetropolitanStatisticalArea__c = 'Some MSA';
        clientCaseRecord.ClientCaseStatus__c = 'In Progress';
        insert clientCaseRecord;
        
        HUDAMIData__c hudamiData = TestDataFactory.createHUDAMIDataRecords(1, false)[0];
        hudamiData.Zipcode__c = '12345';
        hudamiData.CountyName__c = 'Some County';
        hudamiData.TownName__c = 'Some Town';
        hudamiData.MedianFamilyIncome__c = '60000';
        hudamiData.il_metro_name__c = 'SampleMetro';
        hudamiData.Areaname__c = 'SampleArea';
        hudamiData.il30p1__c = '20000';
        hudamiData.il30p2__c = '25000';
        hudamiData.il30p3__c = '30000';
        hudamiData.il50p1__c = '40000';
        hudamiData.il50p2__c = '45000';
        hudamiData.il50p3__c = '50000';
        hudamiData.il80p1__c = '60000';
        hudamiData.il80p2__c = '65000';
        hudamiData.il80p3__c = '70000';
        hudamiData.il30p4__c = '50000';
        hudamiData.il50p4__c = '60000';
        hudamiData.il80p4__c = '70000';
        insert hudamiData;
        
    }
    
    @isTest
    static void testValidAMI() {
        // Fetch a record to test
        Intake__c intakeRecord = [SELECT Id FROM Intake__c LIMIT 1];
        
        // Test validAMI method
        Test.startTest();
        Boolean result = HUDAmiLookupController.validAMI(intakeRecord.Id, NWC2NameSpace+'Intake__c');
        Test.stopTest();
        
    }
    
    @isTest
    static void testGetRecord() {
        // Fetch a record to test
        Intake__c intakeRecord = [SELECT Id FROM Intake__c LIMIT 1];
        
        // Test getRecord method
        Test.startTest();
        SObject result = HUDAmiLookupController.getRecord(intakeRecord.Id, NWC2NameSpace+'Intake__c');
        Test.stopTest();
    }
    
    @isTest
    static void testGetHudAmiUniqueCounty() {
        // Fetch a record to test
        Intake__c intakeRecord = [SELECT Id FROM Intake__c LIMIT 1];
        ClientCase__c clientCaseRecord = [SELECT Id FROM ClientCase__c LIMIT 1];
        // Test getHudAmiUniqueCounty method
        Test.startTest();
        List<String> result = HUDAmiLookupController.getHudAmiUniqueCounty(intakeRecord.Id, NWC2NameSpace+'Intake__c');
        HUDAmiLookupController.getHudAmiUniqueCounty(clientCaseRecord.Id, NWC2NameSpace+'ClientCase__c');
        Test.stopTest();
        
        System.assert(result != null && result.size() > 0, 'The list of unique counties should be retrieved successfully.');
    }
    
    @isTest
    static void testGetHudAmiUniqueTowns() {
        // Fetch a record to test
        Intake__c intakeRecord = [SELECT Id FROM Intake__c LIMIT 1];
        
        // Test getHudAmiUniqueTowns method
        Test.startTest();
        List<HUDAMIData__c> result = HUDAmiLookupController.getHudAmiUniquetowns(intakeRecord.Id, NWC2NameSpace+'Intake__c', 'Some County');
        Test.stopTest();
        
        System.assert(result != null && result.size() > 0, 'The list of unique towns should be retrieved successfully.');
    }
    
    @isTest
    static void testCalculateAMIandCommit() {
        // Fetch records to test
        Intake__c intakeRecord = [SELECT Id FROM Intake__c LIMIT 1];
        HUDAMIData__c hudamiData = [SELECT Id FROM HUDAMIData__c LIMIT 1];
        
        // Test calculateAMIandCommit method
        Test.startTest();
        HUDAmiLookupController.calculateAMIandCommit(intakeRecord.Id, hudamiData.Id, NWC2NameSpace+'Intake__c');
        Test.stopTest();
        
    }
    
    @isTest
    static void testCalculateHouseholdAMI() {
        // Test calculateHouseholdAMI method
        Decimal hhsize = 4;
        Decimal annualIncome = 50000;
        Decimal averageIlincome = 60000;
        
        Decimal result = HUDAmiLookupController.calculateHouseholdAMI(hhsize, annualIncome, averageIlincome);
        
        System.assert(result != null, 'The household AMI should be calculated successfully.');
    }
    
    @isTest
    static void testGetPicklistValOnHami() {
        // Test getpicklistvalonHami method
        Decimal hhami = 50;
        
        String result = HUDAmiLookupController.getpicklistvalonHami(hhami);
    }
    
    @isTest
    static void testRoundUpToFifty() {
        // Test roundUptofifty method
        Integer modvalue = 20;
        Decimal halfincome = 100;
        
        Decimal result = HUDAmiLookupController.roundUptofifty(modvalue, halfincome);
        
        System.assert(result == 130, 'The value should be rounded up to the nearest fifty.');
    }
    
    @isTest
    static void testRoundDownToFifty() {
        // Test rounddowntofifty method
        Integer modvalue = 20;
        Decimal halfincome = 120;
        
        Decimal result = HUDAmiLookupController.rounddowntofifty(modvalue, halfincome);
        
        System.assert(result == 100, 'The value should be rounded down to the nearest fifty.');
    }
    
    @isTest
    static void TestAll() {
        HUDAmiLookupController.getpicklistvalonHami(25);
        HUDAmiLookupController.getpicklistvalonHami(35);
        HUDAmiLookupController.getpicklistvalonHami(60);
        HUDAmiLookupController.getpicklistvalonHami(90);
        HUDAmiLookupController.getpicklistvalonHami(200);
        HUDAmiLookupController.getpicklistvalonHami(-10);
        
        HUDAmiLookupController.calculateHouseholdAMI(1,1500,2500);
        HUDAmiLookupController.calculateHouseholdAMI(2,1500,2500);
        HUDAmiLookupController.calculateHouseholdAMI(3,1500,2500);
        HUDAmiLookupController.calculateHouseholdAMI(4,1500,2500);
        HUDAmiLookupController.calculateHouseholdAMI(5,1500,2500);
        
        
        
        
        HUDAMIData__c hudamiData = [SELECT id FROM HUDAMIData__c LIMIT 1];
        Contact contactRecord = [SELECT id FROM Contact LIMIT 1];
        HUDAmiLookupController.getRecord(contactRecord.id , 'Contact');
        ClientCase__c clientCaseRecord = [SELECT id FROM ClientCase__c LIMIT 1];
        
        string objectName = NWC2NameSpace + 'ClientCase__c';
        HUDAmiLookupController.getRecord(clientCaseRecord.id , objectName);
        
        
        /*  HUDAMIData__c hudamiData2 = new HUDAMIData__c(
Zipcode__c = '12345',
CountyName__c = 'Some County',
TownName__c = 'Some Town',
MedianFamilyIncome__c = '60000',
il50p4__c = '60000'
);
insert hudamiData;*/
        
        HUDAmiLookupController.calculateAMIandCommit(contactRecord.id, hudamiData.id, 'Contact');
        HUDAmiLookupController.calculateAMIandCommit(clientCaseRecord.id, hudamiData.id, objectName);
        
    }
}