objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Organization</fullName>
        <active>true</active>
        <label>Organization</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Referral_Type__c</fullName>
        <formula>TEXT(Account.Type_of_Referral_Organization_Agency__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Referral Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Speciality__c</fullName>
        <label>Speciality</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>Home Insurance</fullName>
                </value>
                <value>
                    <fullName>Retail Banking</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Affiliate</fullName>
        <active>true</active>
        <label>Affiliate</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Referral__c.object
<CustomObject>
    <description>To store referral information, including details of referrals made to other agencies or services for additional support.</description>
    <label>Referral</label>
    <nameField>
        <label>Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateReferralController.cls
public class CreateReferralController {
    @AuraEnabled(cacheable=true)
    public static List<Contact> getReferrals(){ 
        return [SELECT Id, Name,AccountId,Speciality__c, Account.Name,Account.BillingAddress, Account_Referral_Type__c,Email,  Phone  
            FROM Contact WHERE Account.RecordType.Name = 'Organization' and RecordType.Name = 'Affiliate'];
    }

    @AuraEnabled()
    public static List<Referral__c> insertReferrals(List<Referral__c> referrals){
        insert referrals;
        return referrals;
    }
}