objects/Activity.object
<CustomObject>
    <fields>
        <fullName>ActionType__c</fullName>
        <label>Action Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client Action</fullName>
                </value>
                <value>
                    <fullName>Counselor Action</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution</label>
        <referenceTo>Solution__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ClientActionPlan__c.object
<CustomObject>
    <description>To store detailed action plans for clients, outlining goals, obstacles, both client actions and counselor actions to achieve desired outcomes.</description>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Client Action Plans</relationshipLabel>
        <relationshipName>ClientActionPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Action Plan</label>
    <nameField>
        <displayFormat>AP-{00000000}</displayFormat>
        <label>Client Action Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>CreditScore__c</fullName>
        <label>Credit Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HousingExpense__c</fullName>
        <label>Housing Expense</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/FinancialSnapshot__c.object
<CustomObject>
    <description>To store a detailed snapshot of a client&apos;s financial status, including current values and goals.</description>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Financial Snapshots</relationshipLabel>
        <relationshipName>FinancialSnapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CoAppCreditScore__c</fullName>
        <label>Co-App Credit Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CreditScore__c</fullName>
        <label>Median Credit Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CurrentMonthlyDebtObligation__c</fullName>
        <label>Current Household Monthly Creditor Debt</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GrossMonthlyIncome__c</fullName>
        <label>Gross Household Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HousingExpense__c</fullName>
        <label>Housing Expense</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Savings__c</fullName>
        <label>Current Savings</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalAssets__c</fullName>
        <label>Total Assets</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalDebt__c</fullName>
        <label>Total Household Debt</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Snapshot</label>
    <nameField>
        <label>Financial Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Goal__c.object
<CustomObject>
    <description>To store goals set for clients as part of their action plans, detailing specific objectives to be achieved.</description>
    <fields>
        <fullName>ClientActionPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Action Plan</label>
        <referenceTo>ClientActionPlan__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DueDate__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GoalDetails__c</fullName>
        <label>Goal Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>GoalSubject__c</fullName>
        <label>Goal Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GoalType__c</fullName>
        <label>Goal Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Short Term</fullName>
                </value>
                <value>
                    <fullName>Medium Term</fullName>
                </value>
                <value>
                    <fullName>Long Term</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Goal</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Obstacle__c.object
<CustomObject>
    <description>To store obstacles identified in client action plans, highlighting challenges that may impede progress towards goals.</description>
    <fields>
        <fullName>ClientActionPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Action Plan</label>
        <referenceTo>ClientActionPlan__c</referenceTo>
        <relationshipLabel>Obstacles</relationshipLabel>
        <relationshipName>Obstacles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Obstacles</relationshipLabel>
        <relationshipName>Obstacles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DueDate__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Obstacles</relationshipLabel>
        <relationshipName>Obstacles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ObstacleDetails__c</fullName>
        <label>Obstacle Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ObstacleSubject__c</fullName>
        <label>Obstacle Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Obstacle</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Obstacles Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Obstacles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Solution__c.object
<CustomObject>
    <description>To store solutions identified in action plans, detailing strategies and actions to overcome obstacles and achieve goals.</description>
    <fields>
        <fullName>ClientActionPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Action Plan</label>
        <referenceTo>ClientActionPlan__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Obstacle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obstacle</label>
        <referenceTo>Obstacle__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SolutionDetails__c</fullName>
        <label>Solution Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SolutionSubject__c</fullName>
        <label>Solution Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Solution</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Solution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ClientActionPlansControllerTest.cls
/**
* @description    : Test Class for ClientActionPlansController
**/
@IsTest
public class ClientActionPlansControllerTest {
    
    /*
@description    Test method for getGoalsForClientCase
*/
    @testSetup
    private static void testGetGoalsForClientCase1(){
        ClientCase__c clCase = TestDataFactory.createClientCases(1, true)[0];
        
        ClientActionPlan__c  cap = new ClientActionPlan__c ();
        cap.ClientCase__c = clCase.Id;
        insert cap;
        
        Goal__c goal = new Goal__c();
        goal.ClientCase__c = clCase.Id;
        goal.ClientActionPlan__c = cap.Id;
        goal.GoalSubject__c = 'Buy a house';
        goal.GoalDetails__c = 'test details';
        goal.GoalType__c = 'Short Term';
        goal.Status__c = 'Not Started';
        goal.DueDate__c = System.today();
        
        insert goal;
        TestDataFactory.createFinancialSnapshots(clCase.Id , 3, true);
        List<Obstacle__c> obsList = new List<Obstacle__c>();
        
        Obstacle__c obs1 = new Obstacle__c();
        obs1.Goal__c = goal.Id;
        obs1.ObstacleSubject__c = 'Buy a house';
        obs1.ObstacleDetails__c = 'test details';
        obs1.DueDate__c = System.today();
        obsList.add(obs1);
        
        Obstacle__c obs2 = new Obstacle__c();
        obs2.Goal__c = goal.Id;
        obs2.ObstacleSubject__c = 'Lack of opportunity';
        obs2.ObstacleDetails__c = 'test details';
        obs2.DueDate__c = System.today();
        obsList.add(obs2);
        
        insert obsList;
        
        Solution__c sol = new Solution__c();
        sol.Obstacle__c = obs1.Id;
        sol.SolutionSubject__c = 'Increase income';
        sol.SolutionDetails__c = 'test details';
        sol.Status__c = 'Not Started';
        
        insert sol;
        
        List<Task> taskList = new List<Task>();
        
        Task clientTask = new Task();
        clientTask.ActionType__c = 'Client Action';
        clientTask.Subject = 'test sub';
        clientTask.Description = 'test sub';
        clientTask.Status = 'Not Started';
        clientTask.ActivityDate = System.today();
        clientTask.WhatId = sol.Id;
        taskList.add(clientTask);
        
        Task counselorTask = new Task();
        counselorTask.ActionType__c = 'Counselor Action';
        counselorTask.Subject = 'test sub';
        counselorTask.Description = 'test sub';
        counselorTask.Status = 'Completed';
        counselorTask.ActivityDate = System.today();
        counselorTask.WhatId = sol.Id;
        taskList.add(counselorTask);
        
        insert taskList;
        
        ClientActionPlansController.ClientActionPlanWrapper result = ClientActionPlansController.getGoalsForClientCase(clCase.Id);
        
        System.assertNotEquals(null, result);
        System.assertNotEquals(null, result.actionPlans);
        System.assertEquals(1, result.actionPlans.size());
        System.assertEquals(2, result.actionPlans[0].obstacleList.size());
    }
    
    /*
@description    Test method for getGoalsForClientCase
*/
    @IsTest
    private static void testGetGoalsForClientCase2(){
        ClientCase__c clCase = TestDataFactory.createClientCases(1, true)[0];
        
        ClientActionPlan__c  cap = new ClientActionPlan__c ();
        cap.ClientCase__c = clCase.Id;
        insert cap;
        
        Goal__c goal = new Goal__c();
        goal.ClientCase__c = clCase.Id;
        goal.ClientActionPlan__c = cap.Id;
        goal.GoalSubject__c = 'test subject';
        goal.GoalDetails__c = 'test details';
        goal.GoalType__c = 'Short Term';
        goal.Status__c = 'In Progress';
        goal.DueDate__c = System.today();
        
        insert goal;
        
        List<Obstacle__c> obsList = new List<Obstacle__c>();
        
        Obstacle__c obs1 = new Obstacle__c();
        obs1.Goal__c = goal.Id;
        obs1.ObstacleSubject__c = 'Buy a house';
        obs1.ObstacleDetails__c = 'test details';
        obs1.DueDate__c = System.today();
        obsList.add(obs1);
        
        Obstacle__c obs2 = new Obstacle__c();
        obs2.Goal__c = goal.Id;
        obs2.ObstacleSubject__c = 'Lack of opportunity';
        obs2.ObstacleDetails__c = 'test details';
        obs2.DueDate__c = System.today();
        obsList.add(obs2);
        
        insert obsList;
        
        Solution__c sol = new Solution__c();
        sol.Obstacle__c = obs1.Id;
        sol.SolutionSubject__c = 'other';
        sol.SolutionDetails__c = 'test details';
        sol.Status__c = 'Not Started';
        
        insert sol;
        
        List<Task> taskList = new List<Task>();
        
        Task clientTask = new Task();
        clientTask.ActionType__c = 'Client Action';
        clientTask.Subject = 'test sub';
        clientTask.Description = 'test sub';
        clientTask.Status = 'Not Started';
        clientTask.ActivityDate = System.today();
        clientTask.WhatId = sol.Id;
        taskList.add(clientTask);
        
        Task counselorTask = new Task();
        counselorTask.ActionType__c = 'Counselor Action';
        counselorTask.Subject = 'test sub';
        counselorTask.Description = 'test sub';
        counselorTask.Status = 'Completed';
        counselorTask.ActivityDate = System.today();
        counselorTask.WhatId = sol.Id;
        taskList.add(counselorTask);
        
        insert taskList;
        
        ClientActionPlansController.ClientActionPlanWrapper result = ClientActionPlansController.getGoalsForClientCase(clCase.Id);
        
        System.assertNotEquals(null, result);
        System.assertNotEquals(null, result.actionPlans);
        System.assertEquals(1, result.actionPlans.size());
        System.assertEquals(2, result.actionPlans[0].obstacleList.size());
    }
    
    /*
@description    Test method for getGoalsForClientCase
*/
    @IsTest
    private static void testGetGoalsForClientCase3(){
        ClientCase__c clCase = TestDataFactory.createClientCases(1, true)[0];
        
        ClientActionPlan__c  cap = new ClientActionPlan__c ();
        cap.ClientCase__c = clCase.Id;
        insert cap;
        
        Goal__c goal = new Goal__c();
        goal.ClientCase__c = clCase.Id;
        goal.ClientActionPlan__c = cap.Id;
        goal.GoalSubject__c = 'test subject';
        goal.GoalDetails__c = 'test details';
        goal.GoalType__c = 'Short Term';
        goal.Status__c = 'Completed';
        goal.DueDate__c = System.today();
        
        insert goal;
        
        List<Obstacle__c> obsList = new List<Obstacle__c>();
        
        Obstacle__c obs1 = new Obstacle__c();
        obs1.Goal__c = goal.Id;
        obs1.ObstacleSubject__c = 'Buy a house';
        obs1.ObstacleDetails__c = 'test details';
        obs1.DueDate__c = System.today();
        obsList.add(obs1);
        
        Obstacle__c obs2 = new Obstacle__c();
        obs2.Goal__c = goal.Id;
        obs2.ObstacleSubject__c = 'Lack of opportunity';
        obs2.ObstacleDetails__c = 'test details';
        obs2.DueDate__c = System.today();
        obsList.add(obs2);
        
        insert obsList;
        
        Solution__c sol = new Solution__c();
        sol.Obstacle__c = obs1.Id;
        sol.SolutionSubject__c = 'other';
        sol.SolutionDetails__c = 'test details';
        sol.Status__c = 'Not Started';
        
        insert sol;
        
        List<Task> taskList = new List<Task>();
        
        Task clientTask = new Task();
        clientTask.ActionType__c = 'Client Action';
        clientTask.Subject = 'test sub';
        clientTask.Description = 'test sub';
        clientTask.Status = 'Not Started';
        clientTask.ActivityDate = System.today();
        clientTask.WhatId = sol.Id;
        clientTask.Solution__c = sol.Id;
        taskList.add(clientTask);
        
        Task counselorTask = new Task();
        counselorTask.ActionType__c = 'Counselor Action';
        counselorTask.Subject = 'test sub';
        counselorTask.Description = 'test sub';
        counselorTask.Status = 'Completed';
        counselorTask.ActivityDate = System.today();
        counselorTask.WhatId = sol.Id;
        counselorTask.Solution__c = sol.Id;
        taskList.add(counselorTask);
        
        insert taskList;
        Test.startTest();
        ClientActionPlansController.ClientActionPlanWrapper result = ClientActionPlansController.getGoalsForClientCase(clCase.Id);
        Test.stopTest();
        
        
        System.assertNotEquals(null, result);
        System.assertNotEquals(null, result.actionPlans);
        System.assertEquals(1, result.actionPlans.size());
        System.assertEquals(2, result.actionPlans[0].obstacleList.size());
    }
    
    /*
@description    Test method for saveGoalsForClientCase
*/
    @IsTest
    private static void testSaveGoalsForClientCase_Update(){
        ClientCase__c clCase = TestDataFactory.createClientCases(1, true)[0];
        
        ClientActionPlan__c  cap = new ClientActionPlan__c ();
        cap.ClientCase__c = clCase.Id;
        insert cap;
        
        Goal__c goal = new Goal__c();
        goal.ClientCase__c = clCase.Id;
        goal.ClientActionPlan__c = cap.Id;
        goal.GoalSubject__c = 'test subject';
        goal.GoalDetails__c = 'test details';
        goal.GoalType__c = 'Short Term';
        goal.Status__c = 'In Progress';
        goal.DueDate__c = System.today();
        
        insert goal;
        
        List<Obstacle__c> obsList = new List<Obstacle__c>();
        
        Obstacle__c obs1 = new Obstacle__c();
        obs1.Goal__c = goal.Id;
        obs1.ObstacleSubject__c = 'Buy a house';
        obs1.ObstacleDetails__c = 'test details';
        obs1.DueDate__c = System.today();
        obsList.add(obs1);
        
        Obstacle__c obs2 = new Obstacle__c();
        obs2.Goal__c = goal.Id;
        obs2.ObstacleSubject__c = 'Lack of required skills';
        obs2.ObstacleDetails__c = 'test details';
        obs2.DueDate__c = System.today();
        obsList.add(obs2);
        
        insert obsList;
        
        Solution__c sol = new Solution__c();
        sol.Obstacle__c = obs1.Id;
        sol.SolutionSubject__c = 'Reduce debt';
        sol.SolutionDetails__c = 'test details';
        sol.Status__c = 'Not Started';
        
        insert sol;
        
        String jsonString = '{"clientCaseId":"'+ clCase.Id +'","actionPlanId":"'+ cap.Id +'","goalDetail":"goal details","goalId":"'+ goal.Id +'","goalName":"Buy a Car","goalOtherName":"","goalStatus":"Completed","goalType":"Short Term",'+
            '"obstacleList":[{"obsExternalId":"572577","obstacleDetail":"obstacledetail 1","obstacleDueDate":"2024-05-04","obstacleId":"'+ obs1.Id +'","obstacleName":"Lack of opportunity","obstacleOtherName":"",'+
            '"showAddSolutionAction":true,"showObstacleOtherName":false,"solutionList":[{"clientAction":"sdfsd","clientActionDetail":"2342qwfefas","clientActionDueDate":"2024-05-28","clientActionId":"",'+
            '"clientActionStatus":"Completed","counselorAction":"sdfsdf","counselorActionDetail":"asdfasdf","counselorActionDueDate":"2024-06-04","counselorActionId":"","counselorActionStatus":"Completed",'+
            '"showSolutionOtherName":false,"solExternalId":"745113","solutionDetail":"sol details 1","solutionId":"'+ sol.Id +'","solutionName":"Increase income","solutionOtherName":"","viewModeCollapsed":false}],'+
            '"viewModeCollapsed":false},{"obsExternalId":"330117","obstacleDetail":"sdasdfasdf","obstacleDueDate":"2024-05-21",'+
            '"obstacleId":"'+ obs2.Id +'","obstacleName":"Other","obstacleOtherName":"asdfasdfvaxc","showAddSolutionAction":true,"showObstacleOtherName":true,"solutionList":[],"viewModeCollapsed":false}],'+
            '"progressBarAltText":"Progress: 100.0%","progressBarText":"6/6 Action Items Completed","progressBarWidthClass":"slds-progress-bar__value slds-progress-bar__value_success","progressBarWidthStyle":"width:100.0%;",'+
            '"showGoalOtherName":false,"statusClass":"slds-badge slds-theme_success","viewModeCollapsed":true}';
        
        
        
        ClientActionPlansController.GoalWrapper inputWrapper = (ClientActionPlansController.GoalWrapper)JSON.deserialize(jsonString, ClientActionPlansController.GoalWrapper.class);
        
        ClientActionPlansController.saveGoalsForClientCase(inputWrapper);
        
        List<Goal__c> goalList = [Select Id, Name, GoalSubject__c from Goal__c where Id =:goal.Id WITH SECURITY_ENFORCED ];
        
        List<Obstacle__c> obstacleList = [Select Id, Name, ObstacleSubject__c from Obstacle__c 
                                          where Id =:obs1.Id WITH SECURITY_ENFORCED];
        
        List<Solution__c> solutionList = [Select Id, Name, SolutionSubject__c,
                                          (Select Id, Status, Subject, ActionType__c, Description, ActivityDate from Activities__r)
                                          from Solution__c where Id =:sol.Id WITH SECURITY_ENFORCED];
        
        
        System.assertNotEquals(null, goalList);
        System.assertEquals('Buy a Car', goalList[0].GoalSubject__c);
        System.assertNotEquals(null, obstacleList);
        System.assertEquals('Lack of opportunity', obstacleList[0].ObstacleSubject__c);
        System.assertNotEquals(null, solutionList);
        System.assertEquals('Increase income', solutionList[0].SolutionSubject__c);
        System.assertEquals(2, solutionList[0].Activities__r.size());
    }
    
    @isTest
    public static void testFinancialSnapshotWrapper() {
        FinancialSnapshot__c snapshot = [SELECT CreditScore__c, CoAppCreditScore__c, Savings__c, CurrentMonthlyDebtObligation__c,
                                         GrossMonthlyIncome__c, HousingExpense__c, TotalDebt__c, 
                                         TotalAssets__c FROM FinancialSnapshot__c LIMIT 1];
        
        ClientActionPlansController.FinancialSnapshotWrapper wrapper = new ClientActionPlansController.FinancialSnapshotWrapper(snapshot);
        
        // Assert to verify the values are correctly assigned
    /*    System.assertEquals(String.valueOf(snapshot.CreditScore__c), wrapper.creditScore);
        System.assertEquals('N/A', wrapper.coAppCreditScore); // Adjust if snapshot.CurrentMonthlyDebtObligation__c is null
        System.assertEquals(String.valueOf(snapshot.Savings__c), wrapper.savings);
        System.assertEquals(String.valueOf(snapshot.GrossMonthlyIncome__c), wrapper.grossMonthlyIncome);
        System.assertEquals(String.valueOf(snapshot.HousingExpense__c), wrapper.housingExpense);
        System.assertEquals(String.valueOf(snapshot.TotalDebt__c), wrapper.totalDebt);
        System.assertEquals(String.valueOf(snapshot.TotalAssets__c), wrapper.totalAssets);
        System.assertEquals('', wrapper.conditionOfProperty); // As this field is hardcoded to an empty string*/
    }
    
    @isTest
    public static void TestFunctions() {
        Goal__c goal = [Select Id from Goal__c limit 1];
        Solution__c sol =  [Select Id from Solution__c limit 1];
        Test.startTest();
        ClientActionPlansController.hasRemoveObstaclePermission();
        ClientActionPlansController.deleteObstaclesAndSolutionsForGoal(goal.id);
        ClientActionPlansController.deleteSolution(sol.Id);
        Test.stopTest();
    }
    
    @isTest
    public static void TestgetClientCase() {
        ClientCase__c goal = [Select Id from ClientCase__c limit 1];
        Test.startTest();
        ClientActionPlansController.getClientCase(goal.id);
        Test.stopTest();
    }
   
    @IsTest
    static void verifyIsIntakeStaffUser() {
        Test.startTest();
        Boolean isIntakeStaffUser = ClientActionPlansController.isIntakeStaffUser();
        Test.stopTest();
    }
    
    
}