objects/Activity.object
<CustomObject>
    <fields>
        <fullName>AppointmentDuration__c</fullName>
        <label>Appointment Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AppointmentStatus__c</fullName>
        <label>Appointment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HUDActivityType__c</fullName>
        <label>HUD Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>HUDActivityType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <label>Outcome</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Purpose__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Households that received one-on-one counseling that also received education services.</fullName>
                </value>
                <value>
                    <fullName>Households that received information on fair housing, fair lending and/or accessibility rights.</fullName>
                </value>
                <value>
                    <fullName>Households for whom counselor developed a budget customized to a client’s current situation.</fullName>
                </value>
                <value>
                    <fullName>Households that improved their financial capacity (e.g. increased discretionary income, decreased debt load, increased savings, increased credit score, etc.) after receiving Housing Counseling Services.</fullName>
                </value>
                <value>
                    <fullName>Households that gained access to resources to help improve their housing situation (e.g. down payment assistance, rental assistance, utility assistance, etc.) after receiving Housing Counseling Services.</fullName>
                </value>
                <value>
                    <fullName>Households that gained access to non-housing resources (e.g. social service programs, legal services, public benefits such as Social Security or Medicaid, etc.) after receiving Housing Counseling Services</fullName>
                </value>
                <value>
                    <fullName>Homeless or potentially homeless households that obtained temporary or permanent housing after receiving Housing Counseling Services.</fullName>
                </value>
                <value>
                    <fullName>Households gained access to disaster recovery non-housing resources after receiving Housing Counseling Services (e.g. Red Cross/FEMA relief items, legal services, assistance).</fullName>
                </value>
                <value>
                    <fullName>Households obtained disaster recovery housing resources after receiving Housing Counseling Services (e.g. temporary shelter, homeowner rehab, relocation, etc.).</fullName>
                </value>
                <value>
                    <fullName>Households for whom counselor developed or updated an emergency preparedness plan.</fullName>
                </value>
                <value>
                    <fullName>Household that received rental counseling and avoided eviction after receiving Housing Counseling Services.</fullName>
                </value>
                <value>
                    <fullName>Households that received rental counseling and improved living conditions after receiving Housing Counseling Services.</fullName>
                </value>
                <value>
                    <fullName>Households that received pre-purchase/homebuying counseling and purchased housing after receiving Housing Counseling Services.</fullName>
                </value>
                <value>
                    <fullName>Households that received reverse mortgage counseling and obtained a Home Equity Conversion Mortgage (HECM) after receiving Housing Counseling Services.</fullName>
                </value>
                <value>
                    <fullName>Households that received non-delinquency post-purchase counseling that were able to improve home conditions or home affordability after receiving Housing Counseling Services</fullName>
                </value>
                <value>
                    <fullName>Households that prevented or resolved a forward mortgage default after receiving Housing Counseling Services.</fullName>
                </value>
                <value>
                    <fullName>Households that prevented or resolved a reverse mortgage default after receiving Housing Counseling Services.</fullName>
                </value>
                <value>
                    <fullName>Households that received a forward mortgage modification and remained current in their modified mortgage after receiving Housing Counseling Services.</fullName>
                </value>
                <value>
                    <fullName>Households that received a forward mortgage modification and improved their financial capacity after receiving Housing counseling Services.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <label>Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Homeless Assistance</fullName>
                </value>
                <value>
                    <fullName>Rental Topics</fullName>
                </value>
                <value>
                    <fullName>Pre-purchase/Homebuying</fullName>
                </value>
                <value>
                    <fullName>Non-Delinquency Post-Purchase</fullName>
                </value>
                <value>
                    <fullName>Reverse Mortgage</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Forward Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Reverse Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Disaster Preparedness Assistance</fullName>
                </value>
                <value>
                    <fullName>Disaster Recovery Assistance</fullName>
                </value>
                <value>
                    <fullName>Not HUD-Reportable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sumoapp__AdditionalInfo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SUMO Additional Info</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>Outcome__c</fullName>
        <description>HUD-specified outcomes for Education only</description>
        <inlineHelpText>HUD-specified outcomes</inlineHelpText>
        <label>Outcome</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed financial literacy workshop, including home affordability, budgeting and understanding use of credit</fullName>
                </value>
                <value>
                    <fullName>Completed predatory lending, loan scam or other fraud prevention workshop</fullName>
                </value>
                <value>
                    <fullName>Completed fair housing workshop</fullName>
                </value>
                <value>
                    <fullName>Completed homelessness prevention workshop</fullName>
                </value>
                <value>
                    <fullName>Completed rental workshop</fullName>
                </value>
                <value>
                    <fullName>Completed pre-purchase homebuyer education workshop</fullName>
                </value>
                <value>
                    <fullName>Completed non-delinquency post-purchase workshop, including home maintenance and/or financial management for homeowners</fullName>
                </value>
                <value>
                    <fullName>Completed resolving or preventing mortgage delinquency workshop</fullName>
                </value>
                <value>
                    <fullName>Completed other workshop</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <description>Agency to custom relevant purposes</description>
        <inlineHelpText>Choose one most applicable value from the drop-down list</inlineHelpText>
        <label>HUD Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Homeless Assistance</fullName>
                </value>
                <value>
                    <fullName>Pre-purchase/Homebuying</fullName>
                </value>
                <value>
                    <fullName>Rental Topics</fullName>
                </value>
                <value>
                    <fullName>Non-Delinquency Post-Purchase</fullName>
                </value>
                <value>
                    <fullName>Reverse Mortgage</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Forward Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Reverse Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Disaster Preparedness Assistance</fullName>
                </value>
                <value>
                    <fullName>Disaster Recovery Assistance</fullName>
                </value>
                <value>
                    <fullName>Not HUD-Reportable</fullName>
                </value>
                <value>
                    <fullName>Financial Literacy</fullName>
                    <isActive>false</isActive>
                    <label>Financial Literacy</label>
                </value>
                <value>
                    <fullName>Home Improvement Loan</fullName>
                    <isActive>false</isActive>
                    <label>Home Improvement Loan</label>
                </value>
                <value>
                    <fullName>Home Purchase Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Home Purchase Inquiry</label>
                </value>
                <value>
                    <fullName>Job Training</fullName>
                    <isActive>false</isActive>
                    <label>Job Training</label>
                </value>
                <value>
                    <fullName>Mortgage Delinquency Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Mortgage Delinquency Inquiry</label>
                </value>
                <value>
                    <fullName>Rehab Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Rehab Inquiry</label>
                </value>
                <value>
                    <fullName>Rental Assistance</fullName>
                    <isActive>false</isActive>
                    <label>Rental Assistance</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Intake__c.object
<CustomObject>
    <description>To capture and store initial information about clients/prospects during the intake process including New Intake, New Education Only, and New Emergency Triage.</description>
    <fields>
        <fullName>Purpose__c</fullName>
        <label>HUD Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Homeless Assistance</fullName>
                </value>
                <value>
                    <fullName>Pre-purchase/Homebuying</fullName>
                </value>
                <value>
                    <fullName>Rental Topics</fullName>
                </value>
                <value>
                    <fullName>Non-Delinquency Post-Purchase</fullName>
                </value>
                <value>
                    <fullName>Reverse Mortgage</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Forward Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Reverse Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Disaster Preparedness Assistance</fullName>
                </value>
                <value>
                    <fullName>Disaster Recovery Assistance</fullName>
                </value>
                <value>
                    <fullName>Not HUD-Reportable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Intake</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Calendar Event Information</relationshipLabel>
        <relationshipName>SUMOAdditionalInfo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HUDActivityType__c</fullName>
        <label>HUD Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>HUDActivityType</valueSetName>
        </valueSet>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/HUDActivityType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Not Billed to HUD</fullName>
        <default>true</default>
        <label>Not Billed to HUD</label>
    </customValue>
    <customValue>
        <fullName>NOFA 2014-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2014-2 TRNG</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2015-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2015-2 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2016-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2017-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2018-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2019-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2020-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2021-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2022-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2023-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>HO INT</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2024-1 COMP</fullName>
    </customValue>
    <masterLabel>HUD Activity Type</masterLabel>
</GlobalValueSet>

classes/ActivityTimelineController.cls
/*
* @description    Controller class containing methods for Activity Component
* @date           2024-06-01
* @group          Activity Timeline
*/
public abstract class ActivityTimelineController {
    /*
	* @description : To get related events 
	*/ 
    @AuraEnabled
    public static List<ActivityTimelineService.ResultWrapper> getEvents(Id recordId) {
        List<ActivityTimelineService.ResultWrapper> result = new List<ActivityTimelineService.ResultWrapper>();
        String sObjName = recordId.getSObjectType().getDescribe().getName();
        ActivityTimelineService service = null;
        if(sObjName=='Contact'){
            service = new ContactTimelineService();
        } else if(sObjName=='ClientCase__c') {
            service = new ClientCaseTimelineService();
        } else if(sObjName=='Intake__c') {
            service = new IntakeTimelineService();
        }
        if(service!=null){
            result =  service.getAllEvents(recordId);
        }
        System.debug('Result ::: '+result);
        return result;
    }
    
    /*
	* @description : To get related Participants for a given event
	*/ 
    @AuraEnabled(cacheable=true)
    public static List<String> getParticipants(Id eventId) {
        List<String> participantNames=new List<String>();
        for(EventRelation elt : [Select Relation.Name from EventRelation where EventId=:eventId AND Relation.Type='Contact']) {
            participantNames.add(elt.Relation.Name);
        }
        return participantNames;
    }
    
    /*
	* @description : To update Appointment Notes
	*/ 
    @AuraEnabled
    public static void updateAppointmentNotes(String eventId, String funder, String outcome, String purpose, String appointmentStatus, Integer durationInMin, String notes, String hudActivity) {
        if(String.isNotBlank(eventId)){
            List<Event> evtList = [select Id, DurationInMinutes,who.Name, WhatId,AppointmentStatus__c,what.Type,HUDActivityType__c, sumoapp__AdditionalInfo__c from Event where Id =:eventId];
            id RecordTypeId = [Select Id from Recordtype where sObjectType='Task' AND DeveloperName='Reminder']?.Id;
            if(evtList.size() > 0){
                Boolean isAppointmentAttended = !String.isBlank(appointmentStatus) && (evtList[0].AppointmentStatus__c != appointmentStatus) && (appointmentStatus=='Attended');
                System.debug(' Boolean Value set to : '+isAppointmentAttended+' Appointment Status ::: '+appointmentStatus);
                
                if(durationInMin != NULL){
                    evtList[0].AppointmentDuration__c = durationInMin;
                }
                if(appointmentStatus=='No Show') {
                    evtList[0].AppointmentDuration__c = 0;
                }
                evtList[0].Outcome__c = outcome;
                evtList[0].purpose__c = purpose;
                evtList[0].AppointmentStatus__c = appointmentStatus;
                
                evtList[0].HUDActivityType__c = hudActivity;
                
                System.debug('Event :: '+ evtList[0]);
                update evtList; 
                
                if(isAppointmentAttended) {
                    createReminders(new List<Id>{evtList[0].WhatId}, evtList[0].who.Name, RecordTypeId); 
                }
                
                List<sumoapp__AdditionalInfo__c > additionalInfo = [select Id, Notes__c from sumoapp__AdditionalInfo__c  where Id =:evtList[0].sumoapp__AdditionalInfo__c];
                
                if(additionalInfo.size() > 0){
                    additionalInfo[0].Notes__c = notes;
                    if(!Test.isRunningTest()){
                        update additionalInfo;
                    }
                }
            }
        }
    }
    
    /*
	* @description : To get related events 
	*/ 
    @AuraEnabled
    public static ActivityTimelineService.ActivityWrapper getEventWrapper(Id eventId) {
        if(!String.isEmpty(eventId)){
            Event evt = [Select id, purpose__c,Outcome__c,AppointmentDuration__c, sumoapp__AdditionalInfo__r.Notes__c,AppointmentStatus__c FROM Event where Id = :eventId];
            ActivityTimelineService.ActivityWrapper wrap = new ActivityTimelineService.ActivityWrapper();
            wrap.durationInMin = Integer.valueOf(evt.AppointmentDuration__c);
            wrap.notes = evt.sumoapp__AdditionalInfo__r.Notes__c;
            wrap.purpose = evt.purpose__c;
            wrap.outcome = evt.Outcome__c;
            wrap.participants = getParticipants(eventId);
            wrap.appointmentStatus = evt.AppointmentStatus__c;
            return wrap;
        }
        return null;
    }
    
    @AuraEnabled(cacheable=true)
    public static Id getAppointmentRecordTypeId() {
        return [Select Id, Name from RecordType where SobjectType='Event' And Name='Appointment']?.Id;
    }
    
    /*
	* @description : To create reminders
	*/
    public static void createReminders(List<Id> objectIds, String name, Id recordTypeId) {
         
        List<Task> taskstoUpdate = new List<Task>();
        for(Id recId : objectIds) {
            taskstoUpdate.addAll(createReminders(recId, name,recordTypeId));
        }
        insert taskstoUpdate;
    }
    
    public static List<Task> createReminders(Id objectId, String name, Id recordTypeId) {
        List<Task> existingTasks = [SELECT Id FROM Task 
                                WHERE WhatId = :objectId 
                                AND Subject IN ('30DayFollowUp', '60DayFollowUp', '90DayFollowUp')];
    	if (!existingTasks.isEmpty()) {
        	delete existingTasks;
    	}
        List<Task> reminderList = new List<Task>();
        Task tsk = new Task();
        tsk.OwnerId = UserInfo.getUserId();
        tsk.Subject='30DayFollowUp';
        tsk.Priority='Medium';
        tsk.WhatId=objectId;
        tsk.IsReminderSet=true;
        tsk.ReminderDateTime = System.today().addDays(30);
        if(recordTypeId!=null) {
            tsk.RecordTypeId = recordTypeId;
        }
        tsk.Description='Reminder regarding the upcoming 30-day follow-up for '+Name+'. Kindly review the client case and take appropriate actions.';
        
        reminderList.add(tsk);
        
        Task tsk1 = new Task();
        tsk1.OwnerId = UserInfo.getUserId();
        tsk1.Subject='60DayFollowUp';
        tsk1.Priority='Medium';
        tsk1.WhatId=objectId;
        tsk1.IsReminderSet=true;
        tsk1.ReminderDateTime = System.today().addDays(60);
        tsk1.Description='Reminder regarding the upcoming 60-day follow-up for '+Name+'.  Kindly review the client case and take appropriate actions.';
        if(recordTypeId!=null) {
            tsk1.RecordTypeId = recordTypeId;
        }
        reminderList.add(tsk1);
        
        Task task90 = new Task();
        task90.OwnerId = UserInfo.getUserId();
        task90.Subject='90DayFollowUp';
        task90.Priority='Medium';
        task90.WhatId=objectId;
        task90.IsReminderSet=true;
        task90.ReminderDateTime = System.today().addDays(90);
        task90.Description='Reminder regarding the upcoming 90-day follow-up for '+Name+'.  Kindly review the client case and take appropriate actions.';
        if(recordTypeId!=null) {
            task90.RecordTypeId = recordTypeId;
        }
        reminderList.add(task90);
        
        return reminderList;
    }

    /**
* @description       : Method to check that current logged in user is IntakeStaff or not.
**/
    @AuraEnabled
    public static Boolean isIntakeStaffUser(){
        return FeatureManagement.checkPermission('IntakeStaff');
    }
}