objects/AgencyProfile__c.object
<CustomObject>
    <description>To store detailed information about the Agency, including their contact information, operational details, HUD Contact, HUD Office Executive, HUD Office Manager and other relevant attributes.</description>
    <fields>
        <fullName>ValidationCombined1__c</fullName>
        <formula>IF(
ISPICKVAL(HUDOfficeManagerAddress__StateCode__s,&apos;&apos;)  ||
ISBLANK(HUDOfficeManagerAddress__PostalCode__s) ||
ISBLANK(HUDOfficeManagerPhone__c) ||
ISBLANK(HUDOfficeManagerEmail__c) ||
ISBLANK(HUDOfficeExecutiveFirstName__c) ||
ISBLANK(HUDOfficeExecutiveLastName__c) ||
ISBLANK(HUDOfficeExecutiveAddress__Street__s) ||
ISBLANK(HUDOfficeExecutiveAddress__City__s) ||
ISPICKVAL(HUDOfficeExecutiveAddress__StateCode__s,&apos;&apos;)  ||
ISBLANK(HUDOfficeExecutiveAddress__PostalCode__s) ||
ISBLANK(HUDOfficeExecutivePhone__c) ||
ISBLANK(HUDOfficeExecutiveEmail__c),

IF(ISPICKVAL(HUDOfficeManagerAddress__StateCode__s,&apos;&apos;), &apos;HUD Office Manager Address (State/Province), &apos;, &apos;&apos;) &amp;
IF(ISBLANK(HUDOfficeManagerAddress__PostalCode__s), &apos;HUD Office Manager Address (ZIP/Postal Code), &apos;, &apos;&apos;) &amp;
IF(ISBLANK(HUDOfficeManagerPhone__c), &apos;HUD Office Manager Phone Number, &apos;, &apos;&apos;) &amp;
IF(ISBLANK(HUDOfficeManagerEmail__c), &apos;HUD Office Manager Email, &apos;, &apos;&apos;) &amp;
IF(ISBLANK(HUDOfficeExecutiveFirstName__c), &apos;HUD Office Executive First Name, &apos;, &apos;&apos;) &amp;
IF(ISBLANK(HUDOfficeExecutiveLastName__c), &apos;HUD Office Executive Last Name, &apos;, &apos;&apos;) &amp;
IF(ISBLANK(HUDOfficeExecutiveAddress__Street__s), &apos;HUD Office Executive Address (Street), &apos;, &apos;&apos;) &amp;
IF(ISBLANK(HUDOfficeExecutiveAddress__City__s), &apos;HUD Office Executive Address (City), &apos;, &apos;&apos;) &amp;
IF(ISPICKVAL(HUDOfficeExecutiveAddress__StateCode__s,&apos;&apos;), &apos;HUD Office Executive Address (State/Province), &apos;, &apos;&apos;) &amp;
IF(ISBLANK(HUDOfficeExecutiveAddress__PostalCode__s), &apos;HUD Office Executive Address (ZIP/Postal Code), &apos;, &apos;&apos;) &amp;
IF(ISBLANK(HUDOfficeExecutivePhone__c), &apos;HUD Office Executive Phone Number, &apos;, &apos;&apos;) &amp;
IF(ISBLANK(HUDOfficeExecutiveEmail__c), &apos;HUD Office Executive Email	, &apos;, &apos;&apos;),
&apos;NO ERROR&apos;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Validation Combined1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ValidationCombined__c</fullName>
        <formula>IF(
ISBLANK(HUDContactFirstName__c) ||
ISBLANK(HUDContactLastName__c) ||
ISBLANK(HUDContactAddress__Street__s) ||
ISBLANK(HUDContactAddress__City__s) ||
ISPICKVAL(HUDContactAddress__StateCode__s,&apos;&apos;)  ||
ISBLANK(HUDContactAddress__PostalCode__s) ||
ISBLANK(HUDContactPhone__c) ||
ISBLANK(HUDContactEmail__c) ||
ISBLANK(HUDOfficeManagerFirstName__c) ||
ISBLANK(HUDOfficeManagerLastName__c) ||
ISBLANK(HUDOfficeManagerAddress__Street__s) ||
ISBLANK(HUDOfficeManagerAddress__City__s)
,
&apos;Required field(s) missing: &apos; &amp;
IF(ISBLANK(HUDContactFirstName__c), &apos;HUD Contact First Name, &apos;, &apos;&apos;) &amp;
IF(ISBLANK(HUDContactLastName__c), &apos;HUD Contact Last Name, &apos;, &apos;&apos;) &amp;
IF(ISBLANK(HUDContactAddress__Street__s), &apos;HUD Contact Address (Street), &apos;, &apos;&apos;) &amp;
IF(ISBLANK(HUDContactAddress__City__s), &apos;HUD Contact Address (City), &apos;, &apos;&apos;) &amp;
IF(ISPICKVAL(HUDContactAddress__StateCode__s,&apos;&apos;), &apos;HUD Contact Address (State/Province), &apos;, &apos;&apos;) &amp;
IF(ISBLANK(HUDContactAddress__PostalCode__s), &apos;HUD Contact Address (ZIP/Postal Code), &apos;, &apos;&apos;) &amp;
IF(ISBLANK(HUDContactPhone__c), &apos;HUD Contact Phone Number, &apos;, &apos;&apos;) &amp;
IF(ISBLANK(HUDContactEmail__c), &apos;HUD Contact Email, &apos;, &apos;&apos;) &amp;
IF(ISBLANK(HUDOfficeManagerFirstName__c), &apos;HUD Office Manager First Name, &apos;, &apos;&apos;) &amp;
IF(ISBLANK(HUDOfficeManagerLastName__c), &apos;HUD Office Manager Last Name, &apos;, &apos;&apos;) &amp;
IF(ISBLANK(HUDOfficeManagerAddress__Street__s), &apos;HUD Office Manager Address (Street), &apos;, &apos;&apos;) &amp;
IF(ISBLANK(HUDOfficeManagerAddress__City__s), &apos;HUD Office Manager Address (City), &apos;, &apos;&apos;),
&apos;&apos;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Validation Combined</label>
        <type>Text</type>
    </fields>
    <label>Agency Profile</label>
    <nameField>
        <label>Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>ValidationCombined1__c</fullName>
        <formula>IF(
(
ISPICKVAL(EnglishProficiency__c ,&apos;&apos;) ||
ISPICKVAL(FarmWorker__c,&apos;&apos;) ||
ISPICKVAL(DisabledStatus__c,&apos;&apos;) ||
ISPICKVAL(Ethnicity__c,&apos;&apos;) ||
ISPICKVAL(HouseholdType__c,&apos;&apos;) ||
ISPICKVAL(Education__c,&apos;&apos;) ||
ISBLANK(HouseholdSize__c) ||
ISPICKVAL(X1stTimeHomeBuyer__c,&apos;&apos;) ||
ISPICKVAL(ReferralSource__c,&apos;&apos;) ||
ISPICKVAL(ColoniasResidence__c,&apos;&apos;) ||
ISBLANK(NumberofDependents__c)  || isInvalidZip__c  || EvaluateHUDAMI__c) , 

(
IF(ISPICKVAL(EnglishProficiency__c ,&apos;&apos;), &apos;English Proficiency, &apos;, &apos;&apos;) &amp;
IF(ISPICKVAL(FarmWorker__c,&apos;&apos;), &apos;Farm Worker, &apos;, &apos;&apos;) &amp;
IF(ISPICKVAL(DisabledStatus__c,&apos;&apos;), &apos;Disabled Status, &apos;, &apos;&apos;) &amp;
IF(ISPICKVAL(Ethnicity__c,&apos;&apos;), &apos;Ethnicity, &apos;, &apos;&apos;) &amp;
IF(ISPICKVAL(HouseholdType__c,&apos;&apos;), &apos;Household Type, &apos;, &apos;&apos;) &amp;
IF(ISPICKVAL(Education__c,&apos;&apos;), &apos;Education, &apos;, &apos;&apos;) &amp;
IF(ISBLANK(HouseholdSize__c), &apos;Household Size, &apos;, &apos;&apos;) &amp;
IF(ISPICKVAL(X1stTimeHomeBuyer__c,&apos;&apos;), &apos;1st Time Home Buyer, &apos;, &apos;&apos;) &amp;
IF(ISPICKVAL(ReferralSource__c,&apos;&apos;), &apos;Referral Source, &apos;, &apos;&apos;) &amp;
IF(ISPICKVAL(ColoniasResidence__c,&apos;&apos;), &apos;Colonias Residence, &apos;, &apos;&apos;) &amp;
IF(ISBLANK(NumberofDependents__c), &apos;Number of Dependents, &apos;, &apos;&apos;) &amp;
IF(isInvalidZip__c, &apos;Invalid Zip Code/County/Town Entered! &apos;, &apos;&apos;) &amp;
IF(EvaluateHUDAMI__c , &apos;Please Search County By Zip Code to Calculate HUD AMI&apos;,&apos;&apos;)), &quot;NO ERROR&quot;
)</formula>
        <label>Validation Combined1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ValidationCombined__c</fullName>
        <formula>IF(
    (ISBLANK(ClientNumber__c) ||
     ISBLANK(Household__c) ||
     ISPICKVAL(Purpose__c, &apos;&apos;) ||
     ISBLANK(PrimaryClient__c) ||
     ISBLANK(CounsellorName__c) ||
     ISPICKVAL(ClientCaseStatus__c, &apos;&apos;) ||
     ISPICKVAL(Race__c,&apos;&apos;) ||
     ISPICKVAL(MaritalStatus__c,&apos;&apos;) ||
     ISPICKVAL(ClientHUDAssistance__c ,&apos;&apos;) ||
     ISPICKVAL(DiscriminationVictim__c ,&apos;&apos;) ||
     ISPICKVAL(RuralAreaStatus__c,&apos;&apos;)
				
),
    
    (&apos;Required field(s) missing: &apos; &amp;
     IF(ISBLANK(ClientNumber__c), &apos;Client #, &apos;, &apos;&apos;) &amp;
     IF(ISBLANK(Household__c), &apos;Household, &apos;, &apos;&apos;) &amp;
     IF(ISPICKVAL(Purpose__c , &apos;&apos;), &apos;HUD Purpose, &apos;, &apos;&apos;) &amp;
     IF(ISBLANK(PrimaryClient__c), &apos;Primary Client, &apos;, &apos;&apos;) &amp;
     IF(ISBLANK(CounsellorName__c), &apos;Assigned Counselor, &apos;, &apos;&apos;) &amp;
     IF(ISPICKVAL(ClientCaseStatus__c, &apos;&apos;), &apos;Client Case Status, &apos;, &apos;&apos;) &amp;
     IF(ISPICKVAL(Race__c,&apos;&apos;), &apos;Race, &apos;, &apos;&apos;) &amp;
     IF(ISPICKVAL(ClientHUDAssistance__c,&apos;&apos;), &apos;Client HUD Assistance, &apos;, &apos;&apos;) &amp;
     IF(ISPICKVAL(DiscriminationVictim__c,&apos;&apos;), &apos;Discrimination Victim, &apos;, &apos;&apos;) &amp;
     IF(ISPICKVAL(MaritalStatus__c,&apos;&apos;), &apos;Marital Status, &apos;, &apos;&apos;) &amp;
     IF(ISPICKVAL(RuralAreaStatus__c,&apos;&apos;), &apos;Rural Area Status, &apos;, &apos;&apos;)
),

&quot;&quot;)</formula>
        <label>Validation Combined</label>
        <type>Text</type>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ValidationCombined1__c</fullName>
        <formula>IF(
(ISBLANK(MailingCity) ||
ISBLANK(MailingState) ||
ISBLANK(MailingPostalCode) ||
ISPICKVAL(MaritalStatus__c, &apos;&apos;) ||
ISPICKVAL(Education__c, &apos;&apos;) ||
ISPICKVAL(FarmWorker__c, &apos;&apos;) ||
ISPICKVAL(ColoniasResidence__c, &apos;&apos;) ||
ISPICKVAL(DisabledStatus__c, &apos;&apos;) ||
ISBLANK(NumberOfDependents__c) ||
ISPICKVAL(PreferredLanguage__c, &apos;&apos;) || isInvalidZip__c || EvaluateHUDAMI__c) , 

(IF(ISBLANK(MailingCity), &apos;Mailing City, &apos;, &apos;&apos;) &amp;
IF(ISBLANK(MailingState), &apos;Mailing State, &apos;, &apos;&apos;) &amp;
IF(ISBLANK(MailingPostalCode), &apos;Mailing Zip/Postal Code, &apos;, &apos;&apos;) &amp;
IF(ISPICKVAL(MaritalStatus__c, &apos;&apos;), &apos;Marital Status, &apos;, &apos;&apos;) &amp;
IF(ISPICKVAL(Education__c, &apos;&apos;), &apos;Education, &apos;, &apos;&apos;) &amp;
IF(ISPICKVAL(FarmWorker__c, &apos;&apos;), &apos;Farm Worker, &apos;, &apos;&apos;) &amp;
IF(ISPICKVAL(ColoniasResidence__c, &apos;&apos;), &apos;Colonias Residence, &apos;, &apos;&apos;) &amp;
IF(ISPICKVAL(DisabledStatus__c, &apos;&apos;), &apos;Disabled Status, &apos;, &apos;&apos;) &amp;
IF(ISBLANK(NumberOfDependents__c), &apos;Number Of Dependents, &apos;, &apos;&apos;) &amp;
IF(ISPICKVAL(PreferredLanguage__c, &apos;&apos;), &apos;Preferred Language, &apos;, &apos;&apos;) &amp;
IF(isInvalidZip__c, &apos;Invalid Zip Code/County/Town Entered! &apos;, &apos;&apos;) &amp;
IF(EvaluateHUDAMI__c , &apos;Please Search County By Zip Code to Calculate HUD AMI&apos;,&apos;&apos;)), &quot;NO ERROR&quot;
)</formula>
        <label>Validation Combined1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ValidationCombined__c</fullName>
        <formula>IF(
    ISPICKVAL(Race__c, &apos;&apos;) ||
    ISPICKVAL(Ethnicity__c, &apos;&apos;) ||
    ISPICKVAL(HouseholdType__c, &apos;&apos;) ||
    ISBLANK(HouseholdSize__c) ||
    ISPICKVAL(RuralAreaStatus__c, &apos;&apos;) ||
    ISPICKVAL(EnglishProficiency__c, &apos;&apos;) ||
    AND(Not(ChoseNottoProvideIncome__c), OR(ISBLANK(HouseholdMonthlyIncome1__c), HouseholdMonthlyIncome1__c == 0)),
    
    &apos;Required field(s) missing: &apos; &amp;
    IF(ISPICKVAL(Race__c, &apos;&apos;), &apos;Race, &apos;, &apos;&apos;) &amp;
    IF(ISPICKVAL(Ethnicity__c, &apos;&apos;), &apos;Ethnicity, &apos;, &apos;&apos;) &amp;
    IF(ISPICKVAL(HouseholdType__c, &apos;&apos;), &apos;Household Type, &apos;, &apos;&apos;) &amp;
    IF(ISBLANK(HouseholdSize__c), &apos;Household Size, &apos;, &apos;&apos;) &amp;
    IF(ISPICKVAL(RuralAreaStatus__c, &apos;&apos;), &apos;Rural Area Status, &apos;, &apos;&apos;) &amp;
    IF(ISPICKVAL(EnglishProficiency__c, &apos;&apos;), &apos;English Proficiency, &apos;, &apos;&apos;) &amp;
    IF(AND(Not(ChoseNottoProvideIncome__c), OR(ISBLANK(HouseholdMonthlyIncome1__c), HouseholdMonthlyIncome1__c == 0)), &apos;Household Monthly Income &apos;, &apos;&apos;), &quot;&quot; )</formula>
        <label>Validation Combined</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/HUDValidationController.cls
public with sharing class HUDValidationController {

    @AuraEnabled(cacheable=true)
    public static String getValidationErrors(String sobjectName, String recordId){
        String NWC2NameSpace = Utility.getNwc2NameSpace();
        String errorString = '';
        if(String.isNotBlank(sobjectName) && String.isNotBlank(recordId)){
            String queryStr = '';
            
            if(sobjectName == 'Contact'){
                queryStr = 'SELECT Id, '+NWC2NameSpace+'ValidationCombined__c, '+NWC2NameSpace+'ValidationCombined1__c FROM ' + sobjectName + ' WHERE Id = \''+ recordId+'\'';
            } else if(sobjectName == NWC2NameSpace+'ClientCase__c' || sobjectName == NWC2NameSpace+'AgencyProfile__c'){
                queryStr = 'SELECT Id, '+NWC2NameSpace+'ValidationCombined__c, '+NWC2NameSpace+'ValidationCombined1__c FROM ' + sobjectName + ' WHERE Id = \''+ recordId+'\'';
            } else {
                queryStr = 'SELECT Id, '+NWC2NameSpace+'ValidationCombined__c FROM ' + sobjectName + ' WHERE Id = \''+ recordId+'\'';
            }
            
            List<SObject> rec = Database.query(queryStr);
            
            if(!rec.isEmpty() && (sobjectName == NWC2NameSpace+'ClientCase__c' || sobjectName == 'Contact' || sobjectName == NWC2NameSpace+'AgencyProfile__c')){
                if(String.isNotBlank(String.valueOf(rec[0].get(NWC2NameSpace+'ValidationCombined__c'))) && rec[0].get(NWC2NameSpace+'ValidationCombined1__c') != 'NO ERROR'){
                    errorString = String.valueOf(rec[0].get(NWC2NameSpace+'ValidationCombined__c')) + String.valueOf(rec[0].get(NWC2NameSpace+'ValidationCombined1__c'));
                } else if(String.isNotBlank(String.valueOf(rec[0].get(NWC2NameSpace+'ValidationCombined__c'))) && rec[0].get(NWC2NameSpace+'ValidationCombined1__c') == 'NO ERROR'){
                    errorString = String.valueOf(rec[0].get(NWC2NameSpace+'ValidationCombined__c'));
                } else if(String.isBlank(String.valueOf(rec[0].get(NWC2NameSpace+'ValidationCombined__c'))) && rec[0].get(NWC2NameSpace+'ValidationCombined1__c') != 'NO ERROR'){
                    errorString = 'Required field(s) missing: ' + String.valueOf(rec[0].get(NWC2NameSpace+'ValidationCombined1__c'));
                } else if(String.isBlank(String.valueOf(rec[0].get(NWC2NameSpace+'ValidationCombined__c'))) && rec[0].get(NWC2NameSpace+'ValidationCombined1__c') == 'NO ERROR'){
                    errorString = String.valueOf(rec[0].get(NWC2NameSpace+'ValidationCombined1__c'));
                }
            } else{
                errorString = String.valueOf(rec[0].get(NWC2NameSpace+'ValidationCombined__c'));
            }
            
            //return Database.query(queryStr);
        }
        
        return String.isNotBlank(errorString) ? errorString.removeEnd(',') : 'NO ERROR';
    }
}