objects/AgencyProfile__c.object
<CustomObject>
    <description>To store detailed information about the Agency, including their contact information, operational details, HUD Contact, HUD Office Executive, HUD Office Manager and other relevant attributes.</description>
    <fields>
        <fullName>AgencyFAXNumber__c</fullName>
        <description>Agency&apos;s Fax Number.</description>
        <label>Agency FAX Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>AgencyPhoneNumber__c</fullName>
        <description>Agency&apos;s primary phone number.</description>
        <label>Agency Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>AgencyTollFreePhone__c</fullName>
        <description>Agency&apos;s Toll-Free Number.</description>
        <label>Agency Toll Free Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>AgencyWebsite__c</fullName>
        <description>Agency’s web site URL (address).</description>
        <inlineHelpText>Web address of the NWO</inlineHelpText>
        <label>Agency Website</label>
        <type>Url</type>
    </fields>
    <label>Agency Profile</label>
    <nameField>
        <label>Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HUD9902FiscalYear__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>HUD 9902 Fiscal Year</label>
</CustomObject>

objects/IntegrationSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Integration Parameters and Settings</description>
    <fields>
        <fullName>AgencyID__c</fullName>
        <description>Agency ID</description>
        <label>Agency ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AgencyName__c</fullName>
        <description>Agency Name</description>
        <label>CMS Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMSPassword__c</fullName>
        <description>CMS Password</description>
        <label>CMS Password</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndpointURL__c</fullName>
        <description>Endpoint URL</description>
        <label>Endpoint URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <description>Password</description>
        <label>Password</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>Username</description>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VendorID__c</fullName>
        <description>Vendor ID</description>
        <label>Vendor ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Integration Settings</label>
</CustomObject>

objects/X9902__c.object
<CustomObject>
    <description>To store data and information related to HUD 9902 reporting, including fields for Generation and Submission statuses, and serves as the parent object for the 9902 Agency, 9902 Client, 9902 Counselor, and 9902 Summary objects.</description>
    <fields>
        <fullName>AgencyGenerationStatus__c</fullName>
        <label>Agency Profile Generation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AgencyProfile__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Profile information for the agency.</description>
        <inlineHelpText>Provide details if is a Agency profile</inlineHelpText>
        <label>Agency Profile</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ClientGenerationStatus__c</fullName>
        <label>Client Summary Generation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CounselorGenerationStatus__c</fullName>
        <label>Counselor Profile Generation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PeriodEndDate__c</fullName>
        <description>End date of the reporting period.</description>
        <label>Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Summary9902GenerationStatus__c</fullName>
        <label>9902 Summary Generation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>9902</label>
    <nameField>
        <displayFormat>HUD-{000000}</displayFormat>
        <label>9902</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>9902</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HudGenerateAndSubmitControllerTest.cls
@isTest
public class HudGenerateAndSubmitControllerTest {
    @testSetup static void dataSetup() {
        IntegrationSettings__c mc   = new IntegrationSettings__c();
        mc.Name = 'HUD Settings';
        mc.AgencyID__c = '123123';
        mc.EndpointURL__c = 'www.google.com'; 
        mc.VendorID__c = '123123';
        mc.AgencyName__c = 'TEST';
        mc.CMSPassword__c = 'test';
        mc.Username__c = 'test';
        mc.Password__c = 'test';
        insert mc;
        
        String currentYear = String.valueOf(Date.today().adddays(365).year());
        List<HUD9902FiscalYear__c> fiscalYear = TestDataFactory.createHUD9902FiscalYear(currentYear.subString(2), currentYear, 1, true);
        TestDataFactory.createHUD9902FiscalYear(currentYear.subString(2), String.valueOf(Date.today().year()), 1, true);
    
    }
    @isTest
    static void testExecuteSubmissionBatch1() {
        // Setup test data
        X9902__c x9902 = TestDataFactory.createX9902(1, false)[0];
        x9902.PeriodEndDate__c = Date.today().adddays(365);
        insert x9902;
        TestDataFactory.createX9902Agency(1,true,x9902.Id,'Profile');
        TestDataFactory.createX9902Agency(1,true,x9902.Id,'Contact');
        String reportId = x9902.Id;
        Map<String, Boolean> batchChecks = new Map<String, Boolean>{
            HudGenerateAndSubmitController.JOBKEY_AGENCY => true,
            HudGenerateAndSubmitController.JOBKEY_CLIENT => false,
            HudGenerateAndSubmitController.JOBKEY_COUNSELOR => false,
            HudGenerateAndSubmitController.JOBKEY_SUMMARY => false
        };
        
        // Call the method
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Map<String, String> result = HudGenerateAndSubmitController.executeSubmissionBatch(reportId, batchChecks);
        Test.stopTest();
        
        // Assert results
        //System.assertNotEquals(null, result.get(HudGenerateAndSubmitController.JOBKEY_AGENCY));
    }
    @isTest
    static void testExecuteSubmissionBatch2() {
        // Setup test data
        X9902__c x9902 = TestDataFactory.createX9902(1, false)[0];
        insert x9902;
        String reportId = x9902.Id;
        Map<String, Boolean> batchChecks = new Map<String, Boolean>{
            HudGenerateAndSubmitController.JOBKEY_AGENCY => false,
            HudGenerateAndSubmitController.JOBKEY_CLIENT => true,
            HudGenerateAndSubmitController.JOBKEY_COUNSELOR => false,
            HudGenerateAndSubmitController.JOBKEY_SUMMARY => false
        };
        
        // Call the method
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Map<String, String> result = HudGenerateAndSubmitController.executeSubmissionBatch(reportId, batchChecks);
        Test.stopTest();
        
        // Assert results
        //System.assertNotEquals(null, result.get(HudGenerateAndSubmitController.JOBKEY_AGENCY));
    }
    @isTest
    static void testExecuteSubmissionBatch3() {
        // Setup test data
        X9902__c x9902 = TestDataFactory.createX9902(1, false)[0];
        x9902.PeriodEndDate__c = Date.today();
        insert x9902;
        String reportId = x9902.Id;
        Map<String, Boolean> batchChecks = new Map<String, Boolean>{
            HudGenerateAndSubmitController.JOBKEY_AGENCY => false,
            HudGenerateAndSubmitController.JOBKEY_CLIENT => false,
            HudGenerateAndSubmitController.JOBKEY_COUNSELOR => true,
            HudGenerateAndSubmitController.JOBKEY_SUMMARY => false
        };
        
        // Call the method
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Map<String, String> result = HudGenerateAndSubmitController.executeSubmissionBatch(reportId, batchChecks);
        Test.stopTest();
        
        // Assert results
        //System.assertNotEquals(null, result.get(HudGenerateAndSubmitController.JOBKEY_AGENCY));
    }
    @isTest
    static void testExecuteSubmissionBatch4() {
        // Setup test data
        X9902__c x9902 = TestDataFactory.createX9902(1, false)[0];
        insert x9902;
        String reportId = x9902.Id;
        Map<String, Boolean> batchChecks = new Map<String, Boolean>{
            HudGenerateAndSubmitController.JOBKEY_AGENCY => false,
            HudGenerateAndSubmitController.JOBKEY_CLIENT => false,
            HudGenerateAndSubmitController.JOBKEY_COUNSELOR => false,
            HudGenerateAndSubmitController.JOBKEY_SUMMARY => true
        };
        
        // Call the method
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Map<String, String> result = HudGenerateAndSubmitController.executeSubmissionBatch(reportId, batchChecks);
        Test.stopTest();
        
        // Assert results
        //System.assertNotEquals(null, result.get(HudGenerateAndSubmitController.JOBKEY_AGENCY));
    }

    @isTest
    static void testExecuteBatch() {
        // Setup test data
        X9902__c x9902 = TestDataFactory.createX9902(1, false)[0];
        insert x9902;
        String reportId = x9902.id;
        
        AgencyProfile__c agencyProfile = new AgencyProfile__c();
        
        agencyProfile.Name = 'testAgency';
        agencyProfile.AgencyPhoneNumber__c = '1231231231';
        agencyProfile.AgencyTollFreePhone__c = '1231231231';
        agencyProfile.AgencyFAXNumber__c = '1231231231';
        agencyProfile.AgencyWebsite__c = 'http://www.google.com';
        insert agencyProfile;
        
        Map<String, Boolean> batchChecks = new Map<String, Boolean>{
            HudGenerateAndSubmitController.JOBKEY_AGENCY => true,
            HudGenerateAndSubmitController.JOBKEY_CLIENT => false,
            HudGenerateAndSubmitController.JOBKEY_COUNSELOR => false,
            HudGenerateAndSubmitController.JOBKEY_SUMMARY => false
        };
        
        // Call the method
        Test.startTest();
        Map<String, String> result = HudGenerateAndSubmitController.executeBatch(reportId, batchChecks);
        Test.stopTest();
        
        // Assert results
        //System.assertNotEquals(null, result.get(HudGenerateAndSubmitController.JOBKEY_CLIENT));
    }

    @isTest
    static void testGetJobDetails() {
        // Setup test data
        X9902__c x9902 = TestDataFactory.createX9902(1, false)[0];
        insert x9902;
        String reportId = x9902.Id;
        
        TestDataFactory.createX9902Agency(1,true,x9902.Id,'Profile');
        TestDataFactory.createX9902Agency(1,true,x9902.Id,'Contact');
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        HUD9902AgencySubmitBatch agencySubmitBatch = new HUD9902AgencySubmitBatch(reportId);
        String batchId = Database.executeBatch(agencySubmitBatch, 1);
        Map<String, String> batchJobMap = new Map<String, String>{
            HudGenerateAndSubmitController.JOBKEY_AGENCY => batchId,
            HudGenerateAndSubmitController.JOBKEY_CLIENT => batchId,
            HudGenerateAndSubmitController.JOBKEY_COUNSELOR => batchId,
            HudGenerateAndSubmitController.JOBKEY_SUMMARY => batchId
        };
        Map<String, Boolean> batchChecks = new Map<String, Boolean>{
            HudGenerateAndSubmitController.JOBKEY_AGENCY => true,
            HudGenerateAndSubmitController.JOBKEY_CLIENT => true,
            HudGenerateAndSubmitController.JOBKEY_COUNSELOR => true,
            HudGenerateAndSubmitController.JOBKEY_SUMMARY => true
        };
        
        // Call the method
        Test.startTest();
        Map<String, AsyncApexJob> result = HudGenerateAndSubmitController.getJobDetails(batchJobMap, batchChecks);
        Test.stopTest();
        
        // Assert results
        System.assertNotEquals(null, result.get(HudGenerateAndSubmitController.JOBKEY_AGENCY));
    }

    @isTest
    static void testGetValidationErrors() {
        // Setup test data
        String sobjectName = 'Contact';
        X9902__c x9902 = TestDataFactory.createX9902(1, false)[0];
        insert x9902;
        String reportId = x9902.Id;
        
        // Call the method
        Test.startTest();
        Map<String, List<SObject>> result = HudGenerateAndSubmitController.getValidationErrors(sobjectName, reportId);
        Test.stopTest();
        
        // Assert results
        System.assertNotEquals(null, result.get('Contact'));
    }
    
     @isTest
    static void testUpdate9902Status() {
        // Step 1: Create a test X9902__c record
        X9902__c x9902 = TestDataFactory.createX9902(1, false)[0];
        insert x9902;

        // Prepare the batchJobStatusMap and batchChecks
        Map<String, String> batchJobStatusMap = new Map<String, String>{
            'Agency' => 'Completed',
            'Client' => 'Failed',
            'Counselor' => 'Completed',
            'Summary' => 'In Progress'
        };
        Map<String, Boolean> batchChecks = new Map<String, Boolean>{
            'Agency' => true,
            'Client' => true,
            'Counselor' => true,
            'Summary' => true
        };

        // Serialize and Deserialize the Maps
        String batchJobStatusString = JSON.serialize(batchJobStatusMap);
        Map<String, String> deserializedBatchJobStatusMap = (Map<String, String>)JSON.deserialize(batchJobStatusString, Map<String, String>.class);

        String batchChecksString = JSON.serialize(batchChecks);
        Map<String, Boolean> deserializedBatchChecksMap = (Map<String, Boolean>)JSON.deserialize(batchChecksString, Map<String, Boolean>.class);

        Test.startTest();
        HudGenerateAndSubmitController.update9902Status(deserializedBatchJobStatusMap, deserializedBatchChecksMap, x9902.Id);
        Test.stopTest();
        x9902 = [SELECT Id, AgencyGenerationStatus__c, ClientGenerationStatus__c, CounselorGenerationStatus__c, Summary9902GenerationStatus__c FROM X9902__c WHERE Id = :x9902.Id];
        System.debug('Updated X9902__c record: ' + x9902);

        System.assertEquals('Completed', x9902.AgencyGenerationStatus__c);
    }
    
    
}