objects/AgencyProfile__c.object
<CustomObject>
    <description>To store detailed information about the Agency, including their contact information, operational details, HUD Contact, HUD Office Executive, HUD Office Manager and other relevant attributes.</description>
    <fields>
        <fullName>AgencyAddress__c</fullName>
        <label>Agency Address</label>
        <type>Address</type>
    </fields>
    <fields>
        <fullName>AgencyEmailAddress__c</fullName>
        <description>Agency&apos;s Email for public information and inquiries. Must be properly formatted as follows: xxx@xxx.xxx. When not available set value to &apos;N/A&apos;.</description>
        <label>Agency Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>AgencyPhoneNumber__c</fullName>
        <description>Agency&apos;s primary phone number.</description>
        <label>Agency Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>Agency Profile</label>
    <nameField>
        <label>Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FooterController.cls
/**
 * @description  : Class for footer Compass Portal Site
**/
public without sharing class FooterController {
	/**
    * @description : Method to get Agency Profile Data
    **/
    @AuraEnabled(cacheable=true)
    public static AgencyProfile__c getAgencyProfileDetails() {
        try {
            AgencyProfile__c agencyProfileRec = [SELECT Id, Name, AgencyEmailAddress__c	, AgencyPhoneNumber__c, AgencyAddress__c from AgencyProfile__c  LIMIT 1];
            
            return agencyProfileRec != null ? agencyProfileRec : NULL;
        } catch (Exception exe) { 
            LoggerClass.log(exe, null);
            throw new AuraHandledException(exe.getMessage());
        }
        
    }
}