objects/AgencyProfile__c.object
<CustomObject>
    <description>To store detailed information about the Agency, including their contact information, operational details, HUD Contact, HUD Office Executive, HUD Office Manager and other relevant attributes.</description>
    <fields>
        <fullName>AgencyEmailAddress__c</fullName>
        <description>Agency&apos;s Email for public information and inquiries. Must be properly formatted as follows: xxx@xxx.xxx. When not available set value to &apos;N/A&apos;.</description>
        <label>Agency Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>AgencyPhoneNumber__c</fullName>
        <description>Agency&apos;s primary phone number.</description>
        <label>Agency Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>Agency Profile</label>
    <nameField>
        <label>Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>ClientCaseName__c</fullName>
        <description>Concatenated of contact Last Name + First Letter of First Name + Date Created + Service Type</description>
        <formula>PrimaryClient__r.LastName + &quot;, &quot;+ IF(ISNULL(PrimaryClient__r.FirstName) ,&apos;&apos;,MID(PrimaryClient__r.FirstName, 0, 1)) + &quot; - &quot;+  text(DATEVALUE(CreatedDate)) +&quot; - &quot;+  CaseType__r.Name</formula>
        <label>Client Case Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HouseholdType__c</fullName>
        <label>Household Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MaritalStatus__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>HouseholdTypeHeadofHousehold</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <description>HUD-specified outcomes for Education only</description>
        <inlineHelpText>HUD-specified outcomes</inlineHelpText>
        <label>Outcome</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed financial literacy workshop, including home affordability, budgeting and understanding use of credit</fullName>
                </value>
                <value>
                    <fullName>Completed predatory lending, loan scam or other fraud prevention workshop</fullName>
                </value>
                <value>
                    <fullName>Completed fair housing workshop</fullName>
                </value>
                <value>
                    <fullName>Completed homelessness prevention workshop</fullName>
                </value>
                <value>
                    <fullName>Completed rental workshop</fullName>
                </value>
                <value>
                    <fullName>Completed pre-purchase homebuyer education workshop</fullName>
                </value>
                <value>
                    <fullName>Completed non-delinquency post-purchase workshop, including home maintenance and/or financial management for homeowners</fullName>
                </value>
                <value>
                    <fullName>Completed resolving or preventing mortgage delinquency workshop</fullName>
                </value>
                <value>
                    <fullName>Completed other workshop</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <description>Agency to custom relevant purposes</description>
        <inlineHelpText>Choose one most applicable value from the drop-down list</inlineHelpText>
        <label>HUD Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Homeless Assistance</fullName>
                </value>
                <value>
                    <fullName>Pre-purchase/Homebuying</fullName>
                </value>
                <value>
                    <fullName>Rental Topics</fullName>
                </value>
                <value>
                    <fullName>Non-Delinquency Post-Purchase</fullName>
                </value>
                <value>
                    <fullName>Reverse Mortgage</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Forward Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Reverse Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Disaster Preparedness Assistance</fullName>
                </value>
                <value>
                    <fullName>Disaster Recovery Assistance</fullName>
                </value>
                <value>
                    <fullName>Not HUD-Reportable</fullName>
                </value>
                <value>
                    <fullName>Financial Literacy</fullName>
                    <isActive>false</isActive>
                    <label>Financial Literacy</label>
                </value>
                <value>
                    <fullName>Home Improvement Loan</fullName>
                    <isActive>false</isActive>
                    <label>Home Improvement Loan</label>
                </value>
                <value>
                    <fullName>Home Purchase Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Home Purchase Inquiry</label>
                </value>
                <value>
                    <fullName>Job Training</fullName>
                    <isActive>false</isActive>
                    <label>Job Training</label>
                </value>
                <value>
                    <fullName>Mortgage Delinquency Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Mortgage Delinquency Inquiry</label>
                </value>
                <value>
                    <fullName>Rehab Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Rehab Inquiry</label>
                </value>
                <value>
                    <fullName>Rental Assistance</fullName>
                    <isActive>false</isActive>
                    <label>Rental Assistance</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>HouseholdType__c</fullName>
        <label>Household Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MaritalStatus__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>HouseholdTypeHeadofHousehold</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CounselorNote__c.object
<CustomObject>
    <description>To manage and document client case notes related client cases.</description>
    <fields>
        <fullName>ClientCaseName__c</fullName>
        <formula>ClientCase__r.ClientCaseName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Case Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Counselor Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Notes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration in Minutes</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndDateTime__c</fullName>
        <description>Calculate the end time based on start time and duration</description>
        <formula>StartDatetime__c +  (VALUE(TEXT(Duration__c))/1440)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>StartDatetime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Start Date/Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Counselor Note</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>Counselor Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counselor Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Calendar Event Information</relationshipLabel>
        <relationshipName>SUMOAdditionalInfo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>sumoapp__EventName__c</fullName>
        <label>Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Child Events</relationshipLabel>
        <relationshipName>ChildEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BOOKED</fullName>
                    <default>true</default>
                    <label>Booked</label>
                </value>
                <value>
                    <fullName>CANCELED</fullName>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>RESCHEDULED</fullName>
                    <label>Rescheduled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Attendance_Status__c</fullName>
        <label>Attendee Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Attended - Complete</fullName>
                </value>
                <value>
                    <fullName>Attended - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Course Complete</fullName>
                </value>
                <value>
                    <fullName>Course Incomplete</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <formula>TEXT( sumoapp__SumoEvent__r.HUD_Purpose__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outcome</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__EventName__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__EventName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__SumoEvent__c</fullName>
        <label>SUMO Event</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SUMO Attendee</label>
    <nameField>
        <displayFormat>ATD-{000000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/HouseholdTypeHeadofHousehold.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Single adult</fullName>
    </customValue>
    <customValue>
        <fullName>Female-headed single parent household</fullName>
    </customValue>
    <customValue>
        <fullName>Male-headed single parent household</fullName>
    </customValue>
    <customValue>
        <fullName>Married without dependents</fullName>
    </customValue>
    <customValue>
        <fullName>Married with dependents</fullName>
    </customValue>
    <customValue>
        <fullName>Two or more unrelated Adults</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Married with children</fullName>
        <isActive>false</isActive>
        <label>Married with children</label>
    </customValue>
    <customValue>
        <fullName>Male-headed single parent household/Head of Household</fullName>
        <isActive>false</isActive>
        <label>Male-headed single parent household/Head of Household</label>
    </customValue>
    <customValue>
        <fullName>Female-headed single parent household/Head of Household</fullName>
        <isActive>false</isActive>
        <label>Female-headed single parent household/Head of Household</label>
    </customValue>
    <customValue>
        <fullName>Domestic partnership</fullName>
        <isActive>false</isActive>
        <label>Domestic partnership</label>
    </customValue>
    <customValue>
        <fullName>Married without children</fullName>
        <isActive>false</isActive>
        <label>Married without children</label>
    </customValue>
    <masterLabel>Household Type/Head of Household</masterLabel>
</GlobalValueSet>

classes/ActivityTimelineContactPDFController.cls
/**
*Desc: An apex class controller for ActivityTimelinePDF data retrieving 
*/
public with sharing class ActivityTimelineContactPDFController {
    public Contact ContactObj                                   { get; set; }
    public List<ContactManagementEntry> appointments            { get; set; }
    public List<ContactManagementEntry> caseManagementNotes     { get; set; }
    public List<ContactManagementEntry> Courses                 { get; set; }
    public String CurrentDate                                   { get; set; }
    public AgencyProfile__c footer                              { get; set; }

    
    public class ContactManagementEntry {
        public String DateTimeDuration                          { get; set; }
        public String Status                                    { get; set; }
        public String PurposeAndOutcome                         { get; set; }
        public String Subject                                   { get; set; }
        public String Notes                                     { get; set; }
        public String CourseName                                { get; set; }
        public String Description                               { get; set; }
        
        // Constructor for Appointments
        public ContactManagementEntry(String DateTimeDuration, String Status, String Purpose, String Outcome, String Subject, String Notes) {
            this.DateTimeDuration   = DateTimeDuration;
            this.Status             = Status;
            this.PurposeAndOutcome  = (Purpose != null ? Purpose +' - ' : '') + (Outcome != null ? Outcome : '');
            this.Subject            = Subject;
            this.Notes              = Notes;
        }
        
        // Constructor for Notes
        public ContactManagementEntry(String DateTimeDuration, String Subject, String Notes) {
            this.DateTimeDuration   = DateTimeDuration;
            this.Subject            = Subject;
            this.Notes              = Notes;
        }
        
        // Constructor for Courses
        public ContactManagementEntry(String DateTimeDuration, String Status, String CourseName, String Description) {
            this.DateTimeDuration   = DateTimeDuration;
            this.Status             = Status;
            this.CourseName         = CourseName;
            this.Description        = Description;
        }
    }
    
    /**
*Desc: An apex class constructor for the data retrieving functionality
*/
    public ActivityTimelineContactPDFController() {
        try{
            Id ContactId = ApexPages.currentPage().getParameters().get('id');
            Datetime now = Datetime.now();
            String formattedDate = now.format('MM/dd/yyyy');
            CurrentDate = 'Printed on ' + formattedDate;
            if(ContactId != NULL){   
                List<AgencyProfile__c> AgencyDetailList = [SELECT Id, Name, AgencyEmailAddress__c, AgencyAddress__Street__s, AgencyAddress__City__s, AgencyAddress__PostalCode__s, AgencyAddress__StateCode__s, AgencyAddress__CountryCode__s, 
                                                           AgencyAddress__Latitude__s, AgencyPhoneNumber__c 
                                                           FROM AgencyProfile__c WITH SECURITY_ENFORCED Limit 1];
                if(!AgencyDetailList.isEmpty()){
                    footer = AgencyDetailList[0];
                }

                List<Contact> ContactList = [SELECT id, HouseholdType__c,Name 
                                             FROM Contact WHERE id =:ContactId Limit 1];
                if(!ContactList.isEmpty()){
                    ContactObj = ContactList[0];

                    appointments = new List<ContactManagementEntry>();
                    List<Event> caseEventsList = [SELECT Id, Subject, Purpose__c, AppointmentDuration__c, Outcome__c, sumoapp__AdditionalInfo__r.Notes__c, AppointmentStatus__c, ActivityDate, Description 
                                                  FROM Event where WhoId =:ContactId AND recordType.DeveloperName= 'Appointment' WITH SECURITY_ENFORCED ORDER BY ActivityDate DESC];
                    for(Event event: caseEventsList){
                        ContactManagementEntry tle = new ContactManagementEntry(getFormattedStartDatetime(event.ActivityDate, event.AppointmentDuration__c), event.AppointmentStatus__c, event.Purpose__c, event.Outcome__c, event.Subject , event.sumoapp__AdditionalInfo__r.Notes__c);
                        appointments.add(tle);
                    }  

                    caseManagementNotes = new List<ContactManagementEntry>();
                    List<CounselorNote__c> caseManagementNotesList = [SELECT Id, StartDatetime__c, ClientCaseName__c, ClientCase__c, Subject__c, Notes__c, EndDateTime__c, Contact__c, Duration__c 
                                                                      FROM CounselorNote__c WHERE Contact__c =:ContactId WITH SECURITY_ENFORCED ORDER BY StartDatetime__c DESC];
                    String DateOnly;
                    for(CounselorNote__c note: caseManagementNotesList){
                        ContactManagementEntry tle = new ContactManagementEntry(getFormattedStartDatetime(note.StartDatetime__c, note.Duration__c), note.Subject__c, note.Notes__c);
                        caseManagementNotes.add(tle);
                    }
                    
                    //sumoapp__Attendee__c  , Attendance_Status__c
                    List<sumoapp__Attendee__c> AttendeeList = [Select id,sumoapp__SumoEvent__c,Attendance_Status__c, sumoapp__SumoEvent__r.RecordType.DeveloperName,sumoapp__SumoEvent__r.sumoapp__Parent__r.sumoapp__EventName__c,sumoapp__Status__c,
                                                               sumoapp__SumoEvent__r.Name,sumoapp__EventName__c,sumoapp__StartDatetime__c,sumoapp__EndDatetime__c 
                                                               from sumoapp__Attendee__c where sumoapp__ContactRelation__c =:ContactId WITH SECURITY_ENFORCED];  
                    
                    Map<Id, sumoapp__Attendee__c> attendeeMap = new Map<Id, sumoapp__Attendee__c>();
                    for(sumoapp__Attendee__c Att: AttendeeList){
                        attendeeMap.put(Att.sumoapp__SumoEvent__c, Att);
                    }
                    
                    List<id> IdsOfCourse = new List<id>(attendeeMap.keySet());
                    
                    Courses = new List<ContactManagementEntry>();
                    List<sumoapp__AdditionalInfo__c > CoursesLists = [SELECT id, sumoapp__DurationInMinutes__c, sumoapp__StartDatetime__c, sumoapp__EventName__c, CourseLanguage__c,  
                                                                      sumoapp__Description__c, sumoapp__LocationType__c 
                                                                      FROM sumoapp__AdditionalInfo__c WHERE id IN :IdsOfCourse and IsParent__c=false WITH SECURITY_ENFORCED ORDER BY sumoapp__StartDatetime__c DESC];
                    
                    for(sumoapp__AdditionalInfo__c course: CoursesLists){
                        sumoapp__Attendee__c relatedAttendee = attendeeMap.get(course.Id);
                        String attendeeStatus = relatedAttendee != null ? relatedAttendee.Attendance_Status__c : null;
                        ContactManagementEntry tle = new ContactManagementEntry(getFormattedStartDatetime(course.sumoapp__StartDatetime__c, course.sumoapp__DurationInMinutes__c), attendeeStatus, course.sumoapp__EventName__c, course.sumoapp__Description__c);
                        Courses.add(tle);
                    }
                    
                }  
            }
        }
        catch (Exception e) {
            System.debug('Error in Constructor: ' + e.getMessage() + '\n' + e.getStackTraceString());
            throw new AuraHandledException('Error in Constructor: ' + e.getMessage());
        }    
    }
    
  /**
*Desc: Function to get only the Date
*/
     public static String getFormattedStartDatetime(DateTime DateTimeVar, Decimal Duration ) {
    String DateVal = DateTimeVar != null ? DateTimeVar.format('MM/dd/yyyy') : '';
    String TimeVal = DateTimeVar != null ? DateTimeVar.format('hh:mm a') : '';
    return (Duration != NULL) ? (DateVal + ' - ' + TimeVal + ' - ' + Duration + 'min') : (DateVal + ' - ' + TimeVal);
}
}