objects/AgencyProfile__c.object
<CustomObject>
    <description>To store detailed information about the Agency, including their contact information, operational details, HUD Contact, HUD Office Executive, HUD Office Manager and other relevant attributes.</description>
    <fields>
        <fullName>AgencyEmailAddress__c</fullName>
        <description>Agency&apos;s Email for public information and inquiries. Must be properly formatted as follows: xxx@xxx.xxx. When not available set value to &apos;N/A&apos;.</description>
        <label>Agency Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>AgencyPhoneNumber__c</fullName>
        <description>Agency&apos;s primary phone number.</description>
        <label>Agency Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>Agency Profile</label>
    <nameField>
        <label>Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>AnnualHouseholdIncome__c</fullName>
        <formula>HouseholdMonthlyIncome1__c * 12</formula>
        <label>Annual Household Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CaseTypeName__c</fullName>
        <formula>CaseType__r.Name</formula>
        <label>Case Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientCaseName__c</fullName>
        <description>Concatenated of contact Last Name + First Letter of First Name + Date Created + Service Type</description>
        <formula>PrimaryClient__r.LastName + &quot;, &quot;+ IF(ISNULL(PrimaryClient__r.FirstName) ,&apos;&apos;,MID(PrimaryClient__r.FirstName, 0, 1)) + &quot; - &quot;+  text(DATEVALUE(CreatedDate)) +&quot; - &quot;+  CaseType__r.Name</formula>
        <label>Client Case Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientCaseStatus__c</fullName>
        <defaultValue>(&quot;In Progress&quot;)</defaultValue>
        <description>In Progress: Open Case that is in progress and HUD reportable

Closed - Incomplete: Case closed without meeting the original outcome, HUD reportable

Closed - Service Complete: Case closed with meeting the original outcome, HUD reportable

On Hold: Case temporarily paused due to external factors or client request</description>
        <inlineHelpText>[1] In Progress: Case pending

[2] Closed - Incomplete: Didn’t meet original outcome

[3] Closed - Complete: Met the outcome

[4] On Hold: Case temporarily paused</inlineHelpText>
        <label>Client Case Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Closed - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Closed - Complete</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                    <isActive>false</isActive>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <isActive>false</isActive>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <isActive>false</isActive>
                    <label>Prospect</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <description>HUD-specified outcomes for Education only</description>
        <inlineHelpText>HUD-specified outcomes</inlineHelpText>
        <label>Outcome</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed financial literacy workshop, including home affordability, budgeting and understanding use of credit</fullName>
                </value>
                <value>
                    <fullName>Completed predatory lending, loan scam or other fraud prevention workshop</fullName>
                </value>
                <value>
                    <fullName>Completed fair housing workshop</fullName>
                </value>
                <value>
                    <fullName>Completed homelessness prevention workshop</fullName>
                </value>
                <value>
                    <fullName>Completed rental workshop</fullName>
                </value>
                <value>
                    <fullName>Completed pre-purchase homebuyer education workshop</fullName>
                </value>
                <value>
                    <fullName>Completed non-delinquency post-purchase workshop, including home maintenance and/or financial management for homeowners</fullName>
                </value>
                <value>
                    <fullName>Completed resolving or preventing mortgage delinquency workshop</fullName>
                </value>
                <value>
                    <fullName>Completed other workshop</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PrimaryClient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <description>Agency to custom relevant purposes</description>
        <inlineHelpText>Choose one most applicable value from the drop-down list</inlineHelpText>
        <label>HUD Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Homeless Assistance</fullName>
                </value>
                <value>
                    <fullName>Pre-purchase/Homebuying</fullName>
                </value>
                <value>
                    <fullName>Rental Topics</fullName>
                </value>
                <value>
                    <fullName>Non-Delinquency Post-Purchase</fullName>
                </value>
                <value>
                    <fullName>Reverse Mortgage</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Forward Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Reverse Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Disaster Preparedness Assistance</fullName>
                </value>
                <value>
                    <fullName>Disaster Recovery Assistance</fullName>
                </value>
                <value>
                    <fullName>Not HUD-Reportable</fullName>
                </value>
                <value>
                    <fullName>Financial Literacy</fullName>
                    <isActive>false</isActive>
                    <label>Financial Literacy</label>
                </value>
                <value>
                    <fullName>Home Improvement Loan</fullName>
                    <isActive>false</isActive>
                    <label>Home Improvement Loan</label>
                </value>
                <value>
                    <fullName>Home Purchase Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Home Purchase Inquiry</label>
                </value>
                <value>
                    <fullName>Job Training</fullName>
                    <isActive>false</isActive>
                    <label>Job Training</label>
                </value>
                <value>
                    <fullName>Mortgage Delinquency Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Mortgage Delinquency Inquiry</label>
                </value>
                <value>
                    <fullName>Rehab Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Rehab Inquiry</label>
                </value>
                <value>
                    <fullName>Rental Assistance</fullName>
                    <isActive>false</isActive>
                    <label>Rental Assistance</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReferralSource__c</fullName>
        <label>Referral Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ReferralSource</valueSetName>
        </valueSet>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AnnualHouseholdIncome__c</fullName>
        <formula>HouseholdMonthlyIncome1__c * 12</formula>
        <label>Annual Household Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ReferralSource__c</fullName>
        <label>Referral Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ReferralSource</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CounselorNote__c.object
<CustomObject>
    <description>To manage and document client case notes related client cases.</description>
    <fields>
        <fullName>ClientCaseName__c</fullName>
        <formula>ClientCase__r.ClientCaseName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Case Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Counselor Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Notes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration in Minutes</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndDateTime__c</fullName>
        <description>Calculate the end time based on start time and duration</description>
        <formula>StartDatetime__c +  (VALUE(TEXT(Duration__c))/1440)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>StartDatetime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Start Date/Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Counselor Note</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>Counselor Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counselor Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/ReferralSource.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Advertisement</fullName>
    </customValue>
    <customValue>
        <fullName>Employer</fullName>
    </customValue>
    <customValue>
        <fullName>Event</fullName>
    </customValue>
    <customValue>
        <fullName>Lender</fullName>
    </customValue>
    <customValue>
        <fullName>Mailer</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Partner Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Project Own App</fullName>
    </customValue>
    <customValue>
        <fullName>Realtor</fullName>
    </customValue>
    <customValue>
        <fullName>Walk-in</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <customValue>
        <fullName>Word of Mouth</fullName>
    </customValue>
    <customValue>
        <fullName>Referral</fullName>
        <isActive>false</isActive>
        <label>Referral</label>
    </customValue>
    <masterLabel>Referral Source</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/ActivityTimelineCasePDFController.cls
/**
*Desc: An apex class controller for ActivityTimelinePDF data retrieving 
*/

public with sharing class ActivityTimelineCasePDFController {
    public ClientCase__c caseObj 							{ get; set; }
    public List<caseManagementEntry > appointments 			{ get; set; }
    public List<caseManagementEntry > caseManagementNotes 	{ get; set; }
    public AgencyProfile__c footer 							{ get; set; }
    public String CurrentDate                               { get; set; }
    
    public class caseManagementEntry {
        public String DateTimeDuration 						{ get; set; }
        public String Status 								{ get; set; }
        public String PurposeAndOutcome 					{ get; set; }
        public String Subject 								{ get; set; }
        public String Notes 								{ get; set; }
        
        // Constructor for Appointments
        public caseManagementEntry(String DateTimeDuration, String Status, String Purpose, String Outcome, String Subject, String Notes) {
            this.DateTimeDuration 	= DateTimeDuration;
            this.Status				= Status;
            this.PurposeAndOutcome  = (Purpose != null ? Purpose : '') + ' - ' + (Outcome != null ? Outcome : '');
            this.Subject 			= Subject;
            this.Notes 				= Notes;
        }
        // Constructor for Notes
        public caseManagementEntry(String DateTimeDuration, String Subject, String Notes) {
            this.DateTimeDuration 	= DateTimeDuration;
            this.Subject 			= Subject;
            this.Notes 				= Notes;
        }
    }
    
    /**
*Desc: An apex class constructor for the data retrieving functionality
*/
    public ActivityTimelineCasePDFController() {
        try{
            Datetime now = Datetime.now();
            String formattedDate = now.format('MM/dd/yy');
            CurrentDate = 'Printed on ' + formattedDate;
            Id ClientCaseId = ApexPages.currentPage().getParameters().get('id');          
            List<AgencyProfile__c> AgencyDetailList = [SELECT Id, Name, AgencyEmailAddress__c, AgencyAddress__Street__s, AgencyAddress__City__s, AgencyAddress__PostalCode__s, AgencyAddress__StateCode__s, AgencyAddress__CountryCode__s, AgencyAddress__Latitude__s,  AgencyPhoneNumber__c FROM AgencyProfile__c WITH SECURITY_ENFORCED Limit 1];
            if(!AgencyDetailList.isEmpty()){
                footer = AgencyDetailList[0];
            }
            
            if(ClientCaseId != NULL){
                List<ClientCase__c> ClientCaseList = [SELECT id,CaseTypeName__c,ClientCaseStatus__c, PrimaryClient__r.Name, ReferralSource__c, AnnualHouseholdIncome__c FROM ClientCase__c WHERE id =:ClientCaseId WITH SECURITY_ENFORCED Limit 1];
                if(!ClientCaseList.isEmpty()){
                    caseObj = ClientCaseList[0];
                    
                    appointments = new List<caseManagementEntry>();
                    String DateOnly;
                    List<Event> caseEventsList = [SELECT Id, Subject, Purpose__c, Outcome__c, AppointmentStatus__c, sumoapp__AdditionalInfo__r.Notes__c, ActivityDate, AppointmentDuration__c, Description FROM Event where WhatId =:ClientCaseId AND recordType.DeveloperName= 'Appointment' WITH SECURITY_ENFORCED ORDER BY ActivityDate DESC];
                    for(Event event: caseEventsList){
                        caseManagementEntry tle = new caseManagementEntry(getFormattedStartDatetime(event.ActivityDate, event.AppointmentDuration__c), event.AppointmentStatus__c, event.Purpose__c, event.Outcome__c, event.Subject , event.sumoapp__AdditionalInfo__r.Notes__c);
                        appointments.add(tle);
                    } 
                    
                    caseManagementNotes = new List<caseManagementEntry>();
                    List<CounselorNote__c> caseManagementNotesList = [SELECT Id, StartDatetime__c, ClientCaseName__c, ClientCase__c, Subject__c, Notes__c, EndDateTime__c, Contact__c, Duration__c FROM CounselorNote__c WHERE ClientCase__c =:ClientCaseId WITH SECURITY_ENFORCED];            
                    for(CounselorNote__c note: caseManagementNotesList){
                        caseManagementEntry tle = new caseManagementEntry(getFormattedStartDatetime(note.StartDatetime__c, note.Duration__c), note.Subject__c, note.Notes__c);
                        caseManagementNotes.add(tle);
                    }
                }        
            }
        }catch (Exception e) {
            System.debug('Error in Constructor: ' + e.getMessage());
            throw new AuraHandledException('Error in Constructor: ' + e.getMessage());
        }    
    }
    
    /**
*Desc: Function to get only the Date
*/
    public static String getFormattedStartDatetime(DateTime DateTimeVar, Decimal Duration ) {
        String DateVal = DateTimeVar != null ? DateTimeVar.format('yyyy/MM/dd').substring(0, 10) : '';
        String TimeVal = DateTimeVar != null ? DateTimeVar.format('hh:mm a') : '';
        return (Duration != NULL) ? (DateVal + ' - ' + TimeVal + ' - ' + Duration + 'min') : (DateVal + ' - ' + TimeVal);
    } 
}