objects/AgencyProfile__c.object
<CustomObject>
    <description>To store detailed information about the Agency, including their contact information, operational details, HUD Contact, HUD Office Executive, HUD Office Manager and other relevant attributes.</description>
    <label>Agency Profile</label>
    <nameField>
        <label>Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>Facilitator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facilitator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__EndDatetime__c</fullName>
        <label>End Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__EventName__c</fullName>
        <label>Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__RecurringEndDate__c</fullName>
        <label>Recurring End Date</label>
        <type>Date</type>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__Attendee__c.object
<CustomObject>
    <fields>
        <fullName>CertificateNumber__c</fullName>
        <displayFormat>{0000000}</displayFormat>
        <label>Certificate Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>sumoapp__EndDatetime__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__EndDatetime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__EventName__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__EventName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__SumoEvent__c</fullName>
        <label>SUMO Event</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SUMO Attendee</label>
    <nameField>
        <displayFormat>ATD-{000000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CourseCompletionCertificateController.cls
public class CourseCompletionCertificateController {
    public String agencyName { get; set; }
    public String courseName { get; set; }
    public String completionDate { get; set; }
    public String participantName {get;set;}
    public String hudCounselourId {get;set;}
    public String certificateNumber {get;set;}
    public List<String> contactIds {get;set;}

    public CourseCompletionCertificateController() {
        String recIds = ApexPages.currentPage().getParameters().get('Ids');
        String attendeeId = ApexPages.currentPage().getParameters().get('attendeeId');
        
        if(recIds != NULL){
            participantName = '';
            List<String> ids = recIds.split(';;;;');
            contactIds = ids;
            List<Contact> conRec = [Select Id, Name from Contact where Id  IN :ids];
            for(Contact con : conRec){
                participantName += con.Name + ', ';
            }
            participantName = participantName.removeEndIgnoreCase(', ');
        }
        
        List<AgencyProfile__c> agencyRec = [Select id, name from AgencyProfile__c limit 1];
        
        if(agencyRec.size() > 0){
            agencyName = agencyRec[0].Name;
        }
        
        List<sumoapp__Attendee__c> attendeeRec = [Select Id, CertificateNumber__c, sumoapp__SumoEvent__c, sumoapp__SumoEvent__r.sumoapp__RecurringEndDate__c, sumoapp__SumoEvent__r.sumoapp__EndDatetime__c, sumoapp__SumoEvent__r.sumoapp__EventName__c, sumoapp__SumoEvent__r.Facilitator__r.CounselorHUDID__c from sumoapp__Attendee__c where Id =:attendeeId limit 1];
        
        if(attendeeRec.size() > 0 && attendeeRec[0].sumoapp__SumoEvent__c != NULL){
            courseName = attendeeRec[0].sumoapp__SumoEvent__r.sumoapp__EventName__c;
            certificateNumber = attendeeRec[0].CertificateNumber__c;
            hudCounselourId = (attendeeRec[0].sumoapp__SumoEvent__r.Facilitator__c != NULL && attendeeRec[0].sumoapp__SumoEvent__r.Facilitator__r.CounselorHUDID__c != NULL) ? 
                				attendeeRec[0].sumoapp__SumoEvent__r.Facilitator__r.CounselorHUDID__c : '';
            
            if(attendeeRec[0].sumoapp__SumoEvent__r.sumoapp__RecurringEndDate__c != NULL){
                completionDate = attendeeRec[0].sumoapp__SumoEvent__r.sumoapp__RecurringEndDate__c.format();
            } else if(attendeeRec[0].sumoapp__SumoEvent__r.sumoapp__EndDatetime__c != NULL){
                completionDate = Date.valueOf(attendeeRec[0].sumoapp__SumoEvent__r.sumoapp__EndDatetime__c).format();
            }
            
        }
    }
}