objects/AutomationBypass__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Switch Automations on or off.</description>
    <fields>
        <fullName>IntakeAutomationBypass__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Intake Automation Bypass</label>
        <type>Checkbox</type>
    </fields>
    <label>Automation Bypass</label>
</CustomObject>

objects/CaseType__c.object
<CustomObject>
    <description>To organize the various services provided by the Agency for their clients.</description>
    <label>Case Type</label>
    <nameField>
        <label>Case Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>CaseType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>HUD and NW reportable case types</description>
        <label>Case Type</label>
        <referenceTo>CaseType__c</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientCaseStatus__c</fullName>
        <defaultValue>(&quot;In Progress&quot;)</defaultValue>
        <description>In Progress: Open Case that is in progress and HUD reportable

Closed - Incomplete: Case closed without meeting the original outcome, HUD reportable

Closed - Service Complete: Case closed with meeting the original outcome, HUD reportable

On Hold: Case temporarily paused due to external factors or client request</description>
        <inlineHelpText>[1] In Progress: Case pending

[2] Closed - Incomplete: Didn’t meet original outcome

[3] Closed - Complete: Met the outcome

[4] On Hold: Case temporarily paused</inlineHelpText>
        <label>Client Case Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Closed - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Closed - Complete</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                    <isActive>false</isActive>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <isActive>false</isActive>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <isActive>false</isActive>
                    <label>Prospect</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IntakeCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intake Case</label>
        <referenceTo>Intake__c</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Intake__c.object
<CustomObject>
    <description>To capture and store initial information about clients/prospects during the intake process including New Intake, New Education Only, and New Emergency Triage.</description>
    <fields>
        <fullName>CaseType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Type</label>
        <referenceTo>CaseType__c</referenceTo>
        <relationshipName>Intakes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Intake</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UserServicesControllerTest.cls
@isTest
public class UserServicesControllerTest {
	@testSetup 
    static void testSetup() {
        TestDataFactory.createCaseTypes(5,true);
        AutomationBypass__c temp = new AutomationBypass__c ();
        temp.IntakeAutomationBypass__c =true;
        insert temp;
    }
    
    /**
     * @desc: Test Method to test retrieveClientCase method of controller.
     */
    public static testMethod void testRetrieveClientCase() {
        CaseType__c caseType = [SELECT id FROM CaseType__c LIMIT 1];
        UserServicesController.getDesiredServiceRecord(caseType.Id);
        Map<String, Object> desireServiceMap = UserServicesController.getDesiredServices();
        System.assert(desireServiceMap.containsKey('mapping'));
        System.assert(desireServiceMap.containsKey('records'));
        System.assertEquals(2, desireServiceMap.size());
    }
    
    /**
     * @desc: Test Method to test getDesiredServiceRecord method of controller.
     */
    public static testMethod void testGetDesiredServiceRecord() {
        CaseType__c caseType = [SELECT id FROM CaseType__c LIMIT 1];
        Map<String, Object> desireServiceMap = UserServicesController.getDesiredServiceRecord(caseType.Id);
        System.assert(desireServiceMap.containsKey('mapping'));
        System.assert(desireServiceMap.containsKey('records'));
        System.assertEquals(2, desireServiceMap.size());
        System.assertEquals(1, ((List<CaseType__c>)desireServiceMap.get('records')).size());
    }
    
    /**
     * @desc: Test Method to test getDesiredServiceRecord method of controller.
     */
    public static testMethod void testGetIntakeDetails() {
        CaseType__c caseType = [SELECT id FROM CaseType__c LIMIT 1];
        Intake__c intake = new Intake__c();
        intake.CaseType__c = caseType.Id;
        insert intake;
        
        ClientCase__c cc = new ClientCase__c();
        cc.IntakeCase__c = intake.Id;
        cc.ClientCaseStatus__c='In Progress';
        insert cc;
        
        UserServicesController.Wrapper result = UserServicesController.getIntakeDetails(intake.Id);
        System.assertNotEquals(NULL, result);
        System.assertEquals(cc.Id, result.caseClientId);
    }
    
    public static testMethod void testGetClientCaseDetails() {
        CaseType__c caseType = [SELECT id FROM CaseType__c LIMIT 1];
        Intake__c intake = new Intake__c();
        intake.CaseType__c = caseType.Id;
        insert intake;
        
        ClientCase__c cc = new ClientCase__c();
        cc.IntakeCase__c = intake.Id;
        cc.ClientCaseStatus__c='In Progress';
        insert cc;
        
        UserServicesController.Wrapper result = UserServicesController.getIntakeDetails(cc.Id);
        System.assertNotEquals(NULL, result);
        System.assertEquals(cc.Id, result.caseClientId);
    }
    
    @isTest
    static void testGetEnrolledServicesRecord() {
        Map<String, Object> result = new Map<String, Object>();
        Test.startTest();
        UserServicesController.getEnrolledServicesRecord();
        Test.stopTest();
    }
    
}