objects/AutomationBypass__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Switch Automations on or off.</description>
    <fields>
        <fullName>IntakeAutomationBypass__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Intake Automation Bypass</label>
        <type>Checkbox</type>
    </fields>
    <label>Automation Bypass</label>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HouseholdOfAMI__c</fullName>
        <label>Household % Of AMI</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>Number of people in the household</description>
        <inlineHelpText>Total number of people living in the same household</inlineHelpText>
        <label>Household Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MetropolitanStatisticalArea__c</fullName>
        <label>Metropolitan Statistical Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>CoApplicant</fullName>
        <active>true</active>
        <label>Co-Applicant</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/HUDAMIData__c.object
<CustomObject>
    <description>To store data related to Area Median Income (AMI) for various regions, including details such as area names, county names, FIPS codes, and HUD-specific identifiers for HUD AMI calculations.</description>
    <fields>
        <fullName>CountyName__c</fullName>
        <description>HUD Income Limit - Official County Name</description>
        <label>County Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MedianFamilyIncome__c</fullName>
        <description>Median Family Income (MFI) for area</description>
        <label>Median Family Income</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TownName__c</fullName>
        <description>Town Name for Income Limit purposes</description>
        <label>Town Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zipcode__c</fullName>
        <label>Zipcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p1__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 1 Persons in Household</description>
        <label>il30 p1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p2__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 2 Persons in Household</description>
        <label>il30 p2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p3__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 3 Persons in Household</description>
        <label>il30 p3</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p4__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 4 Persons in Household</description>
        <label>il30 p4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p1__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 1 Persons in Household</description>
        <label>il50 p1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p2__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 2 Persons in Household</description>
        <label>il50 p2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p3__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 3 Persons in Household</description>
        <label>il50 p3</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p4__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 4 Persons in Household</description>
        <label>il50 p4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p1__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 1 Persons in Household</description>
        <label>il80 p1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p2__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 2 Persons in Household</description>
        <label>il80 p2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p3__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 3 Persons in Household</description>
        <label>il80 p3</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p4__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 4 Persons in Household</description>
        <label>il80 p4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>HUD AMI Data</label>
    <nameField>
        <label>HUD AMI Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HUD AMI Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Intake__c.object
<CustomObject>
    <description>To capture and store initial information about clients/prospects during the intake process including New Intake, New Education Only, and New Emergency Triage.</description>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HouseholdMonthlyIncome__c</fullName>
        <label>Household Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HouseholdOfAMI__c</fullName>
        <label>Household % Of AMI</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <label>Household Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MetropolitanStatisticalArea__c</fullName>
        <label>Metropolitan Statistical Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MonthlyIncome__c</fullName>
        <label>Total Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Intake</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/IntakeTriggerHandlerTest.cls
@isTest
public class IntakeTriggerHandlerTest {
    
    @testSetup
    static void setupTestData() {

        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];

        List<HUDAMIData__c> hudamiDataList = TestDataFactory.createHUDAMIDataRecords(2, false);
        
        hudamiDataList[0].CountyName__c = 'County1';
        hudamiDataList[0].TownName__c = 'Town1';
        hudamiDataList[0].Zipcode__c = '12345';
        hudamiDataList[0].MedianFamilyIncome__c = '50000';
        hudamiDataList[0].il30p1__c = '20000';
        hudamiDataList[0].il30p2__c = '25000';
        hudamiDataList[0].il30p3__c = '30000';
        hudamiDataList[0].il50p1__c = '40000';
        hudamiDataList[0].il50p2__c = '45000';
        hudamiDataList[0].il50p3__c = '50000';
        hudamiDataList[0].il80p1__c = '60000';
        hudamiDataList[0].il80p2__c = '65000';
        hudamiDataList[0].il80p3__c = '70000';
        hudamiDataList[0].il30p4__c = '50000';
        hudamiDataList[0].il50p4__c = '60000';
        hudamiDataList[0].il80p4__c = '70000';
        
        hudamiDataList[1].CountyName__c = 'County2';
        hudamiDataList[1].TownName__c = 'Town2';
        hudamiDataList[1].Zipcode__c = '67890';
        hudamiDataList[1].MedianFamilyIncome__c = '60000';
        hudamiDataList[1].il30p2__c = '25000';
        hudamiDataList[1].il30p3__c = '30000';
        hudamiDataList[1].il50p1__c = '40000';
        hudamiDataList[1].il50p2__c = '45000';
        hudamiDataList[1].il50p3__c = '50000';
        hudamiDataList[1].il80p1__c = '60000';
        hudamiDataList[1].il80p2__c = '65000';
        hudamiDataList[1].il80p3__c = '70000';
        hudamiDataList[1].il30p4__c = '50000';
        hudamiDataList[1].il50p4__c = '60000';
        hudamiDataList[1].il80p4__c = '70000';
        
        insert hudamiDataList;

        
        AutomationBypass__c bypassSetting = new AutomationBypass__c(SetupOwnerId = p.Id, IntakeAutomationBypass__c = false);
        insert bypassSetting;
        
        List<Account> portalAccounts = TestDataFactory.createAccounts(1, true);
        List<Contact> ConList = TestDataFactory.createContacts(portalAccounts[0].Id, 2, true);
        Contact primaryContact = ConList[0];
        primaryContact.email = 'primary@example.com';
        primaryContact.FirstName = 'Primary';
        update primaryContact;
        Contact coApplicant = ConList[1];
        coApplicant.FirstName = 'CoApplicant';
        coApplicant.Email = 'coapplicant@example.com';
        coApplicant.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Co-Applicant').getRecordTypeId();
        update coApplicant;

    }
    
    public static Intake__c createIntake() {
        Contact con = [SELECT Id FROM Contact WHERE FirstName = 'CoApplicant'];
        Contact primaryContact = [SELECT Id FROM Contact WHERE FirstName = 'Primary'];
        Account acc = [SELECT Id FROM Account LIMIT 1];
        
        Intake__c newIntake = TestDataFactory.createIntakes(con, acc.Id, 1, false)[0];
        
        //Intake__c newIntake = intk;
        newIntake.Town__c = 'Town1';
        newIntake.County__c = 'County1'; 
        newIntake.Address__PostalCode__s = '12345'; 
        newIntake.HouseholdMonthlyIncome__c = 4000; 
        newIntake.HouseholdSize__c = 4;
        
        return newIntake;
    }
    
    @isTest
    static void testBeforeInsert() {
        Intake__c newIntake = createIntake();
        insert newIntake;
        
        Intake__c insertedIntake = [SELECT Id, County__c, Town__c, Address__PostalCode__s, MetropolitanStatisticalArea__c, HouseholdofAMI__c FROM Intake__c WHERE Id = :newIntake.Id];
        System.assertEquals('County1', insertedIntake.County__c);
        System.assertEquals('Town1', insertedIntake.Town__c);
    }
    
    @isTest
    static void testBeforeUpdate() {
        Intake__c newIntake = createIntake();
        insert newIntake;
        
        //newIntake.HouseholdMonthlyIncome__c = 4500;
        newIntake.Address__PostalCode__s = '67890';
        newIntake.MonthlyIncome__c = 3000;
        newIntake.HouseholdSize__c = 8;
        update newIntake;
        
        Intake__c updatedIntake = [SELECT Id, County__c, MonthlyIncome__c, Town__c, Address__PostalCode__s, MetropolitanStatisticalArea__c, HouseholdofAMI__c FROM Intake__c WHERE Id = :newIntake.Id];
        System.assertEquals(3000, updatedIntake.MonthlyIncome__c);
    }
    
    @isTest
    static void testBeforeUpdate2() {
        Intake__c newIntake = createIntake();
        insert newIntake;
        
        //newIntake.HouseholdMonthlyIncome__c = 4500;
        newIntake.Address__PostalCode__s = '67890112';
        newIntake.MonthlyIncome__c = 3000;
        newIntake.HouseholdSize__c = 8;
        update newIntake;
        
        Intake__c updatedIntake = [SELECT Id, County__c, MonthlyIncome__c, Town__c, Address__PostalCode__s, MetropolitanStatisticalArea__c, HouseholdofAMI__c FROM Intake__c WHERE Id = :newIntake.Id];
        System.assertEquals(3000, updatedIntake.MonthlyIncome__c);
    }
    
    @isTest
    static void testBeforeUpdate1() {
        Intake__c newIntake = createIntake();
        insert newIntake;
        
        newIntake.MonthlyIncome__c = 4500;
        update newIntake;
        
        Intake__c updatedIntake = [SELECT Id, County__c, MonthlyIncome__c, Town__c, Address__PostalCode__s, MetropolitanStatisticalArea__c, HouseholdofAMI__c FROM Intake__c WHERE Id = :newIntake.Id];
        System.assertEquals(4500, updatedIntake.MonthlyIncome__c);
    }
    
    @isTest
    static void testBypassAutomation() {
        AutomationBypass__c bypassSetting = [SELECT Id, IntakeAutomationBypass__c FROM AutomationBypass__c];
        bypassSetting.IntakeAutomationBypass__c = true;
        update bypassSetting;
        
        Intake__c newIntake = createIntake();
        insert newIntake;
        
        Intake__c insertedIntake = [SELECT Id, County__c, Town__c, Address__PostalCode__s FROM Intake__c WHERE Id = :newIntake.Id];
        System.assertEquals('County1', insertedIntake.County__c);
        System.assertEquals('Town1', insertedIntake.Town__c);
    }
    
    @isTest
    static void testAfterDelete() {
        Intake__c newIntake = createIntake();
        insert newIntake;
        delete newIntake;
        
        System.assert(true);
    }
}