objects/Budget__c.object
<CustomObject>
    <description>To store budget-related information used to create a detailed budget plan for clients.</description>
    <fields>
        <fullName>ClientCase__c</fullName>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BudgetDetailPageControllerTest.cls
@isTest
public class BudgetDetailPageControllerTest {
    @isTest
    static void testGetBudgetId() {
        ClientCase__c clientCase = TestDataFactory.createClientCases(1, true)[0];
  
        Budget__c budget = new Budget__c(clientcase__c = clientCase.Id);
        insert budget;
        String budgetId = BudgetDetailPageController.getBudgetId(clientCase.Id);
        System.assertEquals(budget.Id, budgetId, 'Expected Budget Id does not match');
        
        String budgetId1 = BudgetDetailPageController.getBudgetId('');
        //System.assertEquals('a1JW4000003g6VVMAY', budgetId);
    }
    @isTest
    static void testGetCurrencyFieldsList() {
        // Call the controller method
        String currencyFields = BudgetDetailPageController.getCurrencyFieldsList();
        System.assertNotEquals(null, currencyFields, 'Currency fields list should not be null');
        System.assertNotEquals('', currencyFields, 'Currency fields list should not be empty');
    }

    @IsTest
    static void verifyIsIntakeStaffUser() {
        Test.startTest();
        Boolean isIntakeStaffUser = BudgetDetailPageController.isIntakeStaffUser();
        Test.stopTest();
    }
}