objects/Budget__c.object
<CustomObject>
    <description>To store budget-related information used to create a detailed budget plan for clients.</description>
    <fields>
        <fullName>ClientCase__c</fullName>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HousingActualCost__c</fullName>
        <formula>ActualMortgageOrRent__c + ActualPhone__c + ActualElectricity__c +  ActualGas__c + ActualWaterAndSewer__c +  ActualWasteRemova__c +  ActualCable__c + ActualMaintenanceOrRepair__c + ActualSupplies__c + HousingActualOther__c +
ActualHomeOwnerAssoc__c
+
ActualHomeEquityLine__c
+ ActualHomeownerRentersInsurance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Housing Actual Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/cic_credit__Credit_Report__c.object
<CustomObject>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Credit Reports</relationshipLabel>
        <relationshipName>Credit_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cic_credit__Score__c</fullName>
        <label>Score</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Credit Report</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Credit Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/cic_credit__Credit_Score__c.object
<CustomObject>
    <fields>
        <fullName>cic_credit__Credit_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Report</label>
        <referenceTo>cic_credit__Credit_Report__c</referenceTo>
        <relationshipLabel>Credit Scores</relationshipLabel>
        <relationshipName>Credit_Scores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cic_credit__Relationship__c</fullName>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Borrower</fullName>
                </value>
                <value>
                    <fullName>Co Borrower</fullName>
                </value>
                <value>
                    <fullName>Joint</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>cic_credit__Score__c</fullName>
        <label>Score</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Credit Score</label>
    <nameField>
        <displayFormat>CS-{000000000}</displayFormat>
        <label>Credit Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Scores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientAsset__c.object
<CustomObject>
    <description>To track assets owned by clients.</description>
    <fields>
        <fullName>AccountBalance__c</fullName>
        <label>Account Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CashDeposit__c</fullName>
        <label>Cash Deposit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CashValue__c</fullName>
        <label>Cash Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Client Assets</relationshipLabel>
        <relationshipName>Client_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PresentMarketValue__c</fullName>
        <label>Present Market Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Client Asset</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>CreditScoreGoal__c</fullName>
        <label>Credit Score Goal</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CreditScore__c</fullName>
        <label>Credit Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CurrentMonthlyDebtObligationGoal__c</fullName>
        <label>Current Monthly Debt Obligation Goal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GrossMonthlyIncomeGoal__c</fullName>
        <label>Gross Monthly Income Goal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HousingExpense__c</fullName>
        <label>Housing Expense</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NetMonthlyIncomeGoal__c</fullName>
        <label>Net Monthly Income Goal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NetWorthGoal__c</fullName>
        <label>Net Worth Goal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PrimaryCoAppCreditScoreGoal__c</fullName>
        <label>Primary Co-App Credit Score Goal</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SavingsGoal__c</fullName>
        <label>Savings Goal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalAssetsGoal__c</fullName>
        <label>Total Assets Goal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalDebtGoal__c</fullName>
        <label>Total Debt Goal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/FinancialSnapshot__c.object
<CustomObject>
    <description>To store a detailed snapshot of a client&apos;s financial status, including current values and goals.</description>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Financial Snapshots</relationshipLabel>
        <relationshipName>FinancialSnapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CoAppCreditScore__c</fullName>
        <label>Co-App Credit Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CreditScore__c</fullName>
        <label>Median Credit Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CurrentMonthlyDebtObligation__c</fullName>
        <label>Current Household Monthly Creditor Debt</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GrossMonthlyIncome__c</fullName>
        <label>Gross Household Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HousingExpense__c</fullName>
        <label>Housing Expense</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NetMonthlyIncome__c</fullName>
        <label>Net Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NetWorth__c</fullName>
        <label>Net Worth</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Savings__c</fullName>
        <label>Current Savings</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalAssets__c</fullName>
        <label>Total Assets</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalDebt__c</fullName>
        <label>Total Household Debt</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Snapshot</label>
    <nameField>
        <label>Financial Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Income__c.object
<CustomObject>
    <description>To capture various sources of income for client cases. It tracks details such as income type (e.g., alimony, bonuses, child support, commissions), amounts (gross and net), and employment status.</description>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Income</relationshipLabel>
        <relationshipName>Income</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MonthlyGrossIncome__c</fullName>
        <label>Monthly Gross Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MonthlyNetIncome__c</fullName>
        <label>Monthly Net Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Income</label>
    <nameField>
        <label>Income Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Income</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Liability__c.object
<CustomObject>
    <description>To track financial liabilities associated with client cases.</description>
    <fields>
        <fullName>AccountBalance__c</fullName>
        <label>Account Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Liabilities</relationshipLabel>
        <relationshipName>Liabilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MinimumMonthlyPayment__c</fullName>
        <label>Minimum Monthly Payment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Liability</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Liability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateFinancialSnapshotsController.cls
/**
 * @description       : Controller Class for CreateFinancialSnapshot  & ClientFinancialMetrics Component.
 **/
public with sharing class CreateFinancialSnapshotsController {

    /**
     * @description       : Get Current Values.
    **/
    @AuraEnabled
    public static FinancialSnapshotWrapper getCurrentValues(String clientCaseId) {

        System.debug('clientCaseId 6 '+clientCaseId);
        FinancialSnapshotWrapper wrapper = new FinancialSnapshotWrapper();

        ClientCase__c clientCaseRec = [SELECT Id, CreditScore__c FROM ClientCase__c WHERE Id =: clientCaseId];
        System.debug('clientCaseRec '+clientCaseRec);

        if (clientCaseRec != null) {
            Decimal creditScoreVal = 0.00;
            if (clientCaseRec.CreditScore__c != null) {
                creditScoreVal = clientCaseRec.CreditScore__c;
            }
            wrapper.creditScore = creditScoreVal;

            List<cic_credit__Credit_Report__c> creditReportList = new List<cic_credit__Credit_Report__c>();
            creditReportList = [SELECT Id, ClientCase__c FROM cic_credit__Credit_Report__c WHERE ClientCase__c =: clientCaseId ORDER BY CreatedDate DESC];
            System.debug('creditReportList 27 @@ '+creditReportList);
            List<cic_credit__Credit_Score__c> creditScoreList = new List<cic_credit__Credit_Score__c>();
            if (!creditReportList.isEmpty()) {
                creditScoreList = [SELECT Id, cic_credit__Credit_Report__c, cic_credit__Relationship__c, cic_credit__Score__c FROM cic_credit__Credit_Score__c WHERE cic_credit__Relationship__c = 'Co Borrower' AND cic_credit__Credit_Report__c =: creditReportList[0].Id ORDER BY cic_credit__Score__c DESC];
                System.debug('creditScoreList 27 @@ '+creditScoreList);
                if (!creditScoreList.isEmpty()) {
                    if (creditScoreList.size() == 1) {
                        wrapper.coAppCreditScore = creditScoreList[0].cic_credit__Score__c;
                    } else if (creditScoreList.size() == 2) {
                        wrapper.coAppCreditScore = creditScoreList[0].cic_credit__Score__c;
                    } else if (creditScoreList.size() == 3) {
                        wrapper.coAppCreditScore = creditScoreList[1].cic_credit__Score__c;
                    }
                }
            }

            System.debug('creditReportList '+creditReportList);

            // wrapper.coAppCreditScore = 0.00;     // Hardcoded for now

            List<ClientAsset__c> clientAssetList = new List<ClientAsset__c>();
            clientAssetList = [SELECT AccountBalance__c, CashDeposit__c, PresentMarketValue__c, Value__c, CashValue__c FROM ClientAsset__c WHERE ClientCase__c =: clientCaseId];

            System.debug('clientAssetList '+clientAssetList);


            Decimal savingValue = 0.00;
            Decimal totalAssetValue = 0.00;
            for (ClientAsset__c clientAsset : clientAssetList) {
                if (clientAsset.AccountBalance__c != null) {
                    savingValue += clientAsset.AccountBalance__c;
                    totalAssetValue += clientAsset.AccountBalance__c;
                }
                if (clientAsset.CashDeposit__c != null) {
                    savingValue += clientAsset.CashDeposit__c;
                    totalAssetValue += clientAsset.CashDeposit__c;
                }

                if (clientAsset.PresentMarketValue__c != null) {
                    totalAssetValue += clientAsset.PresentMarketValue__c;
                }
                if (clientAsset.Value__c != null) {
                    totalAssetValue += clientAsset.Value__c;
                }
                if (clientAsset.CashValue__c != null) {
                    totalAssetValue += clientAsset.CashValue__c;
                }
            }

            wrapper.savings = savingValue;
            wrapper.totalAssets = totalAssetValue;

            List<Liability__c> liablityList = new List<Liability__c>();
            liablityList = [SELECT Id, AccountBalance__c, MinimumMonthlyPayment__c FROM Liability__c WHERE ClientCase__c =: clientCaseId];

            System.debug('liablityList '+liablityList);

            Decimal totalDebtValue = 0.00;
            Decimal currentMDeptOblValue = 0.00;

            for (Liability__c lbty : liablityList) {
                if (lbty.AccountBalance__c != null) {
                    totalDebtValue += lbty.AccountBalance__c;
                }
                if (lbty.MinimumMonthlyPayment__c != null) {
                    currentMDeptOblValue += lbty.MinimumMonthlyPayment__c;
                }
            }
            wrapper.currentlyMonthlyDebtObligation = currentMDeptOblValue;
            wrapper.totalDebt = totalDebtValue;

            List<Income__c> incomeList = new List<Income__c>();
            incomeList = [SELECT Id, MonthlyGrossIncome__c, MonthlyNetIncome__c FROM Income__c WHERE ClientCase__c =: clientCaseId];

            System.debug('incomeList '+incomeList);

            Decimal grossMonthlyIncomeVal = 0.00;
            Decimal netMonthlyIncomeVal = 0.00;
            for (Income__c income : incomeList) {
                if (income.MonthlyGrossIncome__c != null) {
                    grossMonthlyIncomeVal += income.MonthlyGrossIncome__c;
                }
                if (income.MonthlyNetIncome__c != null) {
                    netMonthlyIncomeVal += income.MonthlyNetIncome__c;
                }
            }

            wrapper.grossMonthlyIncome = grossMonthlyIncomeVal;
            wrapper.netMonthlyIncome = netMonthlyIncomeVal;

            List<Budget__c> budgetList = new List<Budget__c>();

            budgetList = [SELECT Id, HousingActualCost__c FROM Budget__c WHERE ClientCase__c =: clientCaseId ORDER BY CreatedDate DESC];
            System.debug('budgetList '+budgetList);
            if (!budgetList.isEmpty()) {
                wrapper.housingExpense = budgetList[0].HousingActualCost__c;
            }
            wrapper.netWorth = totalAssetValue - totalDebtValue;
        }
        System.debug('wrapper '+wrapper);

        if (wrapper != null) {
            System.debug('wrapper 92 '+wrapper);
            return wrapper;
        }
        return null;
    }

    /**
     * @description       : Save Financial Snapshot record with current values.
    **/
    @AuraEnabled
    public static String createFinancialSnapshot(FinancialSnapshot__c finSnapshot) {
        if (finSnapshot != null) {
            insert finSnapshot;
            return 'success';
        }
        return null;
    }

    /**
     * @description       : Fetch Financial Snapshot records and get Picklist values.
    **/
    @AuraEnabled
    public static FinancialSnapshotDetailsWrapper fetchFinancialSnapshots(String clientCaseId) {
        FinancialSnapshotDetailsWrapper detailWrapper = new FinancialSnapshotDetailsWrapper();
        List<PicklistValuesWrapper> wrapper = new List<PicklistValuesWrapper>();

        List<FinancialSnapshot__c> finSnapshotList = new List<FinancialSnapshot__c>();

        finSnapshotList = [SELECT Id, Name, ClientCase__c, CreditScore__c, CoAppCreditScore__c, Savings__c, GrossMonthlyIncome__c, NetMonthlyIncome__c, 
        CurrentMonthlyDebtObligation__c, HousingExpense__c, NetWorth__c, TotalAssets__c, TotalDebt__c FROM FinancialSnapshot__c WHERE ClientCase__c =: clientCaseId ORDER BY CreatedDate DESC];

        System.debug('finSnapshotList '+finSnapshotList);
        System.debug('finSnapshotList size '+finSnapshotList.size());

        for (FinancialSnapshot__c Snapshot : finSnapshotList) {
            PicklistValuesWrapper wrapperObj = new PicklistValuesWrapper();
            wrapperObj.label = Snapshot.Name;
            wrapperObj.value = Snapshot.Id;
            wrapper.add(wrapperObj);
        }
        
        if (!finSnapshotList.isEmpty()) {
            detailWrapper.financialSnapshotRecords = finSnapshotList;
        }
        if (!wrapper.isEmpty()) {
            detailWrapper.picklistValues = wrapper;
        }
        if (detailWrapper != null) {
            return detailWrapper;
        }
        return null;

    }

    /**
     * @description       : Fetch Financial Goals.
    **/
    @AuraEnabled
    public static ClientCase__c fetchGoals(String clientCaseId) {
        List<ClientCase__c> clientCaseList = new List<ClientCase__c>();
        clientCaseList = [SELECT Id, CreditScoreGoal__c, PrimaryCoAppCreditScoreGoal__c, SavingsGoal__c, TotalAssetsGoal__c, TotalDebtGoal__c, 
        NetWorthGoal__c, HousingExpense__c, NetMonthlyIncomeGoal__c, GrossMonthlyIncomeGoal__c, CurrentMonthlyDebtObligationGoal__c FROM ClientCase__c WHERE Id =: clientCaseId];

        if (!clientCaseList.isEmpty()) {
            return clientCaseList[0];
        }
        return null;
    }

    /**
     * @description       : Get Financial Metrics Details to show on Financial Metrics table.
    **/
    @AuraEnabled
    public static FinancialMetricsDetailWrapper getFinacialMetricsDetails(String clientCaseId) {

        FinancialMetricsDetailWrapper wrapper = new FinancialMetricsDetailWrapper();
        wrapper.currentValues = getCurrentValues(clientCaseId);
        wrapper.goal = fetchGoals(clientCaseId);

        if (wrapper != null) {
            return wrapper;
        }
        return null;
    }
    
    public class FinancialSnapshotWrapper {
        @AuraEnabled public Decimal creditScore;
        @AuraEnabled public String coAppCreditScore;
        @AuraEnabled public Decimal savings;
        @AuraEnabled public Decimal grossMonthlyIncome;
        @AuraEnabled public Decimal netMonthlyIncome;
        @AuraEnabled public Decimal currentlyMonthlyDebtObligation;
        @AuraEnabled public Decimal housingExpense;
        @AuraEnabled public Decimal netWorth;
        @AuraEnabled public Decimal totalDebt;
        @AuraEnabled public Decimal totalAssets;
    }

    public class FinancialMetricsDetailWrapper {
        @AuraEnabled public FinancialSnapshotWrapper currentValues;
        @AuraEnabled public ClientCase__c goal;
    }

    public class PicklistValuesWrapper {
        @AuraEnabled public String label;
        @AuraEnabled public String value;
        @AuraEnabled public List<FinancialSnapshot__c> financialSnapshotRecords;
    }

    public class FinancialSnapshotDetailsWrapper {
        @AuraEnabled public List<PicklistValuesWrapper> picklistValues;
        @AuraEnabled public List<FinancialSnapshot__c> financialSnapshotRecords;
    }
}