objects/CaseType__c.object
<CustomObject>
    <description>To organize the various services provided by the Agency for their clients.</description>
    <label>Case Type</label>
    <nameField>
        <label>Case Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>HouseholdType__c</fullName>
        <label>Household Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MaritalStatus__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>HouseholdTypeHeadofHousehold</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/HouseholdTypeHeadofHousehold.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Single adult</fullName>
    </customValue>
    <customValue>
        <fullName>Female-headed single parent household</fullName>
    </customValue>
    <customValue>
        <fullName>Male-headed single parent household</fullName>
    </customValue>
    <customValue>
        <fullName>Married without dependents</fullName>
    </customValue>
    <customValue>
        <fullName>Married with dependents</fullName>
    </customValue>
    <customValue>
        <fullName>Two or more unrelated Adults</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Married with children</fullName>
        <isActive>false</isActive>
        <label>Married with children</label>
    </customValue>
    <customValue>
        <fullName>Male-headed single parent household/Head of Household</fullName>
        <isActive>false</isActive>
        <label>Male-headed single parent household/Head of Household</label>
    </customValue>
    <customValue>
        <fullName>Female-headed single parent household/Head of Household</fullName>
        <isActive>false</isActive>
        <label>Female-headed single parent household/Head of Household</label>
    </customValue>
    <customValue>
        <fullName>Domestic partnership</fullName>
        <isActive>false</isActive>
        <label>Domestic partnership</label>
    </customValue>
    <customValue>
        <fullName>Married without children</fullName>
        <isActive>false</isActive>
        <label>Married without children</label>
    </customValue>
    <masterLabel>Household Type/Head of Household</masterLabel>
</GlobalValueSet>

classes/EmergencyTriageControllerTest.cls
@isTest
public class EmergencyTriageControllerTest {

    @testSetup static void setup() {
        TestDataFactory.createCaseTypes(3, true);
    }
    
    testMethod static void testGetCaseTypes() {
        EmergencyTriageController.getCaseTypes();
    }
    
    testMethod static void testStoreLeadIntake() {
        EmergencyTriageController.IntakeWrapper wrapper = new EmergencyTriageController.IntakeWrapper();
        Contact primaryContact = TestDataFactory.createContacts(null, 1, false).get(0);
        
        
        wrapper.contact =primaryContact;
       	wrapper.intakeCaseType = [Select Name from CaseType__c LIMIT 1]?.Name;
        
        EmergencyTriageController.storeLeadIntake(wrapper);
        
        
    }
    
    testMethod static void testStoreLeadIntakeException() {
        EmergencyTriageController.IntakeWrapper wrapper = new EmergencyTriageController.IntakeWrapper();
        Contact primaryContact = TestDataFactory.createContacts(null, 1, false).get(0);
        
		primaryContact.HouseholdType__c='Single';        
        wrapper.contact =primaryContact;
        
       	wrapper.intakeCaseType = [Select Name from CaseType__c LIMIT 1]?.Name;
        try{
        	EmergencyTriageController.storeLeadIntake(wrapper);    
        }catch(Exception ex) {
            
        }
        
        
        
    }
    
    testMethod static void testGetIntakeDetails() {
        Contact primaryContact = TestDataFactory.createContacts(null, 1, true).get(0);
        TestDataFactory.createIntakes(primaryContact, null, 2, true);
        EmergencyTriageController.getIntakeDetails(primaryContact.Id);
    }
}