objects/CaseType__c.object
<CustomObject>
    <description>To organize the various services provided by the Agency for their clients.</description>
    <label>Case Type</label>
    <nameField>
        <label>Case Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>CaseType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>HUD and NW reportable case types</description>
        <label>Case Type</label>
        <referenceTo>CaseType__c</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientCaseTask__c.object
<CustomObject>
    <description>To store tasks associated with client cases, typically as part of a Case Guidance Template.</description>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Client Case Task</relationshipLabel>
        <relationshipName>Client_Case_Task</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Not Started = Task has not been initiated
In Progress = Counselor is actively working on the task
Skipped = Counselor intentionally bypassed the task for this case - explain reason for skipping in comment field (if applicable)
Done = Counselor has finished the task successfully</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Skipped</fullName>
                </value>
                <value>
                    <fullName>Done</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Client Case Task</label>
    <nameField>
        <label>Client Case Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Case Task</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Log__c.object
<CustomObject>
    <description>To captures detailed information about exceptions and errors encountered in the system.</description>
    <fields>
        <fullName>ClassName__c</fullName>
        <label>ClassName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelatedToRecord__c</fullName>
        <label>Related To Record</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{0000000}</displayFormat>
        <label>Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ClientCaseGuidanceControllerTest.cls
/**
* @description    : Test Class for ClientCaseGuidanceController
**/
@IsTest
public with sharing class ClientCaseGuidanceControllerTest {
    @TestSetup
    static void makeData() {
        Account acc = TestDataFactory.createAccounts(1, true)[0];
        Contact con = TestDataFactory.createContacts(acc.Id, 1, true)[0];
        CaseType__c csType = new CaseType__c();
        insert csType;
        ClientCase__c clCase = TestDataFactory.createClientCases(1, true)[0];
        List<ClientCaseTask__c> clCaseTaskList = TestDataFactory.createClientCaseTasks(
            clCase,
            4,
            true
        );
    }
    
    @IsTest
    static void verifyStatusPicklist() {
        Test.startTest();
        List<Utility.PicklistOption> status = ClientCaseGuidanceController.getStatusPicklist();
        Test.stopTest();
        System.assert(status.size() > 0);
    }
    
    @IsTest
    static void verifyClientCaseTasks() {
        ClientCase__c clCase = [SELECT Id FROM ClientCase__c LIMIT 1];
        Test.startTest();
        List<ClientCaseTask__c> clCaseTasks = ClientCaseGuidanceController.getClientCaseTasks(
            clCase.Id
        );
        Test.stopTest();
        System.assertEquals(4, clCaseTasks.size());
    }
    
    @IsTest
    static void verifyUpdateClientCaseTask() {
        ClientCaseTask__c clCaseTask = [
            SELECT Id
            FROM ClientCaseTask__c
            WHERE Status__c = 'Not Started'
            LIMIT 1
        ];
        Test.startTest();
        ClientCaseGuidanceController.updateClientCaseTask(
            clCaseTask.Id,
            'Done',
            'Test to update Comment.'
        );
        Test.stopTest();
        List<ClientCaseTask__c> clCaseTaskList = [
            SELECT Id, Status__c, Comments__c
            FROM ClientCaseTask__c
            WHERE Id = :clCaseTask.Id
        ];
        System.assertEquals('Done', clCaseTaskList[0].Status__c);
        System.assertEquals(
            'Test to update Comment.',
            clCaseTaskList[0].Comments__c
        );
    }
    
    @IsTest
    static void verifyExceptionHandling() {
        Test.startTest();
        ClientCaseGuidanceController.updateClientCaseTask(
            'FAKE_ID',
            'Done',
            'Test to update Comment.'
        );
        Test.stopTest();
        List<Log__c> logs = [
            SELECT Id, ClassName__c, RelatedToRecord__c
            FROM Log__c
        ];
        System.assertEquals('FAKE_ID', logs[0].RelatedToRecord__c);
    }
    
    @IsTest
    static void verifyIsIntakeStaffUser() {
        Test.startTest();
        Boolean isIntakeStaffUser = ClientCaseGuidanceController.isIntakeStaffUser();
        Test.stopTest();
    }
}