objects/CaseType__c.object
<CustomObject>
    <description>To organize the various services provided by the Agency for their clients.</description>
    <label>Case Type</label>
    <nameField>
        <label>Case Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>HouseholdType__c</fullName>
        <label>Household Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MaritalStatus__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>HouseholdTypeHeadofHousehold</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MailingAddressLine2__c</fullName>
        <label>Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <description>Which HUD 9902-recognized race category the contact belongs to.</description>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RelationshipToPrimaryApplicant__c</fullName>
        <description>contact relationship to primary contact</description>
        <inlineHelpText>If applicable</inlineHelpText>
        <label>Relationship to Primary Applicant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Brother</fullName>
                </value>
                <value>
                    <fullName>Employer</fullName>
                </value>
                <value>
                    <fullName>Father</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Husband</fullName>
                </value>
                <value>
                    <fullName>Mother</fullName>
                </value>
                <value>
                    <fullName>Other Relative</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Sister</fullName>
                </value>
                <value>
                    <fullName>Step-Daughter</fullName>
                </value>
                <value>
                    <fullName>Wife</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/HouseholdTypeHeadofHousehold.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Single adult</fullName>
    </customValue>
    <customValue>
        <fullName>Female-headed single parent household</fullName>
    </customValue>
    <customValue>
        <fullName>Male-headed single parent household</fullName>
    </customValue>
    <customValue>
        <fullName>Married without dependents</fullName>
    </customValue>
    <customValue>
        <fullName>Married with dependents</fullName>
    </customValue>
    <customValue>
        <fullName>Two or more unrelated Adults</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Married with children</fullName>
        <isActive>false</isActive>
        <label>Married with children</label>
    </customValue>
    <customValue>
        <fullName>Male-headed single parent household/Head of Household</fullName>
        <isActive>false</isActive>
        <label>Male-headed single parent household/Head of Household</label>
    </customValue>
    <customValue>
        <fullName>Female-headed single parent household/Head of Household</fullName>
        <isActive>false</isActive>
        <label>Female-headed single parent household/Head of Household</label>
    </customValue>
    <customValue>
        <fullName>Domestic partnership</fullName>
        <isActive>false</isActive>
        <label>Domestic partnership</label>
    </customValue>
    <customValue>
        <fullName>Married without children</fullName>
        <isActive>false</isActive>
        <label>Married without children</label>
    </customValue>
    <masterLabel>Household Type/Head of Household</masterLabel>
</GlobalValueSet>

globalValueSets/Race.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>American Indian/Alaskan Native</fullName>
    </customValue>
    <customValue>
        <fullName>Asian</fullName>
    </customValue>
    <customValue>
        <fullName>Black or African American</fullName>
    </customValue>
    <customValue>
        <fullName>Native Hawaiian or Other Pacific Islander</fullName>
    </customValue>
    <customValue>
        <fullName>White</fullName>
    </customValue>
    <customValue>
        <fullName>More than one race</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Race</description>
    <masterLabel>Race</masterLabel>
</GlobalValueSet>

classes/EducationalIntakeControllerTest.cls
@isTest
public class EducationalIntakeControllerTest {

    @testSetup static void setup() {
        List<String> values = new List<String>{'Education','Homeless Assistance','Rental Topics','Prepurchase/Homebuying','Non-delinquency Post-Purchase','Reverse Mortgage','Resolving or Preventing Forward Mortgage Delinquency or Default','Resolving or Preventing Reverse Mortgage Delinquency or Default','Disaster Preparedness Assistance','Disaster Recovery Assistance','Financial Capability','Housing Stability Capability Program'};
            List<CaseType__c> recList = new List<CaseType__c>();
        for(String elt : values) {
            CaseType__c ct = new CaseType__c();
            ct.Name=elt;
            recList.add(ct);
        }
        
        insert recList;
    }
    
    
    testMethod static void testStoreIntakeForm() {
        EducationalIntakeController.EducationalIntakeWrapper wrap = new EducationalIntakeController.EducationalIntakeWrapper();
        wrap.contact = new Contact(FirstName='Test', LastName='Test',Email='tommy@dummy.com', Phone='9898989898', MailingStreet='Test Street', MailingCity='Test City',  MailingPostalCode='777777');
        
        
        Contact coApp = new Contact();
        coApp.FirstName='Test 2';
        coApp.LastName= 'Test 2';
        coApp.Email='john@dummy.com';
        coApp.Phone='9999999999';
        coApp.RelationshipToPrimaryApplicant__c='Brother';
        coApp.Race__c='Asian';
        
        
        wrap.contacts = new List<Contact>{coApp};
        
        EducationalIntakeController.storeEducationIntake(wrap);
        
        List<Contact> contact = [Select id, FirstName, LastName from Contact where Email='tommy@dummy.com'];
        System.assert(contact.size()>0,'Contact was not created');
        
        List<Contact> coApplicants = [Select id, FirstName, LastName from Contact where Email='john@dummy.com'];
        System.assert(coApplicants.size()>0,'Co Applicant was not created');
        
        EducationalIntakeController.getIntakeDetails(contact[0].Id);
        
    }

	testMethod static void testExceptionInStoreIntake() {
        EducationalIntakeController.EducationalIntakeWrapper wrap = new EducationalIntakeController.EducationalIntakeWrapper();
        wrap.contact = new Contact(FirstName='Test', LastName='Test',Email='tommy@dummy.com', Phone='9898989898', MailingStreet='Test Street', MailingCity='Test City',  MailingPostalCode='777777',MailingAddressLine2__c='Testing');
        
        
        Contact coApp = new Contact();
        coApp.FirstName='Test 2';
        coApp.LastName= 'Test 2';
        coApp.Email='john@dummy.com';
        coApp.Phone='99999999990';
        coApp.RelationshipToPrimaryApplicant__c='Brother';
        coApp.Race__c='Asian';
        coApp.MailingAddressLine2__c='Testing Address Line';
        coApp.HouseHoldType__c='Single Adult';
        
        
        wrap.contacts = new List<Contact>{coApp};
            try{
                EducationalIntakeController.storeEducationIntake(wrap);
            }catch(Exception ex) {
                
            }
        
       
        
        
    }   
    
}