objects/CaseType__c.object
<CustomObject>
    <description>To organize the various services provided by the Agency for their clients.</description>
    <fields>
        <fullName>HUDPurpose__c</fullName>
        <label>Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Homeless Assistance</fullName>
                </value>
                <value>
                    <fullName>Pre-purchase/Homebuying</fullName>
                </value>
                <value>
                    <fullName>Rental Topics</fullName>
                </value>
                <value>
                    <fullName>Non-Delinquency Post-Purchase</fullName>
                </value>
                <value>
                    <fullName>Reverse Mortgage</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Forward Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Reverse Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Disaster Preparedness Assistance</fullName>
                </value>
                <value>
                    <fullName>Disaster Recovery Assistance</fullName>
                </value>
                <value>
                    <fullName>Not HUD-Reportable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Type</label>
    <nameField>
        <label>Case Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>CaseResolutionDate__c</fullName>
        <label>Case Resolution Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CaseResolution__c</fullName>
        <label>Case Resolution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fulfilled (Purchased housing)</fullName>
                </value>
                <value>
                    <fullName>Suspended (Withdrew from counseling)</fullName>
                </value>
                <value>
                    <fullName>Entered Lease Purchase Pgm</fullName>
                </value>
                <value>
                    <fullName>Decided Not to Purchase</fullName>
                </value>
                <value>
                    <fullName>Counseled on HECM; Declined Mortgage</fullName>
                </value>
                <value>
                    <fullName>Referred to Other Agency</fullName>
                </value>
                <value>
                    <fullName>Obtained a HECM</fullName>
                </value>
                <value>
                    <fullName>Rcvd. Home Equity/Home Improvement Loan</fullName>
                </value>
                <value>
                    <fullName>Mortgage Refinanced</fullName>
                </value>
                <value>
                    <fullName>Sold House, Chose Alt. Housing Solution</fullName>
                </value>
                <value>
                    <fullName>Rcvd. Consumer Loan (Unsecured)</fullName>
                </value>
                <value>
                    <fullName>Obtained a Non-FHA Reverse Mortgage</fullName>
                </value>
                <value>
                    <fullName>Complete Financial Mgt/Budget Counseling</fullName>
                </value>
                <value>
                    <fullName>Complete Home Maintenance Counseling</fullName>
                </value>
                <value>
                    <fullName>Counseled and Utilities Brought Current</fullName>
                </value>
                <value>
                    <fullName>Counseled/Referred for Legal Assistance</fullName>
                </value>
                <value>
                    <fullName>Brought Mortgage Current</fullName>
                </value>
                <value>
                    <fullName>Initiated Forbearance Agreement</fullName>
                </value>
                <value>
                    <fullName>Executed Deed-in-lieu</fullName>
                </value>
                <value>
                    <fullName>Sold Property</fullName>
                </value>
                <value>
                    <fullName>Mortgage Foreclosed</fullName>
                </value>
                <value>
                    <fullName>Rcvd. 2nd Mortgage</fullName>
                </value>
                <value>
                    <fullName>Partial Claim</fullName>
                </value>
                <value>
                    <fullName>Mortgage Modified</fullName>
                </value>
                <value>
                    <fullName>Counseled/Referred to Agency</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>Pre-foreclosure Sale</fullName>
                </value>
                <value>
                    <fullName>Entered Debt Management Plan</fullName>
                </value>
                <value>
                    <fullName>Other (final result not listed above)</fullName>
                </value>
                <value>
                    <fullName>Found Alternative (Found alternative rental housing)</fullName>
                </value>
                <value>
                    <fullName>Increase access to credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CaseType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>HUD and NW reportable case types</description>
        <label>Case Type</label>
        <referenceTo>CaseType__c</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientCaseClosedDate__c</fullName>
        <description>Date the case is closed</description>
        <label>Client Case Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ClientCaseStatus__c</fullName>
        <defaultValue>(&quot;In Progress&quot;)</defaultValue>
        <description>In Progress: Open Case that is in progress and HUD reportable

Closed - Incomplete: Case closed without meeting the original outcome, HUD reportable

Closed - Service Complete: Case closed with meeting the original outcome, HUD reportable

On Hold: Case temporarily paused due to external factors or client request</description>
        <inlineHelpText>[1] In Progress: Case pending

[2] Closed - Incomplete: Didn’t meet original outcome

[3] Closed - Complete: Met the outcome

[4] On Hold: Case temporarily paused</inlineHelpText>
        <label>Client Case Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Closed - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Closed - Complete</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                    <isActive>false</isActive>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <isActive>false</isActive>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <isActive>false</isActive>
                    <label>Prospect</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DisabledStatus__c</fullName>
        <label>Disabled Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LastActivityType__c</fullName>
        <label>Last Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Appointment</fullName>
                </value>
                <value>
                    <fullName>Case Management Note</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <description>Agency to custom relevant purposes</description>
        <inlineHelpText>Choose one most applicable value from the drop-down list</inlineHelpText>
        <label>HUD Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Homeless Assistance</fullName>
                </value>
                <value>
                    <fullName>Pre-purchase/Homebuying</fullName>
                </value>
                <value>
                    <fullName>Rental Topics</fullName>
                </value>
                <value>
                    <fullName>Non-Delinquency Post-Purchase</fullName>
                </value>
                <value>
                    <fullName>Reverse Mortgage</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Forward Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Reverse Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Disaster Preparedness Assistance</fullName>
                </value>
                <value>
                    <fullName>Disaster Recovery Assistance</fullName>
                </value>
                <value>
                    <fullName>Not HUD-Reportable</fullName>
                </value>
                <value>
                    <fullName>Financial Literacy</fullName>
                    <isActive>false</isActive>
                    <label>Financial Literacy</label>
                </value>
                <value>
                    <fullName>Home Improvement Loan</fullName>
                    <isActive>false</isActive>
                    <label>Home Improvement Loan</label>
                </value>
                <value>
                    <fullName>Home Purchase Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Home Purchase Inquiry</label>
                </value>
                <value>
                    <fullName>Job Training</fullName>
                    <isActive>false</isActive>
                    <label>Job Training</label>
                </value>
                <value>
                    <fullName>Mortgage Delinquency Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Mortgage Delinquency Inquiry</label>
                </value>
                <value>
                    <fullName>Rehab Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Rehab Inquiry</label>
                </value>
                <value>
                    <fullName>Rental Assistance</fullName>
                    <isActive>false</isActive>
                    <label>Rental Assistance</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <recordTypes>
        <fullName>FinancialCapabilityCounseling</fullName>
        <active>true</active>
        <label>Financial Capability Counseling</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DisabledStatus__c</fullName>
        <label>Disabled Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Calendar Event Information</relationshipLabel>
        <relationshipName>SUMOAdditionalInfo</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/NWQRCounselingReportControllerTest.cls
@istest
public class NWQRCounselingReportControllerTest {
    
    @testSetup 
    static void testSetup() {
        string NWC2NameSpace = Utility.getNwc2NameSpace();
        string objectName = NWC2NameSpace + 'ClientCase__c';

        RecordType rtCC = [Select Id, DeveloperName from RecordType where SobjectType =: objectName And developerName = 'FinancialCapabilityCounseling'];
        Account acc = TestDataFactory.createAccounts(1, true)[0];
        Contact con = TestDataFactory.createContacts(acc.Id, 1, true)[0];
        CaseType__c ct = TestDataFactory.createCaseTypes(1,false)[0];
        ct.HUDPurpose__c = 'Homeless Assistance';
        insert ct;
        
        ClientCase__c cc = TestDataFactory.createClientCases(1,false)[0];
        cc.ClientCaseStatus__c = 'Closed - Complete';
        cc.RecordTypeId = rtCC.Id;
        cc.ClientCaseClosedDate__c = Date.Today();
        cc.Purpose__c = 'Homeless Assistance';
        cc.CaseResolution__c = 'Increase access to credit';
        cc.CaseResolutionDate__c = Date.Today();
        cc.DisabledStatus__c = 'No';
        cc.LastActivityType__c = 'Appointment';
        cc.CaseType__c = ct.Id;
        insert cc;
        
        sumoapp__AdditionalInfo__c info = TestDataFactory.createSumoEventInfo(1, true)[0];
        Event evt = TestDataFactory.createEvent(con, info.Id, 1, false)[0];
        evt.whoId = con.id;
        evt.Purpose__c = 'Resolving or Preventing Forward Mortgage Delinquency or Default';
        evt.StartDateTime = DateTime.now();
        evt.AppointmentStatus__c = 'Attended';
        evt.WhatId = cc.Id;
        insert evt;
	}
    
    static testMethod void testCounselingFetch(){
        
        Test.startTest();
        List<NWQRCounselingReportController.OrsReportWrapper> orsoutput = NWQRCounselingReportController.fetchOrsCounselingRecords(Date.Today() - 1,Date.Today() + 1);
        Test.StopTest();
        
        System.assertEquals(1,orsoutput.size());
    }

}