objects/CaseType__c.object
<CustomObject>
    <description>To organize the various services provided by the Agency for their clients.</description>
    <label>Case Type</label>
    <nameField>
        <label>Case Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>CaseType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>HUD and NW reportable case types</description>
        <label>Case Type</label>
        <referenceTo>CaseType__c</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientCaseName__c</fullName>
        <description>Concatenated of contact Last Name + First Letter of First Name + Date Created + Service Type</description>
        <formula>PrimaryClient__r.LastName + &quot;, &quot;+ IF(ISNULL(PrimaryClient__r.FirstName) ,&apos;&apos;,MID(PrimaryClient__r.FirstName, 0, 1)) + &quot; - &quot;+  text(DATEVALUE(CreatedDate)) +&quot; - &quot;+  CaseType__r.Name</formula>
        <label>Client Case Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientCaseStatus__c</fullName>
        <defaultValue>(&quot;In Progress&quot;)</defaultValue>
        <description>In Progress: Open Case that is in progress and HUD reportable

Closed - Incomplete: Case closed without meeting the original outcome, HUD reportable

Closed - Service Complete: Case closed with meeting the original outcome, HUD reportable

On Hold: Case temporarily paused due to external factors or client request</description>
        <inlineHelpText>[1] In Progress: Case pending

[2] Closed - Incomplete: Didn’t meet original outcome

[3] Closed - Complete: Met the outcome

[4] On Hold: Case temporarily paused</inlineHelpText>
        <label>Client Case Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Closed - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Closed - Complete</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                    <isActive>false</isActive>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <isActive>false</isActive>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <isActive>false</isActive>
                    <label>Prospect</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PrimaryClient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Intake__c.object
<CustomObject>
    <description>To capture and store initial information about clients/prospects during the intake process including New Intake, New Education Only, and New Emergency Triage.</description>
    <fields>
        <fullName>CaseType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Type</label>
        <referenceTo>CaseType__c</referenceTo>
        <relationshipName>Intakes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IntakeRequestName__c</fullName>
        <formula>PrimaryClient__r.LastName + &quot;, &quot;+ IF(ISNULL(PrimaryClient__r.FirstName) ,&apos;&apos;,MID(PrimaryClient__r.FirstName, 0, 1)) + &quot; - &quot;+ text(DATEVALUE(CreatedDate)) +&quot; - &quot;+ CaseType__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Intake Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryClient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Intake_Only</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Intake Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Open Intake</fullName>
                    <default>true</default>
                    <label>Open Intake</label>
                </value>
                <value>
                    <fullName>Open Case</fullName>
                </value>
                <value>
                    <fullName>Converted</fullName>
                    <isActive>false</isActive>
                    <label>Converted</label>
                </value>
                <value>
                    <fullName>New</fullName>
                    <isActive>false</isActive>
                    <label>New</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Intake</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Calendar Event Information</relationshipLabel>
        <relationshipName>SUMOAdditionalInfo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facilitator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facilitator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>sumoapp__EventName__c</fullName>
        <label>Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__LocationType__c</fullName>
        <label>Location Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Child Events</relationshipLabel>
        <relationshipName>ChildEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BOOKED</fullName>
                    <default>true</default>
                    <label>Booked</label>
                </value>
                <value>
                    <fullName>CANCELED</fullName>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>RESCHEDULED</fullName>
                    <label>Rescheduled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Attendance_Status__c</fullName>
        <label>Attendee Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Attended - Complete</fullName>
                </value>
                <value>
                    <fullName>Attended - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Course Complete</fullName>
                </value>
                <value>
                    <fullName>Course Incomplete</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>sumoapp__ContactRelation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Relation</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Event Attendees</relationshipLabel>
        <relationshipName>ContactEventAttendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__EventName__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__EventName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__StartDatetime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>CANCELED</fullName>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>COMPLIMENTARY</fullName>
                    <label>Complimentary</label>
                </value>
                <value>
                    <fullName>DECLINED</fullName>
                    <label>Declined</label>
                </value>
                <value>
                    <fullName>DRAFT</fullName>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>REFUNDED</fullName>
                    <label>Fully Refunded</label>
                </value>
                <value>
                    <fullName>PAID_MANUAL</fullName>
                    <label>Paid - Manual</label>
                </value>
                <value>
                    <fullName>PAID</fullName>
                    <label>Paid - Online</label>
                </value>
                <value>
                    <fullName>PARTIALLY_REFUNDED</fullName>
                    <label>Partially Refunded</label>
                </value>
                <value>
                    <fullName>BOOKED</fullName>
                    <default>true</default>
                    <label>Registered</label>
                </value>
                <value>
                    <fullName>WAITLISTED</fullName>
                    <label>Waitlisted</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sumoapp__SumoEvent__c</fullName>
        <label>SUMO Event</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SUMO Attendee</label>
    <nameField>
        <displayFormat>ATD-{000000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/IntakeCaseController.cls
/**
* @desc: Controller for intakeClientCase LWC component.
* Test class: IntakeCaseControllerTest
*/
public with sharing class IntakeCaseController {
    public static final String COURSE_RECORDTYPE_NAME='Course';
    /**
* @desc: Method to retrieve client cases related to contact Ids provided as an input.
*/
    @AuraEnabled(cacheable = true)
    public static List<ClientCase__c> retrieveClientCase(List<String> contactIds){
        List<String> newConList = new List<String>();
        for(String conId : contactIds){
            if(string.IsNotBlank(conId)){
                newConList.add(String.escapeSingleQuotes(conId));
            }
        }
        List<ClientCase__c> clientCase = [SELECT Id, ClientCaseName__c, OwnerId, Owner.Name, CaseType__c, CaseType__r.Name, ClientCaseStatus__c, LastModifiedDate FROM ClientCase__c Where PrimaryClient__c IN:newConList WITH SECURITY_ENFORCED];
        return clientCase;
    }
    
    
    @AuraEnabled(cacheable = true)
    public static List<Intake__c> retrieveIntakeRequests(List<String> contactIds){
        List<String> newConList = new List<String>();
        for(String conId : contactIds){
            if(string.IsNotBlank(conId)){
                newConList.add(String.escapeSingleQuotes(conId));
            }
            
        }
        List<Intake__c> clientCase = [SELECT Id, IntakeRequestName__c, OwnerId, Owner.Name, CaseType__c, CaseType__r.Name, Status__c, LastModifiedDate FROM Intake__c Where PrimaryClient__c IN:newConList WITH SECURITY_ENFORCED];
        return clientCase;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<CourseWrapper> getCourses(List<String> contactIds) {
        List<CourseWrapper> courses = new List<CourseWrapper>();
        List<Id> parentIds = new List<Id>();
        Map<id,sumoapp__Attendee__c> attendeeToEventMap = new Map<id,sumoapp__Attendee__c>();
        Map<Id, CourseWrapper> parentWrapperMap = new Map<id, CourseWrapper>();
        List<sumoapp__Attendee__c> attendeeList = new List<sumoapp__Attendee__c>([Select sumoapp__SumoEvent__r.sumoapp__Parent__c,Attendance_Status__c,Notes__c,sumoapp__Status__c,sumoapp__ContactRelation__r.Name,id,sumoapp__SumoEvent__c,sumoapp__SumoEvent__r.sumoapp__LocationType__c,sumoapp__SumoEvent__r.RecordType.DeveloperName,sumoapp__SumoEvent__r.sumoapp__Parent__r.sumoapp__EventName__c,sumoapp__SumoEvent__r.Name,sumoapp__EventName__c,sumoapp__StartDatetime__c,sumoapp__SumoEvent__r.Facilitator__r.Name from sumoapp__Attendee__c where sumoapp__ContactRelation__c in :contactIds order by sumoapp__StartDatetime__c]);
        Map<Id, sumoapp__Attendee__c> parentAttendanceStatusMap = getParentAttendanceStatusMap(attendeeList);
        for(sumoapp__Attendee__c attendee : attendeeList) {
            attendeeToEventMap.put(attendee.sumoapp__SumoEvent__c, attendee);
            if(attendee.sumoapp__SumoEvent__r.sumoapp__Parent__c==null && attendee.sumoapp__SumoEvent__r.RecordType.DeveloperName=='Event') {
                courses.add(storeAttendee(attendee));   
            } else if(attendee.sumoapp__SumoEvent__r.sumoapp__Parent__c!=null && attendee.sumoapp__SumoEvent__r.RecordType.DeveloperName=='Course') {
                if(parentWrapperMap.containsKey(attendee.sumoapp__SumoEvent__r.sumoapp__Parent__c)) {
                    CourseWrapper parentWrapper = parentWrapperMap.get(attendee.sumoapp__SumoEvent__r.sumoapp__Parent__c);
                    parentWrapper.children.add(storeAttendee(attendee));
                    if(attendee.sumoapp__StartDatetime__c!=null && parentWrapper.startDate>attendee.sumoapp__StartDatetime__c) {
                        parentWrapper.startDate = attendee.sumoapp__StartDatetime__c;
                    }
                } else {
                    CourseWrapper parentWrapper = new CourseWrapper();
                    parentWrapper.courseName = attendee.sumoapp__SumoEvent__r.sumoapp__Parent__r.sumoapp__EventName__c;
                    parentWrapper.startDate = attendee.sumoapp__StartDatetime__c;
                    parentWrapper.children = new list<CourseWrapper>{storeAttendee(attendee)};
                    parentWrapper.courseLink = '/'+attendee.sumoapp__SumoEvent__r.sumoapp__Parent__c;
                    parentWrapper.recordId = attendee.sumoapp__SumoEvent__r.sumoapp__Parent__c;
                    parentWrapper.status = parentAttendanceStatusMap.get(attendee.sumoapp__SumoEvent__r.sumoapp__Parent__c)?.Attendance_Status__c;
                    parentWrapper.notes=parentAttendanceStatusMap.get(attendee.sumoapp__SumoEvent__r.sumoapp__Parent__c)?.NOtes__c;
                    courses.add(parentWrapper);
                    parentWrapperMap.put(attendee.sumoapp__SumoEvent__r.sumoapp__Parent__c, parentWrapper);
                }
            }
            
        }
        
        System.debug('Key Set : '+parentWrapperMap.keySet());
        return courses;
    }
    
    public static CourseWrapper storeAttendee(sumoapp__Attendee__c attendee) {
        String recordTypeName = attendee?.sumoapp__SumoEvent__r?.RecordType?.DeveloperName;
        String relatedAdditionalName=attendee.sumoapp__EventName__c;
        CourseWrapper wrapper = new CourseWrapper();
        
        wrapper.courseName= (recordTypeName==COURSE_RECORDTYPE_NAME) ? attendee?.sumoapp__SumoEvent__r?.sumoapp__Parent__r?.sumoapp__EventName__c : relatedAdditionalName;
        if(String.isEmpty(wrapper.courseName)){
            wrapper.courseName = relatedAdditionalName;
        }
        wrapper.startDate = attendee.sumoapp__StartDatetime__c;
        wrapper.facilitator = attendee.sumoapp__SumoEvent__r?.Facilitator__r?.Name;
        wrapper.DeliveryType = attendee.sumoapp__SumoEvent__r?.sumoapp__LocationType__c;
        wrapper.courseLink = '/'+attendee.sumoapp__SumoEvent__c;
        wrapper.recordId = attendee.sumoapp__SumoEvent__c;
        wrapper.status = attendee.Attendance_Status__c;  //attendee.sumoapp__Status__c;
        wrapper.notes=attendee.Notes__c;
        return wrapper;
    }
    
    public static Map<ID, sumoapp__Attendee__c> getParentAttendanceStatusMap(List<sumoapp__Attendee__c> attendeeList) {
        Map<ID, sumoapp__Attendee__c> parentAttendeeMap = new Map<Id, sumoapp__Attendee__c>();
        for(sumoapp__Attendee__c attendee : attendeeList) {
            if(attendee.sumoapp__SumoEvent__r.sumoapp__Parent__c==null && attendee.sumoapp__SumoEvent__r.RecordType.DeveloperName=='Course') {
                parentAttendeeMap.put(attendee.sumoapp__SumoEvent__c, attendee);
            }
        }
        
        return parentAttendeeMap;
    }
    
    public class CourseWrapper{
        @AuraEnabled
        public String courseName{get;set;}
        @AuraENabled
        public DateTime startDate{get;set;}
        @AuraEnabled
        public String status{get;set;}
        @AuraEnabled
        public String notes{get;set;}
        @AuraEnabled
        public String facilitator{get;set;}
        @AuraENabled
        public String deliveryType{get;set;}
        @AuraEnabled
        public String courseLink{get;set;}
        @AuraEnabled
        public String recordId{get;set;}
        
        @AuraEnabled
        public List<CourseWrapper> children{get;set;}
    }
}