objects/CaseType__c.object
<CustomObject>
    <description>To organize the various services provided by the Agency for their clients.</description>
    <label>Case Type</label>
    <nameField>
        <label>Case Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseResolutionDate__c</fullName>
        <label>Case Resolution Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CaseSubType__c</fullName>
        <label>Case Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NW Rehab</fullName>
                    <default>true</default>
                    <label>NW Rehab</label>
                </value>
                <value>
                    <fullName>NW Refinance Non-Foreclosure</fullName>
                </value>
                <value>
                    <fullName>NW Client Other Based Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CaseType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>HUD and NW reportable case types</description>
        <label>Case Type</label>
        <referenceTo>CaseType__c</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientCaseClosedDate__c</fullName>
        <description>Date the case is closed</description>
        <label>Client Case Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ClientCaseStatus__c</fullName>
        <defaultValue>(&quot;In Progress&quot;)</defaultValue>
        <description>In Progress: Open Case that is in progress and HUD reportable

Closed - Incomplete: Case closed without meeting the original outcome, HUD reportable

Closed - Service Complete: Case closed with meeting the original outcome, HUD reportable

On Hold: Case temporarily paused due to external factors or client request</description>
        <inlineHelpText>[1] In Progress: Case pending

[2] Closed - Incomplete: Didn’t meet original outcome

[3] Closed - Complete: Met the outcome

[4] On Hold: Case temporarily paused</inlineHelpText>
        <label>Client Case Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Closed - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Closed - Complete</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                    <isActive>false</isActive>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <isActive>false</isActive>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <isActive>false</isActive>
                    <label>Prospect</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClientNumber__c</fullName>
        <description>Client Number pulled from Household</description>
        <formula>Household__r.ClientNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HealthCrisisNatDisasClimateResil__c</fullName>
        <inlineHelpText>Was this service provided in direct response to a public health crisis, or a natural disaster, or to increase or improve climate resilience?</inlineHelpText>
        <label>Health Crisis/Nat Disas/Climate Resil?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>NWORole__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Natural Disaster</fullName>
                </value>
                <value>
                    <fullName>Public Health Crisis</fullName>
                </value>
                <value>
                    <fullName>Increase or improve climate resilience</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IntakeDate__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Date the agency performed intake for the client.</description>
        <label>Intake Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PrimaryClient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <description>Agency to custom relevant purposes</description>
        <inlineHelpText>Choose one most applicable value from the drop-down list</inlineHelpText>
        <label>HUD Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Homeless Assistance</fullName>
                </value>
                <value>
                    <fullName>Pre-purchase/Homebuying</fullName>
                </value>
                <value>
                    <fullName>Rental Topics</fullName>
                </value>
                <value>
                    <fullName>Non-Delinquency Post-Purchase</fullName>
                </value>
                <value>
                    <fullName>Reverse Mortgage</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Forward Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Reverse Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Disaster Preparedness Assistance</fullName>
                </value>
                <value>
                    <fullName>Disaster Recovery Assistance</fullName>
                </value>
                <value>
                    <fullName>Not HUD-Reportable</fullName>
                </value>
                <value>
                    <fullName>Financial Literacy</fullName>
                    <isActive>false</isActive>
                    <label>Financial Literacy</label>
                </value>
                <value>
                    <fullName>Home Improvement Loan</fullName>
                    <isActive>false</isActive>
                    <label>Home Improvement Loan</label>
                </value>
                <value>
                    <fullName>Home Purchase Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Home Purchase Inquiry</label>
                </value>
                <value>
                    <fullName>Job Training</fullName>
                    <isActive>false</isActive>
                    <label>Job Training</label>
                </value>
                <value>
                    <fullName>Mortgage Delinquency Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Mortgage Delinquency Inquiry</label>
                </value>
                <value>
                    <fullName>Rehab Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Rehab Inquiry</label>
                </value>
                <value>
                    <fullName>Rental Assistance</fullName>
                    <isActive>false</isActive>
                    <label>Rental Assistance</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RehabAmount__c</fullName>
        <formula>IF( OR(RecordType.DeveloperName = &apos;MortgageDelinquencyAssistanceCounseling&apos;, RecordType.DeveloperName = &apos;ReverseMortgageCounseling&apos;), RehabCost__c,
IF(RecordType.DeveloperName = &apos;PrepurchaseHomebuyingCounseling&apos;, RehabConstCostNotincinPrice__c + RehabConstrCostsincinPrice__c, IF(RecordType.DeveloperName = &apos;HomeownerCounseling&apos;, IF( ISPICKVAL(CaseSubType__c, &apos;NW Rehab&apos;) , 0,
IF(ISPICKVAL(CaseSubType__c, &apos;NW Refinance Non-Foreclosure&apos;), RehabConstCostNotincinPrice__c + RehabConstrCostsincinPrice__c,
IF(ISPICKVAL(CaseSubType__c, &apos;NW Client Other Based Services&apos;), ServiceCost__c,RehabCost__c))), RehabCost__c)) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rehab Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ServiceCost__c</fullName>
        <label>Service Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label># of Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <recordTypes>
        <fullName>HomeownerCounseling</fullName>
        <active>true</active>
        <label>Homeowner Counseling</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <formula>YEAR(TODAY()) - YEAR(Birthdate) - IF(MONTH(TODAY()) * 100 + DAY(TODAY()) &lt; MONTH(Birthdate) * 100 + DAY(Birthdate), 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ForeclosureIntakeReportController.cls
/**
 * @description       : Controller of ForeclosureIntakeReport lwc for NWQR reporting
 * @group             : 
**/
public with sharing class ForeclosureIntakeReportController {

    /*
    * @description : method to fetch Dara for Total Owner-Occupied Units Repaired
    */
    @AuraEnabled
    public static List<DetailReportWrapper> fetchTable1Data(Date qtrStartDate,Date qtrEndDate, Integer pageNumber){
        Integer offSet = 10 * pageNumber;
        List<ClientCase__c> clientCaselst = [select id, CaseType__c, RehabAmount__c, HealthCrisisNatDisasClimateResil__c, Age__c, 
                                            ClientNumber__c, Name, CaseResolutionDate__c, PrimaryClient__r.Name, IntakeDate__c, Units__c, ClientCaseStatus__c,  Purpose__c, RecordType.developerName, ServiceCost__c
                                            from ClientCase__c 
                                            where ClientCaseClosedDate__c <=: qtrEndDate and ClientCaseClosedDate__c >=: qtrStartDate
                                            And RecordType.developerName = 'HomeownerCounseling' and RehabAmount__c >= 100 and RehabAmount__c < 2000 And Purpose__c = 'Non-Delinquency Post-Purchase'
                                            WITH SECURITY_ENFORCED limit 10 OFFSET : offSet];
        List<DetailReportWrapper> tableData = prepareTableData(clientCaselst);
        return tableData;
    }

    /*
    * @description : method to fetch Dara for Out of your total Owner-Occupied Units Repaired, how many have seniors as the head of household
    */
    @AuraEnabled
    public static List<DetailReportWrapper> fetchTable2Data(Date qtrStartDate,Date qtrEndDate, Integer pageNumber){
        Integer offSet = 10 * pageNumber;
        List<ClientCase__c> clientCaselst = [select id, CaseType__c, RehabAmount__c, HealthCrisisNatDisasClimateResil__c, Age__c, 
                                            ClientNumber__c, Name, CaseResolutionDate__c, PrimaryClient__r.Name, IntakeDate__c, Units__c, ClientCaseStatus__c,  Purpose__c, RecordType.developerName, ServiceCost__c
                                            from ClientCase__c 
                                            where ClientCaseClosedDate__c <=: qtrEndDate and ClientCaseClosedDate__c >=: qtrStartDate
                                            And RecordType.developerName = 'HomeownerCounseling' and RehabAmount__c >= 100 and RehabAmount__c < 2000 And Purpose__c = 'Non-Delinquency Post-Purchase'
                                            And Age__c >= 62
                                            WITH SECURITY_ENFORCED limit 10 OFFSET : offSet];

        List<DetailReportWrapper> tableData = prepareTableData(clientCaselst);
        return tableData;
    }

    /*
    * @description : method to fetch Dara for Out of your total Owner-Occupied Units Repaired, how many were repaired in direct response to a public health crisis or a natural disaster, or to increase or improve climate resilience?
    */
    @AuraEnabled
    public static List<DetailReportWrapper> fetchTable3Data(Date qtrStartDate,Date qtrEndDate, Integer pageNumber){
        Integer offSet = 10 * pageNumber;
        List<ClientCase__c> clientCaselst = [select id, CaseType__c, RehabAmount__c, HealthCrisisNatDisasClimateResil__c, Age__c, 
                                            ClientNumber__c, Name, CaseResolutionDate__c, PrimaryClient__r.Name, IntakeDate__c, Units__c, ClientCaseStatus__c,  Purpose__c, RecordType.developerName, ServiceCost__c
                                            from ClientCase__c 
                                            where ClientCaseClosedDate__c <=: qtrEndDate and ClientCaseClosedDate__c >=: qtrStartDate 
                                            And RecordType.developerName = 'HomeownerCounseling' and RehabAmount__c >= 100 and RehabAmount__c < 2000 And Purpose__c = 'Non-Delinquency Post-Purchase'
                                            And HealthCrisisNatDisasClimateResil__c != null
                                            WITH SECURITY_ENFORCED limit 10 OFFSET : offSet];

        List<DetailReportWrapper> tableData = prepareTableData(clientCaselst);
        return tableData;
    }

    /*
    * @description : method to fetch Dara for Out of your total Owner-Occupied Units Repaired, how many were repaired to increase or improve climate resilience?
    */
    @AuraEnabled
    public static List<DetailReportWrapper> fetchTable4Data(Date qtrStartDate,Date qtrEndDate, Integer pageNumber){
        Integer offSet = 10 * pageNumber;
        List<ClientCase__c> clientCaselst = [select id, CaseType__c, RehabAmount__c, HealthCrisisNatDisasClimateResil__c, Age__c, 
                                            ClientNumber__c, Name, CaseResolutionDate__c, PrimaryClient__r.Name, IntakeDate__c, Units__c, ClientCaseStatus__c,  Purpose__c, RecordType.developerName, ServiceCost__c
                                            from ClientCase__c 
                                            where ClientCaseClosedDate__c <=: qtrEndDate and ClientCaseClosedDate__c >=: qtrStartDate 
                                            And RecordType.developerName = 'HomeownerCounseling' and RehabAmount__c >= 100 and RehabAmount__c < 2000 And Purpose__c = 'Non-Delinquency Post-Purchase'
                                            And HealthCrisisNatDisasClimateResil__c = 'Increase or improve climate resilience'
                                            WITH SECURITY_ENFORCED limit 10 OFFSET : offSet];

        List<DetailReportWrapper> tableData = prepareTableData(clientCaselst);
        return tableData;
    }

    /*
    * @description : method to fetch Dara for Total Owner-Occupied Units Repaired
    */
    @AuraEnabled
    public static List<DetailReportWrapper> fetchTable5Data(Date qtrStartDate,Date qtrEndDate, Integer pageNumber){
        Integer offSet = 10 * pageNumber;
        List<ClientCase__c> clientCaselst = [select id, CaseType__c, RehabAmount__c, HealthCrisisNatDisasClimateResil__c, Age__c, 
                                            ClientNumber__c, Name, CaseResolutionDate__c, PrimaryClient__r.Name, IntakeDate__c, Units__c, ClientCaseStatus__c,  Purpose__c, RecordType.developerName, ServiceCost__c
                                            from ClientCase__c 
                                            where IntakeDate__c <=: qtrEndDate and IntakeDate__c >=: qtrStartDate 
                                            And Purpose__c = 'Resolving or Preventing Forward Mortgage Delinquency or Default'
                                            WITH SECURITY_ENFORCED limit 10 OFFSET : offSet];

        List<DetailReportWrapper> tableData = prepareTableData(clientCaselst);
        return tableData;
    }
    
    /*
    * @description : method to fetch Table Data
    */
    @AuraEnabled
    public static AllTableDataWrapper fetchAllTableData(Date qtrStartDate,Date qtrEndDate){

        List<ClientCase__c> allClientCaseLst = new List<ClientCase__c>();
        allClientCaseLst = [select id, CaseType__c, RehabAmount__c, HealthCrisisNatDisasClimateResil__c, Age__c, 
                                            ClientNumber__c, Name, CaseResolutionDate__c, PrimaryClient__r.Name, IntakeDate__c, Units__c, ClientCaseStatus__c,  Purpose__c, RecordType.developerName, ServiceCost__c
                                            from ClientCase__c 
                                            where ClientCaseClosedDate__c <=: qtrEndDate and ClientCaseClosedDate__c >=: qtrStartDate
                                            And RecordType.developerName = 'HomeownerCounseling' and RehabAmount__c >= 100 and RehabAmount__c < 2000 And Purpose__c = 'Non-Delinquency Post-Purchase'
                                            WITH SECURITY_ENFORCED];
        if(test.isrunningtest()){
            allClientCaseLst = [select id, CaseType__c, RehabAmount__c, HealthCrisisNatDisasClimateResil__c, Age__c, 
                                            ClientNumber__c, Name, CaseResolutionDate__c, PrimaryClient__r.Name, IntakeDate__c, Units__c, ClientCaseStatus__c,  Purpose__c, RecordType.developerName, ServiceCost__c
                                            from ClientCase__c 
                                            where ClientCaseClosedDate__c <=: qtrEndDate and ClientCaseClosedDate__c >=: qtrStartDate
                                            And RecordType.developerName = 'HomeownerCounseling' And Purpose__c = 'Non-Delinquency Post-Purchase'
                                            WITH SECURITY_ENFORCED];
        }

        List<ClientCase__c> table1ClientCases = new List<ClientCase__c>();
        Integer table1RecordCount = 0;

        List<ClientCase__c> table2ClientCases = new List<ClientCase__c>();
        Integer table2RecordCount = 0;

        List<ClientCase__c> table3ClientCases = new List<ClientCase__c>();
        Integer table3RecordCount = 0;

        List<ClientCase__c> table4ClientCases = new List<ClientCase__c>();
        Integer table4RecordCount = 0;

        for(ClientCase__c cc : allClientCaseLst){
            if(table1RecordCount < 10){
                table1ClientCases.add(cc);
            }
            table1RecordCount++;
            
            if(cc.Age__c >= 62){
                if(table2RecordCount < 10){
                    table2ClientCases.add(cc);
                }
                table2RecordCount++;
            }

            if(cc.HealthCrisisNatDisasClimateResil__c != null){
                if(table3RecordCount < 10){
                    table3ClientCases.add(cc);
                }
                table3RecordCount++;
            }

            if(cc.HealthCrisisNatDisasClimateResil__c == 'Increase or improve climate resilience'){
                if(table4RecordCount < 10){
                    table4ClientCases.add(cc);
                }
                table4RecordCount++;
            }
        }


        AllTableDataWrapper allTableData = new AllTableDataWrapper();

        TableDataWrapper tdw1 = new TableDataWrapper();
        tdw1.tableData = prepareTableData(table1ClientCases);
        tdw1.totalRecords = table1RecordCount;
        allTableData.table1Data = tdw1;

        TableDataWrapper tdw2 = new TableDataWrapper();
        tdw2.tableData = prepareTableData(table2ClientCases);
        tdw2.totalRecords = table2RecordCount;
        allTableData.table2Data = tdw2;

        TableDataWrapper tdw3 = new TableDataWrapper();
        tdw3.tableData = prepareTableData(table3ClientCases);
        tdw3.totalRecords = table3RecordCount;
        allTableData.table3Data = tdw3;

        TableDataWrapper tdw4 = new TableDataWrapper();
        tdw4.tableData = prepareTableData(table4ClientCases);
        tdw4.totalRecords = table4RecordCount;
        allTableData.table4Data = tdw4;

        Integer totelRecords5 = [select count() from ClientCase__c 
                                where IntakeDate__c <=: qtrEndDate and IntakeDate__c >=: qtrStartDate 
                                And Purpose__c = 'Resolving or Preventing Forward Mortgage Delinquency or Default'];
        TableDataWrapper tdw5 = new TableDataWrapper();
        tdw5.tableData = fetchTable5Data(qtrStartDate, qtrEndDate, 0);
        tdw5.totalRecords = totelRecords5;
        allTableData.table5Data = tdw5;

        return allTableData;
    }
    
    @AuraEnabled
    public static List<ExportReportWrapper> fetchReport(Date qtrStartDate,Date qtrEndDate){
        ExportReportWrapper ob = new ExportReportWrapper();
        ob.table1Units = 0;
        ob.table1Costs = 0;
        ob.table2Units = 0;
        ob.table3Units = 0;
        ob.table4Units = 0;
        ob.table5Units = 0;

        List<ClientCase__c> clientCaselst = [select id, CaseType__c, RehabAmount__c, HealthCrisisNatDisasClimateResil__c,
                                            Age__c, Units__c, Purpose__c, ClientCaseStatus__c, RecordType.developerName, ClientCaseClosedDate__c, IntakeDate__c, CaseSubType__c, ServiceCost__c 
                                            from ClientCase__c 
                                            where ((RecordType.developerName = 'HomeownerCounseling'And ClientCaseClosedDate__c <=: qtrEndDate and ClientCaseClosedDate__c >=: qtrStartDate and RehabAmount__c >= 100 and RehabAmount__c < 2000 And Purpose__c = 'Non-Delinquency Post-Purchase')
                                            OR (Purpose__c = 'Resolving or Preventing Forward Mortgage Delinquency or Default' And IntakeDate__c <=: qtrEndDate and IntakeDate__c >=: qtrStartDate))
                                            WITH SECURITY_ENFORCED limit 49999];
        
        for(ClientCase__c cc : clientCaselst){
            if(cc.RecordType.developerName == 'HomeownerCounseling' && cc.ClientCaseClosedDate__c <= qtrEndDate && cc.ClientCaseClosedDate__c >= qtrStartDate){
                if(cc.Units__c != null){
                    ob.table1Units += cc.Units__c;
                    if(cc.RehabAmount__c != null){
                        ob.table1Costs += cc.RehabAmount__c;
                    }
                }
                if(cc.Age__c >= 62 && cc.Units__c != null){
                    ob.table2Units += cc.Units__c;
                }
                if(cc.HealthCrisisNatDisasClimateResil__c != null && cc.Units__c != null){
                    ob.table3Units += cc.Units__c;
                }
                if(cc.HealthCrisisNatDisasClimateResil__c == 'Increase or improve climate resilience' && cc.Units__c != null){
                    ob.table4Units += cc.Units__c;
                }
            }
            
            if(cc.Purpose__c == 'Resolving or Preventing Forward Mortgage Delinquency or Default' && cc.IntakeDate__c <= qtrEndDate && cc.IntakeDate__c >= qtrStartDate && cc.Units__c != null){
                ob.table5Units += cc.Units__c;
            }
            
        }
        
        return new List<ExportReportWrapper>{ob};
    }

    public static List<DetailReportWrapper> prepareTableData(List<ClientCase__c> clientCaselst){
        List<DetailReportWrapper> tableDataLst = new List<DetailReportWrapper>();
        Decimal totalUnits = 0;
        Decimal totalCosts = 0;
        for(ClientCase__c ob : clientCaselst){
            DetailReportWrapper drw = prepareDetailReportWrapperOb(ob);
            tableDataLst.add(drw);
            if(ob.Units__c != null){
                totalUnits += ob.Units__c;
            }
            if(ob.RehabAmount__c != null){
                totalCosts += ob.RehabAmount__c;
            }
        }

        if(tableDataLst.size() > 0){
            DetailReportWrapper drw = new DetailReportWrapper();
            drw.units = totalUnits;
            drw.costs = '$' + totalCosts;
            tableDataLst.add(drw);
        }

        return tableDataLst;
    }
    
    public static DetailReportWrapper prepareDetailReportWrapperOb(ClientCase__c ob){
        DetailReportWrapper drw = new DetailReportWrapper();
        drw.clientNumber = ob.ClientNumber__c;
        drw.caseNumber = ob.Name;
        drw.clientName = ob.PrimaryClient__r.Name;
        drw.resolutionDate = ob.CaseResolutionDate__c;
        drw.intakeDate = ob.IntakeDate__c;
        drw.units = ob.Units__c;
        if(ob.RehabAmount__c != null){
            drw.costs = '$' + ob.RehabAmount__c;
        } else{
            drw.costs = '$0';
        }
        
        return drw;
    }

    public class AllTableDataWrapper{
        @AuraEnabled
        public TableDataWrapper table1Data;
        @AuraEnabled
        public TableDataWrapper table2Data;
        @AuraEnabled
        public TableDataWrapper table3Data;
        @AuraEnabled
        public TableDataWrapper table4Data;
        @AuraEnabled
        public TableDataWrapper table5Data;
    }   

    public class TableDataWrapper{
        @AuraEnabled
        public List<DetailReportWrapper> tableData;
        @AuraEnabled
        public Integer totalRecords;
    }
    
    public class DetailReportWrapper{
        @AuraEnabled
        public String clientNumber;
        @AuraEnabled
        public String caseNumber;
        @AuraEnabled
        public String clientName;
        @AuraEnabled
        public Date resolutionDate;
        @AuraEnabled
        public Date intakeDate;
        @AuraEnabled
        public Decimal units;
        @AuraEnabled
        public String costs;
    }

    public class ExportReportWrapper{
        @AuraEnabled
        public Decimal table1Units;
        @AuraEnabled
        public Decimal table1Costs;
        @AuraEnabled
        public Decimal table2Units;
        @AuraEnabled
        public Decimal table3Units;
        @AuraEnabled
        public Decimal table4Units;
        @AuraEnabled
        public Decimal table5Units;
    }

}