objects/CaseType__c.object
<CustomObject>
    <description>To organize the various services provided by the Agency for their clients.</description>
    <fields>
        <fullName>DescriptionEnglish__c</fullName>
        <label>Description (English)</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>DescriptionSpanish__c</fullName>
        <label>Description (Spanish)</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>FrequentlyAskedQuestionsEnglish__c</fullName>
        <inlineHelpText>Recommend limit to a maximum of 3 questions and this will be displayed on the Service Details page over the portal.</inlineHelpText>
        <label>Frequently Asked Questions (English)</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>FrequentlyAskedQuestionsSpanish__c</fullName>
        <inlineHelpText>Recommend limit to a maximum of 3 questions and this will be displayed on the Service Details page over the portal.</inlineHelpText>
        <label>Frequently Asked Questions (Spanish)</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>HighlightsSpanish__c</fullName>
        <label>Highlights (Spanish)</label>
        <length>800</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Highlights__c</fullName>
        <inlineHelpText>Recommend limit to a maximum of 3 bullet points, with each bullet point containing no more than 40 characters, or 130 characters total. This will be displayed on the Service summary card on the portal.</inlineHelpText>
        <label>Highlights (English)</label>
        <length>800</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsPortal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NameSpanish__c</fullName>
        <label>Case Type Name (Spanish)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RequiredDocumentsSpanish__c</fullName>
        <label>Required Documents (Spanish)</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RequiredDocuments__c</fullName>
        <label>Required Documents</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ShortDescriptionSpanish__c</fullName>
        <label>Short Description (Spanish)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ShortDescription__c</fullName>
        <inlineHelpText>Enter a brief (up to 120 characters) summary for the service. This will appear on the portal service page&apos;s summary card.</inlineHelpText>
        <label>Short Description (English)</label>
        <length>130</length>
        <type>Text</type>
    </fields>
    <label>Case Type</label>
    <nameField>
        <label>Case Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>CaseType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>HUD and NW reportable case types</description>
        <label>Case Type</label>
        <referenceTo>CaseType__c</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientCaseStatus__c</fullName>
        <defaultValue>(&quot;In Progress&quot;)</defaultValue>
        <description>In Progress: Open Case that is in progress and HUD reportable

Closed - Incomplete: Case closed without meeting the original outcome, HUD reportable

Closed - Service Complete: Case closed with meeting the original outcome, HUD reportable

On Hold: Case temporarily paused due to external factors or client request</description>
        <inlineHelpText>[1] In Progress: Case pending

[2] Closed - Incomplete: Didn’t meet original outcome

[3] Closed - Complete: Met the outcome

[4] On Hold: Case temporarily paused</inlineHelpText>
        <label>Client Case Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Closed - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Closed - Complete</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                    <isActive>false</isActive>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <isActive>false</isActive>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <isActive>false</isActive>
                    <label>Prospect</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IntakeCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intake Case</label>
        <referenceTo>Intake__c</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrimaryClient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Intake__c.object
<CustomObject>
    <description>To capture and store initial information about clients/prospects during the intake process including New Intake, New Education Only, and New Emergency Triage.</description>
    <fields>
        <fullName>CaseType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Type</label>
        <referenceTo>CaseType__c</referenceTo>
        <relationshipName>Intakes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrimaryClient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Intake_Only</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Intake Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Open Intake</fullName>
                    <default>true</default>
                    <label>Open Intake</label>
                </value>
                <value>
                    <fullName>Open Case</fullName>
                </value>
                <value>
                    <fullName>Converted</fullName>
                    <isActive>false</isActive>
                    <label>Converted</label>
                </value>
                <value>
                    <fullName>New</fullName>
                    <isActive>false</isActive>
                    <label>New</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Intake</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UserServicesController.cls
/**
 * @description  : Manages user services for the Compass Portal Site, offering methods to retrieve desired services and language field mappings for localization.
**/
public without sharing class UserServicesController {
    /*Retrieves a list of desired services with their descriptions and highlights.*/
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getDesiredServices() {
        User user = [SELECT Id, ContactId FROM User WHERE Id =: UserInfo.getUserId() LIMIT 1];
        Set<Id> caseIds = new Set<Id>();
        for(Intake__c intake : [SELECT Id, CaseType__c FROM Intake__c WHERE PrimaryClient__c  =: user.ContactId]){
                caseIds.add(intake.CaseType__c);
        }
        Map<String, Object> desireServiceMap= new Map<String, Object>();
        desireServiceMap.put('records', [SELECT id, Name,NameSpanish__c,ShortDescription__c,ShortDescriptionSpanish__c,// DescriptionEnglish__c, 
            Highlights__c,HighlightsSpanish__c, RequiredDocuments__c FROM CaseType__c WHERE Id NOT IN : caseIds AND IsPortal__c = true LIMIT 2000]);
        desireServiceMap.put('mapping', getMultiLanguageFieldMappings());
        return desireServiceMap;
    }
    
    /*Retrieves desired service with their descriptions and highlights.*/
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getDesiredServiceRecord(String recordId) {
        Map<String, Object> desireServiceMap= new Map<String, Object>();
        desireServiceMap.put('records', [SELECT Id, Name,NameSpanish__c,ShortDescription__c,ShortDescriptionSpanish__c,DescriptionEnglish__c,DescriptionSpanish__c,
            FrequentlyAskedQuestionsEnglish__c, FrequentlyAskedQuestionsSpanish__c, Highlights__c,HighlightsSpanish__c, RequiredDocuments__c, RequiredDocumentsSpanish__c FROM CaseType__c WHERE ID =:recordId]);
        desireServiceMap.put('mapping', getMultiLanguageFieldMappings());
        return desireServiceMap;
    }

        /*Returns mappings of language-specific field names (English and Spanish) for localization.*/
    private static Map<String, Map<String, String>> getMultiLanguageFieldMappings() {
        return new Map<String, Map<String, String>>{
            'English' => new Map<String, String>{'Name' => 'Name', 'ShortDescription' => 'ShortDescription__c', 'Description' => 'DescriptionEnglish__c', 'Highlights' => 'Highlights__c', 'FAQ' => 'FrequentlyAskedQuestionsEnglish__c', 'RequiredDocuments' => 'RequiredDocuments__c'},
            'Spanish' => new Map<String, String>{'Name' => 'NameSpanish__c', 'ShortDescription' => 'ShortDescriptionSpanish__c', 'Description' => 'DescriptionSpanish__c', 'Highlights' => 'HighlightsSpanish__c', 'FAQ' => 'FrequentlyAskedQuestionsSpanish__c', 'RequiredDocuments' => 'RequiredDocumentsSpanish__c'}
        };
    }
    
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getEnrolledServicesRecord() {
        Map<String, Wrapper> enrolledServiceDetails = new Map<String, Wrapper>();
        Map<String, Object> desireServiceMap= new Map<String, Object>();
        User user = [SELECT Id, ContactId FROM User WHERE Id =: UserInfo.getUserId() LIMIT 1];
        Set<Id> caseIds = new Set<Id>();
        for(Intake__c intake : [SELECT Id, CaseType__c, Status__c, (SELECT id, ClientCaseStatus__c FROM Client_Cases__r) 
                                FROM Intake__c WHERE PrimaryClient__c  =: user.ContactId AND PrimaryClient__c  != null]){
                                    System.debug('intake==>'+ intake);
            Wrapper wr = new Wrapper();
            wr.intakeId = intake.Id;
			wr.isEnrolled = true;                                    
            caseIds.add(intake.CaseType__c);
            if(!intake.Client_Cases__r.isEmpty()){
                wr.caseClientId = intake.Client_Cases__r[0].Id;
                wr.status = intake.Client_Cases__r[0].ClientCaseStatus__c;
            }else{
                wr.status = intake.Status__c;
            }
            enrolledServiceDetails.put(intake.CaseType__c, wr);
        }
        desireServiceMap.put('records', [SELECT Id, Name,NameSpanish__c,ShortDescription__c,ShortDescriptionSpanish__c,DescriptionEnglish__c,DescriptionSpanish__c,
            FrequentlyAskedQuestionsEnglish__c, FrequentlyAskedQuestionsSpanish__c, Highlights__c,HighlightsSpanish__c FROM CaseType__c WHERE ID IN : caseIds]);
        desireServiceMap.put('mapping', getMultiLanguageFieldMappings());
        desireServiceMap.put('enrolledServiceDetails', enrolledServiceDetails);
        return desireServiceMap;
    }
    
    @AuraEnabled(cacheable=true)
    public static Wrapper getIntakeDetails(String recordId){
        if(String.isBlank(recordId)){
            return NULL;
        }
        
        ID recId = recordId; 
        String sObjectName = recId.getSObjectType().getDescribe().getName();
		string NWC2NameSpace = Utility.getNwc2NameSpace();
        if(sobjectName == NWC2NameSpace+'Intake__c'){
            List<Intake__c> intakeList = [SELECT Id, CaseType__c, Status__c, (SELECT id, ClientCaseStatus__c FROM Client_Cases__r) FROM Intake__c WHERE Id  =:recId WITH USER_MODE LIMIT 1];
            
            if(intakeList.size() > 0){
                Wrapper result = new Wrapper();
                if(intakeList[0].Client_Cases__r.size() > 0){
                    result.status = intakeList[0].Client_Cases__r[0].ClientCaseStatus__c;
                    result.caseClientId = intakeList[0].Client_Cases__r[0].Id;
                } else{
                    result.status = intakeList[0].Status__c;
                }
                result.serviceId = intakeList[0].CaseType__c;
                result.intakeId = intakeList[0].Id;
                
                return result;
            }
        } else if(sobjectName == NWC2NameSpace+'ClientCase__c'){
            List<ClientCase__c> clientCaseList = [SELECT Id, IntakeCase__c, IntakeCase__r.CaseType__c, IntakeCase__r.Status__c, ClientCaseStatus__c FROM ClientCase__c WHERE Id  =:recId WITH USER_MODE LIMIT 1];
            
            if(clientCaseList.size() > 0){
                Wrapper result = new Wrapper();
                result.status = clientCaseList[0].ClientCaseStatus__c;
                result.caseClientId = clientCaseList[0].Id;
                result.serviceId = clientCaseList[0].IntakeCase__r.CaseType__c;
                result.intakeId = clientCaseList[0].IntakeCase__c;
                
                return result;
            }
        }
        return null;
    }
  
    public class Wrapper{
        @AuraEnabled
        public String caseClientId {get; set;}
        @AuraEnabled
        public String intakeId {get; set;}
        @AuraEnabled
        public String status {get; set;}
        @AuraEnabled
        public String serviceId{get;set;}
        @AuraEnabled
        public Boolean isEnrolled {get; set;}
    }
   
}