objects/CaseType__c.object
<CustomObject>
    <description>To organize the various services provided by the Agency for their clients.</description>
    <fields>
        <fullName>HUDPurpose__c</fullName>
        <label>Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Homeless Assistance</fullName>
                </value>
                <value>
                    <fullName>Pre-purchase/Homebuying</fullName>
                </value>
                <value>
                    <fullName>Rental Topics</fullName>
                </value>
                <value>
                    <fullName>Non-Delinquency Post-Purchase</fullName>
                </value>
                <value>
                    <fullName>Reverse Mortgage</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Forward Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Reverse Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Disaster Preparedness Assistance</fullName>
                </value>
                <value>
                    <fullName>Disaster Recovery Assistance</fullName>
                </value>
                <value>
                    <fullName>Not HUD-Reportable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Type</label>
    <nameField>
        <label>Case Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseResolution__c</fullName>
        <label>Case Resolution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fulfilled (Purchased housing)</fullName>
                </value>
                <value>
                    <fullName>Suspended (Withdrew from counseling)</fullName>
                </value>
                <value>
                    <fullName>Entered Lease Purchase Pgm</fullName>
                </value>
                <value>
                    <fullName>Decided Not to Purchase</fullName>
                </value>
                <value>
                    <fullName>Counseled on HECM; Declined Mortgage</fullName>
                </value>
                <value>
                    <fullName>Referred to Other Agency</fullName>
                </value>
                <value>
                    <fullName>Obtained a HECM</fullName>
                </value>
                <value>
                    <fullName>Rcvd. Home Equity/Home Improvement Loan</fullName>
                </value>
                <value>
                    <fullName>Mortgage Refinanced</fullName>
                </value>
                <value>
                    <fullName>Sold House, Chose Alt. Housing Solution</fullName>
                </value>
                <value>
                    <fullName>Rcvd. Consumer Loan (Unsecured)</fullName>
                </value>
                <value>
                    <fullName>Obtained a Non-FHA Reverse Mortgage</fullName>
                </value>
                <value>
                    <fullName>Complete Financial Mgt/Budget Counseling</fullName>
                </value>
                <value>
                    <fullName>Complete Home Maintenance Counseling</fullName>
                </value>
                <value>
                    <fullName>Counseled and Utilities Brought Current</fullName>
                </value>
                <value>
                    <fullName>Counseled/Referred for Legal Assistance</fullName>
                </value>
                <value>
                    <fullName>Brought Mortgage Current</fullName>
                </value>
                <value>
                    <fullName>Initiated Forbearance Agreement</fullName>
                </value>
                <value>
                    <fullName>Executed Deed-in-lieu</fullName>
                </value>
                <value>
                    <fullName>Sold Property</fullName>
                </value>
                <value>
                    <fullName>Mortgage Foreclosed</fullName>
                </value>
                <value>
                    <fullName>Rcvd. 2nd Mortgage</fullName>
                </value>
                <value>
                    <fullName>Partial Claim</fullName>
                </value>
                <value>
                    <fullName>Mortgage Modified</fullName>
                </value>
                <value>
                    <fullName>Counseled/Referred to Agency</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>Pre-foreclosure Sale</fullName>
                </value>
                <value>
                    <fullName>Entered Debt Management Plan</fullName>
                </value>
                <value>
                    <fullName>Other (final result not listed above)</fullName>
                </value>
                <value>
                    <fullName>Found Alternative (Found alternative rental housing)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CaseType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>HUD and NW reportable case types</description>
        <label>Case Type</label>
        <referenceTo>CaseType__c</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientCaseClosedDate__c</fullName>
        <description>Date the case is closed</description>
        <label>Client Case Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ClientCaseStatus__c</fullName>
        <defaultValue>(&quot;In Progress&quot;)</defaultValue>
        <description>In Progress: Open Case that is in progress and HUD reportable

Closed - Incomplete: Case closed without meeting the original outcome, HUD reportable

Closed - Service Complete: Case closed with meeting the original outcome, HUD reportable

On Hold: Case temporarily paused due to external factors or client request</description>
        <inlineHelpText>[1] In Progress: Case pending

[2] Closed - Incomplete: Didn’t meet original outcome

[3] Closed - Complete: Met the outcome

[4] On Hold: Case temporarily paused</inlineHelpText>
        <label>Client Case Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Closed - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Closed - Complete</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                    <isActive>false</isActive>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <isActive>false</isActive>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <isActive>false</isActive>
                    <label>Prospect</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CounselingTermination__c</fullName>
        <label>Counseling Termination</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ongoing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Dropped Out</fullName>
                </value>
                <value>
                    <fullName>Referred</fullName>
                </value>
                <value>
                    <fullName>No Further Contact</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HealthCrisisNatDisasClimateResil__c</fullName>
        <inlineHelpText>Was this service provided in direct response to a public health crisis, or a natural disaster, or to increase or improve climate resilience?</inlineHelpText>
        <label>Health Crisis/Nat Disas/Climate Resil?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>NWORole__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Natural Disaster</fullName>
                </value>
                <value>
                    <fullName>Public Health Crisis</fullName>
                </value>
                <value>
                    <fullName>Increase or improve climate resilience</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NWORole__c</fullName>
        <label>NWO Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NWO Constructs New Unit for New Home Owner</fullName>
                </value>
                <value>
                    <fullName>NWO Sells a Unit it Had Purchased (with or without rehab) to New Home Owner</fullName>
                </value>
                <value>
                    <fullName>Directly provides Self-Help Housing for New Home Owner</fullName>
                </value>
                <value>
                    <fullName>Plays Intermediary role in providing Self-Help Housing for New Home Owner</fullName>
                </value>
                <value>
                    <fullName>Counselor and/or Broker/Lender ONLY for New Home Owner</fullName>
                </value>
                <value>
                    <fullName>NWO Provides Services to an Existing Home Owner</fullName>
                </value>
                <value>
                    <fullName>Foreclosure Mitigation Counseling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <description>Agency to custom relevant purposes</description>
        <inlineHelpText>Choose one most applicable value from the drop-down list</inlineHelpText>
        <label>HUD Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Homeless Assistance</fullName>
                </value>
                <value>
                    <fullName>Pre-purchase/Homebuying</fullName>
                </value>
                <value>
                    <fullName>Rental Topics</fullName>
                </value>
                <value>
                    <fullName>Non-Delinquency Post-Purchase</fullName>
                </value>
                <value>
                    <fullName>Reverse Mortgage</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Forward Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Reverse Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Disaster Preparedness Assistance</fullName>
                </value>
                <value>
                    <fullName>Disaster Recovery Assistance</fullName>
                </value>
                <value>
                    <fullName>Not HUD-Reportable</fullName>
                </value>
                <value>
                    <fullName>Financial Literacy</fullName>
                    <isActive>false</isActive>
                    <label>Financial Literacy</label>
                </value>
                <value>
                    <fullName>Home Improvement Loan</fullName>
                    <isActive>false</isActive>
                    <label>Home Improvement Loan</label>
                </value>
                <value>
                    <fullName>Home Purchase Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Home Purchase Inquiry</label>
                </value>
                <value>
                    <fullName>Job Training</fullName>
                    <isActive>false</isActive>
                    <label>Job Training</label>
                </value>
                <value>
                    <fullName>Mortgage Delinquency Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Mortgage Delinquency Inquiry</label>
                </value>
                <value>
                    <fullName>Rehab Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Rehab Inquiry</label>
                </value>
                <value>
                    <fullName>Rental Assistance</fullName>
                    <isActive>false</isActive>
                    <label>Rental Assistance</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RehabCost__c</fullName>
        <label>Rehab Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label># of Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <recordTypes>
        <fullName>HomeownerCounseling</fullName>
        <active>true</active>
        <label>Homeowner Counseling</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ForeclosureIntakeReportControllerTest.cls
@istest
public class ForeclosureIntakeReportControllerTest {
    
    @TestSetup
    static void setupData() {
        string NWC2NameSpace = Utility.getNwc2NameSpace();
        string objectName = NWC2NameSpace + 'ClientCase__c';
        RecordType rtCase = [Select Id, DeveloperName from RecordType where SobjectType=:objectName And developerName = 'HomeownerCounseling'];
		
        CaseType__c ct = TestDataFactory.createCaseTypes(1,false)[0];
        ct.HUDPurpose__c = 'Non-Delinquency Post-Purchase';
        insert ct;
        
        ClientCase__c cc = TestDataFactory.createClientCases(1,false)[0];
        cc.RehabCost__c = 2000;
        cc.RecordTypeId = rtCase.Id;
        cc.CaseResolution__c = 'Obtained a HECM';
        cc.Age__c = 69;
        cc.Units__c = 1;
        cc.NWORole__c = 'NWO Provides Services to an Existing Home Owner';
        cc.HealthCrisisNatDisasClimateResil__c = 'Increase or improve climate resilience';
        cc.ClientCaseStatus__c = 'Closed - Complete';
        cc.Purpose__c = 'Non-Delinquency Post-Purchase';
        cc.CounselingTermination__c = 'Completed';
        cc.ClientCaseClosedDate__c = Date.today();
        cc.CaseSubType__c = 'NW Rehab';
        cc.CaseType__c = ct.Id;
        insert cc;
    }
    
    static testMethod void testFetchNWQRFinancingReports(){
        ClientCase__c cc1 = [select id,CaseResolution__c from ClientCase__c limit 1];
        Test.startTest();
        ForeclosureIntakeReportController.AllTableDataWrapper orsoutput = ForeclosureIntakeReportController.fetchAllTableData(System.Today() - 1,System.Today() + 1);
        List<ForeclosureIntakeReportController.DetailReportWrapper> orsoutput1 = ForeclosureIntakeReportController.fetchTable1Data(System.Today() - 1,System.Today() + 1,0);
        List<ForeclosureIntakeReportController.DetailReportWrapper> orsoutput2 = ForeclosureIntakeReportController.fetchTable2Data(System.Today() - 1,System.Today() + 1,0);
        List<ForeclosureIntakeReportController.DetailReportWrapper> orsoutput3 = ForeclosureIntakeReportController.fetchTable3Data(System.Today() - 1,System.Today() + 1,0);
        List<ForeclosureIntakeReportController.DetailReportWrapper> orsoutput4 = ForeclosureIntakeReportController.fetchTable4Data(System.Today() - 1,System.Today() + 1,0);
        Test.StopTest();
    }
    
    static testMethod void testFetchReports(){
        Test.startTest();
        List<ForeclosureIntakeReportController.ExportReportWrapper> orsoutput = ForeclosureIntakeReportController.fetchReport(System.Today() - 1,System.Today() + 1);
        Test.StopTest();
    }

}