objects/CaseType__c.object
<CustomObject>
    <description>To organize the various services provided by the Agency for their clients.</description>
    <fields>
        <fullName>NameSpanish__c</fullName>
        <label>Case Type Name (Spanish)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>is_Reverse_Mortage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Reverse Mortage</label>
        <type>Checkbox</type>
    </fields>
    <label>Case Type</label>
    <nameField>
        <label>Case Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ActiveMilitary__c</fullName>
        <description>Yes, No, Not Applicable</description>
        <label>Active Military</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ActiveMilitary</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CreditScore__c</fullName>
        <label>Credit Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DisabledStatus__c</fullName>
        <label>Disabled Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <description>Pre-defined list</description>
        <label>Education</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Education</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EmploymentStatus__c</fullName>
        <label>Employment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Employed Full-Time</fullName>
                </value>
                <value>
                    <fullName>Employed Part-Time</fullName>
                </value>
                <value>
                    <fullName>Unemployed AND Looking for Work</fullName>
                </value>
                <value>
                    <fullName>Unable to Work Due to Disability</fullName>
                </value>
                <value>
                    <fullName>Stay-at-Home Caregiver OR Parent</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Employed Full-Time AND Student</fullName>
                </value>
                <value>
                    <fullName>Employed Part-Time AND Student</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EnglishProficiency__c</fullName>
        <description>Reflects overall level of English proficiency within the same household as the contact.</description>
        <inlineHelpText>English Proficiency of the primary client</inlineHelpText>
        <label>English Proficiency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Limited_English_Proficiency_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <description>Client’s self-identified ethnicity, used in 9902 reporting</description>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Male, Female, Other/Non-Conforming</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>Number of people in the household</description>
        <inlineHelpText>Total number of people living in the same household</inlineHelpText>
        <label>Household Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HouseholdType__c</fullName>
        <label>Household Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MaritalStatus__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>HouseholdTypeHeadofHousehold</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MailingAddressLine2__c</fullName>
        <label>Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaritalStatus__c</fullName>
        <description>Pre-defined  list</description>
        <label>Marital Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MaritalStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>NumberOfDependents__c</fullName>
        <label>Number of Dependents</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <description>Which HUD 9902-recognized race category the contact belongs to.</description>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RuralAreaStatus__c</fullName>
        <description>Whether or not this contact resides in a rural area as defined by HUD.</description>
        <label>Rural Area Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Rural_Area_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TotalMonthlyIncome__c</fullName>
        <label>Total Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X1stTimeHomeBuyer__c</fullName>
        <description>Yes, No</description>
        <inlineHelpText>Must not have owned a home within the last 3 years.</inlineHelpText>
        <label>1st Time Home Buyer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>X1stTimeHomeBuyer</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>CoApplicant</fullName>
        <active>true</active>
        <label>Co-Applicant</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Intake__c.object
<CustomObject>
    <description>To capture and store initial information about clients/prospects during the intake process including New Intake, New Education Only, and New Emergency Triage.</description>
    <fields>
        <fullName>ActiveMilitary__c</fullName>
        <label>Active Military</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>Not available</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AddressLine2__c</fullName>
        <label>Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CaseType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Type</label>
        <referenceTo>CaseType__c</referenceTo>
        <relationshipName>Intakes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CreditScore__c</fullName>
        <label>Credit Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DisabledStatus__c</fullName>
        <label>Disabled Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Education</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Employment_Status__c</fullName>
        <label>Employment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Employed Full-Time</fullName>
                </value>
                <value>
                    <fullName>Employed Part-Time</fullName>
                </value>
                <value>
                    <fullName>Unemployed AND Looking for Work</fullName>
                </value>
                <value>
                    <fullName>Unable to Work Due to Disability</fullName>
                </value>
                <value>
                    <fullName>Stay-at-Home Caregiver OR Parent</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Employed Full-Time AND Student</fullName>
                </value>
                <value>
                    <fullName>Employed Part-Time AND Student</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EnglishProficiency__c</fullName>
        <description>HUD-Defined English Proficiency</description>
        <inlineHelpText>English Proficiency of the primary client</inlineHelpText>
        <label>English Proficiency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Limited_English_Proficiency_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <label>Household Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HouseholdType__c</fullName>
        <label>Household Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MaritalStatus__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>HouseholdTypeHeadofHousehold</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Household__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Intake_Only</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MaritalStatus__c</fullName>
        <label>Marital Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MaritalStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MonthlyIncome__c</fullName>
        <label>Total Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NumberofDependents__c</fullName>
        <label>Number of Dependents</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PrimaryClient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Intake_Only</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RuralAreaStatus__c</fullName>
        <label>Rural Area Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Rural_Area_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>X1stTimeHomeBuyer__c</fullName>
        <label>1st Time Home Buyer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>Not available</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Intake</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/ActiveMilitary.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>Not available</fullName>
    </customValue>
    <masterLabel>Active Military?</masterLabel>
</GlobalValueSet>

globalValueSets/Education.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Elementary/Primary</fullName>
    </customValue>
    <customValue>
        <fullName>Junior High School</fullName>
    </customValue>
    <customValue>
        <fullName>High School/GED</fullName>
    </customValue>
    <customValue>
        <fullName>Junior College</fullName>
    </customValue>
    <customValue>
        <fullName>University</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate School</fullName>
    </customValue>
    <customValue>
        <fullName>Vocational</fullName>
    </customValue>
    <customValue>
        <fullName>College</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>High School</fullName>
        <isActive>false</isActive>
        <label>High School</label>
    </customValue>
    <customValue>
        <fullName>Elementary</fullName>
        <isActive>false</isActive>
        <label>Elementary</label>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
        <isActive>false</isActive>
        <label>Unknown</label>
    </customValue>
    <description>Education</description>
    <masterLabel>Education</masterLabel>
</GlobalValueSet>

globalValueSets/Ethnicity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Not Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Ethnicity</description>
    <masterLabel>Ethnicity</masterLabel>
</GlobalValueSet>

globalValueSets/Gender.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <customValue>
        <fullName>Other/Non-conforming</fullName>
    </customValue>
    <description>Gender</description>
    <masterLabel>Gender</masterLabel>
</GlobalValueSet>

globalValueSets/HouseholdTypeHeadofHousehold.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Single adult</fullName>
    </customValue>
    <customValue>
        <fullName>Female-headed single parent household</fullName>
    </customValue>
    <customValue>
        <fullName>Male-headed single parent household</fullName>
    </customValue>
    <customValue>
        <fullName>Married without dependents</fullName>
    </customValue>
    <customValue>
        <fullName>Married with dependents</fullName>
    </customValue>
    <customValue>
        <fullName>Two or more unrelated Adults</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Married with children</fullName>
        <isActive>false</isActive>
        <label>Married with children</label>
    </customValue>
    <customValue>
        <fullName>Male-headed single parent household/Head of Household</fullName>
        <isActive>false</isActive>
        <label>Male-headed single parent household/Head of Household</label>
    </customValue>
    <customValue>
        <fullName>Female-headed single parent household/Head of Household</fullName>
        <isActive>false</isActive>
        <label>Female-headed single parent household/Head of Household</label>
    </customValue>
    <customValue>
        <fullName>Domestic partnership</fullName>
        <isActive>false</isActive>
        <label>Domestic partnership</label>
    </customValue>
    <customValue>
        <fullName>Married without children</fullName>
        <isActive>false</isActive>
        <label>Married without children</label>
    </customValue>
    <masterLabel>Household Type/Head of Household</masterLabel>
</GlobalValueSet>

globalValueSets/Limited_English_Proficiency_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Limited English Proficient</fullName>
    </customValue>
    <customValue>
        <fullName>Not Limited English Proficient</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Limited English Proficiency Status</description>
    <masterLabel>Limited English Proficiency Status</masterLabel>
</GlobalValueSet>

globalValueSets/MaritalStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Married</fullName>
    </customValue>
    <customValue>
        <fullName>Single</fullName>
    </customValue>
    <customValue>
        <fullName>Divorced</fullName>
    </customValue>
    <customValue>
        <fullName>Separated</fullName>
    </customValue>
    <customValue>
        <fullName>Widowed</fullName>
    </customValue>
    <customValue>
        <fullName>Choose not to respond</fullName>
    </customValue>
    <customValue>
        <fullName>Legally Separated</fullName>
        <isActive>false</isActive>
        <label>Legally Separated</label>
    </customValue>
    <masterLabel>Marital Status</masterLabel>
</GlobalValueSet>

globalValueSets/Race.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>American Indian/Alaskan Native</fullName>
    </customValue>
    <customValue>
        <fullName>Asian</fullName>
    </customValue>
    <customValue>
        <fullName>Black or African American</fullName>
    </customValue>
    <customValue>
        <fullName>Native Hawaiian or Other Pacific Islander</fullName>
    </customValue>
    <customValue>
        <fullName>White</fullName>
    </customValue>
    <customValue>
        <fullName>More than one race</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Race</description>
    <masterLabel>Race</masterLabel>
</GlobalValueSet>

globalValueSets/Rural_Area_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Lives in a rural area</fullName>
    </customValue>
    <customValue>
        <fullName>Does not live in a rural area</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Rural Area Status</description>
    <masterLabel>Rural Area Status</masterLabel>
</GlobalValueSet>

globalValueSets/X1stTimeHomeBuyer.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>Not available</fullName>
    </customValue>
    <masterLabel>1st Time Home Buyer?</masterLabel>
</GlobalValueSet>

classes/ServiceEnrollmentFormController.cls
/**
 * @description       : 
 * @author            : Soyab
 * @group             : 
 * @last modified on  : 07-15-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public without sharing class ServiceEnrollmentFormController {
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getService(String recordId) {
        if(String.isBlank(recordId)){
            return new Map<String, String>();
        }
        Map<String, Object> desireServiceMap= new Map<String, Object>();
        CaseType__c service = [SELECT Id, Name, NameSpanish__c, is_Reverse_Mortage__c FROM CaseType__c  WHERE ID =:recordId LIMIT 1];
        desireServiceMap.put('record', service);
        desireServiceMap.put('mapping', getMultiLanguageFieldMappings());
        return desireServiceMap;
    }
    
    private static Map<String, Map<String, String>> getMultiLanguageFieldMappings() {
        return new Map<String, Map<String, String>>{
            'English' => new Map<String, String>{'Name' => 'Name'},
            'Spanish' => new Map<String, String>{'Name' => 'NameSpanish__c'}
        };
    }
    

    /*Enrolls a primary contact and applicants into a specified service. Updates the primary contact's, 
    upserts applicants, creates an intake record, and links co-applicants. */
    @AuraEnabled
    public static String enrolledToService(Contact primaryContact, List<Contact> applicants, String serviceId) {
        //Contact primeCon = [SELECT Id, AccountId FROM Contact WHERE Id =: primaryContact.Id];
        try{
            System.debug('primaryContact=>'+ primaryContact);
            System.debug('applicants=>'+ applicants);
            Id accountId = null;
            Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('CoApplicant').getRecordTypeId();
            Intake__c intRecord = new Intake__c();
            if(primaryContact != null){
                primaryContact.MailingCountryCode = Constants.DEFAULT_COUNTRY;
                update primaryContact;
                accountId = [
                    SELECT AccountId 
                    FROM Contact 
                    WHERE Id = :primaryContact.Id 
                    LIMIT 1
                ].AccountId;
            }

            for(Contact con : applicants){
                con.RecordTypeId = recordTypeId;
                con.IsActive__c = true;
                con.AccountId = accountId;
                con.MailingCountryCode = Constants.DEFAULT_COUNTRY;
            }

            if(applicants != null){ 
                upsert applicants;
            }
            
            if(serviceId != null){
                intRecord.CaseType__c = serviceId;  
                intRecord.PrimaryClient__c = primaryContact.Id;  
                intRecord.Household__c = accountId;
                intRecord.Address__Street__s = primaryContact.MailingStreet;
                intRecord.AddressLine2__c = primaryContact.MailingAddressLine2__c;
                intRecord.Address__City__s  = primaryContact.MailingCity;
                intRecord.Address__StateCode__s  = primaryContact.MailingState;
                intRecord.Address__PostalCode__s = primaryContact.MailingPostalCode;
                intRecord.Race__c = primaryContact.Race__c;
                intRecord.Ethnicity__c = primaryContact.Ethnicity__c;
                intRecord.Gender__c = primaryContact.Gender__c;
                intRecord.Education__c = primaryContact.Education__c;
                intRecord.MaritalStatus__c = primaryContact.MaritalStatus__c;
                intRecord.EnglishProficiency__c = primaryContact.EnglishProficiency__c;
                intRecord.ActiveMilitary__c = primaryContact.ActiveMilitary__c;
                intRecord.DisabledStatus__c = primaryContact.DisabledStatus__c;
                intRecord.X1stTimeHomeBuyer__c = primaryContact.X1stTimeHomeBuyer__c;
                intRecord.RuralAreaStatus__c = primaryContact.RuralAreaStatus__c;
                intRecord.HouseholdType__c = primaryContact.HouseholdType__c;
                intRecord.HouseholdSize__c = primaryContact.HouseholdSize__c;
                intRecord.MonthlyIncome__c = primaryContact.TotalMonthlyIncome__c;
                intRecord.NumberOfDependents__c = primaryContact.NumberOfDependents__c;
                intRecord.CreditScore__c = primaryContact.CreditScore__c;
                intRecord.Employment_Status__c = primaryContact.EmploymentStatus__c;
                intRecord.PortalIntake__c = true;
                intRecord.ChoseNottoProvideIncome__c = primaryContact.ChoseNottoProvideIncome__c;
                insert intRecord;
                List<CoApplicant__c> coApplicants = new List<CoApplicant__c>();
                for(Contact con : applicants){
                    coApplicants.add(
                        new CoApplicant__c(
                            IntakeRequest__c = intRecord.Id,
                            Contact__c = con.Id//primaryContact.Id
                        )
                    );
                }
                if(!coApplicants.isEmpty()){
                    insert coApplicants;
                }
            }
            return intRecord.Id;
        }catch (Exception e){ throw new LightningException(e.getMessage() + e.getLineNumber());}
    }
    
    
    @AuraEnabled(cacheable=true)
        public static Map<String,Object> getEnrolledServiceDetails(String recordId){
        System.debug('getEnrolledServiceDetails recordId'+ recordId);
        Map<String,Object> enrolledDetails = new Map<String,Object>{'PrimaryContact' => null, 'CoApplicants' => null};
        Set<Id> coApplicantIds = new Set<Id>();
        List<Intake__c> intakes = [SELECT Id,CreatedDate, PrimaryClient__c from Intake__c WHERE Id = :recordId AND
                                   PrimaryClient__c != NULL LIMIT 1 ];
        if(intakes.isEmpty()){
            return enrolledDetails;
        }
        enrolledDetails.put('SubmittedDate', intakes[0].CreatedDate);
        for(CoApplicant__c applicant : [SELECT Id, Contact__c FROM CoApplicant__c WHERE IntakeRequest__c =:recordId ]){
            coApplicantIds.add(applicant.Contact__c);
        }
        
        enrolledDetails.put('PrimaryContact', EnrollmentFormController.getPrimaryContactInformation());
        enrolledDetails.put('CoApplicants', [SELECT Id, Name, FirstName, MiddleName, LastName, Email, Phone, Suffix, MailingStreet, MailingAddressLine2__c,MailingCity, 
                MailingStateCode, MailingPostalCode, Ethnicity__c, Race__c, Gender__c, EnglishProficiency__c, HouseholdSize__c, 
                HouseholdMonthlyIncome1__c, X1stTimeHomeBuyer__c, RuralAreaStatus__c, Besttimetocontact__c, PreferredLanguage__c,
                RelationshipToPrimaryApplicant__c, Birthdate, MaritalStatus__c, Education__c, DisabledStatus__c,
                NumberOfDependents__c, EmploymentStatus__c, CreditScore__c, ActiveMilitary__c, TotalMonthlyIncome__c, Veteran__c FROM Contact 
                WHERE Id IN:coApplicantIds]);
        return enrolledDetails;
    }
    
    public class LightningException extends Exception {}
}