objects/CaseType__c.object
<CustomObject>
    <description>To organize the various services provided by the Agency for their clients.</description>
    <label>Case Type</label>
    <nameField>
        <label>Case Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>CaseType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>HUD and NW reportable case types</description>
        <label>Case Type</label>
        <referenceTo>CaseType__c</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientCaseStatus__c</fullName>
        <defaultValue>(&quot;In Progress&quot;)</defaultValue>
        <description>In Progress: Open Case that is in progress and HUD reportable

Closed - Incomplete: Case closed without meeting the original outcome, HUD reportable

Closed - Service Complete: Case closed with meeting the original outcome, HUD reportable

On Hold: Case temporarily paused due to external factors or client request</description>
        <inlineHelpText>[1] In Progress: Case pending

[2] Closed - Incomplete: Didn’t meet original outcome

[3] Closed - Complete: Met the outcome

[4] On Hold: Case temporarily paused</inlineHelpText>
        <label>Client Case Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Closed - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Closed - Complete</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                    <isActive>false</isActive>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <isActive>false</isActive>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <isActive>false</isActive>
                    <label>Prospect</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <description>HUD-Defined Education</description>
        <label>Education</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Education</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <description>HUD-Defined Ethnicity</description>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>HUD-Defined Gender</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>HUD-Defined Number in Household</description>
        <inlineHelpText>Total number of people living in the same household as the primary client</inlineHelpText>
        <label>Household Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HouseholdType__c</fullName>
        <label>Household Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MaritalStatus__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>HouseholdTypeHeadofHousehold</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MaritalStatus__c</fullName>
        <description>HUD-Defined Marital Status</description>
        <label>Marital Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MaritalStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <description>HUD-Defined Race</description>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X1stTimeHomeBuyer__c</fullName>
        <description>HUD-Defined 1st Time Homebuyer</description>
        <inlineHelpText>Must not have owned a home within the last 3 years.</inlineHelpText>
        <label>1st Time Home Buyer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>X1stTimeHomeBuyer</valueSetName>
        </valueSet>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CoApplicant__c.object
<CustomObject>
    <description>To store details about household members who are co-applicants of the primary contact.</description>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Co-Applicants</relationshipLabel>
        <relationshipName>Co_Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicants</relationshipLabel>
        <relationshipName>Co_Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IntakeRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intake</label>
        <referenceTo>Intake__c</referenceTo>
        <relationshipLabel>Co-Applicants</relationshipLabel>
        <relationshipName>Co_Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Co-Applicant</label>
    <nameField>
        <displayFormat>CAPP-{00000}</displayFormat>
        <label>Co-Applicant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co-Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <description>Pre-defined list</description>
        <label>Education</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Education</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <description>Client’s self-identified ethnicity, used in 9902 reporting</description>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Male, Female, Other/Non-Conforming</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>Number of people in the household</description>
        <inlineHelpText>Total number of people living in the same household</inlineHelpText>
        <label>Household Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HouseholdType__c</fullName>
        <label>Household Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MaritalStatus__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>HouseholdTypeHeadofHousehold</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MaritalStatus__c</fullName>
        <description>Pre-defined  list</description>
        <label>Marital Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MaritalStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <description>Which HUD 9902-recognized race category the contact belongs to.</description>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TotalMonthlyIncome__c</fullName>
        <label>Total Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X1stTimeHomeBuyer__c</fullName>
        <description>Yes, No</description>
        <inlineHelpText>Must not have owned a home within the last 3 years.</inlineHelpText>
        <label>1st Time Home Buyer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>X1stTimeHomeBuyer</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Intake__c.object
<CustomObject>
    <description>To capture and store initial information about clients/prospects during the intake process including New Intake, New Education Only, and New Emergency Triage.</description>
    <fields>
        <fullName>CaseType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Type</label>
        <referenceTo>CaseType__c</referenceTo>
        <relationshipName>Intakes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Education</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HouseholdMonthlyIncome__c</fullName>
        <label>Household Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <label>Household Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HouseholdType__c</fullName>
        <label>Household Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MaritalStatus__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>HouseholdTypeHeadofHousehold</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MaritalStatus__c</fullName>
        <label>Marital Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MaritalStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X1stTimeHomeBuyer__c</fullName>
        <label>1st Time Home Buyer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>Not available</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Intake</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Education.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Elementary/Primary</fullName>
    </customValue>
    <customValue>
        <fullName>Junior High School</fullName>
    </customValue>
    <customValue>
        <fullName>High School/GED</fullName>
    </customValue>
    <customValue>
        <fullName>Junior College</fullName>
    </customValue>
    <customValue>
        <fullName>University</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate School</fullName>
    </customValue>
    <customValue>
        <fullName>Vocational</fullName>
    </customValue>
    <customValue>
        <fullName>College</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>High School</fullName>
        <isActive>false</isActive>
        <label>High School</label>
    </customValue>
    <customValue>
        <fullName>Elementary</fullName>
        <isActive>false</isActive>
        <label>Elementary</label>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
        <isActive>false</isActive>
        <label>Unknown</label>
    </customValue>
    <description>Education</description>
    <masterLabel>Education</masterLabel>
</GlobalValueSet>

globalValueSets/Ethnicity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Not Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Ethnicity</description>
    <masterLabel>Ethnicity</masterLabel>
</GlobalValueSet>

globalValueSets/Gender.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <customValue>
        <fullName>Other/Non-conforming</fullName>
    </customValue>
    <description>Gender</description>
    <masterLabel>Gender</masterLabel>
</GlobalValueSet>

globalValueSets/HouseholdTypeHeadofHousehold.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Single adult</fullName>
    </customValue>
    <customValue>
        <fullName>Female-headed single parent household</fullName>
    </customValue>
    <customValue>
        <fullName>Male-headed single parent household</fullName>
    </customValue>
    <customValue>
        <fullName>Married without dependents</fullName>
    </customValue>
    <customValue>
        <fullName>Married with dependents</fullName>
    </customValue>
    <customValue>
        <fullName>Two or more unrelated Adults</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Married with children</fullName>
        <isActive>false</isActive>
        <label>Married with children</label>
    </customValue>
    <customValue>
        <fullName>Male-headed single parent household/Head of Household</fullName>
        <isActive>false</isActive>
        <label>Male-headed single parent household/Head of Household</label>
    </customValue>
    <customValue>
        <fullName>Female-headed single parent household/Head of Household</fullName>
        <isActive>false</isActive>
        <label>Female-headed single parent household/Head of Household</label>
    </customValue>
    <customValue>
        <fullName>Domestic partnership</fullName>
        <isActive>false</isActive>
        <label>Domestic partnership</label>
    </customValue>
    <customValue>
        <fullName>Married without children</fullName>
        <isActive>false</isActive>
        <label>Married without children</label>
    </customValue>
    <masterLabel>Household Type/Head of Household</masterLabel>
</GlobalValueSet>

globalValueSets/MaritalStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Married</fullName>
    </customValue>
    <customValue>
        <fullName>Single</fullName>
    </customValue>
    <customValue>
        <fullName>Divorced</fullName>
    </customValue>
    <customValue>
        <fullName>Separated</fullName>
    </customValue>
    <customValue>
        <fullName>Widowed</fullName>
    </customValue>
    <customValue>
        <fullName>Choose not to respond</fullName>
    </customValue>
    <customValue>
        <fullName>Legally Separated</fullName>
        <isActive>false</isActive>
        <label>Legally Separated</label>
    </customValue>
    <masterLabel>Marital Status</masterLabel>
</GlobalValueSet>

globalValueSets/Race.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>American Indian/Alaskan Native</fullName>
    </customValue>
    <customValue>
        <fullName>Asian</fullName>
    </customValue>
    <customValue>
        <fullName>Black or African American</fullName>
    </customValue>
    <customValue>
        <fullName>Native Hawaiian or Other Pacific Islander</fullName>
    </customValue>
    <customValue>
        <fullName>White</fullName>
    </customValue>
    <customValue>
        <fullName>More than one race</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Race</description>
    <masterLabel>Race</masterLabel>
</GlobalValueSet>

globalValueSets/X1stTimeHomeBuyer.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>Not available</fullName>
    </customValue>
    <masterLabel>1st Time Home Buyer?</masterLabel>
</GlobalValueSet>

classes/CoApplicantTriggerHandlerTest.cls
@isTest
public class CoApplicantTriggerHandlerTest {
    
    @testSetup
    static void setupTestData() {
        // Create test data for Intake and ClientCase records
        List<Intake__c> intakes = new List<Intake__c>();
        List<String> values = new List<String>{'Education','Homeless Assistance','Rental Topics','Prepurchase/Homebuying','Non-delinquency Post-Purchase','Reverse Mortgage','Resolving or Preventing Forward Mortgage Delinquency or Default','Resolving or Preventing Reverse Mortgage Delinquency or Default','Disaster Preparedness Assistance','Disaster Recovery Assistance','Financial Capability','Housing Stability Capability Program'};
            List<CaseType__c> CaseTypes = new List<CaseType__c>();
        for(String elt : values) {
            CaseType__c ct = new CaseType__c();
            ct.Name=elt;
            CaseTypes.add(ct);
        }
        
        Account acc = TestDataFactory.createAccounts(1, true)[0];
        Contact con = TestDataFactory.createContacts(acc.id,1, false)[0];
        con.FirstName='Test';
        con.LastName='Test';
        con.Email='tommy@dummy.com'; 
        con.TotalMonthlyIncome__c = 500; 
        con.Phone='9898989898'; 
        con.MailingStreet='Test Street'; 
        con.MailingCity='Test City'; 
        con.MailingState='New York';
        con.MailingPostalCode='777777';
        con.MailingCountry='United States';
        insert con;
        insert CaseTypes;
        
        List<Intake__c> newIntakes = TestDataFactory.createIntakes(con, acc.Id, 5, false);
       
        for (Integer i = 0; i < newIntakes.size(); i++) {
            Intake__c newIntk = newIntakes[i];
            newIntk.Town__c = 'Town' + i;
            newIntk.County__c = 'County' + i;
            newIntk.Address__PostalCode__s = '12345' + i;
            newIntk.HouseholdMonthlyIncome__c = 4000 + (1000 * i); 
            newIntk.HouseholdSize__c = 4 + i;
            intakes.add(newIntk);
        }
        insert intakes;
        
        List<ClientCase__c> cases = TestDataFactory.createClientCases(1, false);
        cases[0].Race__c='Asian';
        cases[0].Ethnicity__c='Not Hispanic';
        cases[0].Gender__c='Female';
        cases[0].HouseholdType__c='Other';
        cases[0].Education__c='Junior College';
        cases[0].MaritalStatus__c='Divorced';
        cases[0].HouseholdSize__c=2;
        cases[0].X1stTimeHomeBuyer__c='Yes';
        cases[0].ClientCaseStatus__c = 'In Progress'; 
        insert cases;
        TestDataFactory.createCoApplicants( intakes[0].Id, con.id, cases[0].Id, 1, true);
        
    }
    
    
    @isTest
    static void testAfterInsert() {
        Contact con = [SELECT id FROM Contact LIMIT 1];
        CoApplicant__c newCoApplicants = new CoApplicant__c(
            Contact__c = con.id,
            IntakeRequest__c = [SELECT Id FROM Intake__c LIMIT 1].Id,
            ClientCase__c = [SELECT Id FROM ClientCase__c LIMIT 1].Id
        );
        
        Test.startTest();
        insert newCoApplicants;
        Test.stopTest();
        
    }
    
    @isTest
    static void testAfterDelete() {
        List<CoApplicant__c> coApplicantsToDelete = [SELECT Id FROM CoApplicant__c LIMIT 5];
        
        Test.startTest();
        delete coApplicantsToDelete;
        Test.stopTest();
        
    }
    
    @isTest
    static void testCalculateHouseholdIncome() {
        List<CoApplicant__c> coApplicants = [SELECT Id, IntakeRequest__c, ClientCase__c,Contact__r.TotalMonthlyIncome__c FROM CoApplicant__c];
        
        Test.startTest();
        CoApplicantTriggerHandler.calculateHouseholdIncome(coApplicants, null);
        Test.stopTest();
    }
}