objects/CaseType__c.object
<CustomObject>
    <description>To organize the various services provided by the Agency for their clients.</description>
    <label>Case Type</label>
    <nameField>
        <label>Case Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>CaseType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>HUD and NW reportable case types</description>
        <label>Case Type</label>
        <referenceTo>CaseType__c</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientCaseStatus__c</fullName>
        <defaultValue>(&quot;In Progress&quot;)</defaultValue>
        <description>In Progress: Open Case that is in progress and HUD reportable

Closed - Incomplete: Case closed without meeting the original outcome, HUD reportable

Closed - Service Complete: Case closed with meeting the original outcome, HUD reportable

On Hold: Case temporarily paused due to external factors or client request</description>
        <inlineHelpText>[1] In Progress: Case pending

[2] Closed - Incomplete: Didn’t meet original outcome

[3] Closed - Complete: Met the outcome

[4] On Hold: Case temporarily paused</inlineHelpText>
        <label>Client Case Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Closed - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Closed - Complete</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                    <isActive>false</isActive>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <isActive>false</isActive>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <isActive>false</isActive>
                    <label>Prospect</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PrimaryClient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Intake__c.object
<CustomObject>
    <description>To capture and store initial information about clients/prospects during the intake process including New Intake, New Education Only, and New Emergency Triage.</description>
    <fields>
        <fullName>CaseType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Type</label>
        <referenceTo>CaseType__c</referenceTo>
        <relationshipName>Intakes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrimaryClient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Intake_Only</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Intake Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Open Intake</fullName>
                    <default>true</default>
                    <label>Open Intake</label>
                </value>
                <value>
                    <fullName>Open Case</fullName>
                </value>
                <value>
                    <fullName>Converted</fullName>
                    <isActive>false</isActive>
                    <label>Converted</label>
                </value>
                <value>
                    <fullName>New</fullName>
                    <isActive>false</isActive>
                    <label>New</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Intake</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Calendar Event Information</relationshipLabel>
        <relationshipName>SUMOAdditionalInfo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facilitator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facilitator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Child Events</relationshipLabel>
        <relationshipName>ChildEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__Attendee__c.object
<CustomObject>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__StartDatetime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__SumoEvent__c</fullName>
        <label>SUMO Event</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SUMO Attendee</label>
    <nameField>
        <displayFormat>ATD-{000000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/IntakeCaseControllerTest.cls
@isTest
public class IntakeCaseControllerTest {
    
    @testSetup static void setup() {
        TestDataFactory.createCaseTypes(2, true);
    }
    
    @isTest
    static void testRetrieveClientCase() {
        // Create test data
        Contact testContact = new Contact(FirstName = 'Test', LastName = 'Contact');
        insert testContact;
        
        Id caseTypeId = [Select Id from CaseType__c LIMIT 1]?.Id;
        ClientCase__c testClientCase = new ClientCase__c(
            PrimaryClient__c = testContact.Id,
            OwnerId = UserInfo.getUserId(),
            CaseType__c = caseTypeId,
            ClientCaseStatus__c = 'In Progress'
        );
        insert testClientCase;
        
        Test.startTest();
        // Call the method
        List<ClientCase__c> result = IntakeCaseController.retrieveClientCase(new List<String>{testContact.Id});
        Test.stopTest();
        
    }
    
    @isTest
    static void testRetrieveIntakeRequests() {
        // Create test data
        Contact testContact = new Contact(FirstName = 'Test', LastName = 'Contact');
        insert testContact;
        
        
        Id caseTypeId = [Select Id from CaseType__c LIMIT 1]?.Id;
        
        Intake__c testIntake = new Intake__c(
            PrimaryClient__c = testContact.Id,
            OwnerId = UserInfo.getUserId(),
            CaseType__c = caseTypeId,
            Status__c = 'Open Intake'
        );
        insert testIntake;
        
        Test.startTest();
        // Call the method
        List<Intake__c> result = IntakeCaseController.retrieveIntakeRequests(new List<String>{testContact.Id});
        Test.stopTest();
        
        
    }
    
    @isTest
    static void testGetCoursesAppointmentRecords() {
        // Create test data
        Contact testContact = new Contact(FirstName = 'Test', LastName = 'Contact');
        insert testContact;
        
        Id caseTypeId = [Select Id from CaseType__c LIMIT 1]?.Id;
        // Check if the RecordType exists before querying
        
        Id courseRecordTypeId,eventRecordType = null;
        
        for(Schema.RecordTypeInfo info : Schema.getGlobalDescribe().get('sumoapp__additionalinfo__c').getDescribe().getRecordTypeInfos()) {
            SYstem.debug('Info : ' + info);
            if(info.getDeveloperName()=='Course') {
                courseRecordTypeId=info.getRecordTypeId();
            } else if(info.getDeveloperName()=='Event') {
                eventRecordType = info.getRecordTypeId();
            }
        }
        
        List<sumoapp__AdditionalInfo__c> addInfos = new List<sumoapp__AdditionalInfo__c>();
        for(sumoapp__AdditionalInfo__c addInfo : TestDataFactory.createSumoEvent(2,false)) {
            addInfo.RecordTypeId=eventRecordType;
            addInfo.Facilitator__c =UserInfo.getUserId();
            addInfos.add(addInfo);
        }
        insert addInfos;
        TestDataFactory.createAttendee(testContact, addInfos.get(0)?.Id, 2, true);
        
        
        Test.startTest();
        // Call the method
        List<IntakeCaseController.CourseWrapper> result = IntakeCaseController.getCourses(new List<String>{testContact.Id});
        Test.stopTest();
        
        
    }
    
    @isTest
    static void testGetCoursesRecords() {
        // Create test data
        Contact testContact = new Contact(FirstName = 'Test', LastName = 'Contact');
        insert testContact;
        
        
        Id courseRecordTypeId,eventRecordType = null;
        
        for(Schema.RecordTypeInfo info : Schema.getGlobalDescribe().get('sumoapp__additionalinfo__c').getDescribe().getRecordTypeInfos()) {
            SYstem.debug('Info : ' + info);
            if(info.getDeveloperName()=='Course') {
                courseRecordTypeId=info.getRecordTypeId();
            } else if(info.getDeveloperName()=='Event') {
                eventRecordType = info.getRecordTypeId();
            }
        }
        
        List<sumoapp__AdditionalInfo__c> addInfos = TestDataFactory.createSumoEvent(3,true);
        
        addInfos.get(0).sumoapp__Parent__c = addInfos.get(1)?.Id;
        addInfos.get(2).sumoapp__Parent__c = addInfos.get(1)?.Id;
        addInfos.get(0).RecordTypeId = courseRecordTypeId;
        addInfos.get(0).sumoapp__StartDatetime__c  = System.now();
        addInfos.get(1).RecordTypeId = courseRecordTypeId;
        addInfos.get(1).sumoapp__StartDatetime__c  = System.now();
        addInfos.get(2).RecordTypeId = courseRecordTypeId;
        addInfos.get(2).sumoapp__StartDatetime__c  = System.now();
        update addInfos;
        
        
        sumoapp__Attendee__c childAttendee = TestDataFactory.createAttendee(testContact, addInfos.get(1)?.Id, 1, true).get(0);
        sumoapp__Attendee__c parentAttendee = TestDataFactory.createAttendee(testContact, addInfos.get(0)?.Id, 1, true).get(0);
        TestDataFactory.createAttendee(testContact, addInfos.get(2)?.Id, 1, true);
        SYstem.debug('From Testclass : Child '+childAttendee);
        SYstem.debug('From Testclass : parent '+parentAttendee);
        SYstem.debug('From Testclass : Parent : Parent__c '+parentAttendee.sumoapp__SumoEvent__r.sumoapp__Parent__c);
        SYstem.debug('From Testclass : Parent : DeveloperName '+parentAttendee.sumoapp__SumoEvent__r.RecordType.DeveloperName);
        SYstem.debug('From Testclass : Child : Parent__c '+childAttendee.sumoapp__SumoEvent__r.sumoapp__Parent__c);
        SYstem.debug('From Testclass : Child : DeveloperName '+childAttendee.sumoapp__SumoEvent__r.RecordType.DeveloperName);
        
        
        Test.startTest();
        // Call the method
        List<IntakeCaseController.CourseWrapper> result = IntakeCaseController.getCourses(new List<String>{testContact.Id});
        Test.stopTest();
        
        
    }
}