objects/CaseType__c.object
<CustomObject>
    <description>To organize the various services provided by the Agency for their clients.</description>
    <fields>
        <fullName>IsClientLookup__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Client Lookup</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsEmergencyTriage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Emergency Triage</label>
        <type>Checkbox</type>
    </fields>
    <label>Case Type</label>
    <nameField>
        <label>Case Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Besttimetocontact__c</fullName>
        <description>Contact’s preferred time to be contacted</description>
        <label>Best Time to Contact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Morning</fullName>
                </value>
                <value>
                    <fullName>Afternoon</fullName>
                </value>
                <value>
                    <fullName>Evening</fullName>
                </value>
                <value>
                    <fullName>Weekend</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MailingAddressLine2__c</fullName>
        <label>Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreferredLanguage__c</fullName>
        <description>Client’s preferred language</description>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English (US)</label>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>ASL</fullName>
                </value>
                <value>
                    <fullName>Cambodian</fullName>
                </value>
                <value>
                    <fullName>Cantonese</fullName>
                </value>
                <value>
                    <fullName>Chinese Mandarin</fullName>
                </value>
                <value>
                    <fullName>Creole</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Goboligok</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hmong</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latin</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
                <value>
                    <fullName>Portuuguese</fullName>
                </value>
                <value>
                    <fullName>Russian</fullName>
                </value>
                <value>
                    <fullName>Swahili</fullName>
                </value>
                <value>
                    <fullName>Turkish</fullName>
                </value>
                <value>
                    <fullName>Ukrainian</fullName>
                </value>
                <value>
                    <fullName>Urdu</fullName>
                </value>
                <value>
                    <fullName>Vietnamese</fullName>
                </value>
                <value>
                    <fullName>Yiddish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <description>Client Social Security Number</description>
        <label>SSN</label>
        <length>11</length>
        <maskChar>X</maskChar>
        <maskType>ssn</maskType>
        <type>EncryptedText</type>
    </fields>
    <recordTypes>
        <fullName>PrimaryClient</fullName>
        <active>true</active>
        <label>Primary Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <label>Prospect</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Intake__c.object
<CustomObject>
    <description>To capture and store initial information about clients/prospects during the intake process including New Intake, New Education Only, and New Emergency Triage.</description>
    <fields>
        <fullName>CaseType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Type</label>
        <referenceTo>CaseType__c</referenceTo>
        <relationshipName>Intakes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Household__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Intake_Only</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IntakeRequestName__c</fullName>
        <formula>PrimaryClient__r.LastName + &quot;, &quot;+ IF(ISNULL(PrimaryClient__r.FirstName) ,&apos;&apos;,MID(PrimaryClient__r.FirstName, 0, 1)) + &quot; - &quot;+ text(DATEVALUE(CreatedDate)) +&quot; - &quot;+ CaseType__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Intake Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryClient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Intake_Only</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Intake Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Open Intake</fullName>
                    <default>true</default>
                    <label>Open Intake</label>
                </value>
                <value>
                    <fullName>Open Case</fullName>
                </value>
                <value>
                    <fullName>Converted</fullName>
                    <isActive>false</isActive>
                    <label>Converted</label>
                </value>
                <value>
                    <fullName>New</fullName>
                    <isActive>false</isActive>
                    <label>New</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Intake</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EmergencyTriageController.cls
public with sharing class EmergencyTriageController {
    
    /**
     * @description : stores the respective records for triage form
	*/
    @AuraEnabled
    public static ResponseWrapper storeLeadIntake(IntakeWrapper requestWrapper) {
        SavePoint sp = Database.setSavePoint();
        ResponseWrapper response = new ResponseWrapper();
        try{

        	Id contactId=null;
			id accountId = null;
        	System.debug('Request Received : ' + requestWrapper);
            if(requestWrapper.contact!=null && Schema.sObjectType.Contact.isCreateable()) {
                Contact contact = requestWrapper.contact;
                //RecordType prospectRecordType = [SELECT Id, Name, DeveloperName FROM RecordType where SobjectType='Contact' AND NAme='Prospect' WITH SECURITY_ENFORCED];
                Id prospectRTId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Prospect').getRecordTypeId();
                Id primaryClientRTId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('PrimaryClient').getRecordTypeId();
                Contact con;
                if(contact.Id != null ){
                    con = [SELECT Id, RecordTypeId FROM Contact WHERE Id = :contact.Id WITH SECURITY_ENFORCED];
                    if(con.RecordTypeId != primaryClientRTId){
                        contact.RecordTypeId = prospectRTId;
                    }
                }else{
                    contact.RecordTypeId = prospectRTId;
                }
                response.contactId = Database.upsert(contact, true, AccessLevel.USER_MODE)?.getId();
                contactId = contact?.Id;
                
                System.debug('Contact Created : '+contact);
                accountID = [Select id,AccountID from Contact where id=:contact.Id WITH SECURITY_ENFORCED LIMIT 1]?.AccountID;
            }
            if(requestWrapper.intakeCaseType!=null && Schema.sObjectType.Intake__c.isCreateable()) {
                Id caseTypeId = [Select Id from CaseType__c where Name=:requestWrapper.intakeCaseType LIMIT 1]?.Id ;
                Id intakeId = [Select id from Intake__c where PrimaryClient__c=:contactId AND CaseType__r.Name=:requestWrapper.intakeCaseType]?.Id;
            	Intake__c intake = new Intake__c();
                intake.id = intakeId;
                intake.PrimaryClient__c = contactId;
                intake.CaseType__c=caseTypeId;
                intake.Status__c='Open Intake';
                intake.Household__c = accountID;
                response.intakeId = Database.upsert(intake, true, AccessLevel.USER_MODE)?.getId();
                
            }
        	return response;
        } catch(Exception e) {
            Database.rollback(sp);
            LoggerClass.log(e,'educationFormSubmit');
            throw new AuraHandledException(e.getMessage());
        }
        
    }
    
    /**
     * @description : retrieves the respective records for emergency form
	*/
    @AuraEnabled
    public static IntakeWrapper getIntakeDetails(Id contactId) {
        IntakeWrapper wrapper = new IntakeWrapper();
        wrapper.contact = [Select id, FirstName, MiddleName, LastName, Suffix, SSN__c, Email, Phone, Besttimetocontact__c, PreferredLanguage__c, Birthdate, MailingStreet, MailingAddressLine2__c, MailingPostalCode, MailingCity, MailingStateCode from contact where id=:contactId LIMIT 1];
        
        wrapper.intakeCaseType = [Select id, CaseType__r.Name,IntakeRequestName__c from Intake__c where CaseType__r.isEmergencyTriage__c=true AND PrimaryClient__c=:contactID LIMIT 1]?.CaseType__r?.Name;
        
        return wrapper;
        
    }

    @AuraEnabled
    public static String getIntakeName(Id intakeId) {
        return [Select id,IntakeRequestName__c from Intake__c where id =: intakeId]?.IntakeRequestName__c;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<CaseType__c> getCaseTypes() {
        List<CaseType__c> caseTypes = [Select id, Name from CaseType__c where isEmergencyTriage__c=true AND IsClientLookup__c=true];
        return caseTypes;
    }
    
    
    public class IntakeWrapper{
        @AuraEnabled
        public Contact contact{get;set;}
        
        @AuraEnabled
        public String intakeCaseType{get;set;}
    }
    
    public class ResponseWrapper{
        
        @AuraENabled
        public String contactId{get;set;}
        
        @AuraEnabled
        public String intakeId{get;set;}
        
        @AuraEnabled
        public String errorMessage{get;set;}
    }

}