objects/CaseType__c.object
<CustomObject>
    <description>To organize the various services provided by the Agency for their clients.</description>
    <fields>
        <fullName>HUDPurpose__c</fullName>
        <label>Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Homeless Assistance</fullName>
                </value>
                <value>
                    <fullName>Pre-purchase/Homebuying</fullName>
                </value>
                <value>
                    <fullName>Rental Topics</fullName>
                </value>
                <value>
                    <fullName>Non-Delinquency Post-Purchase</fullName>
                </value>
                <value>
                    <fullName>Reverse Mortgage</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Forward Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Reverse Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Disaster Preparedness Assistance</fullName>
                </value>
                <value>
                    <fullName>Disaster Recovery Assistance</fullName>
                </value>
                <value>
                    <fullName>Not HUD-Reportable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Type</label>
    <nameField>
        <label>Case Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>CaseType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>HUD and NW reportable case types</description>
        <label>Case Type</label>
        <referenceTo>CaseType__c</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientCaseName__c</fullName>
        <description>Concatenated of contact Last Name + First Letter of First Name + Date Created + Service Type</description>
        <formula>PrimaryClient__r.LastName + &quot;, &quot;+ IF(ISNULL(PrimaryClient__r.FirstName) ,&apos;&apos;,MID(PrimaryClient__r.FirstName, 0, 1)) + &quot; - &quot;+  text(DATEVALUE(CreatedDate)) +&quot; - &quot;+  CaseType__r.Name</formula>
        <label>Client Case Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <description>HUD-specified outcomes for Education only</description>
        <inlineHelpText>HUD-specified outcomes</inlineHelpText>
        <label>Outcome</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed financial literacy workshop, including home affordability, budgeting and understanding use of credit</fullName>
                </value>
                <value>
                    <fullName>Completed predatory lending, loan scam or other fraud prevention workshop</fullName>
                </value>
                <value>
                    <fullName>Completed fair housing workshop</fullName>
                </value>
                <value>
                    <fullName>Completed homelessness prevention workshop</fullName>
                </value>
                <value>
                    <fullName>Completed rental workshop</fullName>
                </value>
                <value>
                    <fullName>Completed pre-purchase homebuyer education workshop</fullName>
                </value>
                <value>
                    <fullName>Completed non-delinquency post-purchase workshop, including home maintenance and/or financial management for homeowners</fullName>
                </value>
                <value>
                    <fullName>Completed resolving or preventing mortgage delinquency workshop</fullName>
                </value>
                <value>
                    <fullName>Completed other workshop</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <description>Agency to custom relevant purposes</description>
        <inlineHelpText>Choose one most applicable value from the drop-down list</inlineHelpText>
        <label>HUD Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Homeless Assistance</fullName>
                </value>
                <value>
                    <fullName>Pre-purchase/Homebuying</fullName>
                </value>
                <value>
                    <fullName>Rental Topics</fullName>
                </value>
                <value>
                    <fullName>Non-Delinquency Post-Purchase</fullName>
                </value>
                <value>
                    <fullName>Reverse Mortgage</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Forward Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Reverse Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Disaster Preparedness Assistance</fullName>
                </value>
                <value>
                    <fullName>Disaster Recovery Assistance</fullName>
                </value>
                <value>
                    <fullName>Not HUD-Reportable</fullName>
                </value>
                <value>
                    <fullName>Financial Literacy</fullName>
                    <isActive>false</isActive>
                    <label>Financial Literacy</label>
                </value>
                <value>
                    <fullName>Home Improvement Loan</fullName>
                    <isActive>false</isActive>
                    <label>Home Improvement Loan</label>
                </value>
                <value>
                    <fullName>Home Purchase Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Home Purchase Inquiry</label>
                </value>
                <value>
                    <fullName>Job Training</fullName>
                    <isActive>false</isActive>
                    <label>Job Training</label>
                </value>
                <value>
                    <fullName>Mortgage Delinquency Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Mortgage Delinquency Inquiry</label>
                </value>
                <value>
                    <fullName>Rehab Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Rehab Inquiry</label>
                </value>
                <value>
                    <fullName>Rental Assistance</fullName>
                    <isActive>false</isActive>
                    <label>Rental Assistance</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CounselorNote__c.object
<CustomObject>
    <description>To manage and document client case notes related client cases.</description>
    <fields>
        <fullName>ClientCaseName__c</fullName>
        <formula>ClientCase__r.ClientCaseName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Case Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Counselor Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>Counselor Note</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>Counselor Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counselor Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Intake__c.object
<CustomObject>
    <description>To capture and store initial information about clients/prospects during the intake process including New Intake, New Education Only, and New Emergency Triage.</description>
    <fields>
        <fullName>CaseType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Type</label>
        <referenceTo>CaseType__c</referenceTo>
        <relationshipName>Intakes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <label>HUD Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Homeless Assistance</fullName>
                </value>
                <value>
                    <fullName>Pre-purchase/Homebuying</fullName>
                </value>
                <value>
                    <fullName>Rental Topics</fullName>
                </value>
                <value>
                    <fullName>Non-Delinquency Post-Purchase</fullName>
                </value>
                <value>
                    <fullName>Reverse Mortgage</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Forward Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Reverse Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Disaster Preparedness Assistance</fullName>
                </value>
                <value>
                    <fullName>Disaster Recovery Assistance</fullName>
                </value>
                <value>
                    <fullName>Not HUD-Reportable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Intake</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Calendar Event Information</relationshipLabel>
        <relationshipName>SUMOAdditionalInfo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HUDActivityType__c</fullName>
        <label>HUD Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>HUDActivityType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>sumoapp__EventName__c</fullName>
        <label>Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Child Events</relationshipLabel>
        <relationshipName>ChildEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>sumoapp__Service__c</referenceTo>
        <relationshipLabel>Service Infos</relationshipLabel>
        <relationshipName>ServiceInfos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__Attendee__c.object
<CustomObject>
    <fields>
        <fullName>HUDActivityType__c</fullName>
        <formula>TEXT( sumoapp__SumoEvent__r.HUDActivityType__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>HUD Activity Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <formula>TEXT( sumoapp__SumoEvent__r.HUD_Purpose__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outcome</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__SumoEvent__c</fullName>
        <label>SUMO Event</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SUMO Attendee</label>
    <nameField>
        <displayFormat>ATD-{000000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/HUDActivityType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Not Billed to HUD</fullName>
        <default>true</default>
        <label>Not Billed to HUD</label>
    </customValue>
    <customValue>
        <fullName>NOFA 2014-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2014-2 TRNG</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2015-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2015-2 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2016-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2017-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2018-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2019-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2020-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2021-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2022-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2023-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>HO INT</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2024-1 COMP</fullName>
    </customValue>
    <masterLabel>HUD Activity Type</masterLabel>
</GlobalValueSet>

classes/ContactTimelineService.cls
public class ContactTimelineService extends ActivityTimelineService{
	
    /*
     * @description : To get Appointments for the corresponding Contact Record
     */
    public override List<ActivityWrapper> getAppointments(Id recordId){
        
        List<ActivityWrapper> result = new List<ActivityWrapper>();
        List<Id> eventIDs = new List<Id>();
        for(EventRelation elt : [Select EventId from EventRelation where RelationId=:recordId AND Relation.Type='Contact']) {
            eventIDs.add(elt.EventId);
        }
        Set<ID> clientCaseIds= new Set<Id>();
        Set<ID> intakeIds = new Set<ID>();
        Map<id, Event> eventMap = new Map<id,Event>();
        for(Event evt : [Select id,what.Type,Subject,Purpose__c,AppointmentStatus__c,Outcome__c,Who.Name,AppointmentDuration__c, StartDateTime,EndDateTime,sumoapp__AdditionalInfo__c,sumoapp__AdditionalInfo__r.Notes__c,sumoapp__AdditionalInfo__r.sumoapp__Service__r.Name, HUDActivityType__c  from Event where ID in :eventIDs AND RecordType.Name = 'Appointment' WITH USER_MODE]) {
            String NWC2NameSpace = Utility.getNwc2NameSpace();
            if(evt.what.Type!=null && NWC2NameSpace+'ClientCase__c'==evt.what.Type) {
           		clientCaseIds.add(evt.WhatId);
            } else if(evt.what.Type!=null && NWC2NameSpace+'Intake__c'==evt.what.Type) {
                intakeIds.add(evt.WhatId);
            }
            eventMap.put(evt.id, evt);
            //result.add(convertEventToWrapper(evt));
        }
        
        Map<Id,CLientCase__c> clientCaseMap = new Map<Id,ClientCase__c>();
        Map<Id,Intake__c> intakeMap = new Map<Id,Intake__c>();
        if(!eventMap.isEmpty()) {
            clientCaseMap = new Map<Id, ClientCase__c>([Select Id,ClientCaseName__c,Purpose__c,CaseType__r.HUDPurpose__c from ClientCase__c where id in :clientCaseIds]);
            intakeMap = new Map<Id,Intake__c>([Select Id,CaseType__r.HUDPurpose__c from Intake__c where id in :intakeIds]);
        }
        
        for(Id eventId : eventMap.keySet()) {
            String Purpose;
           Event evt = eventMap.get(eventId);
            if(clientCaseMap.get(evt.WhatId)!=null) {
                Purpose = clientCaseMap.get(evt.WhatId).CaseType__r?.HUDPurpose__c;
            } else if(intakeMap.get(evt.whatId)!=null) {
                Purpose = intakeMap.get(evt.WhatId).CaseType__r?.HUDPurpose__c;
            }
           result.add(convertEventToWrapper(evt,clientCaseMap.get(evt.WhatId),Purpose)); 
        }
        
        
        
        return result;
    }
    
    /*
     * @description : To get Courses for the corresponding Contact Record
     */
    public override List<ActivityWrapper> getCourses(Id recordId){
        List<ActivityWrapper> result = new List<ActivityWrapper>();
        for(sumoapp__Attendee__c attendee : [Select id,sumoapp__SumoEvent__c,sumoapp__SumoEvent__r.RecordType.DeveloperName,sumoapp__SumoEvent__r.sumoapp__Parent__c,sumoapp__SumoEvent__r.sumoapp__Parent__r.sumoapp__EventName__c,sumoapp__SumoEvent__r.Name,sumoapp__EventName__c,sumoapp__StartDatetime__c,sumoapp__EndDatetime__c from sumoapp__Attendee__c where sumoapp__ContactRelation__c=:recordId WITH SECURITY_ENFORCED]) {
            if((attendee.sumoapp__SumoEvent__r.sumoapp__Parent__c==null && attendee.sumoapp__SumoEvent__r.RecordType.DeveloperName=='Course') ) {
                continue;
            }
            result.add(convertCourseToWrapper(attendee));
        }
        return result;
    }
    
    /*
     * @description : To get Counselor Notes  for the corresponding Contact Record
     */
    public override List<ActivityWrapper> getCounselorNotes(Id recordId){
        List<ActivityWrapper> counselingNotes = new List<ActivityWrapper>();
        for(CounselorNote__c note : [Select id,Name,StartDatetime__c,Subject__c,Notes__c,ClientCase__c,ClientCase__r.ClientCaseName__c,Contact__c from CounselorNote__c where Contact__c=:recordId WITH SECURITY_ENFORCED]) {
            counselingNotes.add(convertNoteToWrapper(note));
        }
        
        return counselingNotes;
    }

}