objects/CaseType__c.object
<CustomObject>
    <description>To organize the various services provided by the Agency for their clients.</description>
    <label>Case Type</label>
    <nameField>
        <label>Case Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>CaseType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>HUD and NW reportable case types</description>
        <label>Case Type</label>
        <referenceTo>CaseType__c</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChoseNottoProvideIncome__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Chose Not to Provide Income</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CounselingTermination__c</fullName>
        <label>Counseling Termination</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ongoing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Dropped Out</fullName>
                </value>
                <value>
                    <fullName>Referred</fullName>
                </value>
                <value>
                    <fullName>No Further Contact</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CoApplicant__c.object
<CustomObject>
    <description>To store details about household members who are co-applicants of the primary contact.</description>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Co-Applicants</relationshipLabel>
        <relationshipName>Co_Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicants</relationshipLabel>
        <relationshipName>Co_Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IntakeRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intake</label>
        <referenceTo>Intake__c</referenceTo>
        <relationshipLabel>Co-Applicants</relationshipLabel>
        <relationshipName>Co_Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Co-Applicant</label>
    <nameField>
        <displayFormat>CAPP-{00000}</displayFormat>
        <label>Co-Applicant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co-Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ChoseNottoProvideIncome__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Chose Not to Provide Income</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>CoApplicant</fullName>
        <active>true</active>
        <label>Co-Applicant</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Intake__c.object
<CustomObject>
    <description>To capture and store initial information about clients/prospects during the intake process including New Intake, New Education Only, and New Emergency Triage.</description>
    <fields>
        <fullName>CaseType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Type</label>
        <referenceTo>CaseType__c</referenceTo>
        <relationshipName>Intakes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChoseNottoProvideIncome__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Chose Not to Provide Income</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Intake Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Open Intake</fullName>
                    <default>true</default>
                    <label>Open Intake</label>
                </value>
                <value>
                    <fullName>Open Case</fullName>
                </value>
                <value>
                    <fullName>Converted</fullName>
                    <isActive>false</isActive>
                    <label>Converted</label>
                </value>
                <value>
                    <fullName>New</fullName>
                    <isActive>false</isActive>
                    <label>New</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Intake</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Calendar Event Information</relationshipLabel>
        <relationshipName>SUMOAdditionalInfo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsParent__c</fullName>
        <formula>IsBlank(sumoapp__Parent__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sumoapp__Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Child Events</relationshipLabel>
        <relationshipName>ChildEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EnrollmentFormControllerTest.cls
@isTest
public class EnrollmentFormControllerTest {
    
    @testSetup
    static void setup() {
        List<Account> portalAccounts = TestDataFactory.createAccounts(1, true);
        List<Contact> ConList = TestDataFactory.createContacts(portalAccounts[0].Id, 2, true);
        Contact primaryContact = ConList[0];
        primaryContact.email = 'primary@example.com';
        primaryContact.FirstName = 'Primary';
        update primaryContact;
        Contact coApplicant = ConList[1];
        coApplicant.FirstName = 'CoApplicant';
        coApplicant.Email = 'coapplicant@example.com';
        coApplicant.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Co-Applicant').getRecordTypeId();
        update coApplicant;
        
        List<sumoapp__AdditionalInfo__c> courses = TestDataFactory.createSumoEvent(2, false);
        sumoapp__AdditionalInfo__c course = courses[0];
        insert course;
        sumoapp__AdditionalInfo__c courseWithChild = courses[1]; 
        courseWithChild.sumoapp__Parent__c = course.Id;
        insert courseWithChild;
	
        List<CaseType__c> caseTypes = TestDataFactory.createCaseTypes(1, true);
        List<ClientCase__c> clientCase = TestDataFactory.createClientCases(1, false);
        clientCase[0].CounselingTermination__c = 'Completed';
        insert clientCase;
        Intake__c intake = TestDataFactory.createIntakes(coApplicant, portalAccounts[0].id, 1, false)[0];
        intake.Status__c='Open Intake';
        intake.CaseType__c = caseTypes[0].Id;
        insert intake;
        
        CoApplicant__c coApplicantRecord = new CoApplicant__c();
        coApplicantRecord.Contact__c = primaryContact.Id;
        coApplicantRecord.IntakeRequest__c = intake.Id;
        insert coApplicantRecord;
    }
    
    @isTest
    static void testGetPicklistValues() {
        Test.startTest();
        List<String> fields = new List<String>{'MailingStateCode'};
            Map<String, List<EnrollmentFormController.PickListWrapper>> result = EnrollmentFormController.getPicklistValues(fields, 'Contact');
        System.assertNotEquals(null, result);
        System.assertNotEquals(null, result.get('MailingStateCode'));
        Test.stopTest();
    }
    
    /*@isTest
    static void testGetCoApplicantContacts() {
        UserRole userrole = [Select Id, DeveloperName From UserRole Limit 1];
        
        User adminUser = [Select Id, UserRoleId From User Where Profile.Name='System Administrator' Limit 1];
        
        adminUser.UserRoleId = userRole.Id;
        adminUser.isActive = true;
        User communityUser;
        update adminUser;
        System.runAs(adminUser){
            Id profileId = [Select Id From Profile Where Name ='Customer Community Login User'].Id;
            List<Contact> contacts = [SELECT Id FROM Contact WHERE Email = 'testrecord@test.com1'];
            communityUser = TestDataFactory.createCommunityUser('Customer Community Login User','userTest0001@gmail.com', 'Lname', true);
            //    communityUser.ContactId = primaryContact[0].Id;
            update communityUser;
        }
        System.runAs(communityUser) {
            List<Contact> contacts = EnrollmentFormController.getCoApplicantContacts();
            System.assertEquals(0, contacts.size());
        }
        
    }*/
    
    @isTest
    static void testGetPrimaryContactInformation() {
        Test.startTest();
        Contact primaryContact = EnrollmentFormController.getPrimaryContactInformation();
        System.assertNotEquals(null, primaryContact);
        Test.stopTest();
    }
    
    @isTest
    static void testGetCourseName() {
        sumoapp__AdditionalInfo__c course = [SELECT Id FROM sumoapp__AdditionalInfo__c LIMIT 1];
        Test.startTest();
        Map<String, Object> result = EnrollmentFormController.getCourseName(course.Id);
        System.assertEquals(course.Id, ((sumoapp__AdditionalInfo__c)result.get('record')).Id);
        Test.stopTest();
    }
    
    @isTest
    static void testUpdateRecords() {
        List<Contact> applicants = [SELECT Id FROM Contact WHERE RecordType.Name = 'Co-Applicant'];
        Contact primaryContact = [SELECT Id, ChoseNottoProvideIncome__c FROM Contact WHERE FirstName = 'Primary' LIMIT 1];
        sumoapp__AdditionalInfo__c course = [SELECT Id,IsParent__c,(select id from sumoapp__ChildEvents__r) FROM sumoapp__AdditionalInfo__c WHERE sumoapp__Parent__c != null LIMIT 1];
        Test.startTest();
        List<Object> result = EnrollmentFormController.updateRecords(primaryContact, applicants, course.Id);
        System.assertEquals(3, result.size());
        Test.stopTest();
    }
    
    @isTest
    static void testUpdateRecordsWithChild() {
        List<Contact> applicants = [SELECT Id FROM Contact WHERE RecordType.Name = 'Co-Applicant'];
        Contact primaryContact = [SELECT Id, ChoseNottoProvideIncome__c FROM Contact WHERE FirstName = 'Primary' LIMIT 1];
        sumoapp__AdditionalInfo__c course = [SELECT Id,IsParent__c,(select id from sumoapp__ChildEvents__r) FROM sumoapp__AdditionalInfo__c WHERE sumoapp__Parent__c = null LIMIT 1];
        Test.startTest();
        List<Object> result = EnrollmentFormController.updateRecords(primaryContact, applicants, course.Id);
        System.assertEquals(3, result.size());
        Test.stopTest();
    }
    
    @isTest
    static void testFetchAllContactCoApplicants() {
        ClientCase__c clientCase = [SELECT Id FROM ClientCase__c LIMIT 1];
        Test.startTest();
        List<Object> result = EnrollmentFormController.fetchAllContactCoApplicants(clientCase.Id);
        Test.stopTest();
    }
    
    @isTest
    static void testInsertCoApplicant() {
        Intake__c intake = [SELECT Id FROM Intake__c LIMIT 1];
        Contact primaryContact = [SELECT Id FROM Contact WHERE Email = 'primary@example.com' LIMIT 1];
        Test.startTest();
        EnrollmentFormController.insertCoApplicant(intake.Id, primaryContact.Id);
        Test.stopTest();
    }
    
    @isTest
    static void testDeleteCoApplicant() {
        CoApplicant__c coApplicant = [SELECT Id FROM CoApplicant__c LIMIT 1];
        Test.startTest();
        EnrollmentFormController.deleteCoApplicant(coApplicant.Id);
        Test.stopTest();
    }
    
    @isTest
    static void testGetRecordStatusIntake() {
        String intakeId = [SELECT Id FROM Intake__c LIMIT 1].Id;
         System.debug('intakeId===>'+intakeId);
        Test.startTest();
        String status = EnrollmentFormController.getRecordStatus(intakeId);
        System.assertEquals('Open Intake', status);
        Test.stopTest();
    }
    
    @isTest
    static void testGetRecordStatusClientCase() {
        String clientCaseId = [SELECT Id FROM ClientCase__c LIMIT 1].Id;
        System.debug('clientCaseId===>'+clientCaseId);
        Test.startTest();
        String status = EnrollmentFormController.getRecordStatus(clientCaseId);
        System.assertEquals('Closed - Incomplete', status);
        Test.stopTest();
    }
}