objects/CaseType__c.object
<CustomObject>
    <description>To organize the various services provided by the Agency for their clients.</description>
    <fields>
        <fullName>NameSpanish__c</fullName>
        <label>Case Type Name (Spanish)</label>
        <type>TextArea</type>
    </fields>
    <label>Case Type</label>
    <nameField>
        <label>Case Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>CaseType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>HUD and NW reportable case types</description>
        <label>Case Type</label>
        <referenceTo>CaseType__c</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <description>Agency to custom relevant purposes</description>
        <inlineHelpText>Choose one most applicable value from the drop-down list</inlineHelpText>
        <label>HUD Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Homeless Assistance</fullName>
                </value>
                <value>
                    <fullName>Pre-purchase/Homebuying</fullName>
                </value>
                <value>
                    <fullName>Rental Topics</fullName>
                </value>
                <value>
                    <fullName>Non-Delinquency Post-Purchase</fullName>
                </value>
                <value>
                    <fullName>Reverse Mortgage</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Forward Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Reverse Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Disaster Preparedness Assistance</fullName>
                </value>
                <value>
                    <fullName>Disaster Recovery Assistance</fullName>
                </value>
                <value>
                    <fullName>Not HUD-Reportable</fullName>
                </value>
                <value>
                    <fullName>Financial Literacy</fullName>
                    <isActive>false</isActive>
                    <label>Financial Literacy</label>
                </value>
                <value>
                    <fullName>Home Improvement Loan</fullName>
                    <isActive>false</isActive>
                    <label>Home Improvement Loan</label>
                </value>
                <value>
                    <fullName>Home Purchase Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Home Purchase Inquiry</label>
                </value>
                <value>
                    <fullName>Job Training</fullName>
                    <isActive>false</isActive>
                    <label>Job Training</label>
                </value>
                <value>
                    <fullName>Mortgage Delinquency Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Mortgage Delinquency Inquiry</label>
                </value>
                <value>
                    <fullName>Rehab Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Rehab Inquiry</label>
                </value>
                <value>
                    <fullName>Rental Assistance</fullName>
                    <isActive>false</isActive>
                    <label>Rental Assistance</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Intake__c.object
<CustomObject>
    <description>To capture and store initial information about clients/prospects during the intake process including New Intake, New Education Only, and New Emergency Triage.</description>
    <fields>
        <fullName>CaseType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Type</label>
        <referenceTo>CaseType__c</referenceTo>
        <relationshipName>Intakes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <label>HUD Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Homeless Assistance</fullName>
                </value>
                <value>
                    <fullName>Pre-purchase/Homebuying</fullName>
                </value>
                <value>
                    <fullName>Rental Topics</fullName>
                </value>
                <value>
                    <fullName>Non-Delinquency Post-Purchase</fullName>
                </value>
                <value>
                    <fullName>Reverse Mortgage</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Forward Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Reverse Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Disaster Preparedness Assistance</fullName>
                </value>
                <value>
                    <fullName>Disaster Recovery Assistance</fullName>
                </value>
                <value>
                    <fullName>Not HUD-Reportable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Intake</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Calendar Event Information</relationshipLabel>
        <relationshipName>SUMOAdditionalInfo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__Duration__c</fullName>
        <label>Duration</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>15</fullName>
                    <label>15 Minutes</label>
                </value>
                <value>
                    <fullName>30</fullName>
                    <label>30 Minutes</label>
                </value>
                <value>
                    <fullName>45</fullName>
                    <label>45 Minutes</label>
                </value>
                <value>
                    <fullName>60</fullName>
                    <default>true</default>
                    <label>1 hour</label>
                </value>
                <value>
                    <fullName>90</fullName>
                    <label>1.5 hour</label>
                </value>
                <value>
                    <fullName>120</fullName>
                    <label>2 hours</label>
                </value>
                <value>
                    <fullName>150</fullName>
                    <label>2.5 hours</label>
                </value>
                <value>
                    <fullName>180</fullName>
                    <label>3 hours</label>
                </value>
                <value>
                    <fullName>210</fullName>
                    <label>3.5 hours</label>
                </value>
                <value>
                    <fullName>240</fullName>
                    <label>4 hours</label>
                </value>
                <value>
                    <fullName>270</fullName>
                    <label>4.5 hours</label>
                </value>
                <value>
                    <fullName>300</fullName>
                    <label>5 hours</label>
                </value>
                <value>
                    <fullName>330</fullName>
                    <label>5.5 hours</label>
                </value>
                <value>
                    <fullName>360</fullName>
                    <label>6 hours</label>
                </value>
                <value>
                    <fullName>390</fullName>
                    <label>6.5 hours</label>
                </value>
                <value>
                    <fullName>420</fullName>
                    <label>7 hours</label>
                </value>
                <value>
                    <fullName>450</fullName>
                    <label>7.5 hours</label>
                </value>
                <value>
                    <fullName>480</fullName>
                    <label>8 hours</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <isActive>false</isActive>
                    <label>10</label>
                </value>
                <value>
                    <fullName>20</fullName>
                    <isActive>false</isActive>
                    <label>20</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <isActive>false</isActive>
                    <label>5</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sumoapp__EventName__c</fullName>
        <label>Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__GenerateVirtualDetails__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Generate Virtual Details</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sumoapp__Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>sumoapp__Location__c</referenceTo>
        <relationshipLabel>Location Infos</relationshipLabel>
        <relationshipName>LocationInfos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BOOKED</fullName>
                    <default>true</default>
                    <label>Booked</label>
                </value>
                <value>
                    <fullName>CANCELED</fullName>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>RESCHEDULED</fullName>
                    <label>Rescheduled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__Location__c.object
<CustomObject>
    <label>SUMO Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SUMO Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UserAppointmentsController.cls
public without sharing class UserAppointmentsController {
    @AuraEnabled(cacheable=true)
    public static List<EventsWrapper> getUserAppointments(String language){
        List<EventsWrapper> appointments = new List<EventsWrapper>();
        try {
            List<User> users = [ SELECT 
                                 Id,
                                 ContactId 
                                 FROM User 
                                 WHERE 
                                 Id = :UserInfo.getUserId()
                                ];

            if (users.isEmpty() || users[0].ContactId == null) return appointments;
            List<Id> eventIds = new List<Id>();
            for(EventRelation elt : [ Select EventId, Relation.Name
                                      FROM EventRelation
                                      WHERE RelationId = :users[0].ContactId
                                      AND Relation.Type='Contact']) {                     
                eventIds.add(elt.EventId);                
            }
            List<Event> events = [ SELECT Id,
                        Subject,
                        sumoapp__AdditionalInfo__c,
                        sumoapp__AdditionalInfo__r.sumoapp__Status__c,
                        Purpose__c,
                        StartDateTime,
                        EndDateTime,
                        sumoapp__AdditionalInfo__r.sumoapp__EventName__c,
                        sumoapp__AdditionalInfo__r.sumoapp__Location__r.Name,
                        sumoapp__AdditionalInfo__r.sumoapp__Duration__c,
                        sumoapp__AdditionalInfo__r.sumoapp__GenerateVirtualDetails__c,
                        sumoapp__OrganizerFullName__c,
                        WhatId
                        FROM Event
                        WHERE Id in :eventIDs AND StartDateTime > today
                        AND What.Type IN ('Intake__c', 'ClientCase__c') 
                        // AND WhoId = :users[0].ContactId
                    ];
            Set<Id> intakeClientCaseIds = new Set<Id>();
            for(Event evt: events) {
                if(evt.WhatId != null) {
                    intakeClientCaseIds.add(evt.WhatId);
                }
            }

            Map<Id, String> intakeClientCaseToCaseType = new Map<Id, String>();
            for(Intake__c itk: [SELECT Id, CaseType__r.Name, CaseType__r.NameSpanish__c  FROM Intake__c WHERE Id IN :intakeClientCaseIds]) {
                intakeClientCaseToCaseType.put(itk.Id, language == 'en-US' ? itk.CaseType__r.Name : itk.CaseType__r.NameSpanish__c);
            }

            for(ClientCase__c itk: [SELECT Id, CaseType__r.Name, CaseType__r.NameSpanish__c FROM ClientCase__c WHERE Id IN :intakeClientCaseIds]) {
                intakeClientCaseToCaseType.put(itk.Id, language == 'en-US' ? itk.CaseType__r.Name : itk.CaseType__r.NameSpanish__c);
            }

            // Get participants list
            Map<Id, List<String>> eventIdToParticipants = new  Map<Id, List<String>>();
            for(EventRelation elt : [Select
                                      EventId,
                                      Relation.Name 
                                      FROM EventRelation 
                                      WHERE EventId IN :eventIds
                                      AND Relation.Type IN ('Contact', 'User')]) {
                if(eventIdToParticipants.containsKey(elt.EventId)) {
                    eventIdToParticipants.get(elt.EventId).add(elt.Relation?.Name);
                } else {
                    eventIdToParticipants.put(elt.EventId, new List<String> { elt.Relation?.Name });
                }
            }
            
            EventsWrapper wrap;
            String caseType;
            for(Event evt: events) {
                caseType = intakeClientCaseToCaseType.containsKey(evt.WhatId) ? intakeClientCaseToCaseType?.get(evt.WhatId) : '';
                wrap = new EventsWrapper(evt, caseType, eventIdToParticipants.get(evt.Id));
                appointments.add(wrap);
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return appointments;
    }
    
     @AuraEnabled(cacheable=true)
    public static List<Utility.PicklistOption> getPicklistValuesOfSubject() {
        List<Utility.PicklistOption> options = new List<Utility.PicklistOption>();
        List<Schema.PicklistEntry> values = Event.Subject.getDescribe().getPicklistValues();
        Map<String,String> statusApiToLabelMap = new Map<String,String>();
        For(Schema.PicklistEntry sp : values){
            options.add(new Utility.PicklistOption(sp.getLabel(), sp.getValue()));
        }
        return options;
    }

    public class EventsWrapper {
        public EventsWrapper(Event evt, String caseType, List<String> participants) {
            this.evt = evt;
            this.caseType = caseType;
            this.participants = participants;
        }
        @AuraEnabled
        public Event evt;
        @AuraEnabled
        public String caseType;
        @AuraEnabled
        public List<String> participants;
    }
}