objects/ClientActionPlan__c.object
<CustomObject>
    <description>To store detailed action plans for clients, outlining goals, obstacles, both client actions and counselor actions to achieve desired outcomes.</description>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Client Action Plans</relationshipLabel>
        <relationshipName>ClientActionPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Action Plan</label>
    <nameField>
        <displayFormat>AP-{00000000}</displayFormat>
        <label>Client Action Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Goal__c.object
<CustomObject>
    <description>To store goals set for clients as part of their action plans, detailing specific objectives to be achieved.</description>
    <fields>
        <fullName>ClientActionPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Action Plan</label>
        <referenceTo>ClientActionPlan__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DueDate__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GoalDetails__c</fullName>
        <label>Goal Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>GoalSubject__c</fullName>
        <label>Goal Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GoalType__c</fullName>
        <label>Goal Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Short Term</fullName>
                </value>
                <value>
                    <fullName>Medium Term</fullName>
                </value>
                <value>
                    <fullName>Long Term</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Goal</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Obstacle__c.object
<CustomObject>
    <description>To store obstacles identified in client action plans, highlighting challenges that may impede progress towards goals.</description>
    <fields>
        <fullName>ClientActionPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Action Plan</label>
        <referenceTo>ClientActionPlan__c</referenceTo>
        <relationshipLabel>Obstacles</relationshipLabel>
        <relationshipName>Obstacles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Obstacles</relationshipLabel>
        <relationshipName>Obstacles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DueDate__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Obstacles</relationshipLabel>
        <relationshipName>Obstacles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ObstacleDetails__c</fullName>
        <label>Obstacle Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ObstacleSubject__c</fullName>
        <label>Obstacle Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Obstacle</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Obstacles Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Obstacles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Solution__c.object
<CustomObject>
    <description>To store solutions identified in action plans, detailing strategies and actions to overcome obstacles and achieve goals.</description>
    <fields>
        <fullName>ClientActionPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Action Plan</label>
        <referenceTo>ClientActionPlan__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Obstacle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obstacle</label>
        <referenceTo>Obstacle__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SolutionDetails__c</fullName>
        <label>Solution Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SolutionSubject__c</fullName>
        <label>Solution Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Solution</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Solution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PrintActionPlanVfControllerTest.cls
@IsTest
public class PrintActionPlanVfControllerTest {
	@testSetup 
    static void testSetup() {
        ClientCase__c clCase = TestDataFactory.createClientCases(1, true)[0];
        
        ClientActionPlan__c  cap = new ClientActionPlan__c ();
        cap.ClientCase__c = clCase.Id;
        insert cap;
        
        Goal__c goal = new Goal__c();
        goal.ClientCase__c = clCase.Id;
        goal.ClientActionPlan__c = cap.Id;
        goal.GoalSubject__c = 'Buy a house';
        goal.GoalDetails__c = 'test details';
        goal.GoalType__c = 'Short Term';
        goal.Status__c = 'Not Started';
        goal.DueDate__c = System.today();
        
        insert goal;
        
        List<Obstacle__c> obsList = new List<Obstacle__c>();
        
        Obstacle__c obs1 = new Obstacle__c();
        obs1.Goal__c = goal.Id;
        obs1.ObstacleSubject__c = 'Buy a house';
        obs1.ObstacleDetails__c = 'test details';
        obs1.DueDate__c = System.today();
        obsList.add(obs1);
        
        Obstacle__c obs2 = new Obstacle__c();
        obs2.Goal__c = goal.Id;
        obs2.ObstacleSubject__c = 'Lack of opportunity';
        obs2.ObstacleDetails__c = 'test details';
        obs2.DueDate__c = System.today();
        obsList.add(obs2);
        
        insert obsList;
        
        Solution__c sol = new Solution__c();
        sol.Obstacle__c = obs1.Id;
        sol.SolutionSubject__c = 'Increase income';
        sol.SolutionDetails__c = 'test details';
        sol.Status__c = 'Not Started';
        
        insert sol;
        
        List<Task> taskList = new List<Task>();
        
        Task clientTask = new Task();
        clientTask.ActionType__c = 'Client Action';
        clientTask.Subject = 'test sub';
        clientTask.Description = 'test sub';
        clientTask.Status = 'Not Started';
        clientTask.ActivityDate = System.today();
        clientTask.WhatId = sol.Id;
        taskList.add(clientTask);
        
        Task counselorTask = new Task();
        counselorTask.ActionType__c = 'Counselor Action';
        counselorTask.Subject = 'test sub';
        counselorTask.Description = 'test sub';
        counselorTask.Status = 'Completed';
        counselorTask.ActivityDate = System.today();
        counselorTask.WhatId = sol.Id;
        taskList.add(counselorTask);
        
        insert taskList;
        
        TestDataFactory.createFinancialSnapshots(clCase.Id , 3, true);
	}
    
    @isTest
    static void getPrintActionPlanVf() {
        ClientCase__c cc = [Select Id from ClientCase__c limit 1];
        
        Test.startTest();
            PageReference pageRef = Page.printActionPlanVf;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('Id', cc.Id);
            PrintActionPlanVfController objCtrl = new PrintActionPlanVfController();
        	System.assertNotEquals(NULL, objCtrl.clientCaseName);
        	System.assertNotEquals(NULL, objCtrl.wrapList);
        	System.assertNotEquals(NULL, objCtrl.wrapList[0].actionPlans);
        	System.assertEquals(1, objCtrl.wrapList[0].actionPlans.size());
        	System.assertNotEquals(NULL, objCtrl.wrapList[0].actionPlans[0].obstacleList);
        	System.assertEquals(2, objCtrl.wrapList[0].actionPlans[0].obstacleList.size());
        Test.stopTest();
    }

}