objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <formula>Account.ClientNumber__c</formula>
        <label>Client #</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CounselorTraining__c.object
<CustomObject>
    <description>To store information about counselor training, including completed courses, certifications, and relevant training activities.</description>
    <fields>
        <fullName>Counselor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Counselor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Counselor_Training</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Counselor Training</label>
    <nameField>
        <displayFormat>Training {000000}</displayFormat>
        <label>Counselor Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counselor Training</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HUD9902ErrorLog__c.object
<CustomObject>
    <fields>
        <fullName>X9902__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>9902</label>
        <referenceTo>X9902__c</referenceTo>
        <relationshipLabel>HUD 9902 Error Logs</relationshipLabel>
        <relationshipName>HUD_9902_Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HUD 9902 Error Log</label>
    <nameField>
        <displayFormat>HEL-{000000}</displayFormat>
        <label>HUD 9902 Error Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HUD 9902 Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Calendar Event Information</relationshipLabel>
        <relationshipName>SUMOAdditionalInfo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CourseNumber__c</fullName>
        <label>Course Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__Attendee__c.object
<CustomObject>
    <fields>
        <fullName>sumoapp__ContactRelation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Relation</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Event Attendees</relationshipLabel>
        <relationshipName>ContactEventAttendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__SumoEvent__c</fullName>
        <label>SUMO Event</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SUMO Attendee</label>
    <nameField>
        <displayFormat>ATD-{000000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>CMSCounselorID__c</fullName>
        <description>Represents the unique identifier or code assigned to the counselor</description>
        <inlineHelpText>If this field is blank the user will not be reported to HUD as a counselor.</inlineHelpText>
        <label>CMS Counselor ID</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/X9902__c.object
<CustomObject>
    <description>To store data and information related to HUD 9902 reporting, including fields for Generation and Submission statuses, and serves as the parent object for the 9902 Agency, 9902 Client, 9902 Counselor, and 9902 Summary objects.</description>
    <fields>
        <fullName>ClientSubmissionStatus__c</fullName>
        <description>Status of the submission made by the client. Indicate the current status of the submission.</description>
        <label>Client Summary Submission</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CounselorSubmissionStatus__c</fullName>
        <description>Status of the submission made by the counselor. Indicate the current status of the submission.</description>
        <label>Counselor Profile Submission</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Summary9902SubmissionStatus__c</fullName>
        <description>Status of the submission of the 9902. Indicate the current status of the submission of the 9902.</description>
        <label>9902 Summary Submission</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>9902</label>
    <nameField>
        <displayFormat>HUD-{000000}</displayFormat>
        <label>9902</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>9902</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HUD9902ErrorUtilityService.cls
public with sharing class HUD9902ErrorUtilityService {
    private static String NWC2NameSpace = Utility.getNwc2NameSpace();
    
	@future
    public static void processErrorForSummary(Id X9902RecId) {
        X9902__c x9902Rec = [SELECT Id, ClientSubmissionStatus__c, Summary9902SubmissionStatus__c FROM X9902__c WHERE Id = :X9902RecId LIMIT 1];
        HUD9902ErrorUtility.deleteErrorRecords(x9902Rec.Id, new Set<String>{'9902 Summary', 'SUMO Attendee', 'Course'});
        if (x9902Rec.Summary9902SubmissionStatus__c == null || x9902Rec.Summary9902SubmissionStatus__c == '' || x9902Rec.Summary9902SubmissionStatus__c == 'DONE') return;
        List<HUD9902ErrorLog__c> errLogs = new List<HUD9902ErrorLog__c>();
        String hudErrors = x9902Rec.Summary9902SubmissionStatus__c;

        // Add generic error records first
        Set<String> genericErrors = HUD9902ErrorUtility.getGenericErrors(hudErrors);
        for (String errorMsg: genericErrors) {
            errLogs.add(HUD9902ErrorUtility.createErrorRecord(x9902Rec, null, errorMsg, '9902 Summary'));
        }

        // Process record specific error having line numbers
        Map<Integer, String> errorLineNumberToMsg = HUD9902ErrorUtility.getLineNumberDetails(hudErrors);
        Map<String, Integer> identifierToLineNum = new Map<String, Integer>();
        Map<Integer, String> lineNumToIdentifier = new Map<Integer, String>();
        Set<String> identifiers = new Set<String>();

        Set<String> gsIdentifiers = new Set<String>();
        Set<String> gsAttendeeIdentifiers = new Set<String>();
        Set<String> attendeeIdentifiers = new Set<String>();
        String gsIdentifier;
        String gsAttendeeIdentifier;
        String attendeeIdentifier;
        for (Integer lineNumber: errorLineNumberToMsg.keySet()) {
            System.debug('lineNumber::' + lineNumber + ' Msg::' + errorLineNumberToMsg.get(lineNumber));
            gsIdentifier = HUD9902ErrorUtility.getIdentifierTagValueAtLine(HUD9902ErrorUtility.readContentVersion(x9902Rec.Id, '9902_Summary%'), lineNumber, 'Course');
            gsAttendeeIdentifier = HUD9902ErrorUtility.getIdentifierTagValueAtLine(HUD9902ErrorUtility.readContentVersion(x9902Rec.Id, '9902_Summary%'), lineNumber, 'Group Session Attendee');
            attendeeIdentifier = HUD9902ErrorUtility.getIdentifierTagValueAtLine(HUD9902ErrorUtility.readContentVersion(x9902Rec.Id, '9902_Summary%'), lineNumber, 'Attendee');
            // Group Session
            if (gsIdentifier != null) {
                gsIdentifiers.add(gsIdentifier);
                identifierToLineNum.put(gsIdentifier, lineNumber);
            }
            // Group Session Attendee
            if (gsAttendeeIdentifier != null) {
                gsAttendeeIdentifiers.add(gsAttendeeIdentifier);
                identifierToLineNum.put(gsAttendeeIdentifier, lineNumber);
                lineNumToIdentifier.put(lineNumber, gsAttendeeIdentifier);
            }
            // Attendee
            if (attendeeIdentifier != null) {
                attendeeIdentifiers.add(attendeeIdentifier);
                identifierToLineNum.put(attendeeIdentifier, lineNumber);
            }
        }

        System.debug('gsIdentifiers::' + JSON.serializePretty(gsIdentifiers));
        System.debug('gsAttendeeIdentifiers::' + JSON.serializePretty(gsAttendeeIdentifiers));
        System.debug('attendeeIdentifiers::' + JSON.serializePretty(attendeeIdentifiers));

        // get attendee to group session identifier map
        Map<String, List<String>> attendeeToGsIdentifiers = HUD9902ErrorUtility.getAttendeeToGroupSessionIdentifierMap(HUD9902ErrorUtility.readContentVersion(x9902Rec.Id, '9902_Summary%'), identifierToLineNum, lineNumToIdentifier);
        System.debug('attendeeToGsIdentifiers::' + JSON.serializePretty(attendeeToGsIdentifiers));

        Map<String, Id> result = new Map<String, Id>();
        // Group Session
        if (!gsIdentifiers.isEmpty()) {
            // Process Group Session Records
            List<sumoapp__AdditionalInfo__c> courseRecs = HUD9902ErrorUtility.getSourceCourseRecs(gsIdentifiers);
            result.putAll(HUD9902ErrorUtility.matchStringsToSObjects(gsIdentifiers, courseRecs, HUD9902ErrorUtilityService.NWC2NameSpace + 'CourseNumber__c'));
        }

        // Group Session attendee
        if (!gsAttendeeIdentifiers.isEmpty()) {
            // Process Group Session Records
            List<sumoapp__Attendee__c> attendeeRecs = HUD9902ErrorUtility.getSourceAttendeeRecs(gsAttendeeIdentifiers);
            List<sumoapp__Attendee__c> filteredAttendeeRecs = new List<sumoapp__Attendee__c>();
            for (sumoapp__Attendee__c attendee: attendeeRecs) {
                if (attendeeToGsIdentifiers.get(attendee.sumoapp__ContactRelation__r?.Client__c) != null && attendeeToGsIdentifiers.get(attendee.sumoapp__ContactRelation__r.Client__c).contains(attendee.sumoapp__SumoEvent__r?.CourseNumber__c)) {
                    filteredAttendeeRecs.add(attendee);
                }
            }
            System.debug('filteredAttendeeRecs::' + JSON.serializePretty(filteredAttendeeRecs));
            result.putAll(HUD9902ErrorUtility.matchStringsToSObjects(gsAttendeeIdentifiers, filteredAttendeeRecs, 'sumoapp__ContactRelation__r.Client__c'));
        }

        // Attendee
        if (!attendeeIdentifiers.isEmpty()) {
            // Process Attendee Records
            List<sumoapp__Attendee__c> attendeeRecs = HUD9902ErrorUtility.getSourceAttendeeRecs(attendeeIdentifiers);
            result.putAll(HUD9902ErrorUtility.matchStringsToSObjects(attendeeIdentifiers, attendeeRecs, 'sumoapp__ContactRelation__r.Client__c'));
        }

        System.debug('result::' + JSON.serializePretty(result));
        Id recId;
        for (String ident: result.keySet()) {
            recId = result.get(ident);
            errLogs.add(HUD9902ErrorUtility.createErrorRecord(x9902Rec, recId, errorLineNumberToMsg.get(identifierToLineNum.get(ident)), '9902 Summary'));
        }
        if (!errLogs.isEmpty()) insert errLogs;
    }
    
    @future
    public static void processErrorForCounselor(Id X9902RecId) {
        X9902__c x9902Rec = [SELECT Id, CounselorSubmissionStatus__c FROM X9902__c WHERE Id = :X9902RecId LIMIT 1];
        HUD9902ErrorUtility.deleteErrorRecords(x9902Rec.Id, new Set<String>{'9902 Counselor', 'Counselor Training', 'User'});
        if (x9902Rec.CounselorSubmissionStatus__c == null || x9902Rec.CounselorSubmissionStatus__c == '' || x9902Rec.CounselorSubmissionStatus__c == 'DONE') return;
        List<HUD9902ErrorLog__c> errLogs = new List<HUD9902ErrorLog__c>();
        String hudErrors = x9902Rec.CounselorSubmissionStatus__c;

        // Add generic error records first
        Set<String> genericErrors = HUD9902ErrorUtility.getGenericErrors(hudErrors);
        for (String errorMsg: genericErrors) {
            errLogs.add(HUD9902ErrorUtility.createErrorRecord(x9902Rec, null, errorMsg, '9902 Counselor'));
        }

        // Process record specific error having line numbers
        Map<Integer, String> errorLineNumberToMsg = HUD9902ErrorUtility.getLineNumberDetails(hudErrors);
        Map<String, Integer> identifierToLineNum = new Map<String, Integer>();
        Set<String> identifiers = new Set<String>();
        String identifier;
        for (Integer lineNumber: errorLineNumberToMsg.keySet()) {
            identifier = HUD9902ErrorUtility.getIdentifierTagValueAtLine(HUD9902ErrorUtility.readContentVersion(x9902Rec.Id, '9902_Counselor%'), lineNumber);
            if (identifier != null) {
                identifiers.add(identifier);
            }
            identifierToLineNum.put(identifier, lineNumber);
        }
        if (!identifiers.isEmpty()) {
            // Process Group Session Records
            List<User> counselorRecs = HUD9902ErrorUtility.getSourceCounselorRecs(identifiers);
            Map<String, Id> result = HUD9902ErrorUtility.matchStringsToSObjects(identifiers, counselorRecs, HUD9902ErrorUtilityService.NWC2NameSpace + 'CMSCounselorID__c');

            // Process Attendee Records
            List<CounselorTraining__c> counselorTrainingRecs = HUD9902ErrorUtility.getSourceCounselorTrainingRecs(identifiers);
            result.putAll(HUD9902ErrorUtility.matchStringsToSObjects(identifiers, counselorTrainingRecs, HUD9902ErrorUtilityService.NWC2NameSpace + 'Counselor__r.CMSCounselorID__c'));
            Id recId;
            for (String ident: result.keySet()) {
                recId = result.get(ident);
                errLogs.add(HUD9902ErrorUtility.createErrorRecord(x9902Rec, recId, errorLineNumberToMsg.get(identifierToLineNum.get(ident)), '9902 Counselor'));
                System.debug(ident + '  :  ' + HUD9902ErrorUtility.generateRecordUrl(recId));
            }
        }
        if (!errLogs.isEmpty()) insert errLogs;
    }

    @future
    public static void processErrorForClinet(Id X9902RecId) {
        //System.debug('processErrorForClinet:' + X9902RecId);
        X9902__c x9902Rec = [SELECT Id, ClientSubmissionStatus__c FROM X9902__c WHERE Id = :X9902RecId LIMIT 1];
        
        //System.debug('x9902Rec:' + x9902Rec);
        HUD9902ErrorUtility.deleteErrorRecords(x9902Rec.Id, new Set<String>{'Client Case'});
        if (x9902Rec.ClientSubmissionStatus__c == null || x9902Rec.ClientSubmissionStatus__c == '' || x9902Rec.ClientSubmissionStatus__c == 'DONE') return;
        
        List<HUD9902ErrorLog__c> errLogs = new List<HUD9902ErrorLog__c>();
        String hudErrors = x9902Rec.ClientSubmissionStatus__c;
        //System.debug('hudErrors:' + hudErrors);

        /*Not sre if we have any generic error for client - so commmentning it
        // Add generic error records first
        Set<String> genericErrors = HUD9902ErrorUtility.getGenericErrors(hudErrors);
        for (String errorMsg: genericErrors) {
            errLogs.add(HUD9902ErrorUtility.createErrorRecord(x9902Rec, null, errorMsg, '9902 Summary'));
        }
        */

        // Process record specific error having line numbers
        Map<Integer, String> errorLineNumberToMsg = HUD9902ErrorUtility.getLineNumberDetails(hudErrors);
        Map<String, Integer> identifierToLineNum = new Map<String, Integer>();
        Set<String> identifiers = new Set<String>();
        String identifier;
        System.debug('errorLineNumberToMsg:' + errorLineNumberToMsg);
        System.debug('errorLineNumberToMsg:' + errorLineNumberToMsg.keySet().size());
        for (Integer lineNumber: errorLineNumberToMsg.keySet()) {
            identifier = HUD9902ErrorUtility.getIdentifierTagValueAtLine(HUD9902ErrorUtility.readContentVersion(x9902Rec.Id, 'Client_Summary%'), lineNumber);
            if (identifier != null) {
                identifiers.add(identifier);
            }
            identifierToLineNum.put(identifier, lineNumber);
        }
        System.debug('identifiers:' + identifiers);
        if (!identifiers.isEmpty()) {
            // Process Client Case Records
            List<ClientCase__c> clientRecs = HUD9902ErrorUtility.getSourceClientCaseRecs(identifiers);
            System.debug('clientRecs:' + clientRecs);
            Map<String, Id> result = HUD9902ErrorUtility.matchStringsToSObjects(identifiers, clientRecs, 'Name');
            System.debug('result:' + result);

            Id recId;
            for (String ident: result.keySet()) {
                recId = result.get(ident);
                errLogs.add(HUD9902ErrorUtility.createErrorRecord(x9902Rec, recId, errorLineNumberToMsg.get(identifierToLineNum.get(ident)), '9902 Client'));
                System.debug(ident + '  :  ' + HUD9902ErrorUtility.generateRecordUrl(recId));
            }
        }
        System.debug('errLogs:' + errLogs);
        if (!errLogs.isEmpty()) insert errLogs;
    }
}