objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>Address</type>
    </fields>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AreaMedianIncome__c</fullName>
        <label>Area Median Income</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Below 30% of AMI</fullName>
                </value>
                <value>
                    <fullName>30 - 49% of AMI</fullName>
                </value>
                <value>
                    <fullName>50 - 79% of AMI</fullName>
                </value>
                <value>
                    <fullName>80 - 100% of AMI</fullName>
                </value>
                <value>
                    <fullName>101% - 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Above 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Chose not to respond</fullName>
                </value>
                <value>
                    <fullName>Above 100% AMI</fullName>
                    <isActive>false</isActive>
                    <label>Above 100% AMI</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClientCaseClosedDate__c</fullName>
        <description>Date the case is closed</description>
        <label>Client Case Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DisabledStatus__c</fullName>
        <label>Disabled Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <description>HUD-Defined Ethnicity</description>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>HUD-Defined Gender</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HouseholdMonthlyIncome1__c</fullName>
        <label>Household Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>HUD-Defined Number in Household</description>
        <inlineHelpText>Total number of people living in the same household as the primary client</inlineHelpText>
        <label>Household Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HouseholdType__c</fullName>
        <label>Household Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MaritalStatus__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>HouseholdTypeHeadofHousehold</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IntakeDate__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Date the agency performed intake for the client.</description>
        <label>Intake Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MailingAddressLine2__c</fullName>
        <label>Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryClient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <description>HUD-Defined Race</description>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RuralAreaStatus__c</fullName>
        <description>HUD-Defined  Rural Status (Household)</description>
        <label>Rural Area Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Rural_Area_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <formula>YEAR(TODAY()) - YEAR(Birthdate) - IF(MONTH(TODAY()) * 100 + DAY(TODAY()) &lt; MONTH(Birthdate) * 100 + DAY(Birthdate), 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AreaMedianIncome__c</fullName>
        <label>Area Median Income</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Below 30% of AMI</fullName>
                </value>
                <value>
                    <fullName>30 - 49% of AMI</fullName>
                </value>
                <value>
                    <fullName>50 - 79% of AMI</fullName>
                </value>
                <value>
                    <fullName>80 - 100% of AMI</fullName>
                </value>
                <value>
                    <fullName>101% - 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Above 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Chose not to respond</fullName>
                </value>
                <value>
                    <fullName>Above 100% AMI</fullName>
                    <isActive>false</isActive>
                    <label>Above 100% AMI</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <formula>Account.ClientNumber__c</formula>
        <label>Client #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DisabledStatus__c</fullName>
        <label>Disabled Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <description>Client’s self-identified ethnicity, used in 9902 reporting</description>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Male, Female, Other/Non-Conforming</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HouseholdMonthlyIncome1__c</fullName>
        <label>Household Monthly Income</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>Number of people in the household</description>
        <inlineHelpText>Total number of people living in the same household</inlineHelpText>
        <label>Household Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HouseholdType__c</fullName>
        <label>Household Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MaritalStatus__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>HouseholdTypeHeadofHousehold</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MailingAddressLine2__c</fullName>
        <label>Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreferredLanguage__c</fullName>
        <description>Client’s preferred language</description>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English (US)</label>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>ASL</fullName>
                </value>
                <value>
                    <fullName>Cambodian</fullName>
                </value>
                <value>
                    <fullName>Cantonese</fullName>
                </value>
                <value>
                    <fullName>Chinese Mandarin</fullName>
                </value>
                <value>
                    <fullName>Creole</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Goboligok</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hmong</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latin</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
                <value>
                    <fullName>Portuuguese</fullName>
                </value>
                <value>
                    <fullName>Russian</fullName>
                </value>
                <value>
                    <fullName>Swahili</fullName>
                </value>
                <value>
                    <fullName>Turkish</fullName>
                </value>
                <value>
                    <fullName>Ukrainian</fullName>
                </value>
                <value>
                    <fullName>Urdu</fullName>
                </value>
                <value>
                    <fullName>Vietnamese</fullName>
                </value>
                <value>
                    <fullName>Yiddish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <description>Which HUD 9902-recognized race category the contact belongs to.</description>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RuralAreaStatus__c</fullName>
        <description>Whether or not this contact resides in a rural area as defined by HUD.</description>
        <label>Rural Area Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Rural_Area_Status</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Ethnicity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Not Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Ethnicity</description>
    <masterLabel>Ethnicity</masterLabel>
</GlobalValueSet>

globalValueSets/Gender.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <customValue>
        <fullName>Other/Non-conforming</fullName>
    </customValue>
    <description>Gender</description>
    <masterLabel>Gender</masterLabel>
</GlobalValueSet>

globalValueSets/HouseholdTypeHeadofHousehold.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Single adult</fullName>
    </customValue>
    <customValue>
        <fullName>Female-headed single parent household</fullName>
    </customValue>
    <customValue>
        <fullName>Male-headed single parent household</fullName>
    </customValue>
    <customValue>
        <fullName>Married without dependents</fullName>
    </customValue>
    <customValue>
        <fullName>Married with dependents</fullName>
    </customValue>
    <customValue>
        <fullName>Two or more unrelated Adults</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Married with children</fullName>
        <isActive>false</isActive>
        <label>Married with children</label>
    </customValue>
    <customValue>
        <fullName>Male-headed single parent household/Head of Household</fullName>
        <isActive>false</isActive>
        <label>Male-headed single parent household/Head of Household</label>
    </customValue>
    <customValue>
        <fullName>Female-headed single parent household/Head of Household</fullName>
        <isActive>false</isActive>
        <label>Female-headed single parent household/Head of Household</label>
    </customValue>
    <customValue>
        <fullName>Domestic partnership</fullName>
        <isActive>false</isActive>
        <label>Domestic partnership</label>
    </customValue>
    <customValue>
        <fullName>Married without children</fullName>
        <isActive>false</isActive>
        <label>Married without children</label>
    </customValue>
    <masterLabel>Household Type/Head of Household</masterLabel>
</GlobalValueSet>

globalValueSets/Race.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>American Indian/Alaskan Native</fullName>
    </customValue>
    <customValue>
        <fullName>Asian</fullName>
    </customValue>
    <customValue>
        <fullName>Black or African American</fullName>
    </customValue>
    <customValue>
        <fullName>Native Hawaiian or Other Pacific Islander</fullName>
    </customValue>
    <customValue>
        <fullName>White</fullName>
    </customValue>
    <customValue>
        <fullName>More than one race</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Race</description>
    <masterLabel>Race</masterLabel>
</GlobalValueSet>

globalValueSets/Rural_Area_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Lives in a rural area</fullName>
    </customValue>
    <customValue>
        <fullName>Does not live in a rural area</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Rural Area Status</description>
    <masterLabel>Rural Area Status</masterLabel>
</GlobalValueSet>

classes/NWQRCounselingReportController.cls
/**
 * @description       : Controller of HudOrsCounselingReport lwc for NWQR reporting
 * @group             : 
**/
public with sharing class NWQRCounselingReportController {
    
    /*
    * @description : method to fetch Client Case records
    */
    @AuraEnabled
    public static List<OrsReportWrapper> fetchOrsCounselingRecords(Date dtStartdateClosed, Date dtEnddateClosed){
        List<OrsReportWrapper> orsWrapperList = new List<OrsReportWrapper>();

        List<String> purposeList = new List<String>{'Homeless Assistance','Pre-purchase/Homebuying','Rental Topics','Non-Delinquency Post-Purchase',
        'Reverse Mortgage','Resolving or Preventing Forward Mortgage Delinquency or Default','Resolving or Preventing Reverse Mortgage Delinquency or Default',
        'Disaster Preparedness Assistance','Disaster Recovery Assistance'};

        List<Id> clientCaseIdLst = new List<Id>();
        for(Event ob : [SELECT WhatId FROM Event where AppointmentStatus__c = 'Attended' and What.Type = 'ClientCase__c']){
            clientCaseIdLst.add(ob.WhatId);
        }

        List<ClientCase__c> clientCaseList = [select id, PrimaryClient__r.Client__c ,IntakeDate__c, Age__c, Gender__c, Race__c, 
                                              Ethnicity__c, DisabledStatus__c, HouseholdType__c, HouseholdSize__c, HouseholdMonthlyIncome1__c, 
                                              AreaMedianIncome__c, PrimaryClient__r.PreferredLanguage__c, PrimaryClient__r.RuralAreaStatus__c, ClientCaseClosedDate__c,
                                              Address__c, MailingAddressLine2__c, Purpose__c, LastEventDate__c,
                                              One_on_One_Disaster_Preparedness_Assista__c, One_on_One_Disaster_Recovery_Assistance__c, One_on_One_Forward_Mortgage_Delinquency__c, 
                                              One_on_One_Homeless_Assistance__c, One_on_One_Non_Delinquency_Post_Purchase__c, One_on_One_Pre_purchase_Homebuying__c,
                                              One_on_One_Rental_Topics__c, One_on_One_Reverse_Mortgage__c, One_on_One_Reverse_Mortgage_Delinquency__c 
                                              from ClientCase__c
                                              where ClientCaseClosedDate__c <=: dtEnddateClosed and ClientCaseClosedDate__c >=: dtStartdateClosed
                                              and ClientCaseStatus__c = 'Closed - Complete' and Purpose__c != null and id IN : clientCaseIdLst and Purpose__c IN : purposeList
                                              WITH SECURITY_ENFORCED limit 49999];

        List<NWQR_Picklist_Mapping__mdt> pickListAdj = [select id, Label__c, Value__c from NWQR_Picklist_Mapping__mdt where ObjectApiName__c = 'ClientCase__c' And (FieldApiName__c = 'AreaMedianIncome__c' OR FieldApiName__c = 'Gender__c' OR FieldApiName__c = 'Race__c')];
        Map<String,String> labelValueMap = new Map<String,String>();
        for(NWQR_Picklist_Mapping__mdt mdt : pickListAdj){
            if(mdt.Value__c != null && mdt.Label__c != null){
                labelValueMap.put(mdt.Value__c,mdt.Label__c);
            }
        }
        
        for(ClientCase__c clientCase : clientCaseList){
            if(clientCase.LastEventDate__c == null || clientCase.LastEventDate__c <= clientCase.ClientCaseClosedDate__c){
                OrsReportWrapper orswrap = new OrsReportWrapper();
            
                orswrap.Household_Number = clientCase.PrimaryClient__r.Client__c;
                orswrap.Date_Opened = clientCase.IntakeDate__c.format();
                orswrap.Current_Age = clientCase.Age__c;
                if(labelValueMap.containsKey(clientCase.Gender__c)){
                    orswrap.Head_of_Household_Gender = labelValueMap.get(clientCase.Gender__c);
                }else{
                    orswrap.Head_of_Household_Gender = clientCase.Gender__c;
                }

                if(labelValueMap.containsKey(clientCase.Race__c)){
                    orswrap.Head_of_Household_Race = labelValueMap.get(clientCase.Race__c);
                }else{
                    orswrap.Head_of_Household_Race = clientCase.Race__c;
                }
                orswrap.Head_of_Household_Ethnicity = clientCase.Ethnicity__c;
                if(clientCase.DisabledStatus__c == 'Yes'){
                    orswrap.Disabled = 'Disabled';
                }else if(clientCase.DisabledStatus__c == 'No'){
                    orswrap.Disabled = 'Not disabled';
                }
                orswrap.Household_Type = clientCase.HouseholdType__c;
                orswrap.Total_Household_Members = clientCase.HouseholdSize__c;
                orswrap.Household_Gross_Monthly_Income = clientCase.HouseholdMonthlyIncome1__c;
                if(labelValueMap.containsKey(clientCase.AreaMedianIncome__c)){
                    orswrap.Household_AMI = labelValueMap.get(clientCase.AreaMedianIncome__c);
                }else{
                    orswrap.Household_AMI = clientCase.AreaMedianIncome__c;
                }
                orswrap.Preferred_Language = clientCase.PrimaryClient__r.PreferredLanguage__c;
                if(clientCase.Address__c != null){
                    orswrap.BillingStreet = clientCase.Address__c.getstreet();
                    orswrap.BillingCity = clientCase.Address__c.getcity();
                    orswrap.BillingState = clientCase.address__c.getStateCode();
                    orswrap.BillingPostalCode = clientCase.Address__c.getpostalCode();
                }
                orswrap.Apt = clientCase.MailingAddressLine2__c;
                orswrap.ORS_Rural_Area_Status = clientCase.PrimaryClient__r.RuralAreaStatus__c;
                orswrap.One_on_One_Homeless_Assistance = clientCase.One_on_One_Homeless_Assistance__c;
                orswrap.One_on_One_Rental_Topics = clientCase.One_on_One_Rental_Topics__c;
                orswrap.One_on_One_Pre_purchase_Homebuying = clientCase.One_on_One_Pre_purchase_Homebuying__c;
                orswrap.One_on_One_Non_Delinquency_Post_Purchase = clientCase.One_on_One_Non_Delinquency_Post_Purchase__c;
                orswrap.One_on_One_Reverse_Mortgage = clientCase.One_on_One_Reverse_Mortgage__c;
                orswrap.One_on_One_Forward_Mortgage_Delinquency = clientCase.One_on_One_Forward_Mortgage_Delinquency__c;
                orswrap.One_on_One_Reverse_Mortgage_Delinquency = clientCase.One_on_One_Reverse_Mortgage_Delinquency__c;
                orswrap.One_on_One_Disaster_Preparedness_Assista = clientCase.One_on_One_Disaster_Preparedness_Assista__c;
                orswrap.One_on_One_Disaster_Recovery_Assistance = clientCase.One_on_One_Disaster_Recovery_Assistance__c;
                orswrap.Date_Closed = clientCase.ClientCaseClosedDate__c.format();
                orsWrapperList.add(orswrap);
            }
        }
        return orsWrapperList;
    }
    
    public class OrsReportWrapper{
        @AuraEnabled
        public String Household_Number;
        @AuraEnabled
        public String Date_Opened;
        @AuraEnabled
        public Decimal Current_Age;
        @AuraEnabled
        public String Head_of_Household_Gender;
        @AuraEnabled
        public String Head_of_Household_Race;
        @AuraEnabled
        public String Head_of_Household_Ethnicity;
        @AuraEnabled
        public String Disabled;
        @AuraEnabled
        public String Household_Type;
        @AuraEnabled
        public Decimal Total_Household_Members;
        @AuraEnabled
        public Decimal Household_Gross_Monthly_Income;
        @AuraEnabled
        public String Household_AMI;
        @AuraEnabled
        public String Preferred_Language;
        @AuraEnabled
        public String BillingStreet;
        @AuraEnabled
        public String Apt;
        @AuraEnabled
        public String BillingCity;
        @AuraEnabled
        public String BillingState;
        @AuraEnabled
        public String BillingPostalCode;
        @AuraEnabled
        public String ORS_Rural_Area_Status;
        @AuraEnabled
        public String One_on_One_Homeless_Assistance;
        @AuraEnabled
        public String One_on_One_Rental_Topics;
        @AuraEnabled
        public String One_on_One_Pre_purchase_Homebuying;
        @AuraEnabled
        public String One_on_One_Non_Delinquency_Post_Purchase;
        @AuraEnabled
        public String One_on_One_Reverse_Mortgage;
        @AuraEnabled
        public String One_on_One_Forward_Mortgage_Delinquency;
        @AuraEnabled
        public String One_on_One_Reverse_Mortgage_Delinquency;
        @AuraEnabled
        public String One_on_One_Disaster_Preparedness_Assista;
        @AuraEnabled
        public String One_on_One_Disaster_Recovery_Assistance;
        @AuraEnabled
        public String Date_Closed;
    }
    
}