objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>AreaMedianIncome__c</fullName>
        <label>Area Median Income</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Below 30% of AMI</fullName>
                </value>
                <value>
                    <fullName>30 - 49% of AMI</fullName>
                </value>
                <value>
                    <fullName>50 - 79% of AMI</fullName>
                </value>
                <value>
                    <fullName>80 - 100% of AMI</fullName>
                </value>
                <value>
                    <fullName>101% - 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Above 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Chose not to respond</fullName>
                </value>
                <value>
                    <fullName>Above 100% AMI</fullName>
                    <isActive>false</isActive>
                    <label>Above 100% AMI</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChoseNottoProvideIncome__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Chose Not to Provide Income</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DateAMILastCalculated__c</fullName>
        <label>Date AMI Last Calculated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EvaluateHUDAMI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EvaluateHUDAMI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HouseholdMonthlyIncome1__c</fullName>
        <label>Household Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HouseholdOfAMI__c</fullName>
        <label>Household % of AMI</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>HUD-Defined Number in Household</description>
        <inlineHelpText>Total number of people living in the same household as the primary client</inlineHelpText>
        <label>Household Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MetropolitanStatisticalArea__c</fullName>
        <label>Metropolitan Statistical Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MonthlyIncome__c</fullName>
        <label>Total Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isInvalidZip__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isInvalidZip</label>
        <type>Checkbox</type>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CoApplicant__c.object
<CustomObject>
    <description>To store details about household members who are co-applicants of the primary contact.</description>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Co-Applicants</relationshipLabel>
        <relationshipName>Co_Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicants</relationshipLabel>
        <relationshipName>Co_Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IntakeRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intake</label>
        <referenceTo>Intake__c</referenceTo>
        <relationshipLabel>Co-Applicants</relationshipLabel>
        <relationshipName>Co_Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Co-Applicant</label>
    <nameField>
        <displayFormat>CAPP-{00000}</displayFormat>
        <label>Co-Applicant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co-Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AreaMedianIncome__c</fullName>
        <label>Area Median Income</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Below 30% of AMI</fullName>
                </value>
                <value>
                    <fullName>30 - 49% of AMI</fullName>
                </value>
                <value>
                    <fullName>50 - 79% of AMI</fullName>
                </value>
                <value>
                    <fullName>80 - 100% of AMI</fullName>
                </value>
                <value>
                    <fullName>101% - 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Above 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Chose not to respond</fullName>
                </value>
                <value>
                    <fullName>Above 100% AMI</fullName>
                    <isActive>false</isActive>
                    <label>Above 100% AMI</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChoseNottoProvideIncome__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Chose Not to Provide Income</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DateAMILastCalculated__c</fullName>
        <label>Date AMI Last Calculated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EvaluateHUDAMI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EvaluateHUDAMI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HouseholdMonthlyIncome1__c</fullName>
        <label>Household Monthly Income</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HouseholdOfAMI__c</fullName>
        <label>Household % Of AMI</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>Number of people in the household</description>
        <inlineHelpText>Total number of people living in the same household</inlineHelpText>
        <label>Household Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MetropolitanStatisticalArea__c</fullName>
        <label>Metropolitan Statistical Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalMonthlyIncome__c</fullName>
        <label>Total Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isInvalidZip__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isInvalidZip</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>CoApplicant</fullName>
        <active>true</active>
        <label>Co-Applicant</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/HUDAMIData__c.object
<CustomObject>
    <description>To store data related to Area Median Income (AMI) for various regions, including details such as area names, county names, FIPS codes, and HUD-specific identifiers for HUD AMI calculations.</description>
    <fields>
        <fullName>Areaname__c</fullName>
        <description>HUD Income Limit Area Name</description>
        <label>Area name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CountyName__c</fullName>
        <description>HUD Income Limit - Official County Name</description>
        <label>County Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TownName__c</fullName>
        <description>Town Name for Income Limit purposes</description>
        <label>Town Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zipcode__c</fullName>
        <label>Zipcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>HUD AMI Data</label>
    <nameField>
        <label>HUD AMI Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HUD AMI Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ClientCaseTriggerHandler.cls
/**
* @desc: Handles trigger logic and data processing for ClientCase__c object.
*/
public inherited sharing class ClientCaseTriggerHandler {
    
    /**
* @desc: Executes before inserting new ClientCase__c records.
* @param newClientCase: List of new ClientCase__c records being inserted.
*/
    public static void beforeInsert(List<ClientCase__c> newClientCase) {
        populateFieldsOnClientCase(newClientCase, new Map<Id, ClientCase__c>(), true);
    }
    
    /**
* @desc: Executes before updating existing ClientCase__c records.
* @param newClientCase: List of new ClientCase__c records being updated.
* @param oldClientCase: Map of old ClientCase__c records being updated.
*/
    public static void beforeUpdate(List<ClientCase__c> newClientCase, Map<Id, ClientCase__c> oldClientCase) {
        try {
            populateFieldsOnClientCase(newClientCase, oldClientCase, false);
        } catch (Exception e) {
            System.debug('Error in beforeUpdate: ' + e.getMessage());
        }
    }
    
    public static List<ClientCase__c> populateUniqueClientId(List<ClientCase__c> ccList){
        Set<String> uniqueValuesSet = new Set<String>();
        String uniqueId;
        Boolean isUnique = false;
        while(!isUnique){
            while(uniqueValuesSet.size() < ccList.size()){
                uniqueValuesSet.add(Utility.getNewUniqueId());
            }
            List<ClientCase__c> ccListDump = checkDuplicacy(uniqueValuesSet);
            if(ccListDump.size() > 0){
                uniqueValuesSet = new Set<String>();
            } else {
                isUnique = true;
            }
        }
        Integer index = 0;
        List<String> uniqueValuesList = new List<String>(uniqueValuesSet);
        for(ClientCase__c cc : ccList){
            cc.Name = uniqueValuesList[index];
            index++;
        }
        if(!Trigger.isExecuting){
            Database.update(ccList,false);
        }
        return ccList;
    }
    
    public static List<ClientCase__c> checkDuplicacy(Set<String> uniqueValuesSet){
        return new List<ClientCase__c>([Select id from ClientCase__c where Name in: uniqueValuesSet limit 1]);
    }
    
    /**
* @desc: Populates additional fields on ClientCase__c records based on related HUDAMIData__c.
* @param newClientCase: List of new ClientCase__c records to process.
* @param oldClientCase: Map of old ClientCase__c records to check for changes.
* @param IsNew: Boolean flag indicating if the records are new.
*/
    public static void populateFieldsOnClientCase(List<ClientCase__c> newClientCase, Map<Id, ClientCase__c> oldClientCase, Boolean IsNew) {
        Map<String, List<HUDAMIData__c>> hudamiDataMap = new Map<String, List<HUDAMIData__c>>();
        Set<String> zipCodes = new Set<String>();
        Set<String> townCountyZipKeys = new Set<String>();
        List<ClientCase__c> validZipClientCaseList = new List<ClientCase__c>(); 
        List<ClientCase__c> changedMonthlyIncomeCClist = new List<ClientCase__c>(); 

        if (IsNew) {
            for (ClientCase__c newCC : newClientCase) {
                if (newCC.Address__PostalCode__s != null && (newCC.County__c == null && newCC.Town__c == null)) {
                    zipCodes.add(newCC.Address__PostalCode__s);
                    validZipClientCaseList.add(newCC);
                } else {
                    String townCountyZipKey = 
                        (String.isBlank(newCC.Town__c) ? '' : newCC.Town__c) + '-' + 
                        (String.isBlank(newCC.County__c) ? '' : newCC.County__c) + '-' + 
                        (String.isBlank(newCC.Address__PostalCode__s) ? '' : newCC.Address__PostalCode__s);
                    townCountyZipKeys.add(townCountyZipKey);
                    validZipClientCaseList.add(newCC);  
                }
            }
            populateUniqueClientId(newClientCase);
            RecalculateIncome(newClientCase, false);
        } else {
            for (ClientCase__c newCC : newClientCase) {
                ClientCase__c oldCC = oldClientCase.get(newCC.Id);
                if (oldCC != null) {
                    if (newCC.Address__PostalCode__s != oldCC.Address__PostalCode__s) {
                        if (newCC.Town__c != oldCC.Town__c && newCC.County__c != oldCC.County__c) {
                            System.debug('With Zip code, town and county have also been updated');
                        } else {
                            zipCodes.add(newCC.Address__PostalCode__s);
                            validZipClientCaseList.add(newCC);  
                        }
                        System.debug('if zipCode Changes');
                    } else if (newCC.MonthlyIncome__c != oldCC.MonthlyIncome__c || newCC.HouseholdMonthlyIncome1__c != oldCC.HouseholdMonthlyIncome1__c || newCC.HouseholdSize__c != oldCC.HouseholdSize__c || newCC.County__c != oldCC.County__c || newCC.Town__c != oldCC.Town__c) {
                        String townCountyZipKey = 
                            (String.isBlank(newCC.Town__c) ? '' : newCC.Town__c) + '-' + 
                            (String.isBlank(newCC.County__c) ? '' : newCC.County__c) + '-' + 
                            (String.isBlank(newCC.Address__PostalCode__s) ? '' : newCC.Address__PostalCode__s);
                        townCountyZipKeys.add(townCountyZipKey);
                        validZipClientCaseList.add(newCC);  
                        System.debug('if else Other fields Changes');
                    }
                    if(newCC.MonthlyIncome__c != oldCC.MonthlyIncome__c )
                    {
                        changedMonthlyIncomeCClist.add(newCC);
                        // validZipClientCaseList.add(newCC);  
                    }
                }
            }
            if (!changedMonthlyIncomeCClist.isEmpty()) {
                RecalculateIncome(changedMonthlyIncomeCClist, false);
            }
        }
        
        List<HUDAMIData__c> hudamiRecordsByZip = new List<HUDAMIData__c>();
        List<HUDAMIData__c> hudamiRecordsByTownCountyZip = new List<HUDAMIData__c>();
        
        if (!zipCodes.isEmpty()) {
            hudamiRecordsByZip = Utility.getHUDAMIData(zipCodes, new Set<String>());
        }
        
        if (!townCountyZipKeys.isEmpty()) {
            hudamiRecordsByTownCountyZip = Utility.getHUDAMIData(new Set<String>(), townCountyZipKeys);
        }

        addToHudamiDataMap(hudamiDataMap, hudamiRecordsByZip);
        addToHudamiDataMap(hudamiDataMap, hudamiRecordsByTownCountyZip);

        if (!validZipClientCaseList.isEmpty()) {         
            newClientCase = validZipClientCaseList;      
        } else {                                     
            newClientCase = new List<ClientCase__c>();   
        }                                            

        for (ClientCase__c clientcase : newClientCase) {
            if (!hudamiDataMap.isEmpty()) {                  
                processIntakeRecord(clientcase, hudamiDataMap);  
            }                                                
            else {                                           
                clientcase.isInvalidZip__c = true;               
                // clientcase.EvaluateHUDAMI__c = false;            
                clientcase.County__c = null;                
                clientcase.Town__c = null;                  
                clientcase.MetropolitanStatisticalArea__c = null;  
                clientcase.AreaMedianIncome__c = null;            
                clientcase.DateAMILastCalculated__c = null;      
                clientcase.HouseholdOfAMI__c = null;             
                System.debug('Invalid Zip Code Entered');    
            }                                                
        }
    }
    
    /**
* @desc: Adds HUDAMIData__c records to the hudamiDataMap.
* @param hudamiDataMap: Map containing HUDAMIData__c records keyed by Zipcode and Town-County-Zip keys.
* @param records: List of HUDAMIData__c records to add to the map.
*/
    private static void addToHudamiDataMap(Map<String, List<HUDAMIData__c>> hudamiDataMap, List<HUDAMIData__c> records) {
        for (HUDAMIData__c hud : records) {
            String zipKey = hud.Zipcode__c;
            String townCountyZipKey = hud.TownName__c + '-' + hud.CountyName__c + '-' + hud.Zipcode__c;
            if (!hudamiDataMap.containsKey(zipKey)) {
                hudamiDataMap.put(zipKey, new List<HUDAMIData__c>());
            }
            hudamiDataMap.get(zipKey).add(hud);
            
            if (!hudamiDataMap.containsKey(townCountyZipKey)) {
                hudamiDataMap.put(townCountyZipKey, new List<HUDAMIData__c>());
            }
            hudamiDataMap.get(townCountyZipKey).add(hud);
        }
    }
    
    /**
* @desc: Processes each ClientCase__c record to determine if HUDAMI evaluation is required and updates fields accordingly.
* @param clientcase: ClientCase__c record to process.
* @param hudamiDataMap: Map containing HUDAMIData__c records keyed by Zipcode and Town-County-Zip keys.
*/
    private static void processIntakeRecord(ClientCase__c clientcase, Map<String, List<HUDAMIData__c>> hudamiDataMap) {
        String zipKey = clientcase.Address__PostalCode__s;
        String townCountyZipKey = (String.isBlank(clientcase.Town__c) ? '' : clientcase.Town__c) + '-' + 
            (String.isBlank(clientcase.County__c) ? '' : clientcase.County__c) + '-' + 
            (String.isBlank(clientcase.Address__PostalCode__s) ? '' : clientcase.Address__PostalCode__s);
        if (hudamiDataMap.containsKey(zipKey) && hudamiDataMap.get(zipKey).size() > 1) {
            clientcase.EvaluateHUDAMI__c = true;
            clientcase.isInvalidZip__c = false;      
            clientcase.County__c = null;
            clientcase.Town__c = null;
            clientcase.MetropolitanStatisticalArea__c = null;
            clientcase.AreaMedianIncome__c = null;
            clientcase.DateAMILastCalculated__c = null;
            clientcase.HouseholdOfAMI__c = null;
        } else if (hudamiDataMap.containsKey(zipKey) && hudamiDataMap.get(zipKey).size() == 1) {
            HUDAMIData__c hudRec = hudamiDataMap.get(zipKey)[0];
            updateIntakeRecord(clientcase, hudRec);
            clientcase.isInvalidZip__c = false;        
            clientcase.EvaluateHUDAMI__c = false;       
        } else if (hudamiDataMap.containsKey(townCountyZipKey)) {
            HUDAMIData__c hudRec = hudamiDataMap.get(townCountyZipKey)[0];
            updateIntakeRecord(clientcase, hudRec);
            clientcase.isInvalidZip__c = false;     
            clientcase.EvaluateHUDAMI__c = false;       
        }                                    
    }
    
    /**
* @desc: Updates ClientCase__c fields with HUDAMIData__c values.
* @param clientcase: ClientCase__c record to update.
* @param hudRec: HUDAMIData__c record containing data to update ClientCase__c.
*/
    private static void updateIntakeRecord(ClientCase__c clientcase, HUDAMIData__c hudRec) {
        Decimal annualHouseholdIncome = (clientcase.HouseholdMonthlyIncome1__c != null) ? (clientcase.HouseholdMonthlyIncome1__c * 12) : 0;
        Integer householdSize = (clientcase.HouseholdSize__c != null) ? clientcase.HouseholdSize__c.intValue() : 0;
        if(!clientcase.ChoseNottoProvideIncome__c){
            HUDAMICalculationService.HUDAMIServiceWrapper wrapper =
                HUDAMICalculationService.getHudAmiCalculatedWrapper(hudRec, householdSize, annualHouseholdIncome);
            
            if (String.isBlank(wrapper.error)) {
                clientcase.County__c = wrapper.countyName != null ? wrapper.countyName : '';
                clientcase.MetropolitanStatisticalArea__c = wrapper.metropolitanStatisticalArea != null ? wrapper.metropolitanStatisticalArea : '';
                clientcase.AreaMedianIncome__c = wrapper.areaMedianIncome != null ? wrapper.areaMedianIncome : '';
                //clientcase.AreaName__c = wrapper.areaname != null ? wrapper.areaname : ''; //fields needs to be created if required
                clientcase.Town__c = wrapper.townName != null ? wrapper.townName : '';
                //clientcase.Address__PostalCode__s = wrapper.zipcode != null ? wrapper.zipcode : '';
                //clientcase.Address__StateCode__s = wrapper.stateCode != null ? wrapper.stateCode : '';
                clientcase.DateAMILastCalculated__c = System.now();
                clientcase.HouseholdOfAMI__c = wrapper.householdOfAMI != null ? wrapper.householdOfAMI : 0.0;
            } else {
                System.debug('Error in wrapper: ' + wrapper.error);
            }
        }
    } 
    
/**
* @desc: Recalculate Household Monthly Income on intake
*/
    
    public static void RecalculateIncome(List<ClientCase__c> clientCases, Boolean isFromContact) {
        List<CoApplicant__c> coApplicants = [
            SELECT Id, IntakeRequest__c, ClientCase__c, Contact__r.TotalMonthlyIncome__c  
            FROM CoApplicant__c 
            WHERE ClientCase__c IN :clientCases
        ];
        
        Map<Id, Decimal> clientCaseToCoApplicantIncomeMap = new Map<Id, Decimal>();
        
        for (CoApplicant__c coApplicant : coApplicants) {
            if (coApplicant.ClientCase__c != null && coApplicant.Contact__r.TotalMonthlyIncome__c != null) {
                if (!clientCaseToCoApplicantIncomeMap.containsKey(coApplicant.ClientCase__c)) {
                    clientCaseToCoApplicantIncomeMap.put(coApplicant.ClientCase__c, 0);
                }
                clientCaseToCoApplicantIncomeMap.put(coApplicant.ClientCase__c, 
                                                     clientCaseToCoApplicantIncomeMap.get(coApplicant.ClientCase__c) + coApplicant.Contact__r.TotalMonthlyIncome__c );
            } else {
                System.debug('CoApplicant or Monthly Income is null for Id: ' + coApplicant.Id);
            }
        }
                
        for (ClientCase__c cc : clientCases) {
            Decimal totalIncome = 0;
            if (cc.MonthlyIncome__c != null) {
                totalIncome += cc.MonthlyIncome__c;
            }
            
            if (clientCaseToCoApplicantIncomeMap.containsKey(cc.Id)) {
                totalIncome += clientCaseToCoApplicantIncomeMap.get(cc.Id);
            }

            cc.HouseholdMonthlyIncome1__c = (totalIncome > 0 ? totalIncome : null);
        }

        if (isFromContact == true) {
            update clientCases;
        }
    }
}