objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>CounselingTermination__c</fullName>
        <label>Counseling Termination</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ongoing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Dropped Out</fullName>
                </value>
                <value>
                    <fullName>Referred</fullName>
                </value>
                <value>
                    <fullName>No Further Contact</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Calendar Event Information</relationshipLabel>
        <relationshipName>SUMOAdditionalInfo</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ClientCaseTimelineServiceTest.cls
@IsTest
public class ClientCaseTimelineServiceTest {
    
    @TestSetup
    static void setupTestData() {
        List<ClientCase__c> clientCases = TestDataFactory.createClientCases(1, false);
        clientCases[0].CounselingTermination__c = 'Completed';
        insert clientCases;
        
        Account acc = TestDataFactory.createAccounts(1, true)[0];
        Contact con = TestDataFactory.createContacts(acc.id, 1, true)[0];
        ClientCase__c clientCase = [SELECT Id FROM ClientCase__c LIMIT 1];
        Id recordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Event' AND SobjectType = 'sumoapp__AdditionalInfo__c' LIMIT 1]?.Id;
        sumoapp__AdditionalInfo__c info = TestDataFactory.createSumoEventInfo(1, true)[0];
        
        Event evt = TestDataFactory.createEvent(con, info.Id, 1, false)[0];
        evt.whatId = clientCase.id;
        insert evt;
    }
    
    @IsTest
    static void testGetAppointments() {
        ClientCase__c clientCase = [SELECT Id FROM ClientCase__c LIMIT 1];
        ClientCaseTimelineService service = new ClientCaseTimelineService();
        service.getAppointments(clientCase.Id);
    }
    
    @IsTest
    static void testGetCounselorNotes() {
        ClientCase__c clientCase = [SELECT Id FROM ClientCase__c LIMIT 1];
        ClientCaseTimelineService service = new ClientCaseTimelineService(); 
        service.getCounselorNotes(clientCase.Id);
    }
    
    @IsTest
    static void testGetCourses() {
        ClientCase__c clientCase = [SELECT Id FROM ClientCase__c LIMIT 1];
        ClientCaseTimelineService service = new ClientCaseTimelineService();
        service.getCourses(clientCase.Id);
    }
}