objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>AnnualHouseholdIncome__c</fullName>
        <formula>HouseholdMonthlyIncome1__c * 12</formula>
        <label>Annual Household Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AreaMedianIncome__c</fullName>
        <label>Area Median Income</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Below 30% of AMI</fullName>
                </value>
                <value>
                    <fullName>30 - 49% of AMI</fullName>
                </value>
                <value>
                    <fullName>50 - 79% of AMI</fullName>
                </value>
                <value>
                    <fullName>80 - 100% of AMI</fullName>
                </value>
                <value>
                    <fullName>101% - 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Above 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Chose not to respond</fullName>
                </value>
                <value>
                    <fullName>Above 100% AMI</fullName>
                    <isActive>false</isActive>
                    <label>Above 100% AMI</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChoseNottoProvideIncome__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Chose Not to Provide Income</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ClientCaseStatus__c</fullName>
        <defaultValue>(&quot;In Progress&quot;)</defaultValue>
        <description>In Progress: Open Case that is in progress and HUD reportable

Closed - Incomplete: Case closed without meeting the original outcome, HUD reportable

Closed - Service Complete: Case closed with meeting the original outcome, HUD reportable

On Hold: Case temporarily paused due to external factors or client request</description>
        <inlineHelpText>[1] In Progress: Case pending

[2] Closed - Incomplete: Didn’t meet original outcome

[3] Closed - Complete: Met the outcome

[4] On Hold: Case temporarily paused</inlineHelpText>
        <label>Client Case Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Closed - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Closed - Complete</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                    <isActive>false</isActive>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <isActive>false</isActive>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <isActive>false</isActive>
                    <label>Prospect</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EvaluateHUDAMI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EvaluateHUDAMI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HouseholdMonthlyIncome1__c</fullName>
        <label>Household Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>HUD-Defined Number in Household</description>
        <inlineHelpText>Total number of people living in the same household as the primary client</inlineHelpText>
        <label>Household Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MetropolitanStatisticalArea__c</fullName>
        <label>Metropolitan Statistical Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MonthlyIncome__c</fullName>
        <label>Total Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isInvalidZip__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isInvalidZip</label>
        <type>Checkbox</type>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CoApplicant__c.object
<CustomObject>
    <description>To store details about household members who are co-applicants of the primary contact.</description>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Co-Applicants</relationshipLabel>
        <relationshipName>Co_Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicants</relationshipLabel>
        <relationshipName>Co_Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IntakeRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intake</label>
        <referenceTo>Intake__c</referenceTo>
        <relationshipLabel>Co-Applicants</relationshipLabel>
        <relationshipName>Co_Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Co-Applicant</label>
    <nameField>
        <displayFormat>CAPP-{00000}</displayFormat>
        <label>Co-Applicant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co-Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AnnualHouseholdIncome__c</fullName>
        <formula>HouseholdMonthlyIncome1__c * 12</formula>
        <label>Annual Household Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ChoseNottoProvideIncome__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Chose Not to Provide Income</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CorrespondingPortalUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Corresponding Portal User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EvaluateHUDAMI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EvaluateHUDAMI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HouseholdMonthlyIncome1__c</fullName>
        <label>Household Monthly Income</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>Number of people in the household</description>
        <inlineHelpText>Total number of people living in the same household</inlineHelpText>
        <label>Household Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MetropolitanStatisticalArea__c</fullName>
        <label>Metropolitan Statistical Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <description>Client Social Security Number</description>
        <label>SSN</label>
        <length>11</length>
        <maskChar>X</maskChar>
        <maskType>ssn</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>TotalMonthlyIncome__c</fullName>
        <label>Total Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cic_credit__SSN__c</fullName>
        <label>SSN</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isInvalidZip__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isInvalidZip</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>CoApplicant</fullName>
        <active>true</active>
        <label>Co-Applicant</label>
    </recordTypes>
    <recordTypes>
        <fullName>PrimaryClient</fullName>
        <active>true</active>
        <label>Primary Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <label>Prospect</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/HUDAMIData__c.object
<CustomObject>
    <description>To store data related to Area Median Income (AMI) for various regions, including details such as area names, county names, FIPS codes, and HUD-specific identifiers for HUD AMI calculations.</description>
    <fields>
        <fullName>CountyName__c</fullName>
        <description>HUD Income Limit - Official County Name</description>
        <label>County Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TownName__c</fullName>
        <description>Town Name for Income Limit purposes</description>
        <label>Town Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zipcode__c</fullName>
        <label>Zipcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>HUD AMI Data</label>
    <nameField>
        <label>HUD AMI Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HUD AMI Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Intake__c.object
<CustomObject>
    <description>To capture and store initial information about clients/prospects during the intake process including New Intake, New Education Only, and New Emergency Triage.</description>
    <fields>
        <fullName>AnnualHouseholdIncome__c</fullName>
        <formula>HouseholdMonthlyIncome__c * 12</formula>
        <label>Annual Household Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ChoseNottoProvideIncome__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Chose Not to Provide Income</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EvaluateHUDAMI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EvaluateHUDAMI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HouseholdMonthlyIncome__c</fullName>
        <label>Household Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <label>Household Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MetropolitanStatisticalArea__c</fullName>
        <label>Metropolitan Statistical Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MonthlyIncome__c</fullName>
        <label>Total Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Intake Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Open Intake</fullName>
                    <default>true</default>
                    <label>Open Intake</label>
                </value>
                <value>
                    <fullName>Open Case</fullName>
                </value>
                <value>
                    <fullName>Converted</fullName>
                    <isActive>false</isActive>
                    <label>Converted</label>
                </value>
                <value>
                    <fullName>New</fullName>
                    <isActive>false</isActive>
                    <label>New</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isInvalidZip__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isInvalidZip</label>
        <type>Checkbox</type>
    </fields>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Intake</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContactTriggerHandler.cls
/**
 * @desc: ContactTriggerHandler is used to handle trigger events for Contact objects.
 */
public inherited sharing class ContactTriggerHandler {
    static Id coappRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName()
        .get('CoApplicant')
        .getRecordTypeId();
    static Id primaryClientRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName()
        .get('PrimaryClient')
        .getRecordTypeId();
    static Id prospectRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName()
        .get('Prospect')
        .getRecordTypeId();
    public static Map<String, Set<Id>> recursiveMap = new Map<String, Set<Id>>();
    public static Map<Id, Contact> contactToUpdateMap = new Map<Id, Contact>();
    public static boolean flag = true;
    public static boolean isInvalidKey = false;
    public static Set<String> ZipKeys = new Set<String>();

    
    /**
     * @desc:Handles before insert trigger events for Contact.
     */
    public static void beforeInsert(List<Contact> newContactList) {
        for(Contact con:newContactList){
            if(String.isNotBlank(con.SSN__c)){
                con.cic_credit__SSN__c = con.SSN__c;
            }
        }
    }
    
    /**
     * @desc:Handles before update trigger events for Contact.
     */
    public static void beforeUpdate(List<Contact> newContactList, Map<Id, Contact> oldContactMap) {
        for(Contact con:newContactList){
            if(String.isNotBlank(con.SSN__c) && con.SSN__c != oldContactMap.get(con.Id).SSN__c){
                con.cic_credit__SSN__c = con.SSN__c;
            }
        }
    }
    
    /**
     * @desc:Handles after insert trigger events for Contact.
     */
    public static void afterInsert(List<Contact> newContactList) {
        processContacts(getAccountsToRecomputeHudAmi(newContactList, null));
    }

    /**
     * @desc:Handles after update trigger events for Contact.
     */
    public static void afterUpdate(
        List<Contact> newContactList,
        Map<Id, Contact> oldContactMap
    ) {
        calculateHouseholdIncome(newContactList, oldContactMap);
        processContacts(
            getAccountsToRecomputeHudAmi(newContactList, oldContactMap)
        );
    }

    /**
     * @desc:Calculate Household Income of Intake/ClientCase for co-applicants.
     */
    private static void calculateHouseholdIncome(
        List<Contact> newContactList,
        Map<Id, Contact> oldContactMap
    ) {
        List<CoApplicant__c> coAppList = new List<CoApplicant__c>();
        Set<Id> conIds = new Set<Id>();
        for (Contact newCon : newContactList) {
            Contact oldCon = oldContactMap.get(newCon.Id);
            if (newCon.RecordTypeId == coappRecTypeId && newCon.TotalMonthlyIncome__c != oldCon.TotalMonthlyIncome__c) {
                conIds.add(newCon.Id);
            }
        }

        Set<Id> clientCaseIds = new Set<Id>();
        Set<Id> intakeIds = new Set<Id>();

        if (conIds.size() > 0) {
            coAppList = [
                SELECT Id, ClientCase__c, Contact__c, IntakeRequest__c
                FROM CoApplicant__c
                WHERE Contact__c IN :conIds WITH SECURITY_ENFORCED
            ];

            for (CoApplicant__c coApp : coAppList) {
                if (coApp.IntakeRequest__c != null) {
                    intakeIds.add(coApp.IntakeRequest__c);
                }
                if (coApp.ClientCase__c != null) {
                    clientCaseIds.add(coApp.ClientCase__c);
                }
            }

            List<Intake__c> intakeList = new List<Intake__c>();
            List<ClientCase__c> clientCaseList = new List<ClientCase__c>();
            intakeList = [SELECT Id, MonthlyIncome__c, HouseholdMonthlyIncome__c FROM Intake__c WHERE Id IN :intakeIds AND Status__c = 'Open Intake' WITH SECURITY_ENFORCED];

            if (!intakeList.isEmpty()) {
                IntakeTriggerHandler.RecalculateIncome(intakeList, true);
            }
            
            clientCaseList = [SELECT Id, MonthlyIncome__c, HouseholdMonthlyIncome1__c FROM ClientCase__c WHERE Id IN :clientCaseIds AND ClientCaseStatus__c = 'In Progress' WITH SECURITY_ENFORCED];
            
            if (!clientCaseList.isEmpty()) {
                ClientCaseTriggerHandler.RecalculateIncome(clientCaseList, true);
            }
        }
    }

    /**
     * @desc:Gets accounts to recompute HUD AMI.
     */
    private static Set<Id> getAccountsToRecomputeHudAmi(
        List<Contact> newContactList,
        Map<Id, Contact> oldContactMap
    ) {
        Set<Id> accIdSet = new Set<Id>();

        for (Contact newCon : newContactList) {
            if (oldContactMap == null) {
                if (
                    (newCon.RecordTypeId == coappRecTypeId ||
                    newCon.RecordTypeId == primaryClientRecTypeId ||
                    newCon.RecordTypeId == prospectRecTypeId) && (newCon.MailingPostalCode != null || newCon.County__c != null || newCon.Town__c != null || newCon.TotalMonthlyIncome__c > 0)
                ) {
                    System.debug('newCon.MailingPostalCode GuestUser 130 '+newCon.MailingPostalCode);
                    System.debug('newCon.CorrespondingPortalUser__c GuestUser 130 '+newCon.CorrespondingPortalUser__c);
                    if (newCon.MailingPostalCode != null && (newCon.County__c == null && newCon.Town__c == null) && (newCon.RecordTypeId == primaryClientRecTypeId ||
                    newCon.RecordTypeId == prospectRecTypeId)) {
                        System.debug('newCon.MailingPostalCode GuestUser 133 '+newCon.MailingPostalCode);
                        ZipKeys.add(newCon.MailingPostalCode);
                    }
                    accIdSet.add(newCon.AccountId);
                }
            } else {
                Contact oldCon = oldContactMap.get(newCon.Id);
                if (newCon.RecordTypeId == coappRecTypeId) {
                    if (newCon.MailingPostalCode != oldCon.MailingPostalCode) {
                        System.debug('newCon change zip GuestUser 141'+newCon);
                        accIdSet.add(newCon.AccountId);
                        ZipKeys.add(newCon.MailingPostalCode);
                    } else if (
                        newCon.isActive__c != oldCon.isActive__c ||
                        newCon.AccountId != oldCon.AccountId ||
                        newCon.TotalMonthlyIncome__c !=
                        oldCon.TotalMonthlyIncome__c
                    ) {
                        System.debug('newCon GuestUser 150'+newCon);
                        accIdSet.add(newCon.AccountId);
                        accIdSet.add(oldCon.AccountId);
                    }
                } else if (newCon.RecordTypeId == primaryClientRecTypeId || newCon.RecordTypeId == prospectRecTypeId) {
                    if (newCon.MailingPostalCode != oldCon.MailingPostalCode) {
                        System.debug('newCon change zip GuestUser 157'+newCon);
                        accIdSet.add(newCon.AccountId);
                        ZipKeys.add(newCon.MailingPostalCode);
                    } else if (
                        // newCon.RecordTypeId != oldCon.RecordTypeId ||
                        newCon.County__c != oldCon.County__c ||
                        newCon.AccountId != oldCon.AccountId ||
                        newCon.HouseholdMonthlyIncome1__c !=
                        oldCon.HouseholdMonthlyIncome1__c ||
                        newCon.Town__c != oldCon.Town__c ||
                        newCon.HouseholdSize__c != oldCon.HouseholdSize__c ||
                        newCon.AnnualHouseholdIncome__c !=
                        oldCon.AnnualHouseholdIncome__c ||
                        newCon.TotalMonthlyIncome__c !=
                        oldCon.TotalMonthlyIncome__c
                    ) {
                        accIdSet.add(newCon.AccountId);
                        accIdSet.add(oldCon.AccountId);
                        isInvalidKey = true;
                    }
                }
            }
        }
        return accIdSet;
    }

    /**
     * @desc:Processes the given set of account IDs.
     */
    private static void processContacts(Set<Id> accountIds) {
        if (accountIds.isEmpty()) {
            return;
        }
        System.debug('accountIds GuestUser '+accountIds);
        Map<Id, List<Contact>> accountToListOfCoAppMap = new Map<Id, List<Contact>>();
        Map<Id, Contact> accountToPrimaryContactMap = new Map<Id, Contact>();

        List<Contact> allContacts = [
            SELECT
                Id,
                TotalMonthlyIncome__c,
                County__c,
                Town__c,
                HouseholdSize__c,
                AccountId,
                RecordTypeId,
                MailingPostalCode,
                ChoseNottoProvideIncome__c 
            FROM Contact
            WHERE
                AccountId IN :accountIds
                AND ((RecordTypeId = :coappRecTypeId
                AND isActive__c = TRUE)
                OR RecordTypeId = :primaryClientRecTypeId
                OR RecordTypeId = :prospectRecTypeId)
                WITH SECURITY_ENFORCED
        ];

        Set<String> townCountyZipKeys = new Set<String>();
        System.debug('allContacts GuestUser '+allContacts);

        for (Contact con : allContacts) {
            if (
                con.RecordTypeId == primaryClientRecTypeId ||
                con.RecordTypeId == prospectRecTypeId
            ) {
                accountToPrimaryContactMap.put(con.AccountId, con);
            } else {
                if (!accountToListOfCoAppMap.containsKey(con.AccountId)) {
                    accountToListOfCoAppMap.put(
                        con.AccountId,
                        new List<Contact>()
                    );
                }
                accountToListOfCoAppMap.get(con.AccountId).add(con);
            }

            String townCountyZipKey =
                (String.isBlank(con.Town__c) ? '' : con.Town__c) +
                '-' +
                (String.isBlank(con.County__c) ? '' : con.County__c) +
                '-' +
                (String.isBlank(con.MailingPostalCode)
                    ? ''
                    : con.MailingPostalCode);
            townCountyZipKeys.add(townCountyZipKey);
        }

        Map<String, List<HUDAMIData__c>> hudamiDataMap = new Map<String, List<HUDAMIData__c>>();
        if (!ZipKeys.isEmpty()) {
            List<HUDAMIData__c> zipKeyHudamiRecords = Utility.getHUDAMIData(ZipKeys, new Set<String>());

            for (HUDAMIData__c hud : zipKeyHudamiRecords) {
                String key = hud.Zipcode__c;

                if (!hudamiDataMap.containsKey(key)) {
                    hudamiDataMap.put(key, new List<HUDAMIData__c>());
                }
                hudamiDataMap.get(key).add(hud);
            }
        }
        System.debug('townCountyZipKeys GuestUser '+townCountyZipKeys);

        if (!townCountyZipKeys.isEmpty()) {
            List<HUDAMIData__c> townCountyZipKeyHudamiRecords = Utility.getHUDAMIData(new Set<String>(), townCountyZipKeys);

            for (HUDAMIData__c hud : townCountyZipKeyHudamiRecords) {
                    String key =
                    (String.isBlank(hud.TownName__c) ? '' : hud.TownName__c) + '-' + 
                            (String.isBlank(hud.CountyName__c) ? '' : hud.CountyName__c) + '-' + 
                            (String.isBlank(hud.Zipcode__c) ? '' : hud.Zipcode__c);
                if (!hudamiDataMap.containsKey(key)) {
                    hudamiDataMap.put(key, new List<HUDAMIData__c>());
                }
                hudamiDataMap.get(key).add(hud);
            }
        }

        for (Id accId : accountIds) {
            Double totalIncome = 0;
            if (accountToListOfCoAppMap.containsKey(accId)) {
                for (Contact con : accountToListOfCoAppMap.get(accId)) {
                    if(con.TotalMonthlyIncome__c != NULL){
                        totalIncome += con.TotalMonthlyIncome__c;
                    }
                }
            }

            Contact primaryCon = accountToPrimaryContactMap.get(accId);
            System.debug('primaryCon GuestUser '+primaryCon);
            if (primaryCon != null) {
                totalIncome += primaryCon.TotalMonthlyIncome__c != null ? primaryCon.TotalMonthlyIncome__c : 0;
                primaryCon.HouseholdMonthlyIncome1__c = (totalIncome > 0 ? totalIncome : null);
                contactToUpdateMap.put(primaryCon.Id, primaryCon);
            }
            // System.debug('primaryCon.HouseholdMonthlyIncome1__c GuestUser '+primaryCon.HouseholdMonthlyIncome1__c);

            if (
                primaryCon != null &&
                primaryCon.HouseholdSize__c != null
            ) {
                String countyTownZipKey =
                    (String.isBlank(primaryCon.Town__c)
                        ? ''
                        : primaryCon.Town__c) +
                    '-' +
                    (String.isBlank(primaryCon.County__c)
                        ? ''
                        : primaryCon.County__c) +
                    '-' +
                    (String.isBlank(primaryCon.MailingPostalCode)
                        ? ''
                        : primaryCon.MailingPostalCode);

                String zipKey = primaryCon.MailingPostalCode;
                if (hudamiDataMap.containsKey(zipKey)) {
                    List<HUDAMIData__c> hudamiRecords = hudamiDataMap.get(
                        zipKey
                    );
                    processHUDAMIData(primaryCon, hudamiRecords);
                } else if (hudamiDataMap.containsKey(countyTownZipKey)) {
                    List<HUDAMIData__c> hudamiRecords = hudamiDataMap.get(
                        countyTownZipKey
                    );
                    processHUDAMIData(primaryCon, hudamiRecords);
                } else {
                    System.debug(
                        '#Contact No HUD AMI Records found for ZIP or County-Town-ZIP combination'
                    );
                    // primaryCon.EvaluateHUDAMI__c = false;
                    if (isInvalidKey == false) {
                        primaryCon.isInvalidZip__c = true;
                        primaryCon.County__c = null;
                        primaryCon.Town__c = null;
                        primaryCon.MetropolitanStatisticalArea__c = null;
                        primaryCon.AreaMedianIncome__c = null;
                        primaryCon.DateAMILastCalculated__c = null;
                        primaryCon.HouseholdOfAMI__c = null;
                    }
                }
            }

            if (!contactToUpdateMap.isEmpty()) {
                Database.SaveResult[] updateResults = Database.update(
                    contactToUpdateMap.values(),
                    false
                );
                for (Database.SaveResult sr : updateResults) {
                    if (!sr.isSuccess()) {
                        for (Database.Error err : sr.getErrors()) {
                            EventLog__e l = new EventLog__e();
                            l.ExceptionMessage__c = err.getMessage();
                            EventBus.publish(l);
                            System.debug(
                                'Error updating Contact: ' +
                                    err.getStatusCode() +
                                    ': ' +
                                    err.getMessage()
                            );
                        }
                    }
                }
            }
        }
    }

    /**
     * @desc:Processes HUD AMI data for the given contact.
     */
    private static void processHUDAMIData(
        Contact primaryCon,
        List<HUDAMIData__c> hudamiRecords
    ) {
        List<Contact> contactsToUpdate = new List<Contact>();
        if(!primaryCon.ChoseNottoProvideIncome__c){
            if (hudamiRecords.size() > 1) {
                primaryCon.EvaluateHUDAMI__c = true;
                primaryCon.isInvalidZip__c = false;
                primaryCon.County__c = null;
                primaryCon.Town__c = null;
                primaryCon.MetropolitanStatisticalArea__c = null;
                primaryCon.AreaMedianIncome__c = null;
                primaryCon.DateAMILastCalculated__c = null;
                primaryCon.HouseholdOfAMI__c = null;
            } else {
                HUDAMIData__c hudamiRecord = hudamiRecords[0];
    
                HUDAMICalculationService.HUDAMIServiceWrapper wrapper = new HUDAMICalculationService.HUDAMIServiceWrapper();
    
    		if(primaryCon.HouseholdMonthlyIncome1__c != null){    
                wrapper = HUDAMICalculationService.getHudAmiCalculatedWrapper(
                    hudamiRecord,
                    (Integer) primaryCon.HouseholdSize__c,
                    Math.round(primaryCon.HouseholdMonthlyIncome1__c * 12)
                );
            } 
                System.debug('String.isBlank(wrapper.error) '+ wrapper.error);
                if (String.isBlank(wrapper.error)) {
                    primaryCon.County__c = wrapper.countyName != null
                        ? wrapper.countyName
                        : '';
                    primaryCon.MetropolitanStatisticalArea__c = wrapper.metropolitanStatisticalArea !=
                        null
                        ? wrapper.metropolitanStatisticalArea
                        : '';
                    primaryCon.AreaMedianIncome__c = wrapper.areaMedianIncome !=
                        null
                        ? wrapper.areaMedianIncome
                        : '';
                    primaryCon.Town__c = wrapper.townName != null
                        ? wrapper.townName
                        : '';
                    primaryCon.DateAMILastCalculated__c = wrapper.aMILastCalculatedDate !=
                        null
                        ? wrapper.aMILastCalculatedDate
                        : null;
                    primaryCon.EvaluateHUDAMI__c = false;
                    primaryCon.isInvalidZip__c = false;
                    primaryCon.HouseholdOfAMI__c = wrapper.householdOfAMI != null
                        ? wrapper.householdOfAMI
                        : 0.0;
                }
            }
            contactToUpdateMap.put(primaryCon.Id, primaryCon);
        }
    }
}