objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientCaseTask__c.object
<CustomObject>
    <description>To store tasks associated with client cases, typically as part of a Case Guidance Template.</description>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Client Case Task</relationshipLabel>
        <relationshipName>Client_Case_Task</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Display_Order__c</fullName>
        <label>Display Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Intake__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intake</label>
        <referenceTo>Intake__c</referenceTo>
        <relationshipLabel>Client Case Task</relationshipLabel>
        <relationshipName>Client_Case_Task</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Not Started = Task has not been initiated
In Progress = Counselor is actively working on the task
Skipped = Counselor intentionally bypassed the task for this case - explain reason for skipping in comment field (if applicable)
Done = Counselor has finished the task successfully</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Skipped</fullName>
                </value>
                <value>
                    <fullName>Done</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StepDetails__c</fullName>
        <label>Step Details</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>StepName__c</fullName>
        <label>Step Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Client Case Task</label>
    <nameField>
        <label>Client Case Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Case Task</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Intake__c.object
<CustomObject>
    <description>To capture and store initial information about clients/prospects during the intake process including New Intake, New Education Only, and New Emergency Triage.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Intake Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Open Intake</fullName>
                    <default>true</default>
                    <label>Open Intake</label>
                </value>
                <value>
                    <fullName>Open Case</fullName>
                </value>
                <value>
                    <fullName>Converted</fullName>
                    <isActive>false</isActive>
                    <label>Converted</label>
                </value>
                <value>
                    <fullName>New</fullName>
                    <isActive>false</isActive>
                    <label>New</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Intake</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ClientCaseGuidanceController.cls
/**
* @description       : Class for Client Case Guidance.
**/
public with sharing class ClientCaseGuidanceController {
    /**
* @description       : Method to get all the picklist field values.
**/
    @AuraEnabled(cacheable=true)
    public static List<Utility.PicklistOption> getStatusPicklist() {
        string NWC2NameSpace = Utility.getNwc2NameSpace();
        String objectApiName = NWC2NameSpace+'ClientCaseTask__c';
        String fieldApiName = NWC2NameSpace+'Status__c';
        return SObjectUtility.getPicklistLabelVal(objectApiName, fieldApiName);
    }
    
    /**
* @description       : Method to fetch all related client case tasks sorted by display order.
**/
    @AuraEnabled(cacheable=true)
    public static List<ClientCaseTask__c> getClientCaseTasks(
        String clientCaseId
    ) {
        return [
            SELECT Id, StepName__c, Status__c, StepDetails__c, Comments__c
            FROM ClientCaseTask__c
            WHERE ClientCase__c = :clientCaseId
            OR Intake__c = :clientCaseId
            ORDER BY Display_Order__c
        ];
    }
    
    /**
* @description       : Method to update client case task status and comment.
**/
    @AuraEnabled
    public static void updateClientCaseTask(
        String recordId,
        String status,
        String comments
    ) {
        try {
            Boolean hasUpdate = false;
            ClientCaseTask__c taskToUpdate = new ClientCaseTask__c();
            taskToUpdate.Id = recordId;
            if (!String.isEmpty(status)) {
                taskToUpdate.Status__c = status;
                hasUpdate = true;
            }
            if (!String.isEmpty(comments)) {
                taskToUpdate.Comments__c = comments;
                hasUpdate = true;
            }
            if (hasUpdate) {
                update taskToUpdate;
            }
        } catch (Exception e) {
            LoggerClass.log(e, recordId);
        }
    }
    
    /**
* @description       : Method to check that current logged in user is IntakeStaff or not.
**/
    @AuraEnabled
    public static Boolean isIntakeStaffUser(){
        return FeatureManagement.checkPermission('IntakeStaff');
    } 
}