objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>ClientCaseStatus__c</fullName>
        <defaultValue>(&quot;In Progress&quot;)</defaultValue>
        <description>In Progress: Open Case that is in progress and HUD reportable

Closed - Incomplete: Case closed without meeting the original outcome, HUD reportable

Closed - Service Complete: Case closed with meeting the original outcome, HUD reportable

On Hold: Case temporarily paused due to external factors or client request</description>
        <inlineHelpText>[1] In Progress: Case pending

[2] Closed - Incomplete: Didn’t meet original outcome

[3] Closed - Complete: Met the outcome

[4] On Hold: Case temporarily paused</inlineHelpText>
        <label>Client Case Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Closed - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Closed - Complete</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                    <isActive>false</isActive>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <isActive>false</isActive>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <isActive>false</isActive>
                    <label>Prospect</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CounselSessionDateStart__c</fullName>
        <label>Counsel Session Date Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CounselingTermination__c</fullName>
        <label>Counseling Termination</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ongoing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Dropped Out</fullName>
                </value>
                <value>
                    <fullName>Referred</fullName>
                </value>
                <value>
                    <fullName>No Further Contact</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HUDGrant__c</fullName>
        <label>HUD Grant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Comprehensive</fullName>
                </value>
                <value>
                    <fullName>Colonias</fullName>
                </value>
                <value>
                    <fullName>HECM</fullName>
                </value>
                <value>
                    <fullName>S8</fullName>
                </value>
                <value>
                    <fullName>Predatory Lending</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>MMMSA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HouseholdDebt__c</fullName>
        <label>Household Debt</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PrimaryClient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Repository__c</fullName>
        <label>Repository</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Equifax</fullName>
                </value>
                <value>
                    <fullName>Experian</fullName>
                </value>
                <value>
                    <fullName>Other Repository</fullName>
                </value>
                <value>
                    <fullName>RMCR</fullName>
                </value>
                <value>
                    <fullName>Trans Union</fullName>
                </value>
                <value>
                    <fullName>Tri merge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CounselorNote__c.object
<CustomObject>
    <description>To manage and document client case notes related client cases.</description>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Counselor Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration in Minutes</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>StartDatetime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Start Date/Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Counselor Note</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>Counselor Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counselor Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ActivityTimelineCasePDFControllerTest.cls
@isTest
public class ActivityTimelineCasePDFControllerTest {
    @testSetup
    static void setup() {
        Account acc = TestDataFactory.createAccounts(1, true)[0];
        Contact testContact = TestDataFactory.createContacts(acc.id,1, true)[0];

        List<ClientCase__c> ClientCaseList = TestDataFactory.createClientCases(1,false);
        ClientCaseList[0].PrimaryClient__c = testContact.Id;
        ClientCaseList[0].ClientCaseStatus__c = '	In Progress';
        ClientCaseList[0].CounselingTermination__c = 'Ongoing';
        ClientCaseList[0].CounselSessionDateStart__c = Datetime.now()+2;
        ClientCaseList[0].HouseholdDebt__c = 2500;
        ClientCaseList[0].HUDGrant__c  = 'MMMSA';
        ClientCaseList[0].Repository__c = 'Experian';
        insert ClientCaseList;

        CounselorNote__c counselorNote1 = TestDataFactory.createCounselorNote(ClientCaseList[0].Id, testContact.id, 1, true)[0];
        
        CounselorNote__c counselorNote2 = TestDataFactory.createCounselorNote(ClientCaseList[0].Id, testContact.id, 1, false)[0];
        counselorNote2.StartDatetime__c = DateTime.now()+3;
        counselorNote2.Notes__c = 'Test Note 2';
        counselorNote2.Duration__c = 45;
        insert counselorNote2;

        Event event1 = TestDataFactory.createEvent(testContact, NULL, 1, FALSE)[0];
        event1.WhatId = ClientCaseList[0].Id;
        event1.ActivityDate = Date.today().addDays(-1);
        event1.ActivityDateTime = Date.today().addDays(3);
        INSERT event1;
        
        Event event2 = TestDataFactory.createEvent(testContact, NULL, 1, FALSE)[0];
        event2.WhatId = ClientCaseList[0].Id;
        event2.ActivityDate = Date.today().addDays(-1);
        event2.DurationInMinutes = 90;
        event2.ActivityDateTime = Date.today().addDays(3);
        insert event2;
    }

    @isTest
    static void testActivityTimelineCasePDFController() {
        Test.setCurrentPage(Page.ActivityTimelineCasePDF); 
        ApexPages.currentPage().getParameters().put('id', [SELECT Id FROM ClientCase__c LIMIT 1].Id);
        ActivityTimelineCasePDFController controller = new ActivityTimelineCasePDFController();

    }
    
    @isTest
    static void Test1() {
        ActivityTimelineCasePDFController.caseManagementEntry cme = new ActivityTimelineCasePDFController.caseManagementEntry('DateTimeDuration', 'Status', 'Purpose', 'Outcome', 'Subject', 'Notes');
    }
}