objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CloudDocument__c.object
<CustomObject>
    <description>To manage and store documents related to client cases, contacts, and intake.</description>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Cloud Documents</relationshipLabel>
        <relationshipName>CloudDocuments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cloud Document</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Cloud Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cloud Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DocumentStorageSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>AccountSharedKey__c</fullName>
        <label>Account Shared Key</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ContainerName__c</fullName>
        <label>Container Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>StorageInstanceURL__c</fullName>
        <label>Storage Instance URL</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>StorageName__c</fullName>
        <label>Storage Name</label>
        <type>TextArea</type>
    </fields>
    <label>DocumentStorageSetting</label>
</CustomObject>

objects/Intake__c.object
<CustomObject>
    <description>To capture and store initial information about clients/prospects during the intake process including New Intake, New Education Only, and New Emergency Triage.</description>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Intake</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FileUploadControllerTest.cls
/*
	@description    Test Class for  FileUploadController apex class 
*/
@isTest
public class FileUploadControllerTest {
    
    /*
	@description    This method is for setting up data for testing in the test class  	
	*/
	@TestSetup
    public static void dataSetup(){
        List<Account> lstAcc = TestDataFactory.createAccounts(1, true);
        List<Contact> con = TestDataFactory.createContacts(lstAcc[0].id, 1, true);
        DocumentStorageSetting__c setting = new DocumentStorageSetting__c();
        setting.AccountSharedKey__c = 'test';
        setting.ContainerName__c =  'test';
        setting.StorageName__c =  'test';
        setting.StorageInstanceURL__c =  'test';
        insert setting;
        
        TestDataFactory.createClientCases(1, true);
        TestDataFactory.createIntakes(con[0], lstAcc[0].id, 1, true);
    }
    
    /*
	@description    This method tests the uploadFilesToStorage method.
*/
    testMethod static void testUploadFilesToStorage(){
        Test.setMock(HttpCalloutMock.class, new FileUploadMock());
        List<Contact> lstCon = [SELECT Id FROM Contact LIMIT 1];
        Test.startTest();
        FileUploadWrapper.AzureFileUploadWrapper fileWrapper =new FileUploadWrapper.AzureFileUploadWrapper();
        fileWrapper =new FileUploadWrapper.AzureFileUploadWrapper();  
        fileWrapper.filename = 'ors12';
        fileWrapper.filecontent = '';
        fileWrapper.fileextension = 'pdf';
        fileWrapper.option = 'Other';
        fileWrapper.externalDoc = true;
        fileWrapper.isVerified = true;
        fileWrapper.filelength = '10000';
        fileWrapper.fileType = 'pdf';
        fileWrapper.uniqueId = lstCon[0].Id;
        fileWrapper.fileprefix = 'data:pdf;base64';
        FileUploadController.uploadFilesToStorage(fileWrapper);
        List<CloudDocument__c> cdList = [SELECT Id FROM CloudDocument__c];
        System.assertEquals(cdList.size(), 1);
        FileUploadController.uploadFilesToStorage(new FileUploadWrapper.AzureFileUploadWrapper());
        Test.stopTest();
    }
    
    testMethod static void testClientCase(){
        Test.setMock(HttpCalloutMock.class, new FileUploadMock());
        List<ClientCase__c> ClientCase = [SELECT Id FROM ClientCase__c LIMIT 1];
        Test.startTest();
        FileUploadWrapper.AzureFileUploadWrapper fileWrapper =new FileUploadWrapper.AzureFileUploadWrapper();
        fileWrapper =new FileUploadWrapper.AzureFileUploadWrapper();  
        fileWrapper.filename = 'ors12';
        fileWrapper.filecontent = '';
        fileWrapper.fileextension = 'pdf';
        fileWrapper.option = 'Other';
        fileWrapper.externalDoc = true;
        fileWrapper.isVerified = true;
        fileWrapper.filelength = '10000';
        fileWrapper.fileType = 'pdf';
        fileWrapper.uniqueId = ClientCase[0].Id;
        fileWrapper.fileprefix = 'data:pdf;base64';
        FileUploadController.uploadFilesToStorage(fileWrapper);
        List<CloudDocument__c> cdList = [SELECT Id FROM CloudDocument__c];
        FileUploadController.uploadFilesToStorage(new FileUploadWrapper.AzureFileUploadWrapper());
        Test.stopTest();
    }
    
    testMethod static void testIntake(){
        Test.setMock(HttpCalloutMock.class, new FileUploadMock());
        List<Intake__c> Intake = [SELECT Id FROM Intake__c LIMIT 1];
        Test.startTest();
        FileUploadWrapper.AzureFileUploadWrapper fileWrapper =new FileUploadWrapper.AzureFileUploadWrapper();
        fileWrapper =new FileUploadWrapper.AzureFileUploadWrapper();  
        fileWrapper.filename = 'ors12';
        fileWrapper.filecontent = '';
        fileWrapper.fileextension = 'pdf';
        fileWrapper.option = 'Other';
        fileWrapper.externalDoc = true;
        fileWrapper.isVerified = true;
        fileWrapper.filelength = '10000';
        fileWrapper.fileType = 'pdf';
        fileWrapper.uniqueId = Intake[0].Id;
        fileWrapper.fileprefix = 'data:pdf;base64';
        FileUploadController.uploadFilesToStorage(fileWrapper);
        List<CloudDocument__c> cdList = [SELECT Id FROM CloudDocument__c];
        FileUploadController.uploadFilesToStorage(new FileUploadWrapper.AzureFileUploadWrapper());
        Test.stopTest();
    }
    
    /*
	@description    This class returns mock response for file upload.
	*/
    public class FileUploadMock implements HttpCalloutMock {
    	public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"example":"test"}');
            res.setStatusCode(201);
            return res;
        }
    }
}