objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>ClientCaseName__c</fullName>
        <description>Concatenated of contact Last Name + First Letter of First Name + Date Created + Service Type</description>
        <formula>PrimaryClient__r.LastName + &quot;, &quot;+ IF(ISNULL(PrimaryClient__r.FirstName) ,&apos;&apos;,MID(PrimaryClient__r.FirstName, 0, 1)) + &quot; - &quot;+  text(DATEVALUE(CreatedDate)) +&quot; - &quot;+  CaseType__r.Name</formula>
        <label>Client Case Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <description>HUD-specified outcomes for Education only</description>
        <inlineHelpText>HUD-specified outcomes</inlineHelpText>
        <label>Outcome</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed financial literacy workshop, including home affordability, budgeting and understanding use of credit</fullName>
                </value>
                <value>
                    <fullName>Completed predatory lending, loan scam or other fraud prevention workshop</fullName>
                </value>
                <value>
                    <fullName>Completed fair housing workshop</fullName>
                </value>
                <value>
                    <fullName>Completed homelessness prevention workshop</fullName>
                </value>
                <value>
                    <fullName>Completed rental workshop</fullName>
                </value>
                <value>
                    <fullName>Completed pre-purchase homebuyer education workshop</fullName>
                </value>
                <value>
                    <fullName>Completed non-delinquency post-purchase workshop, including home maintenance and/or financial management for homeowners</fullName>
                </value>
                <value>
                    <fullName>Completed resolving or preventing mortgage delinquency workshop</fullName>
                </value>
                <value>
                    <fullName>Completed other workshop</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <description>Agency to custom relevant purposes</description>
        <inlineHelpText>Choose one most applicable value from the drop-down list</inlineHelpText>
        <label>HUD Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Homeless Assistance</fullName>
                </value>
                <value>
                    <fullName>Pre-purchase/Homebuying</fullName>
                </value>
                <value>
                    <fullName>Rental Topics</fullName>
                </value>
                <value>
                    <fullName>Non-Delinquency Post-Purchase</fullName>
                </value>
                <value>
                    <fullName>Reverse Mortgage</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Forward Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Reverse Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Disaster Preparedness Assistance</fullName>
                </value>
                <value>
                    <fullName>Disaster Recovery Assistance</fullName>
                </value>
                <value>
                    <fullName>Not HUD-Reportable</fullName>
                </value>
                <value>
                    <fullName>Financial Literacy</fullName>
                    <isActive>false</isActive>
                    <label>Financial Literacy</label>
                </value>
                <value>
                    <fullName>Home Improvement Loan</fullName>
                    <isActive>false</isActive>
                    <label>Home Improvement Loan</label>
                </value>
                <value>
                    <fullName>Home Purchase Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Home Purchase Inquiry</label>
                </value>
                <value>
                    <fullName>Job Training</fullName>
                    <isActive>false</isActive>
                    <label>Job Training</label>
                </value>
                <value>
                    <fullName>Mortgage Delinquency Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Mortgage Delinquency Inquiry</label>
                </value>
                <value>
                    <fullName>Rehab Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Rehab Inquiry</label>
                </value>
                <value>
                    <fullName>Rental Assistance</fullName>
                    <isActive>false</isActive>
                    <label>Rental Assistance</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CounselorNote__c.object
<CustomObject>
    <description>To manage and document client case notes related client cases.</description>
    <fields>
        <fullName>ClientCaseName__c</fullName>
        <formula>ClientCase__r.ClientCaseName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Case Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Counselor Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>StartDatetime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Start Date/Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Counselor Note</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>Counselor Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counselor Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Calendar Event Information</relationshipLabel>
        <relationshipName>SUMOAdditionalInfo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HUDActivityType__c</fullName>
        <label>HUD Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>HUDActivityType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>sumoapp__EventName__c</fullName>
        <label>Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Child Events</relationshipLabel>
        <relationshipName>ChildEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__Attendee__c.object
<CustomObject>
    <fields>
        <fullName>HUDActivityType__c</fullName>
        <formula>TEXT( sumoapp__SumoEvent__r.HUDActivityType__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>HUD Activity Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <formula>TEXT( sumoapp__SumoEvent__r.HUD_Purpose__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outcome</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__EventName__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__EventName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__StartDatetime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__SumoEvent__c</fullName>
        <label>SUMO Event</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SUMO Attendee</label>
    <nameField>
        <displayFormat>ATD-{000000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/HUDActivityType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Not Billed to HUD</fullName>
        <default>true</default>
        <label>Not Billed to HUD</label>
    </customValue>
    <customValue>
        <fullName>NOFA 2014-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2014-2 TRNG</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2015-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2015-2 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2016-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2017-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2018-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2019-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2020-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2021-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2022-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2023-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>HO INT</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2024-1 COMP</fullName>
    </customValue>
    <masterLabel>HUD Activity Type</masterLabel>
</GlobalValueSet>

classes/ActivityTimelineService.cls
public abstract class ActivityTimelineService {
    
    public static final String UPCOMING_EVENTS_KEY = '999999';
    public static final String COURSE_RECORDTYPE_NAME='Course';
    
    /*
     * @description : To fetch all the events for a given record
     */
    public List<ResultWrapper> getAllEvents(Id recordId){
        Map<String, List<ActivityWrapper>> eventGroupBYMonth = new Map<String, List<ActivityWrapper>>();
        List<ActivityWrapper> result = new List<ActivityWrapper>();
        result.addAll(getAppointments(recordId));
        result.addAll(getCourses(recordId));
        result.addAll(getCounselorNotes(recordId));
        result.sort(new ResultWrapperComparator());
        
        for(ActivityWrapper wrap : result) {
            if(wrap.eventDate!=null) {
                String monthName = wrap.eventDate > System.now() ? UPCOMING_EVENTS_KEY : wrap.eventDate.format('yyyyMM');
                if(eventGroupBYMonth.containsKey(monthName)) {
                    List<ActivityWrapper> events = eventGroupBYMonth.get(monthName);
                    events.add(wrap);
                    eventGroupBYMonth.put(monthName, events);
                } else {
                    List<ActivityWrapper> events = new List<ActivityWrapper>();
                    events.add(wrap);
                    eventGroupBYMonth.put(monthName, events);
                }
                
            }
            
        } 
        
        //transform Map to ResultWrapper
        List<ResultWrapper> eventList = new List<ResultWrapper>();
        for(String key : eventGroupBYMonth.keySet()) {
            List<ActivityWrapper> events = eventGroupBYMonth.get(key);
            
            String monthName = key==UPCOMING_EVENTS_KEY ? 'Upcoming Events' : events.get(0).eventDate.format('MMMMM yyyy');
            ResultWrapper wrapper = new ResultWrapper();
            wrapper.title=key;
            wrapper.monthName=monthName;
            wrapper.eventList = events;
            eventList.add(wrapper);
        }
        eventList.sort(new EventWrapperComparator());
        for(ResultWrapper w : eventList) {
            System.debug(w.monthName);
            System.debug(w);
        }
        return eventList;
        
    }
    
    public abstract List<ActivityWrapper> getAppointments(Id recordId);
    
    public abstract List<ActivityWrapper> getCourses(Id recordId);
    
    public abstract List<ActivityWrapper> getCounselorNotes(Id recordId);
    
    /*
     * @description : To convent instance of an Event to ActivityWrapper
     */
    protected ActivityWrapper convertEventToWrapper(Event evt, ClientCase__c cc, String Purpose) {
        ActivityWrapper wrap = new ActivityWrapper();
        wrap.title=evt.Subject;
        wrap.type='Appointment';
        wrap.isAppointment=true;
        wrap.eventDate=evt.StartDateTime;
        wrap.recordId=evt.Id;
        wrap.relatedId=evt.sumoapp__AdditionalInfo__c;
        if(evt.purpose__c!=null) {
            wrap.purpose = evt.purpose__c;
        } else {
            wrap.purpose = Purpose;
        }
        wrap.caseTypePurposeApiValue = Purpose;
        Schema.DescribeFieldResult field = Event.purpose__c.getDescribe();
        for (Schema.PicklistEntry f : field.getPicklistValues()){
            if(f.getValue() == Purpose){
                wrap.caseTypePurposeLabel = f.getLabel();
                break;
            }
        }
        wrap.outcome = evt.Outcome__c;
        wrap.appointmentStatus = evt.AppointmentStatus__c;
        wrap.hudActivity=evt.HUDActivityType__c;
        
        
        if(evt.StartDateTime != null && evt.EndDateTime != null){
            wrap.notesDurationDate = evt.StartDateTime.format('MMM dd, hh:mm a')+' - '+evt.EndDateTime.format('hh:mm a');
        }
        if(!Test.isRunningTest()){
            wrap.contactName=evt.Who.Name;
        }
        if(evt.AppointmentDuration__c!=null) {
            wrap.durationInMin=Integer.valueOf(evt.AppointmentDuration__c);
        } else if(evt.StartDateTime != null && evt.EndDateTime != null){
            long start = evt.StartDateTime.getTime();
            long endTime = evt.EndDateTime.getTime();
            wrap.durationInMin = Integer.valueOf((endTime - start)/(1000*60));
        }
        
        
        wrap.notes=evt.sumoapp__AdditionalInfo__r.Notes__c;
        
        if(cc!=null) {
            ClientCaseWrapper clientCase = new ClientCaseWrapper();
            clientCase.recordId=cc.Id;
            clientCase.name = cc.ClientCaseName__c;
            //wrap.purpose=cc.Purpose__c;
            wrap.clientCase = clientCase;
        }
        return wrap;
    }
    
    /*
     * @description : To convent instance of a Course to ActivityWrapper
     */
    protected ActivityWrapper convertCourseToWrapper(sumoapp__Attendee__c attendee) {
        String recordTypeName = attendee?.sumoapp__SumoEvent__r?.RecordType?.DeveloperName;
        String relatedAdditionalName=attendee.sumoapp__EventName__c;
        ActivityWrapper wrap = new ActivityWrapper();
        wrap.title= (recordTypeName==COURSE_RECORDTYPE_NAME) ? attendee?.sumoapp__SumoEvent__r?.sumoapp__Parent__r?.sumoapp__EventName__c : relatedAdditionalName;
        wrap.description=relatedAdditionalName;
        wrap.type='Course';
        wrap.isCourse=true;
        wrap.eventDate=attendee.sumoapp__StartDatetime__c;
        wrap.recordId=attendee.Id;
        wrap.relatedId=attendee.sumoapp__SumoEvent__c;
        return wrap;
    }
    
    /*
     * @description : To convent instance of a Note to ActivityWrapper
     */
    protected ActivityWrapper convertNoteToWrapper(CounselorNote__c note) {
        ActivityWrapper wrapper = new ActivityWrapper();
        wrapper.title=note.Subject__c;
        wrapper.type='Note';
        wrapper.isNote=true;
        wrapper.eventDate = note.StartDatetime__c;
        wrapper.recordId=note.id;
        if(note.ClientCase__c!=null) {
            ClientCaseWrapper clientCase = new ClientCaseWrapper();
            clientCase.recordId=note.ClientCase__c;
            clientCase.name = note.ClientCase__r.ClientCaseName__c;
            wrapper.clientCase = clientCase;
        }
        return wrapper;
    }
    
    public class ClientCaseWrapper{
        @AuraENabled public String name{get;set;}
        @AuraEnabled public String recordId{get;set;}
    }
    
    public class ActivityWrapper{
        @AuraEnabled public String title{get;set;}
        @AuraEnabled public String description{get;set;}
        @AuraEnabled public String type{get;set;}
        @AuraEnabled public string recordId{get;set;}
        @AuraEnabled public string relatedId{get;set;}
        @AuraEnabled public DateTime eventDate{get;set;}
        @AuraEnabled public Boolean isCourse{get;set;}
        @AuraEnabled public Boolean isNote{get;set;}
        @AuraEnabled public Boolean isAppointment{get;set;}
        @AuraEnabled public String contactName{get;set;}
        @AuraEnabled public String funder{get;set;}
        @AuraEnabled public String outcome{get;set;}
        @AuraEnabled public String purpose{get;set;}
        @AuraEnabled public Integer durationInMin{get;set;}
        @AuraEnabled public String notesDurationDate{get;set;}
        @AuraEnabled public string notes{get;set;}
        @AuraEnabled public string hudActivity{get;set;}        
        @AuraEnabled public String appointmentStatus{get;set;}
        @AuraEnabled public List<String> participants{get;set;}
        @AuraEnabled public String caseTypePurposeLabel{get;set;}
        @AuraEnabled public String caseTypePurposeApiValue{get;set;}
        
        @AuraEnabled public String getDisplayDate() {
            return eventDate!=null ? eventDate.format('h:mm a | MM/dd/yyyy') : '';
        }
        @AuraEnabled public ClientCaseWrapper clientCase{get;set;}
        public ActivityWrapper() {
            this.isCourse = false;
            this.isNote = false;
            this.isAppointment = false;
        }
    }
    
    public class ResultWrapper {
        @AuraEnabled public String title{get;set;}
        @AuraEnabled public String monthName{get;set;}
        @AuraEnabled public List<ActivityWrapper> eventList{get;set;}
    }
    
    
    public class ResultWrapperComparator implements Comparator<ActivityWrapper> {
        
        public Integer compare(ActivityWrapper wrap1, ActivityWrapper wrap2) {
            if(wrap1.eventDate==wrap2.eventDate) {
                return 0;
            } else if(wrap1.eventDate < wrap2.eventDate) {
                return 1;
            }
            else {
                return -1;
            }
        }
    }
    
    public class EventWrapperComparator implements Comparator<ResultWrapper> {
        public Integer compare(ResultWrapper wrap1, ResultWrapper wrap2) {
            return wrap2.title.compareTo(wrap1.title);
        }
    }
    
}