objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>ClientCaseClosedDate__c</fullName>
        <description>Date the case is closed</description>
        <label>Client Case Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ClientCaseStatus__c</fullName>
        <defaultValue>(&quot;In Progress&quot;)</defaultValue>
        <description>In Progress: Open Case that is in progress and HUD reportable

Closed - Incomplete: Case closed without meeting the original outcome, HUD reportable

Closed - Service Complete: Case closed with meeting the original outcome, HUD reportable

On Hold: Case temporarily paused due to external factors or client request</description>
        <inlineHelpText>[1] In Progress: Case pending

[2] Closed - Incomplete: Didn’t meet original outcome

[3] Closed - Complete: Met the outcome

[4] On Hold: Case temporarily paused</inlineHelpText>
        <label>Client Case Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Closed - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Closed - Complete</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                    <isActive>false</isActive>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <isActive>false</isActive>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <isActive>false</isActive>
                    <label>Prospect</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <recordTypes>
        <fullName>FinancialCapabilityCounseling</fullName>
        <active>true</active>
        <label>Financial Capability Counseling</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HudOrsFinancialCapabilityReportCtrlTest.cls
@isTest
public class HudOrsFinancialCapabilityReportCtrlTest {
    @testSetup
    static void setupTestData() {
        string NWC2NameSpace = Utility.getNwc2NameSpace();
        string objectName = NWC2NameSpace + 'ClientCase__c';
        // Create test data for the ClientCase__c object
        RecordType rt = [SELECT Id FROM RecordType WHERE DeveloperName = 'FinancialCapabilityCounseling' AND SObjectType =: objectName LIMIT 1];

        ClientCase__c case1 = TestDataFactory.createClientCases(1,false)[0];
		case1.ClientCaseClosedDate__c = Date.today().addDays(-1);       
      	case1.ClientCaseClosedDate__c = Date.today().addDays(-1);
        case1.ClientCaseStatus__c = 'Closed - Complete';
        insert case1;
    }

    @isTest
    static void testFetchORSFinancialRecords() {
        // Set test dates
        Date qtrStartDate = Date.today().addMonths(-3);
        Date qtrEndDate = Date.today();

        Test.startTest();

        // Call the method to test
        Map<String, List<HudOrsFinancialCapabilityReportCtrl.OrsReportWrapper>> result = HudOrsFinancialCapabilityReportCtrl.fetchORSFinancialRecords(qtrStartDate, qtrEndDate);
		HudOrsFinancialCapabilityReportCtrl.ORS_FCWrapper result2 = HudOrsFinancialCapabilityReportCtrl.fetchNWQRFCAggregateValidation(qtrStartDate, qtrEndDate);
        Test.stopTest();
		System.debug('### result : '+result.size()); 
        System.assertNotEquals(null, result);
    }
}