objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>CaseResolutionDate__c</fullName>
        <label>Case Resolution Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CaseResolution__c</fullName>
        <label>Case Resolution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fulfilled (Purchased housing)</fullName>
                </value>
                <value>
                    <fullName>Suspended (Withdrew from counseling)</fullName>
                </value>
                <value>
                    <fullName>Entered Lease Purchase Pgm</fullName>
                </value>
                <value>
                    <fullName>Decided Not to Purchase</fullName>
                </value>
                <value>
                    <fullName>Counseled on HECM; Declined Mortgage</fullName>
                </value>
                <value>
                    <fullName>Referred to Other Agency</fullName>
                </value>
                <value>
                    <fullName>Obtained a HECM</fullName>
                </value>
                <value>
                    <fullName>Rcvd. Home Equity/Home Improvement Loan</fullName>
                </value>
                <value>
                    <fullName>Mortgage Refinanced</fullName>
                </value>
                <value>
                    <fullName>Sold House, Chose Alt. Housing Solution</fullName>
                </value>
                <value>
                    <fullName>Rcvd. Consumer Loan (Unsecured)</fullName>
                </value>
                <value>
                    <fullName>Obtained a Non-FHA Reverse Mortgage</fullName>
                </value>
                <value>
                    <fullName>Complete Financial Mgt/Budget Counseling</fullName>
                </value>
                <value>
                    <fullName>Complete Home Maintenance Counseling</fullName>
                </value>
                <value>
                    <fullName>Counseled and Utilities Brought Current</fullName>
                </value>
                <value>
                    <fullName>Counseled/Referred for Legal Assistance</fullName>
                </value>
                <value>
                    <fullName>Brought Mortgage Current</fullName>
                </value>
                <value>
                    <fullName>Initiated Forbearance Agreement</fullName>
                </value>
                <value>
                    <fullName>Executed Deed-in-lieu</fullName>
                </value>
                <value>
                    <fullName>Sold Property</fullName>
                </value>
                <value>
                    <fullName>Mortgage Foreclosed</fullName>
                </value>
                <value>
                    <fullName>Rcvd. 2nd Mortgage</fullName>
                </value>
                <value>
                    <fullName>Partial Claim</fullName>
                </value>
                <value>
                    <fullName>Mortgage Modified</fullName>
                </value>
                <value>
                    <fullName>Counseled/Referred to Agency</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>Pre-foreclosure Sale</fullName>
                </value>
                <value>
                    <fullName>Entered Debt Management Plan</fullName>
                </value>
                <value>
                    <fullName>Other (final result not listed above)</fullName>
                </value>
                <value>
                    <fullName>Found Alternative (Found alternative rental housing)</fullName>
                </value>
                <value>
                    <fullName>Increase access to credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClientCaseStatus__c</fullName>
        <defaultValue>(&quot;In Progress&quot;)</defaultValue>
        <description>In Progress: Open Case that is in progress and HUD reportable

Closed - Incomplete: Case closed without meeting the original outcome, HUD reportable

Closed - Service Complete: Case closed with meeting the original outcome, HUD reportable

On Hold: Case temporarily paused due to external factors or client request</description>
        <inlineHelpText>[1] In Progress: Case pending

[2] Closed - Incomplete: Didn’t meet original outcome

[3] Closed - Complete: Met the outcome

[4] On Hold: Case temporarily paused</inlineHelpText>
        <label>Client Case Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Closed - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Closed - Complete</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                    <isActive>false</isActive>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <isActive>false</isActive>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <isActive>false</isActive>
                    <label>Prospect</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CounselingTermination__c</fullName>
        <label>Counseling Termination</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ongoing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Dropped Out</fullName>
                </value>
                <value>
                    <fullName>Referred</fullName>
                </value>
                <value>
                    <fullName>No Further Contact</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan</label>
        <referenceTo>Loan__c</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Grant__c.object
<CustomObject>
    <fields>
        <fullName>ClientCase__c</fullName>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FundingType__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CDBG</fullName>
                </value>
                <value>
                    <fullName>Client Sweat Equity</fullName>
                </value>
                <value>
                    <fullName>DOE (WAP) Weatherization Funds</fullName>
                </value>
                <value>
                    <fullName>HFA</fullName>
                </value>
                <value>
                    <fullName>Non NWO CDFI</fullName>
                </value>
                <value>
                    <fullName>NWOs other funds</fullName>
                </value>
                <value>
                    <fullName>Other sources (e.g. FHLB/AHP/Corporations/Foundations/NWA/NCC)</fullName>
                </value>
                <value>
                    <fullName>City Government</fullName>
                    <isActive>false</isActive>
                    <label>City Government</label>
                </value>
                <value>
                    <fullName>Corporation</fullName>
                    <isActive>false</isActive>
                    <label>Corporation</label>
                </value>
                <value>
                    <fullName>Federal Government</fullName>
                    <isActive>false</isActive>
                    <label>Federal Government</label>
                </value>
                <value>
                    <fullName>Foundation</fullName>
                    <isActive>false</isActive>
                    <label>Foundation</label>
                </value>
                <value>
                    <fullName>Gift of Equity</fullName>
                    <isActive>false</isActive>
                    <label>Gift of Equity</label>
                </value>
                <value>
                    <fullName>NCC</fullName>
                    <isActive>false</isActive>
                    <label>NCC</label>
                </value>
                <value>
                    <fullName>NWO Loan Funds</fullName>
                    <isActive>false</isActive>
                    <label>NWO Loan Funds</label>
                </value>
                <value>
                    <fullName>NWO Other</fullName>
                    <isActive>false</isActive>
                    <label>NWO Other</label>
                </value>
                <value>
                    <fullName>NeighborWorks America</fullName>
                    <isActive>false</isActive>
                    <label>NeighborWorks America</label>
                </value>
                <value>
                    <fullName>Other Source</fullName>
                    <isActive>false</isActive>
                    <label>Other Source</label>
                </value>
                <value>
                    <fullName>Private Lending Institution</fullName>
                    <isActive>false</isActive>
                    <label>Private Lending Institution</label>
                </value>
                <value>
                    <fullName>State or County Government</fullName>
                    <isActive>false</isActive>
                    <label>State or County Government</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant</label>
    <nameField>
        <displayFormat>G- {YYYY}/{MM} - {0000}</displayFormat>
        <label>Grant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Loan__c.object
<CustomObject>
    <description>To capture details related to loans for client cases.</description>
    <fields>
        <fullName>ClientCase__c</fullName>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Loan</relationshipLabel>
        <relationshipName>Loan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Loan</label>
    <nameField>
        <displayFormat>L- {YYYY}/{MM} - {0000}</displayFormat>
        <label>Loan</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan</pluralLabel>
    <recordTypes>
        <fullName>Loan</fullName>
        <active>true</active>
        <label>Loan</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/NwqrFinancingReportControllerTest.cls
@istest
public class NwqrFinancingReportControllerTest {
    
    @TestSetup
    static void setupData() {
        User adminUser = GrantTriggerHandlerTest.createAdminUserWithAllPermission();
        System.runAs(adminUser){
            RecordType rtCon = [Select Id, DeveloperName from RecordType where SobjectType='Contact' And developerName = 'Affiliate'];
            Account acc = TestDataFactory.createAccounts(1, true)[0];
            Contact con = TestDataFactory.createContacts(acc.Id, 1, false)[0];
            con.recordTypeId = rtCon.Id;
            insert con;
            
            ClientCase__c cc = TestDataFactory.createClientCases(1,false)[0];
            cc.ClientCaseStatus__c = 'Closed - Complete';
            cc.CounselingTermination__c = 'Completed';
            cc.CaseResolution__c = 'Increase access to credit';
        	cc.CaseResolutionDate__c = Date.Today();
            insert cc;
            
            Loan__c loan = TestDataFactory.createLoan(con, 1, false)[0];
            loan.ClientCase__c = cc.Id;
            loan.Status__c = 'Approved';
            insert loan;
            
            ClientCase__c cc2 = TestDataFactory.createClientCases(1,false)[0];
            cc2.ClientCaseStatus__c = 'Closed - Complete';
            cc2.CounselingTermination__c = 'Completed';
            cc2.CaseResolution__c = 'Increase access to credit';
        	cc2.CaseResolutionDate__c = Date.Today();
            insert cc2;
            
            Grant__c grant = new Grant__c();
            grant.FundingType__c = 'CDBG';
            grant.FundingSource__c = 'Government (Federal/State/Local)';
            grant.ClientCase__c = cc2.Id;
            grant.FundingAmount__c = 100;
            grant.Grantor__c = 'test';
            grant.StatusType__c = 'Approved';
            insert grant;
        }
    }
    
    static testMethod void testEetchNWQRFinancingReports(){
        User adminUser = [Select id, IsActive from User where userName = 'utst@test.com1' limit 1];
        System.runAs(adminUser){
            Test.startTest();
            List<NwqrFinancingReportController.NwqrReportWrapper> orsoutput = NwqrFinancingReportController.fetchNWQRFinancingReports(System.Today() - 1,System.Today() + 1);
            Test.StopTest();
            
            System.assertEquals(2,orsoutput.size());
        }
    }
    
}