objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Grant__c.object
<CustomObject>
    <fields>
        <fullName>ClientCase__c</fullName>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FinancingType__c</fullName>
        <label>Financing Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>First grant</fullName>
                </value>
                <value>
                    <fullName>All other grants</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FundingAmount__c</fullName>
        <label>Funding Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Grant</label>
    <nameField>
        <displayFormat>G- {YYYY}/{MM} - {0000}</displayFormat>
        <label>Grant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/GrantTriggerHandler.cls
public with sharing class GrantTriggerHandler {
    public static void recomputeGrantFinancing(List<Grant__c> grantList, Boolean fromTrigger){
        
        Set<Id> clientCaseIdSet = new Set<Id>();
        Map<Id,List<Grant__c>> ccToNewGrantMap = new Map<Id,List<Grant__c>>();
        List<Grant__c> grantsToUpdate = new List<Grant__c>();
        
        for(Grant__c grant : grantList){
            clientCaseIdSet.add(grant.ClientCase__c);
            if(ccToNewGrantMap.containskey(grant.ClientCase__c)){
                ccToNewGrantMap.get(grant.ClientCase__c).add(grant);
            } else {
                ccToNewGrantMap.put(grant.ClientCase__c,new List<Grant__c>{grant});
            }
        }
        for(ClientCase__c cc : [Select id, (Select id, FundingAmount__c FROM Grants__r order by FundingAmount__c desc limit 1) from ClientCase__c where id in :clientCaseIdSet]){
            Grant__c highestGrant;
            if(cc.Grants__r != null && cc.Grants__r.size() > 0 && cc.Grants__r[0] != null && cc.Grants__r[0].Id != null){
                highestGrant = cc.Grants__r[0];
            }
            if(highestGrant == null){
                Decimal highestAmt = 0;
                Boolean flag = false;
                for(Grant__c grant : ccToNewGrantMap.get(cc.Id)){
                    if(grant.FundingAmount__c > highestAmt){
                        highestAmt = grant.FundingAmount__c;
                    }
                }
                for(Grant__c grant : ccToNewGrantMap.get(cc.Id)){
                    if((!flag) && grant.FundingAmount__c == highestAmt){
                        grant.FinancingType__c = 'First grant';
                        flag = true;
                    } else {
                        grant.FinancingType__c = 'All other grants';
                    }
                    if(!fromTrigger){
                        grantsToUpdate.add(grant);
                    }
                }
            } else {
                Decimal highestAmt = 0;
                Boolean flag = false;
                for(Grant__c grant : ccToNewGrantMap.get(cc.Id)){
                    if(grant.FundingAmount__c > highestAmt){
                        highestAmt = grant.FundingAmount__c;
                    }
                }
                if(highestAmt > highestGrant.FundingAmount__c){
                    highestGrant.FinancingType__c = 'All other grants';
                    grantsToUpdate.add(highestGrant);
                    for(Grant__c grant : ccToNewGrantMap.get(cc.Id)){
                        if((!flag) && grant.FundingAmount__c == highestAmt){
                            grant.FinancingType__c = 'First grant';
                            flag = true;
                        } else {
                            grant.FinancingType__c = 'All other grants';
                        }
                        if(!fromTrigger){
                            grantsToUpdate.add(grant);
                        }
                    }
                } else {
                    for(Grant__c grant : ccToNewGrantMap.get(cc.Id)){
                        grant.FinancingType__c = 'All other grants';
                        if(!fromTrigger){
                            grantsToUpdate.add(grant);
                        }
                    }
                }
            }
        }
        if(grantsToUpdate.size() > 0){
            Database.update(grantsToUpdate, false);
        }
    }
}