objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CloudDocument__c.object
<CustomObject>
    <description>To manage and store documents related to client cases, contacts, and intake.</description>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Cloud Documents</relationshipLabel>
        <relationshipName>CloudDocuments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cloud Documents</relationshipLabel>
        <relationshipName>Cloud_Documents</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DecodedFileLocation__c</fullName>
        <label>Decoded File Location</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ExternalDocument__c</fullName>
        <defaultValue>false</defaultValue>
        <label>External Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FileContentPrefix__c</fullName>
        <label>File Content Prefix</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FileName__c</fullName>
        <label>FileName</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Filetype__c</fullName>
        <label>File type</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FolderName__c</fullName>
        <label>Folder Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IntakeRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intake Request</label>
        <referenceTo>Intake__c</referenceTo>
        <relationshipLabel>Cloud Documents</relationshipLabel>
        <relationshipName>Cloud_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsVerified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Verified</label>
        <type>Checkbox</type>
    </fields>
    <label>Cloud Document</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Cloud Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cloud Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Intake__c.object
<CustomObject>
    <description>To capture and store initial information about clients/prospects during the intake process including New Intake, New Education Only, and New Emergency Triage.</description>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Intake</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FileUploadController.cls
/*
@description    Controller class containing methods for file upload functionality
*/
public with sharing class FileUploadController {
    
    /*
    @description    This method uploads the file to Azure and creates a document record for reference in sfdc.
                    This method if used in the fileUpload lwc component.
    */
    @AuraEnabled
    public static void uploadFilesToStorage(FileUploadWrapper.AzureFileUploadWrapper fileWrapper){
        try{
            boolean fileUploaded = FileUploadHandler.putfileInAzure(filewrapper.filename, fileWrapper.fileextension, 
                                                                    fileWrapper.filelength, EncodingUtil.base64Decode(fileWrapper.filecontent),
                                                                    filewrapper.fileType, filewrapper.option, fileWrapper.uniqueId);
            
            System.debug('File Uploaded : '+fileUploaded);
            
            Id objectId = Id.valueOf(fileWrapper.uniqueId);
            String objectName = objectId?.getSObjectType()?.getDescribe().getName();
            System.debug('Object Name : ' + objectName);
            System.debug('Parent Record : ' + filewrapper.parentId);
            
            System.debug('Contact : '+(objectName=='Contact' && fileUploaded && Schema.sObjectType.CloudDocument__c.isCreateable()));
            System.debug('Client Case : '+(objectName=='Intake__c' && fileUploaded && Schema.sObjectType.CloudDocument__c.isCreateable()));
            System.debug('Intake Case : '+(objectName=='ClientCase__c' && fileUploaded && Schema.sObjectType.CloudDocument__c.isCreateable()));
            
            if(objectName=='Contact' && fileUploaded && Schema.sObjectType.CloudDocument__c.isCreateable()) {            
                CloudDocument__c cloudDoc = new CloudDocument__c();
                cloudDoc.Contact__c = fileWrapper.uniqueId;
                cloudDoc.DecodedFileLocation__c = FileUploadHandler.generateFileName(fileWrapper.uniqueId, filewrapper.option, filewrapper.filename, fileWrapper.fileextension);
                cloudDoc.ExternalDocument__c = fileWrapper.externalDoc;
                cloudDoc.Filetype__c = fileWrapper.fileType;
                cloudDoc.IsVerified__c = fileWrapper.isVerified;
                cloudDoc.FolderName__c = fileWrapper.option;
                cloudDoc.fileName__c = filewrapper.fileName + '.' + filewrapper.fileExtension;
                cloudDoc.FileContentPrefix__c = filewrapper.fileprefix;
                insert cloudDoc;
                System.debug('Document Uploaded : '+cloudDoc);
                
            } else if(objectName=='ClientCase__c' && fileUploaded && Schema.sObjectType.CloudDocument__c.isCreateable()) {
                CloudDocument__c cloudDoc = new CloudDocument__c();
                cloudDoc.ClientCase__c = fileWrapper.uniqueId;
                cloudDoc.Contact__c = fileWrapper.parentId;
                cloudDoc.DecodedFileLocation__c = FileUploadHandler.generateFileName(fileWrapper.uniqueId, filewrapper.option, filewrapper.filename, fileWrapper.fileextension);
                cloudDoc.ExternalDocument__c = fileWrapper.externalDoc;
                cloudDoc.Filetype__c = fileWrapper.fileType;
                cloudDoc.IsVerified__c = fileWrapper.isVerified;
                cloudDoc.FolderName__c = fileWrapper.option;
                cloudDoc.fileName__c = filewrapper.fileName + '.' + filewrapper.fileExtension;
                cloudDoc.FileContentPrefix__c = filewrapper.fileprefix;
                insert cloudDoc;
                System.debug('Document Uploaded : '+cloudDoc);
                
            } else if(objectName=='Intake__c' && fileUploaded && Schema.sObjectType.CloudDocument__c.isCreateable()) {
                CloudDocument__c cloudDoc = new CloudDocument__c();
                if(String.isNotBlank(filewrapper.clientCaseId)){
                    cloudDoc.ClientCase__c = fileWrapper.clientCaseId;
                }else{
                    cloudDoc.IntakeRequest__c = fileWrapper.uniqueId;
                }
                cloudDoc.Contact__c = fileWrapper.parentId;
                cloudDoc.DecodedFileLocation__c = FileUploadHandler.generateFileName(fileWrapper.uniqueId, filewrapper.option, filewrapper.filename, fileWrapper.fileextension);
                cloudDoc.ExternalDocument__c = fileWrapper.externalDoc;
                cloudDoc.Filetype__c = fileWrapper.fileType;
                cloudDoc.IsVerified__c = fileWrapper.isVerified;
                cloudDoc.FolderName__c = fileWrapper.option;
                cloudDoc.fileName__c = filewrapper.fileName + '.' + filewrapper.fileExtension;
                cloudDoc.FileContentPrefix__c = filewrapper.fileprefix;
                insert cloudDoc;
                System.debug('Document Uploaded : '+cloudDoc);
            }
        }catch (Exception e) {
            LoggerClass.log(e,fileWrapper.uniqueId);
        }
    }
    
     /**
* @description       : Method to check that current logged in user is IntakeStaff or not.
**/
    @AuraEnabled
    public static Boolean isIntakeStaffUser(){
        return FeatureManagement.checkPermission('IntakeStaff');
    } 
}