objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>AnnualHouseholdIncome__c</fullName>
        <formula>HouseholdMonthlyIncome1__c * 12</formula>
        <label>Annual Household Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ChoseNottoProvideIncome__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Chose Not to Provide Income</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HouseholdMonthlyIncome1__c</fullName>
        <label>Household Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>HUD-Defined Number in Household</description>
        <inlineHelpText>Total number of people living in the same household as the primary client</inlineHelpText>
        <label>Household Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MonthlyIncome__c</fullName>
        <label>Total Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PrimaryClient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CoApplicant__c.object
<CustomObject>
    <description>To store details about household members who are co-applicants of the primary contact.</description>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Co-Applicants</relationshipLabel>
        <relationshipName>Co_Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicants</relationshipLabel>
        <relationshipName>Co_Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IntakeRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intake</label>
        <referenceTo>Intake__c</referenceTo>
        <relationshipLabel>Co-Applicants</relationshipLabel>
        <relationshipName>Co_Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Co-Applicant</label>
    <nameField>
        <displayFormat>CAPP-{00000}</displayFormat>
        <label>Co-Applicant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co-Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AnnualHouseholdIncome__c</fullName>
        <formula>HouseholdMonthlyIncome1__c * 12</formula>
        <label>Annual Household Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ChoseNottoProvideIncome__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Chose Not to Provide Income</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HouseholdMonthlyIncome1__c</fullName>
        <label>Household Monthly Income</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>Number of people in the household</description>
        <inlineHelpText>Total number of people living in the same household</inlineHelpText>
        <label>Household Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalMonthlyIncome__c</fullName>
        <label>Total Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>CoApplicant</fullName>
        <active>true</active>
        <label>Co-Applicant</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Intake__c.object
<CustomObject>
    <description>To capture and store initial information about clients/prospects during the intake process including New Intake, New Education Only, and New Emergency Triage.</description>
    <fields>
        <fullName>AnnualHouseholdIncome__c</fullName>
        <formula>HouseholdMonthlyIncome__c * 12</formula>
        <label>Annual Household Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ChoseNottoProvideIncome__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Chose Not to Provide Income</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HouseholdMonthlyIncome__c</fullName>
        <label>Household Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <label>Household Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MonthlyIncome__c</fullName>
        <label>Total Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PrimaryClient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Intake_Only</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Intake</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CoApplicantTriggerHandler.cls
/**
* Handler class for CoApplicant trigger.
*/
public class CoApplicantTriggerHandler {
    
    /**
* @desc:Handles after insert trigger events for CoApplicant__c.
*/
    public static void afterInsert(List<CoApplicant__c> newCoApplicants) {
        calculateHouseholdIncome(newCoApplicants, null);
    }
    
    /**
* @desc:Handles after update trigger events for CoApplicant__c.
*/
    public static void afterDelete(List<CoApplicant__c> newCoApplicants, Map<Id, CoApplicant__c> oldCoApplicants) {
        calculateHouseholdIncome(newCoApplicants, oldCoApplicants);
    }
    
    /**
* @desc:Handles after update trigger events for CoApplicant__c.
*/
    public static void afterUpdate(List<CoApplicant__c> newCoApplicants, Map<Id, CoApplicant__c> oldCoApplicants) {
        calculateHouseholdIncome(newCoApplicants, null);
    }

/**
* Calculates household income for CoApplicants.
*/
    public static void calculateHouseholdIncome(List<CoApplicant__c> newCoApplicants, Map<Id, CoApplicant__c> oldCoApplicantsMap) {
        Set<Id> intakeIds = new Set<Id>();
        Set<Id> clientCaseIds = new Set<Id>();
        
        if (oldCoApplicantsMap == null) {
            for (CoApplicant__c coApplicant : newCoApplicants) {
                
                if (coApplicant.IntakeRequest__c != null) {
                    intakeIds.add(coApplicant.IntakeRequest__c);
                }
                if (coApplicant.ClientCase__c != null) {
                    clientCaseIds.add(coApplicant.ClientCase__c);
                }
            }
        }
        else
        {
            for (Id oldCoApplicantId : oldCoApplicantsMap.keySet()) {
                
                
                CoApplicant__c oldCoApplicant = oldCoApplicantsMap.get(oldCoApplicantId);
                
                if (oldCoApplicant.IntakeRequest__c != null) {
                    intakeIds.add(oldCoApplicant.IntakeRequest__c);
                }
                if (oldCoApplicant.ClientCase__c != null) {
                    clientCaseIds.add(oldCoApplicant.ClientCase__c);
                }
            }
        } 
        
        
        if (!intakeIds.isEmpty()) {
            List<CoApplicant__c> coApplicants = [
                SELECT Id, IntakeRequest__c, Contact__r.TotalMonthlyIncome__c 
                FROM CoApplicant__c 
                WHERE IntakeRequest__c IN :intakeIds
            ];
            
            Map<Id, Decimal> intakeToCoApplicantIncomeMap = new Map<Id, Decimal>();
            for (CoApplicant__c coApplicant : coApplicants) {
                if (coApplicant.IntakeRequest__c != null && coApplicant.Contact__r.TotalMonthlyIncome__c != null) {
                    if (!intakeToCoApplicantIncomeMap.containsKey(coApplicant.IntakeRequest__c)) {
                        intakeToCoApplicantIncomeMap.put(coApplicant.IntakeRequest__c, 0);
                    }
                    intakeToCoApplicantIncomeMap.put(coApplicant.IntakeRequest__c, 
                                                     intakeToCoApplicantIncomeMap.get(coApplicant.IntakeRequest__c) + coApplicant.Contact__r.TotalMonthlyIncome__c );
                } else {
                    System.debug('CoApplicant or Monthly Income is null for Id @%@: ' + coApplicant.Id);
                }
            }
            
            
            List<Intake__c> intakes = [
                SELECT Id, MonthlyIncome__c, HouseholdMonthlyIncome__c , primaryClient__r.TotalMonthlyIncome__c, ChoseNottoProvideIncome__c
                FROM Intake__c 
                WHERE Id IN :intakeIds
            ];
            
            List<Intake__c> intakesToUpdate = new List<Intake__c>();
            for (Intake__c intake : intakes) {
                Decimal totalIncome = 0;
                if(!intake.ChoseNottoProvideIncome__c){
                    if (intake.MonthlyIncome__c != null) {
                        totalIncome += intake.MonthlyIncome__c;
                    }
                    
                    if (intakeToCoApplicantIncomeMap.containsKey(intake.Id)) {
                        totalIncome += intakeToCoApplicantIncomeMap.get(intake.Id);
                    }
                }                
                intake.HouseholdMonthlyIncome__c = (totalIncome > 0 ? totalIncome : null);
                intakesToUpdate.add(intake);
            }
            if (!intakesToUpdate.isEmpty()) {
                update intakesToUpdate;
            }
        }
        
        if (!clientCaseIds.isEmpty()) {
            List<CoApplicant__c> coApplicants = [
                SELECT Id, IntakeRequest__c, ClientCase__c, Contact__r.TotalMonthlyIncome__c  
                FROM CoApplicant__c 
                WHERE ClientCase__c IN :clientCaseIds
            ];
            System.debug('coApplicants. @%@ '+coApplicants);
            Map<Id, Decimal> clientCaseToCoApplicantIncomeMap = new Map<Id, Decimal>();
            
            for (CoApplicant__c coApplicant : coApplicants) {
                if (coApplicant.ClientCase__c != null && coApplicant.Contact__r.TotalMonthlyIncome__c != null) {
                    if (!clientCaseToCoApplicantIncomeMap.containsKey(coApplicant.ClientCase__c)) {
                        clientCaseToCoApplicantIncomeMap.put(coApplicant.ClientCase__c, 0);
                    }
                    clientCaseToCoApplicantIncomeMap.put(coApplicant.ClientCase__c, 
                                                         clientCaseToCoApplicantIncomeMap.get(coApplicant.ClientCase__c) + coApplicant.Contact__r.TotalMonthlyIncome__c );
                } else {
                    System.debug('CoApplicant or Monthly Income is null for Id: ' + coApplicant.Id);
                }
            }
            System.debug('clientCaseToCoApplicantIncomeMap @%@ '+clientCaseToCoApplicantIncomeMap);

            List<ClientCase__c> CCToUpdate = [
                SELECT Id, AnnualHouseholdIncome__c, MonthlyIncome__c,HouseholdMonthlyIncome1__c, HouseholdSize__c, County__c, Town__c, PrimaryClient__r.TotalMonthlyIncome__c, ChoseNottoProvideIncome__c
                FROM ClientCase__c
                WHERE Id IN :clientCaseIds
            ];
            
            List<ClientCase__c> clientCasesToUpdate = new List<ClientCase__c>();
            for (ClientCase__c cc : CCToUpdate) {
                Decimal totalIncome = 0;
                if(!cc.ChoseNottoProvideIncome__c){
                    if (cc.MonthlyIncome__c != null) {
                        totalIncome += cc.MonthlyIncome__c;
                    }
                    
                    if (clientCaseToCoApplicantIncomeMap.containsKey(cc.Id)) {
                        totalIncome += clientCaseToCoApplicantIncomeMap.get(cc.Id);
                    }
                }
                cc.HouseholdMonthlyIncome1__c = (totalIncome > 0 ? totalIncome : null);
                clientCasesToUpdate.add(cc);
            }
            
            if (!clientCasesToUpdate.isEmpty()) {
                update clientCasesToUpdate;
            }
        }
    }
}