objects/ClientAsset__c.object
<CustomObject>
    <description>To track assets owned by clients.</description>
    <fields>
        <fullName>AccountBalance__c</fullName>
        <label>Account Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CashDeposit__c</fullName>
        <label>Cash Deposit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CashValue__c</fullName>
        <label>Cash Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Client Assets</relationshipLabel>
        <relationshipName>Client_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PresentMarketValue__c</fullName>
        <label>Present Market Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Client Asset</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/FinancialSnapshot__c.object
<CustomObject>
    <description>To store a detailed snapshot of a client&apos;s financial status, including current values and goals.</description>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Financial Snapshots</relationshipLabel>
        <relationshipName>FinancialSnapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NetMonthlyIncome__c</fullName>
        <label>Net Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Snapshot</label>
    <nameField>
        <label>Financial Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Income__c.object
<CustomObject>
    <description>To capture various sources of income for client cases. It tracks details such as income type (e.g., alimony, bonuses, child support, commissions), amounts (gross and net), and employment status.</description>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Income</relationshipLabel>
        <relationshipName>Income</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MonthlyGrossIncome__c</fullName>
        <label>Monthly Gross Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MonthlyNetIncome__c</fullName>
        <label>Monthly Net Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Income</label>
    <nameField>
        <label>Income Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Income</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Liability__c.object
<CustomObject>
    <description>To track financial liabilities associated with client cases.</description>
    <fields>
        <fullName>AccountBalance__c</fullName>
        <label>Account Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Liabilities</relationshipLabel>
        <relationshipName>Liabilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MinimumMonthlyPayment__c</fullName>
        <label>Minimum Monthly Payment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Liability</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Liability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateFinancialSnapshotsControllerTest.cls
@istest
public class CreateFinancialSnapshotsControllerTest {
    
    @testSetup 
    static void testSetup() {
        ClientCase__c cc = TestDataFactory.createClientCases(1,true)[0];
        ClientAsset__c ca = new ClientAsset__c(AccountBalance__c=1000, CashDeposit__c=200, PresentMarketValue__c =1100, Value__c=800,CashValue__c=900,ClientCase__c=cc.Id);
        insert ca;
        Liability__c l = new Liability__c(AccountBalance__c=1000, MinimumMonthlyPayment__c=700,ClientCase__c=cc.Id);
        insert l;
        Income__c i = new Income__c(MonthlyGrossIncome__c=10000, MonthlyNetIncome__c=800,ClientCase__c=cc.Id);
        insert i;
        FinancialSnapshot__c fss = new FinancialSnapshot__c(ClientCase__c=cc.Id);
        insert fss;
    }
    
    static testMethod void testcreateFinancialSnapshot(){
        Test.startTest();
        String s = CreateFinancialSnapshotsController.createFinancialSnapshot(new FinancialSnapshot__c(NetMonthlyIncome__c=1000));
        System.assertEquals('success',s);
        
        String s1 = CreateFinancialSnapshotsController.createFinancialSnapshot(null);
        System.assertEquals(null,s1);
        Test.StopTest();
    }
    
    static testMethod void testFetchFinancialSnapshots(){
        ClientCase__c cc = [select id from ClientCase__c];
        Test.startTest();
        CreateFinancialSnapshotsController.FinancialSnapshotDetailsWrapper output = CreateFinancialSnapshotsController.fetchFinancialSnapshots(cc.Id);
		CreateFinancialSnapshotsController.FinancialSnapshotDetailsWrapper output1 = CreateFinancialSnapshotsController.fetchFinancialSnapshots(null);
        System.assertEquals(null,output1.financialSnapshotRecords);
        Test.StopTest();
    }
    
    static testMethod void testGetFinacialMetricsDetails(){
        ClientCase__c cc = [select id from ClientCase__c];
        Test.startTest();
        CreateFinancialSnapshotsController.FinancialMetricsDetailWrapper output = CreateFinancialSnapshotsController.getFinacialMetricsDetails(cc.Id);
        System.assertEquals(cc,output.goal);
       
        Test.StopTest();
    }
    
}