objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>Outcome__c</fullName>
        <description>HUD-specified outcomes for Education only</description>
        <inlineHelpText>HUD-specified outcomes</inlineHelpText>
        <label>Outcome</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed financial literacy workshop, including home affordability, budgeting and understanding use of credit</fullName>
                </value>
                <value>
                    <fullName>Completed predatory lending, loan scam or other fraud prevention workshop</fullName>
                </value>
                <value>
                    <fullName>Completed fair housing workshop</fullName>
                </value>
                <value>
                    <fullName>Completed homelessness prevention workshop</fullName>
                </value>
                <value>
                    <fullName>Completed rental workshop</fullName>
                </value>
                <value>
                    <fullName>Completed pre-purchase homebuyer education workshop</fullName>
                </value>
                <value>
                    <fullName>Completed non-delinquency post-purchase workshop, including home maintenance and/or financial management for homeowners</fullName>
                </value>
                <value>
                    <fullName>Completed resolving or preventing mortgage delinquency workshop</fullName>
                </value>
                <value>
                    <fullName>Completed other workshop</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <description>Agency to custom relevant purposes</description>
        <inlineHelpText>Choose one most applicable value from the drop-down list</inlineHelpText>
        <label>HUD Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Homeless Assistance</fullName>
                </value>
                <value>
                    <fullName>Pre-purchase/Homebuying</fullName>
                </value>
                <value>
                    <fullName>Rental Topics</fullName>
                </value>
                <value>
                    <fullName>Non-Delinquency Post-Purchase</fullName>
                </value>
                <value>
                    <fullName>Reverse Mortgage</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Forward Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Reverse Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Disaster Preparedness Assistance</fullName>
                </value>
                <value>
                    <fullName>Disaster Recovery Assistance</fullName>
                </value>
                <value>
                    <fullName>Not HUD-Reportable</fullName>
                </value>
                <value>
                    <fullName>Financial Literacy</fullName>
                    <isActive>false</isActive>
                    <label>Financial Literacy</label>
                </value>
                <value>
                    <fullName>Home Improvement Loan</fullName>
                    <isActive>false</isActive>
                    <label>Home Improvement Loan</label>
                </value>
                <value>
                    <fullName>Home Purchase Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Home Purchase Inquiry</label>
                </value>
                <value>
                    <fullName>Job Training</fullName>
                    <isActive>false</isActive>
                    <label>Job Training</label>
                </value>
                <value>
                    <fullName>Mortgage Delinquency Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Mortgage Delinquency Inquiry</label>
                </value>
                <value>
                    <fullName>Rehab Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Rehab Inquiry</label>
                </value>
                <value>
                    <fullName>Rental Assistance</fullName>
                    <isActive>false</isActive>
                    <label>Rental Assistance</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Solution__c.object
<CustomObject>
    <description>To store solutions identified in action plans, detailing strategies and actions to overcome obstacles and achieve goals.</description>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Solution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Calendar Event Information</relationshipLabel>
        <relationshipName>SUMOAdditionalInfo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HUDActivityType__c</fullName>
        <label>HUD Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>HUDActivityType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>sumoapp__EventName__c</fullName>
        <label>Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__SumoId__c</fullName>
        <externalId>true</externalId>
        <label>Sumo Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__Attendee__c.object
<CustomObject>
    <fields>
        <fullName>HUDActivityType__c</fullName>
        <formula>TEXT( sumoapp__SumoEvent__r.HUDActivityType__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>HUD Activity Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <formula>TEXT( sumoapp__SumoEvent__r.HUD_Purpose__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outcome</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__EventName__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__EventName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__StartDatetime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__SumoEvent__c</fullName>
        <label>SUMO Event</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SUMO Attendee</label>
    <nameField>
        <displayFormat>ATD-{000000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/HUDActivityType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Not Billed to HUD</fullName>
        <default>true</default>
        <label>Not Billed to HUD</label>
    </customValue>
    <customValue>
        <fullName>NOFA 2014-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2014-2 TRNG</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2015-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2015-2 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2016-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2017-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2018-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2019-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2020-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2021-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2022-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2023-1 COMP</fullName>
    </customValue>
    <customValue>
        <fullName>HO INT</fullName>
    </customValue>
    <customValue>
        <fullName>NOFA 2024-1 COMP</fullName>
    </customValue>
    <masterLabel>HUD Activity Type</masterLabel>
</GlobalValueSet>

classes/ActivityTimelineServiceTest.cls
@IsTest
public class ActivityTimelineServiceTest {
    
    
    @testSetup static void setup() {
        Account acc = TestDataFactory.createAccounts(1, true)[0];
        Contact con = TestDataFactory.createContacts(acc.id,2, true)[0];
        
        sumoapp__AdditionalInfo__c AdditionalInfo = TestDataFactory.createSumoEvent( 1, true)[0];
        TestDataFactory.createEvent(con, NULL, 1, true);
        TestDataFactory.createAttendee(con,AdditionalInfo.id, 1, true);
        List<ClientCase__c> clientCaseList = TestDataFactory.createClientCases(1, true);
        //TestDataFactory.createCounselorNote(con, clientCaseList[0], 1, true);
        
    }
    
    private class TestActivityTimelineService extends ActivityTimelineService {
        
        public override List<ActivityWrapper> getAppointments(Id recordId) {
            List<ActivityWrapper> appointments = new List<ActivityWrapper>();
            Event evt = [SELECT Id, WhoId, WhatId, Location, Subject, IsAllDayEvent, EndDateTime, OwnerId, IsGroupEvent, SystemModstamp, RecurrenceTimeZoneSidKey, RecurrenceDayOfMonth, Recurrence2PatternText, sumoapp__AdditionalInfo__c,
                         sumoapp__SumoId__c, sumoapp__StartDateTimeTimezone__c, AppointmentStatus__c, sumoapp__WhoIdIsNotArrived__c, sumoapp__OrganizerFullName__c, StartDateTime, AppointmentDuration__c, sumoapp__AdditionalInfo__r.Notes__c,
                         sumoapp__OrganizerTitle__c, Outcome__c, HUDActivityType__c, Purpose__c, Solution__c, ActionType__c, IsRecurrence2 FROM Event Limit 1];
            appointments.add(convertEventToWrapper(evt, null,null));
            return appointments;
        }
        
        public override List<ActivityWrapper> getCourses(Id recordId) {
            List<ActivityWrapper> courses = new List<ActivityWrapper>();
            sumoapp__Attendee__c attendee = [SELECT id, sumoapp__SumoEvent__c, sumoapp__EventName__c, sumoapp__StartDatetime__c, sumoapp__SumoEvent__r.RecordType.DeveloperName  FROM sumoapp__Attendee__c Limit 1];
            courses.add(convertCourseToWrapper(attendee));
            return courses;
        }
        
        public override List<ActivityWrapper> getCounselorNotes(Id recordId) {
            List<ActivityWrapper> notes = new List<ActivityWrapper>();
            ClientCase__c cc= [Select id, Name from ClientCase__c limit 1];
            Contact con = [Select Id From Contact LIMIT 1];
            notes.add(convertNoteToWrapper(TestDataFactory.createCounselorNote(con, cc, 1, false).get(0)));
            return notes;
        }
    } 
    
    @IsTest
    static void testGetAllEvents() {
        TestActivityTimelineService service = new TestActivityTimelineService();
        Id recordId = [SELECT id FROM Contact Limit 1].id;
        List<ActivityTimelineService.ResultWrapper> results = service.getAllEvents(recordId);
    }
}