objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>CounselingTermination__c</fullName>
        <label>Counseling Termination</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ongoing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Dropped Out</fullName>
                </value>
                <value>
                    <fullName>Referred</fullName>
                </value>
                <value>
                    <fullName>No Further Contact</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Calendar Event Information</relationshipLabel>
        <relationshipName>SUMOAdditionalInfo</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContactTimelineServiceTest.cls
@isTest
public class ContactTimelineServiceTest {
    
    @testSetup
    static void setupTestData() {
        
        List<ClientCase__c> clientCase = TestDataFactory.createClientCases(1, false);
        clientCase[0].CounselingTermination__c = 'Completed';
        insert clientCase;
        
        Account acc = TestDataFactory.createAccounts(1, true)[0];
        Contact con = TestDataFactory.createContacts(acc.id, 1, true)[0];
        
        
        sumoapp__AdditionalInfo__c sumoEvent = TestDataFactory.createSumoEvent(1, true)[0];
        TestDataFactory.createAttendee(con, sumoEvent.id, 1, true);
        //TestDataFactory.createCounselorNote(con, clientCase, 1, true);
        
        List<Event> evt = TestDataFactory.createEvent(con, sumoEvent.id, 1, true);
        
        EventRelation er = new EventRelation(EventId = evt[0].Id, RelationId = con.Id);
        //insert er;
        
    }

    @isTest
    static void testGetAppointments() {
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        ContactTimelineService service = new ContactTimelineService();

        Test.startTest();
        service.getAppointments(testContact.Id);
        Test.stopTest();
    }

    @isTest
    static void testGetCourses() {
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        ContactTimelineService service = new ContactTimelineService();

        Test.startTest();
        service.getCourses(testContact.Id);
        Test.stopTest();
    }

    @isTest
    static void testGetCounselorNotes() {
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        ContactTimelineService service = new ContactTimelineService();

        Test.startTest();
        service.getCounselorNotes(testContact.Id);
        Test.stopTest();
    }
}