objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>ClientCaseStatus__c</fullName>
        <defaultValue>(&quot;In Progress&quot;)</defaultValue>
        <description>In Progress: Open Case that is in progress and HUD reportable

Closed - Incomplete: Case closed without meeting the original outcome, HUD reportable

Closed - Service Complete: Case closed with meeting the original outcome, HUD reportable

On Hold: Case temporarily paused due to external factors or client request</description>
        <inlineHelpText>[1] In Progress: Case pending

[2] Closed - Incomplete: Didn’t meet original outcome

[3] Closed - Complete: Met the outcome

[4] On Hold: Case temporarily paused</inlineHelpText>
        <label>Client Case Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Closed - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Closed - Complete</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                    <isActive>false</isActive>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <isActive>false</isActive>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <isActive>false</isActive>
                    <label>Prospect</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>HUD-Defined Number in Household</description>
        <inlineHelpText>Total number of people living in the same household as the primary client</inlineHelpText>
        <label>Household Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MonthlyIncome__c</fullName>
        <label>Total Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Grant__c.object
<CustomObject>
    <fields>
        <fullName>ClientCase__c</fullName>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Grants</relationshipLabel>
        <relationshipName>Grants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FundingAmount__c</fullName>
        <label>Funding Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Grantor__c</fullName>
        <label>Grantor</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusType__c</fullName>
        <label>Status Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant</label>
    <nameField>
        <displayFormat>G- {YYYY}/{MM} - {0000}</displayFormat>
        <label>Grant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/HUDAMIData__c.object
<CustomObject>
    <description>To store data related to Area Median Income (AMI) for various regions, including details such as area names, county names, FIPS codes, and HUD-specific identifiers for HUD AMI calculations.</description>
    <fields>
        <fullName>Areaname__c</fullName>
        <description>HUD Income Limit Area Name</description>
        <label>Area name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CountyName__c</fullName>
        <description>HUD Income Limit - Official County Name</description>
        <label>County Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MedianFamilyIncome__c</fullName>
        <description>Median Family Income (MFI) for area</description>
        <label>Median Family Income</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StateCode__c</fullName>
        <label>State code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StateName__c</fullName>
        <description>Name of US State or Territory Client Case is taking place in</description>
        <label>State Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TownName__c</fullName>
        <description>Town Name for Income Limit purposes</description>
        <label>Town Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zipcode__c</fullName>
        <label>Zipcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p1__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 1 Persons in Household</description>
        <label>il30 p1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p2__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 2 Persons in Household</description>
        <label>il30 p2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p3__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 3 Persons in Household</description>
        <label>il30 p3</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p4__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 4 Persons in Household</description>
        <label>il30 p4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p1__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 1 Persons in Household</description>
        <label>il50 p1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p2__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 2 Persons in Household</description>
        <label>il50 p2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p3__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 3 Persons in Household</description>
        <label>il50 p3</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p4__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 4 Persons in Household</description>
        <label>il50 p4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p1__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 1 Persons in Household</description>
        <label>il80 p1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p2__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 2 Persons in Household</description>
        <label>il80 p2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p3__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 3 Persons in Household</description>
        <label>il80 p3</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p4__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 4 Persons in Household</description>
        <label>il80 p4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il_metro_name__c</fullName>
        <label>Metro Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>HUD AMI Data</label>
    <nameField>
        <label>HUD AMI Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HUD AMI Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GrantTriggerHandlerTest.cls
@isTest
public class GrantTriggerHandlerTest {
        
    public static User createAdminUserWithAllPermission() {
        
        Profile adminProfile = [Select id from Profile where name = 'System Administrator' limit 1];
        UserRole ur = new UserRole(Name = 'Admin');
        insert ur;
        
        User adminUser = TestDataFactory.createUsers(adminProfile.Id,ur.Id, 1, true)[0];
        
        PermissionSet ps = [SELECT Id, Name FROM PermissionSet WHERE Name = 'SUMOPlatformAdmin' LIMIT 1];
        PermissionSet ps1 = [SELECT Id, Name FROM PermissionSet WHERE Name = 'NWCompassHUDReportingPermissions' LIMIT 1];
        PermissionSet ps2 = [SELECT Id, Name FROM PermissionSet WHERE Name = 'NWCompassQuarterlyReportingPermissions' LIMIT 1];
        PermissionSet ps3 = [SELECT Id, Name FROM PermissionSet WHERE Name = 'NWCompassSystemAdminPermissions' LIMIT 1];
        PermissionSet ps4 = [SELECT Id, Name FROM PermissionSet WHERE Name = 'NWCompassStandardPermissions' LIMIT 1];
        
        List<PermissionSetAssignment> psaList = new List<PermissionSetAssignment>();
        
        PermissionSetAssignment psa = new PermissionSetAssignment(AssigneeId = adminUser.Id, PermissionSetId = ps.Id);
        PermissionSetAssignment psa1 = new PermissionSetAssignment(AssigneeId = adminUser.Id, PermissionSetId = ps1.Id);
        PermissionSetAssignment psa2 = new PermissionSetAssignment(AssigneeId = adminUser.Id, PermissionSetId = ps2.Id);
        PermissionSetAssignment psa3 = new PermissionSetAssignment(AssigneeId = adminUser.Id, PermissionSetId = ps3.Id);
        PermissionSetAssignment psa4 = new PermissionSetAssignment(AssigneeId = adminUser.Id, PermissionSetId = ps4.Id);
        
        psaList.add(psa);
        psaList.add(psa1);
        psaList.add(psa2);
        psaList.add(psa3);
        psaList.add(psa4);
        insert psaList;
        
        return adminUser;
    }
    
    @testSetup
    static void setup() {
        User adminUser = createAdminUserWithAllPermission();
        System.runAs(adminUser){
            List<HUDAMIData__c> hudamiDataList = TestDataFactory.createHUDAMIDataRecords(3, false);
            // Modify all values for each record
            hudamiDataList[0] = new HUDAMIData__c(
                CountyName__c = 'SampleCounty',
                TownName__c = 'SampleTown',
                Zipcode__c = '12345',
                StateCode__c = 'SC',
                StateName__c = 'SampleState',
                MedianFamilyIncome__c = '60000',
                il_metro_name__c = 'SampleMetro',
                Areaname__c = 'SampleArea',
                il30p1__c = '20000',
                il30p2__c = '25000',
                il30p3__c = '30000',
                il50p1__c = '40000',
                il50p2__c = '45000',
                il50p3__c = '50000',
                il80p1__c = '60000',
                il80p2__c = '65000',
                il80p3__c = '70000',
                il30p4__c = '50000',
                il50p4__c = '60000',
                il80p4__c = '70000'
            );
            
            hudamiDataList[1] = new HUDAMIData__c(
                CountyName__c = 'SampleCounty',
                TownName__c = 'SampleTown',
                Zipcode__c = '54321',
                StateCode__c = 'SC',
                StateName__c = 'SampleState',
                MedianFamilyIncome__c = '60000',
                il_metro_name__c = 'SampleMetro',
                Areaname__c = 'SampleArea',
                il30p1__c = '20000',
                il30p2__c = '25000',
                il30p3__c = '30000',
                il50p1__c = '40000',
                il50p2__c = '45000',
                il50p3__c = '50000',
                il80p1__c = '60000',
                il80p2__c = '65000',
                il80p3__c = '70000',
                il30p4__c = '50000',
                il50p4__c = '60000',
                il80p4__c = '70000'
            );
            
            hudamiDataList[2] = new HUDAMIData__c(
                CountyName__c = 'Sample1County',
                TownName__c = 'Sample1Town',
                Zipcode__c = '54321',
                StateCode__c = 'SC',
                StateName__c = 'SampleState',
                MedianFamilyIncome__c = '60000',
                il_metro_name__c = 'SampleMetro',
                Areaname__c = 'SampleArea',
                il30p1__c = '20000',
                il30p2__c = '25000',
                il30p3__c = '30000',
                il50p1__c = '40000',
                il50p2__c = '45000',
                il50p3__c = '50000',
                il80p1__c = '60000',
                il80p2__c = '65000',
                il80p3__c = '70000',
                il30p4__c = '50000',
                il50p4__c = '60000',
                il80p4__c = '70000'
            );
            
            // Insert the records
            insert hudamiDataList;        
        }
    }
    
    @isTest
    static void testBeforeInsert() {
        User adminUser = [Select id, IsActive from User where userName = 'utst@test.com1' limit 1];
        System.runAs(adminUser){
            // Create a new ClientCase__c record
            List<HUDAMIData__c> hudamiDataList = [SELECT Id, CountyName__c, TownName__c, Zipcode__c, MedianFamilyIncome__c , il30p1__c, il30p2__c FROM HUDAMIData__c];
            List<ClientCase__c> cases = TestDataFactory.createClientCases(1, false);
            cases[0].Town__c = 'SampleTown';
            cases[0].County__c = 'SampleCounty';
            cases[0].Address__PostalCode__s = '54321';
            cases[0].MonthlyIncome__c = 1000;
            cases[0].HouseholdSize__c = 9;
            cases[0].ClientCaseStatus__c = 'In Progress';
            
            Test.startTest();
            insert cases;
            Grant__c grant = new Grant__c();
            grant.ClientCase__c = cases[0].Id;
            grant.Grantor__c = 'Sample Grantor';
            grant.FundingAmount__c = 1264;
            grant.StatusType__c = 'Approved';
            insert grant;
            
            grant = new Grant__c();
            grant.ClientCase__c = cases[0].Id;
            grant.Grantor__c = 'Sample Grantor';
            grant.FundingAmount__c = 4444;
            grant.StatusType__c = 'Approved';
            insert grant;
            Test.stopTest();
        }
    }
}