objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>Outcome__c</fullName>
        <description>HUD-specified outcomes for Education only</description>
        <inlineHelpText>HUD-specified outcomes</inlineHelpText>
        <label>Outcome</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed financial literacy workshop, including home affordability, budgeting and understanding use of credit</fullName>
                </value>
                <value>
                    <fullName>Completed predatory lending, loan scam or other fraud prevention workshop</fullName>
                </value>
                <value>
                    <fullName>Completed fair housing workshop</fullName>
                </value>
                <value>
                    <fullName>Completed homelessness prevention workshop</fullName>
                </value>
                <value>
                    <fullName>Completed rental workshop</fullName>
                </value>
                <value>
                    <fullName>Completed pre-purchase homebuyer education workshop</fullName>
                </value>
                <value>
                    <fullName>Completed non-delinquency post-purchase workshop, including home maintenance and/or financial management for homeowners</fullName>
                </value>
                <value>
                    <fullName>Completed resolving or preventing mortgage delinquency workshop</fullName>
                </value>
                <value>
                    <fullName>Completed other workshop</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <description>Agency to custom relevant purposes</description>
        <inlineHelpText>Choose one most applicable value from the drop-down list</inlineHelpText>
        <label>HUD Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Homeless Assistance</fullName>
                </value>
                <value>
                    <fullName>Pre-purchase/Homebuying</fullName>
                </value>
                <value>
                    <fullName>Rental Topics</fullName>
                </value>
                <value>
                    <fullName>Non-Delinquency Post-Purchase</fullName>
                </value>
                <value>
                    <fullName>Reverse Mortgage</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Forward Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Reverse Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Disaster Preparedness Assistance</fullName>
                </value>
                <value>
                    <fullName>Disaster Recovery Assistance</fullName>
                </value>
                <value>
                    <fullName>Not HUD-Reportable</fullName>
                </value>
                <value>
                    <fullName>Financial Literacy</fullName>
                    <isActive>false</isActive>
                    <label>Financial Literacy</label>
                </value>
                <value>
                    <fullName>Home Improvement Loan</fullName>
                    <isActive>false</isActive>
                    <label>Home Improvement Loan</label>
                </value>
                <value>
                    <fullName>Home Purchase Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Home Purchase Inquiry</label>
                </value>
                <value>
                    <fullName>Job Training</fullName>
                    <isActive>false</isActive>
                    <label>Job Training</label>
                </value>
                <value>
                    <fullName>Mortgage Delinquency Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Mortgage Delinquency Inquiry</label>
                </value>
                <value>
                    <fullName>Rehab Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Rehab Inquiry</label>
                </value>
                <value>
                    <fullName>Rental Assistance</fullName>
                    <isActive>false</isActive>
                    <label>Rental Assistance</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Calendar Event Information</relationshipLabel>
        <relationshipName>SUMOAdditionalInfo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>sumoapp__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>sumoapp__Service__c</referenceTo>
        <relationshipLabel>Service Infos</relationshipLabel>
        <relationshipName>ServiceInfos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <formula>TEXT( sumoapp__SumoEvent__r.HUD_Purpose__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outcome</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__StartDatetime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <label>SUMO Attendee</label>
    <nameField>
        <displayFormat>ATD-{000000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/sumoapp__Service__c.object
<CustomObject>
    <label>SUMO Service/Skill</label>
    <nameField>
        <label>Service/Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SUMO Services/Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ActivityTimelineControllerTest.cls
@isTest
public class ActivityTimelineControllerTest {
    
    @testSetup static void setup() {
        
        Account acc = TestDataFactory.createAccounts(1, true)[0];
        List<Contact> testContacts = TestDataFactory.createContacts(acc.id,2, true);
        
        Contact con = testContacts[0];
        con.LastName = 'Test';
        update con;
        Contact con2 = testContacts[1];
        
        Id recordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Event' AND SobjectType = 'sumoapp__AdditionalInfo__c' LIMIT 1]?.Id;
        sumoapp__AdditionalInfo__c info = TestDataFactory.createSumoEvent(1 , false)[0];
        info.sumoapp__StartDatetime__c = System.now().addMinutes(-30);
        info.RecordTypeId = recordTypeId;
        insert info;
        
        sumoapp__Attendee__c attendee = TestDataFactory.createAttendee(con, info.id, 1,  true)[0]; 
        sumoapp__Service__c service = new sumoapp__Service__c();
        service.Name = 'Appointment';
        insert service;
        
        sumoapp__AdditionalInfo__c info1 = TestDataFactory.createSumoEvent(1, false)[0];
        info1.RecordTypeId = recordTypeId;
        info1.sumoapp__Service__c = service.Id;
        insert info1;
        
        List<ClientCase__c> clientCaseList = TestDataFactory.createClientCases(1, true);
        
        Event evt = TestDataFactory.createEvent(con, NULL, 1, FALSE)[0];
        evt.sumoapp__AdditionalInfo__c = info.Id;
        insert evt;
        
        Event evt1 = TestDataFactory.createEvent(con, NULL, 1, FALSE)[0];
        evt1.sumoapp__AdditionalInfo__c = info.Id;
        insert evt1;
        
        Event evt2 = TestDataFactory.createEvent(con, NULL, 1, FALSE)[0];
        evt2.sumoapp__AdditionalInfo__c = info.Id;
        insert evt2;
        
        List<ClientCase__c> cases = TestDataFactory.createClientCases(1, true);
        //TestDataFactory.createCounselorNote(cases.get(0).Id, con.Id, 3, true);
        
        EventRelation er = new EventRelation();
        er.RelationId = con2.Id;
        er.EventId = evt.Id;
        insert er;
    }
    
    @isTest static void testGetEvents() {
        Contact con = [SELECT Id FROM Contact WHERE LastName = 'Test' LIMIT 1];
        List<ActivityTimelineService.ResultWrapper> result = ActivityTimelineController.getEvents(con.Id);
        System.assertNotEquals(null, result, 'Result should not be null');
        System.assertNotEquals(0, result.size(), 'Result list should not be empty');
    }
    
    @isTest static void testGetEventsSecond() {
        ClientCase__c clientCase = [SELECT Id FROM ClientCase__c LIMIT 1];
        List<ActivityTimelineService.ResultWrapper> result = ActivityTimelineController.getEvents(clientCase.Id);
        System.assertNotEquals(null, result, 'Result should not be null');
        // Add assertions based on expected results
    }
    
    @isTest static void testGetParticipants() {
        Id eventId = [SELECT EventId FROM EventRelation LIMIT 1]?.EventId;
        List<String> participants = ActivityTimelineController.getParticipants(eventId);
        System.assertNotEquals(null, participants, 'Participants list should not be null');
        System.assertNotEquals(0, participants.size(), 'Participants list should not be empty');
    }
    
    @isTest static void testUpdateAppointmentNotes() {
        Event evt = [SELECT Id, sumoapp__AdditionalInfo__c FROM Event LIMIT 1];
        
        // Replace with an actual valid picklist value
        String validOutcome = 'Households that received one-on-one counseling that also received education services.'; // Make sure this value exists in your picklist
        
        ActivityTimelineController.updateAppointmentNotes(
            evt.Id, 
            'Households that received one-on-one counseling that also received education services.', 
            validOutcome, 
            'Rental Topics', 
            'Attended', 
            60, 
            'Test notes',
            'NOFA 2015-1 COMP'
        );
        
        Event updatedEvent = [SELECT Id, Outcome__c, purpose__c, AppointmentDuration__c, AppointmentStatus__c, sumoapp__AdditionalInfo__c FROM Event WHERE Id = :evt.Id];
        sumoapp__AdditionalInfo__c additionalInfo = [SELECT Id, Notes__c FROM sumoapp__AdditionalInfo__c WHERE Id = :updatedEvent.sumoapp__AdditionalInfo__c];
    }
    
    @isTest static void testGetEventWrapper() {
        Event evt = [SELECT Id, sumoapp__AdditionalInfo__c FROM Event LIMIT 1];
        ActivityTimelineService.ActivityWrapper wrapper = ActivityTimelineController.getEventWrapper(evt.Id);
        System.assertNotEquals(null, wrapper, 'Wrapper should not be null');
        // Add additional assertions based on the expected results
        System.assertNotEquals(0, wrapper.participants.size(), 'Participants list should not be empty');
    }
    
    @isTest static void testGetAppointmentRecordTypeId() {
        Id recordTypeId = ActivityTimelineController.getAppointmentRecordTypeId();
        System.assertNotEquals(null, recordTypeId, 'Record Type Id should not be null');
        System.assertEquals('Appointment', [SELECT Name FROM RecordType WHERE Id = :recordTypeId].Name, 'Record Type Name should be Appointment');
    }

    @IsTest
    static void verifyIsIntakeStaffUser() {
        Test.startTest();
        Boolean isIntakeStaffUser = ActivityTimelineController.isIntakeStaffUser();
        Test.stopTest();
    }
}