objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>PrimaryClient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Client Cases</relationshipLabel>
        <relationshipName>Client_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Intake__c.object
<CustomObject>
    <description>To capture and store initial information about clients/prospects during the intake process including New Intake, New Education Only, and New Emergency Triage.</description>
    <fields>
        <fullName>PrimaryClient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Intake_Only</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Intake</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EmailController.cls
public without sharing class EmailController {
 @AuraEnabled(cacheable=true)
 public static List<EmailMessage> getEmailRecords(Id recId)
 {
  return [SELECT Id, AttachmentIds, HasAttachment, Subject, FromAddress,TextBody, ToAddress, MessageDate,RelatedToID FROM
EmailMessage where RelatedToID= :recId
               ORDER BY MessageDate DESC];
}
    @AuraEnabled(cacheable=true)
    public static String getContactEmailAddress(Id parentId) {
        List<Contact> contactRecordList = [
            SELECT Email
            FROM Contact
            WHERE Id IN (SELECT PrimaryClient__c FROM ClientCase__c WHERE Id = :parentId)
            LIMIT 1
        ];
        return (contactRecordList.size() > 0)  ? contactRecordList[0].Email : null;
    }
   
     @AuraEnabled(cacheable=true)
    public static String getIntakeEmailAddress(Id parentId) {
        List<Contact> contactRecordList = [
			SELECT Email 
            from Contact
            WHERE Id IN (SELECT PrimaryClient__c FROM Intake__c WHERE Id = :parentId)
            LIMIT 1
        ];
        return  (contactRecordList.size() > 0) ? contactRecordList[0].Email  : null;
    }
}