objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <description>HUD-Defined Ethnicity</description>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IntakeDate__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Date the agency performed intake for the client.</description>
        <label>Intake Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <description>Agency to custom relevant purposes</description>
        <inlineHelpText>Choose one most applicable value from the drop-down list</inlineHelpText>
        <label>HUD Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Homeless Assistance</fullName>
                </value>
                <value>
                    <fullName>Pre-purchase/Homebuying</fullName>
                </value>
                <value>
                    <fullName>Rental Topics</fullName>
                </value>
                <value>
                    <fullName>Non-Delinquency Post-Purchase</fullName>
                </value>
                <value>
                    <fullName>Reverse Mortgage</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Forward Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Reverse Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Disaster Preparedness Assistance</fullName>
                </value>
                <value>
                    <fullName>Disaster Recovery Assistance</fullName>
                </value>
                <value>
                    <fullName>Not HUD-Reportable</fullName>
                </value>
                <value>
                    <fullName>Financial Literacy</fullName>
                    <isActive>false</isActive>
                    <label>Financial Literacy</label>
                </value>
                <value>
                    <fullName>Home Improvement Loan</fullName>
                    <isActive>false</isActive>
                    <label>Home Improvement Loan</label>
                </value>
                <value>
                    <fullName>Home Purchase Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Home Purchase Inquiry</label>
                </value>
                <value>
                    <fullName>Job Training</fullName>
                    <isActive>false</isActive>
                    <label>Job Training</label>
                </value>
                <value>
                    <fullName>Mortgage Delinquency Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Mortgage Delinquency Inquiry</label>
                </value>
                <value>
                    <fullName>Rehab Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Rehab Inquiry</label>
                </value>
                <value>
                    <fullName>Rental Assistance</fullName>
                    <isActive>false</isActive>
                    <label>Rental Assistance</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <description>HUD-Defined Race</description>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <recordTypes>
        <fullName>FinancialCapabilityCounseling</fullName>
        <active>true</active>
        <label>Financial Capability Counseling</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <description>Client’s self-identified ethnicity, used in 9902 reporting</description>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <description>Which HUD 9902-recognized race category the contact belongs to.</description>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Intake__c.object
<CustomObject>
    <description>To capture and store initial information about clients/prospects during the intake process including New Intake, New Education Only, and New Emergency Triage.</description>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IntakeDate__c</fullName>
        <label>Intake Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <label>HUD Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Homeless Assistance</fullName>
                </value>
                <value>
                    <fullName>Pre-purchase/Homebuying</fullName>
                </value>
                <value>
                    <fullName>Rental Topics</fullName>
                </value>
                <value>
                    <fullName>Non-Delinquency Post-Purchase</fullName>
                </value>
                <value>
                    <fullName>Reverse Mortgage</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Forward Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Resolving or Preventing Reverse Mortgage Delinquency or Default</fullName>
                </value>
                <value>
                    <fullName>Disaster Preparedness Assistance</fullName>
                </value>
                <value>
                    <fullName>Disaster Recovery Assistance</fullName>
                </value>
                <value>
                    <fullName>Not HUD-Reportable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Intake</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Calendar Event Information</relationshipLabel>
        <relationshipName>SUMOAdditionalInfo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facilitator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facilitator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HUD_Purpose__c</fullName>
        <label>HUD Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completed financial literacy workshop, including home affordability, budgeting and understanding use of credit</fullName>
                </value>
                <value>
                    <fullName>Completed predatory lending, loan scam or other fraud prevention workshop</fullName>
                </value>
                <value>
                    <fullName>Completed fair housing workshop</fullName>
                </value>
                <value>
                    <fullName>Completed homelessness prevention workshop</fullName>
                </value>
                <value>
                    <fullName>Completed rental workshop</fullName>
                </value>
                <value>
                    <fullName>Completed pre-purchase homebuyer education workshop</fullName>
                </value>
                <value>
                    <fullName>Completed non-delinquency post-purchase workshop, including home maintenance and/or financial management for homeowners</fullName>
                </value>
                <value>
                    <fullName>Completed resolving or preventing mortgage delinquency workshop</fullName>
                </value>
                <value>
                    <fullName>Completed disaster preparedness assistance workshop</fullName>
                </value>
                <value>
                    <fullName>Completed disaster recovery assistance workshop</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sumoapp__EndDatetime__c</fullName>
        <label>End Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Attendance_Status__c</fullName>
        <label>Attendee Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Attended - Complete</fullName>
                </value>
                <value>
                    <fullName>Attended - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Course Complete</fullName>
                </value>
                <value>
                    <fullName>Course Incomplete</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExcludeAttendeeFromHUD9902__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude Attendee From HUD 9902</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>sumoapp__EndDatetime__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__EndDatetime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__StartDatetime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <label>SUMO Attendee</label>
    <nameField>
        <displayFormat>ATD-{000000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>CMSCounselorID__c</fullName>
        <description>Represents the unique identifier or code assigned to the counselor</description>
        <inlineHelpText>If this field is blank the user will not be reported to HUD as a counselor.</inlineHelpText>
        <label>CMS Counselor ID</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CounselorHUDID__c</fullName>
        <description>The unique identifier or code assigned to the counselor by HUD</description>
        <inlineHelpText>The 6-digit number found on the counselor&apos;s HUD certificate. If the counselor works for agency but does not conduct one-on-one counseling sessions, they may not have a HUD Counselor ID. Enter NA</inlineHelpText>
        <label>Counselor HUD ID</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmploymentEndDate__c</fullName>
        <description>The date on which the counselor&apos;s employment with the organization ends.</description>
        <inlineHelpText>Enter the date on which the counselor&apos;s employment with the organization ends</inlineHelpText>
        <label>Employment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EmploymentStartDate__c</fullName>
        <description>The date on which the counselor&apos;s employment with the organization began.</description>
        <inlineHelpText>Enter the date on which the counselor&apos;s employment with the organization began</inlineHelpText>
        <label>Employment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsCounselor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Counselor</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Ethnicity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Not Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Ethnicity</description>
    <masterLabel>Ethnicity</masterLabel>
</GlobalValueSet>

globalValueSets/Race.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>American Indian/Alaskan Native</fullName>
    </customValue>
    <customValue>
        <fullName>Asian</fullName>
    </customValue>
    <customValue>
        <fullName>Black or African American</fullName>
    </customValue>
    <customValue>
        <fullName>Native Hawaiian or Other Pacific Islander</fullName>
    </customValue>
    <customValue>
        <fullName>White</fullName>
    </customValue>
    <customValue>
        <fullName>More than one race</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Race</description>
    <masterLabel>Race</masterLabel>
</GlobalValueSet>

classes/HUD9902SummaryReportGenerateBatchTest.cls
@isTest
public class HUD9902SummaryReportGenerateBatchTest {    
    
    @testSetup
    static void setup() {
    
        List<User> adminUser = new List<User>();
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        adminUser = TestDataFactory.createUsers(adminProfile.Id,'', 1, false);
        adminUser[0].isActive = true;
        adminUser[0].IsCounselor__c = true;
        adminUser[0].CounselorHUDID__c = 'HUD451';
        adminUser[0].CMSCounselorID__c = '17775';
        adminUser[0].EmploymentEndDate__c = Date.today();
        adminUser[0].EmploymentStartDate__c = Date.today().addYears(-1);
        insert adminUser;
        PermissionSet ps = [SELECT Id, Name FROM PermissionSet WHERE Name = 'SUMOPlatformAdmin' LIMIT 1];
        PermissionSet ps1 = [SELECT Id, Name FROM PermissionSet WHERE Name = 'NWCompassHUDReportingPermissions' LIMIT 1];
        PermissionSet ps2 = [SELECT Id, Name FROM PermissionSet WHERE Name = 'NWCompassQuarterlyReportingPermissions' LIMIT 1];
        PermissionSet ps3 = [SELECT Id, Name FROM PermissionSet WHERE Name = 'NWCompassSystemAdminPermissions' LIMIT 1];
        PermissionSet ps4 = [SELECT Id, Name FROM PermissionSet WHERE Name = 'NWCompassStandardPermissions' LIMIT 1];
        //SELECT Id, PermissionSetId, AssigneeId, Assignee.Name FROM PermissionSetAssignment WHERE PermissionSetId =  '0PSHF0000007qyB4AQ'
        List<PermissionSetAssignment> psaList = new List<PermissionSetAssignment>();
        //insert psa;
        PermissionSetAssignment psa = new PermissionSetAssignment(AssigneeId = adminUser[0].Id, PermissionSetId = ps.Id);
        PermissionSetAssignment psa1 = new PermissionSetAssignment(AssigneeId = adminUser[0].Id, PermissionSetId = ps1.Id);
        PermissionSetAssignment psa2 = new PermissionSetAssignment(AssigneeId = adminUser[0].Id, PermissionSetId = ps2.Id);
        PermissionSetAssignment psa3 = new PermissionSetAssignment(AssigneeId = adminUser[0].Id, PermissionSetId = ps3.Id);
        PermissionSetAssignment psa4 = new PermissionSetAssignment(AssigneeId = adminUser[0].Id, PermissionSetId = ps4.Id);
        
        
        psaList.add(psa);
        psaList.add(psa1);
        psaList.add(psa2);
        psaList.add(psa3);
        psaList.add(psa4);
        insert psaList;
        
        RecordType fccRT = [SELECT Id FROM RecordType WHERE DeveloperName = 'FinancialCapabilityCounseling' AND SObjectType = :HUD9902Helper.CLIENT_CASE_OBJECT LIMIT 1];
        Id primaryClientRecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Contact' AND Name = 'Primary Client' LIMIT 1].Id;
        
        System.runAs(adminUser[0]) {
        TestDataFactory.createX9902(1, True);
        Account acc = TestDataFactory.createAccounts(1, True)[0];
        Contact con = TestDataFactory.createContacts(acc.Id, 1, false)[0];
        con.RecordTypeId = primaryClientRecordTypeId;
        insert con;
        
        List<sumoapp__AdditionalInfo__c> SumoEvents = TestDataFactory.createSumoEvent(5, false);
        for (sumoapp__AdditionalInfo__c AdditionalInfo: SumoEvents) {
            AdditionalInfo.RecordTypeId = Schema.SObjectType.sumoapp__AdditionalInfo__c.getRecordTypeInfosByName().get('Course').getRecordTypeId();
            AdditionalInfo.sumoapp__EndDatetime__c = DateTime.now().addDays(5);
            AdditionalInfo.Facilitator__c = adminUser[0].Id;
            AdditionalInfo.sumoapp__StartDatetime__c =  Date.Today();
            AdditionalInfo.HUD_Purpose__c = 'Completed rental workshop';
            
        }
        insert SumoEvents;
        
        sumoapp__Attendee__c Attendee = TestDataFactory.createAttendee(con, SumoEvents[0].Id, 1, false)[0];
        Attendee.Attendance_Status__c = 'Course Complete';
        Attendee.ExcludeAttendeeFromHUD9902__c = false;      
        insert Attendee;
        
        Intake__c Intake = TestDataFactory.createIntakes(con, acc.Id, 1, True)[0];
        
        List<ClientCase__c> clientCases = TestDataFactory.createClientCases(5, false);
        for (Integer i = 0; i < 5; i++) {
            clientCases[i].IntakeDate__c = Date.newInstance(2023, 1, 15).addDays(i);
            clientCases[i].RecordTypeId = fccRT.Id; 
        }
        insert clientCases;
        
        List<Event> events = TestDataFactory.createEvent(con, SumoEvents[0].Id, 5, False);
        
        integer i=0;
        for (sumoapp__AdditionalInfo__c course : SumoEvents) {
            events[i].sumoapp__AdditionalInfo__c = course.Id;
            events[i].WhatId = clientCases[i].id;
            events[i].Purpose__c = 'Rental Topics';
            events[i].ActivityDateTime = Date.today();
            events[i].StartDateTime = Date.today();
            events[i].EndDateTime = Date.today();
            events[i].DurationInMinutes = 0;
            events[i].AppointmentStatus__c = 'Attended';
            i++;            
        }
        insert events;
        }
    }
    
    @isTest
    static void testBatchExecution() {
        X9902__c x9902 = [SELECT Id FROM X9902__c LIMIT 1];
        HUD9902SummaryReportGenerateBatch batch = new HUD9902SummaryReportGenerateBatch(x9902.Id);
        Test.startTest();
        Database.executeBatch(batch);
        Contact con = [SELECT Id, Ethnicity__c, Race__C, AreaMedianIncome__c, RuralAreaStatus__c, EnglishProficiency__c FROM Contact LIMIT 1];
        con.Ethnicity__c = 'Hispanic';
        con.Race__C = 'American Indian/Alaskan Native';
        con.AreaMedianIncome__c = 'Below 30% of AMI';
        con.RuralAreaStatus__c = 'Lives in a rural area';
        con.EnglishProficiency__c = 'Limited English Proficient';
        update con;
        Database.executeBatch(batch);
        Test.stopTest();
        
    }

    static void testBatchExecution1() {
        X9902__c x9902 = [SELECT Id FROM X9902__c LIMIT 1];
        HUD9902SummaryReportGenerateBatch batch = new HUD9902SummaryReportGenerateBatch(x9902.Id);
        Test.startTest();
        Contact con = [SELECT Id, Ethnicity__c, Race__C, AreaMedianIncome__c, RuralAreaStatus__c, EnglishProficiency__c FROM Contact LIMIT 1];
        con.Ethnicity__c = 'Not Hispanic';
        con.RuralAreaStatus__c = 'Does not live in a rural area';
        con.Race__C = 'Black or African American';
        con.AreaMedianIncome__c = '50 - 79% of AMI';
        con.EnglishProficiency__c = 'Not Limited English Proficient';
        update con;
        Database.executeBatch(batch);
        Test.stopTest();
    }
    static void testBatchExecution2() {
        X9902__c x9902 = [SELECT Id FROM X9902__c LIMIT 1];
        HUD9902SummaryReportGenerateBatch batch = new HUD9902SummaryReportGenerateBatch(x9902.Id);
        Test.startTest();
        Contact con = [SELECT Id, Ethnicity__c, Race__C, AreaMedianIncome__c, RuralAreaStatus__c, EnglishProficiency__c FROM Contact LIMIT 1];
        con.Ethnicity__c = 'Not Hispanic';
        con.RuralAreaStatus__c = 'Does not live in a rural area';
        con.EnglishProficiency__c = 'Not Limited English Proficient';
        con.Race__C = 'Native Hawaiian or Other Pacific Islander';
        con.AreaMedianIncome__c = '80 - 100% of AMI';
        update con;
        Database.executeBatch(batch);
        Test.stopTest();
    }
    static void testBatchExecution3() {
        X9902__c x9902 = [SELECT Id FROM X9902__c LIMIT 1];
        HUD9902SummaryReportGenerateBatch batch = new HUD9902SummaryReportGenerateBatch(x9902.Id);
        Test.startTest();
        Contact con = [SELECT Id, Ethnicity__c, Race__C, AreaMedianIncome__c, RuralAreaStatus__c, EnglishProficiency__c FROM Contact LIMIT 1];
        con.Ethnicity__c = 'Not Hispanic';
        con.RuralAreaStatus__c = 'Does not live in a rural area';
        con.EnglishProficiency__c = 'Not Limited English Proficient';
        con.Race__C = 'White';
        con.AreaMedianIncome__c = '101% - 120% of AMI';
        update con;
        Database.executeBatch(batch);
        Test.stopTest();
    }
    static void testBatchExecution4() {
        X9902__c x9902 = [SELECT Id FROM X9902__c LIMIT 1];
        HUD9902SummaryReportGenerateBatch batch = new HUD9902SummaryReportGenerateBatch(x9902.Id);
        Test.startTest();
        Contact con = [SELECT Id, Ethnicity__c, Race__C, AreaMedianIncome__c, RuralAreaStatus__c, EnglishProficiency__c FROM Contact LIMIT 1];
        con.Ethnicity__c = 'Not Hispanic';
        con.RuralAreaStatus__c = 'Does not live in a rural area';
        con.EnglishProficiency__c = 'Not Limited English Proficient';
        con.Race__C = 'More than one race';
        con.AreaMedianIncome__c = '101% - 120% of AMI';
        update con;
        Database.executeBatch(batch);
        Test.stopTest();
    }
    
    @isTest
    static void testNoClientCases() {
        X9902__c x9902 = [SELECT Id FROM X9902__c LIMIT 1];
        delete [SELECT Id FROM ClientCase__c];
        HUD9902SummaryReportGenerateBatch batch = new HUD9902SummaryReportGenerateBatch(x9902.Id);
        Test.startTest();
        Database.executeBatch(batch);
        Test.stopTest();
    }
    
    @isTest
    static void testBatchWithNoCourses() {
        X9902__c x9902Record = new X9902__c(
            PeriodStartDate__c = Date.today().addDays(-30),
            PeriodEndDate__c = Date.today(),
            Quarter__c = 'Quarter 1'
        );
        insert x9902Record;
        List<ClientCase__c> clientCases = TestDataFactory.createClientCases(2, true);
        Test.startTest();
        HUD9902SummaryReportGenerateBatch batch = new HUD9902SummaryReportGenerateBatch(x9902Record.Id);
        Database.executeBatch(batch);
        Test.stopTest();
    }
    
    @IsTest
    static void testUpdateCount_HudActivityTypeNotBilled() {
        X9902__c x9902Record = new X9902__c(
            PeriodStartDate__c = Date.today().addDays(-30),
            PeriodEndDate__c = Date.today(),
            Quarter__c = 'Quarter 1'
        );
        insert x9902Record;
        String hudActivityType = 'Not Billed to HUD';
        String key = 'SomeKey';
        Map<String, Integer> picklistToActivityCount = new Map<String, Integer>{ key => 2 };
            
            HUD9902SummaryReportGenerateBatch instance = new HUD9902SummaryReportGenerateBatch(x9902Record.Id);
        instance.updateCount(hudActivityType, key, picklistToActivityCount);
    }
    
    @IsTest
    static void testUpdateCount_HudActivityTypeOther() {
        X9902__c x9902Record = new X9902__c(
            PeriodStartDate__c = Date.today().addDays(-30),
            PeriodEndDate__c = Date.today(),
            Quarter__c = 'Quarter 1'
        );
        insert x9902Record;
        
        String hudActivityType = 'Picklist Value'; 
        String key = 'SomeKey';
        Map<String, Integer> picklistToActivityCount = new Map<String, Integer>{ key => 2 };       
            HUD9902SummaryReportGenerateBatch instance = new HUD9902SummaryReportGenerateBatch(x9902Record.Id);
        instance.updateCount(hudActivityType, key, picklistToActivityCount);
    }
    
}