objects/ClientCase__c.object
<CustomObject>
    <description>To manage client-case relationships, tracking the services provided by the Agency.</description>
    <label>Client Case</label>
    <nameField>
        <label>Client Case #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Intake__c.object
<CustomObject>
    <description>To capture and store initial information about clients/prospects during the intake process including New Intake, New Education Only, and New Emergency Triage.</description>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Intake</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>ClientCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Case</label>
        <referenceTo>ClientCase__c</referenceTo>
        <relationshipLabel>Calendar Event Information</relationshipLabel>
        <relationshipName>SUMOAdditionalInfo</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/IntakeTimelineServiceTest.cls
@isTest
public class IntakeTimelineServiceTest {
	
    @TestSetup
    static void setupTestData() {
       	
        Account acc = TestDataFactory.createAccounts(1, true)[0];
        Contact con = TestDataFactory.createContacts(acc.id, 1, true)[0];
        //ClientCase__c clientCase = [SELECT Id FROM ClientCase__c LIMIT 1];
        List<Intake__c> intake = TestDataFactory.createIntakes(con, acc.Id, 1, true);
        Id recordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Event' AND SobjectType = 'sumoapp__AdditionalInfo__c' LIMIT 1]?.Id;
        sumoapp__AdditionalInfo__c info = TestDataFactory.createSumoEventInfo(1, true)[0];
        
        Event evt = TestDataFactory.createEvent(con, info.Id, 1, false)[0];
        evt.whatId = intake.get(0).id;
        insert evt;
    }
    
    
    @IsTest
    static void testGetAppointments() {
        Intake__c  intake = [SELECT Id FROM Intake__c LIMIT 1];
        IntakeTimelineService service = new IntakeTimelineService();
        service.getAppointments(intake.Id);
    }
    
    @IsTest
    static void testGetCounselorNotes() {
        Intake__c  intake = [SELECT Id FROM Intake__c LIMIT 1];
        IntakeTimelineService service = new IntakeTimelineService();
        service.getCounselorNotes(intake.Id);
    }
    
    @IsTest
    static void testGetCourses() {
        Intake__c  intake = [SELECT Id FROM Intake__c LIMIT 1];
        IntakeTimelineService service = new IntakeTimelineService();
        service.getCourses(intake.Id);
    }
}