objects/CoApplicant__c.object
<CustomObject>
    <description>To store details about household members who are co-applicants of the primary contact.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Co-Applicants</relationshipLabel>
        <relationshipName>Co_Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IntakeRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intake</label>
        <referenceTo>Intake__c</referenceTo>
        <relationshipLabel>Co-Applicants</relationshipLabel>
        <relationshipName>Co_Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Co-Applicant</label>
    <nameField>
        <displayFormat>CAPP-{00000}</displayFormat>
        <label>Co-Applicant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co-Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AreaMedianIncome__c</fullName>
        <label>Area Median Income</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Below 30% of AMI</fullName>
                </value>
                <value>
                    <fullName>30 - 49% of AMI</fullName>
                </value>
                <value>
                    <fullName>50 - 79% of AMI</fullName>
                </value>
                <value>
                    <fullName>80 - 100% of AMI</fullName>
                </value>
                <value>
                    <fullName>101% - 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Above 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Chose not to respond</fullName>
                </value>
                <value>
                    <fullName>Above 100% AMI</fullName>
                    <isActive>false</isActive>
                    <label>Above 100% AMI</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChoseNottoProvideIncome__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Chose Not to Provide Income</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DateAMILastCalculated__c</fullName>
        <label>Date AMI Last Calculated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EvaluateHUDAMI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EvaluateHUDAMI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HouseholdOfAMI__c</fullName>
        <label>Household % Of AMI</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>Number of people in the household</description>
        <inlineHelpText>Total number of people living in the same household</inlineHelpText>
        <label>Household Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MetropolitanStatisticalArea__c</fullName>
        <label>Metropolitan Statistical Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalMonthlyIncome__c</fullName>
        <label>Total Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isInvalidZip__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isInvalidZip</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>CoApplicant</fullName>
        <active>true</active>
        <label>Co-Applicant</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/HUDAMIData__c.object
<CustomObject>
    <description>To store data related to Area Median Income (AMI) for various regions, including details such as area names, county names, FIPS codes, and HUD-specific identifiers for HUD AMI calculations.</description>
    <fields>
        <fullName>Areaname__c</fullName>
        <description>HUD Income Limit Area Name</description>
        <label>Area name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UniqueKey__c</fullName>
        <formula>TownName__c+&apos;-&apos;+CountyName__c+&apos;-&apos;+Zipcode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unique Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zipcode__c</fullName>
        <label>Zipcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>HUD AMI Data</label>
    <nameField>
        <label>HUD AMI Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HUD AMI Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Intake__c.object
<CustomObject>
    <description>To capture and store initial information about clients/prospects during the intake process including New Intake, New Education Only, and New Emergency Triage.</description>
    <fields>
        <fullName>AreaMedianIncome__c</fullName>
        <label>Area Median Income</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Below 30% of AMI</fullName>
                </value>
                <value>
                    <fullName>30 - 49% of AMI</fullName>
                </value>
                <value>
                    <fullName>50 - 79% of AMI</fullName>
                </value>
                <value>
                    <fullName>80 - 100% of AMI</fullName>
                </value>
                <value>
                    <fullName>101% - 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Above 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Chose not to respond</fullName>
                </value>
                <value>
                    <fullName>Above 100% AMI</fullName>
                    <isActive>false</isActive>
                    <label>Above 100% AMI</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChoseNottoProvideIncome__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Chose Not to Provide Income</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DateAMILastCalculated__c</fullName>
        <label>Date AMI Last Calculated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EvaluateHUDAMI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EvaluateHUDAMI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HouseholdMonthlyIncome__c</fullName>
        <label>Household Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HouseholdOfAMI__c</fullName>
        <label>Household % Of AMI</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <label>Household Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IntakeDate__c</fullName>
        <label>Intake Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MetropolitanStatisticalArea__c</fullName>
        <label>Metropolitan Statistical Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MonthlyIncome__c</fullName>
        <label>Total Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isInvalidZip__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isInvalidZip</label>
        <type>Checkbox</type>
    </fields>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Intake</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/IntakeTriggerHandler.cls
/**
* @desc: Handler class for Intake__c triggers to manage field population and automation logic.
*/
public inherited sharing class IntakeTriggerHandler {
    
    /**
* @desc: Handles the logic before inserting new Intake__c records.
* @param newIntakeList: List of new Intake__c records being inserted.
*/
    public static void beforeInsert(List<Intake__c> newIntakeList) {
        populateFieldsOnIntake(newIntakeList, New Map<Id, Intake__c>(), true);
    }
    
    /**
* @desc: Handles the logic before updating existing Intake__c records.
* @param newIntakeList: List of new Intake__c records being updated.
* @param oldIntakeMap: Map of old Intake__c records being updated.
*/
    public static void beforeUpdate(List<Intake__c> newIntakeList, Map<Id, Intake__c> oldIntakeMap) {
        try {
            populateFieldsOnIntake(newIntakeList, oldIntakeMap, false);
        } catch (Exception e) {
            System.debug('IntakeTriggerHandler Error in beforeUpdate: ' + e.getMessage());
        }
    }
    
    /**
* @desc: Populates fields on Intake__c records based on HUDAMI data.
* @param newIntakeList: List of new Intake__c records.
* @param oldIntakeMap: Map of old Intake__c records.
* @param isNew: Boolean indicating if the records are new.
*/
    public static void populateFieldsOnIntake(List<Intake__c> newIntakeList, Map<Id, Intake__c> oldIntakeMap, Boolean isNew) {
        Map<String, List<HUDAMIData__c>> hudamiDataMap = new Map<String, List<HUDAMIData__c>>();
        Set<String> zipCodes = new Set<String>();
        Set<String> townCountyZipKeys = new Set<String>();

        List<Intake__c> validZipIntakeList = new List<Intake__c>(); 
        List<Intake__c> changedMonthlyIncomeIntakelist = new List<Intake__c>();
        
        if (isNew) {
            for (Intake__c newIntake : newIntakeList) {
                newIntake.IntakeDate__c = Date.today();
                if (newIntake.Address__PostalCode__s != null && (newIntake.County__c == null && newIntake.Town__c == null)) {
                    zipCodes.add(newIntake.Address__PostalCode__s);
                    validZipIntakeList.add(newIntake);
                } else {
                    String townCountyZipKey = 
                    (String.isBlank(newIntake.Town__c) ? '' : newIntake.Town__c) + '-' + 
                    (String.isBlank(newIntake.County__c) ? '' : newIntake.County__c) + '-' + 
                    (String.isBlank(newIntake.Address__PostalCode__s) ? '' : newIntake.Address__PostalCode__s);
                    townCountyZipKeys.add(townCountyZipKey);
                    validZipIntakeList.add(newIntake);
                }
            }
            RecalculateIncome(newIntakeList, false);
        }
        else {
            for (Intake__c newIntake : newIntakeList) {
                Intake__c oldIntake = oldIntakeMap.get(newIntake.Id);
                if (oldIntake != null) {
                    if (newIntake.Address__PostalCode__s != oldIntake.Address__PostalCode__s) {
                        if (newIntake.Town__c != oldIntake.Town__c && newIntake.County__c != oldIntake.County__c) {
                            // Handle logic if both town and county changed.
                        } else {
                            zipCodes.add(newIntake.Address__PostalCode__s);
                            validZipIntakeList.add(newIntake);  
                        }
                    } else if (newIntake.HouseholdMonthlyIncome__c != oldIntake.HouseholdMonthlyIncome__c ||
                               newIntake.MonthlyIncome__c != oldIntake.MonthlyIncome__c ||
                               newIntake.HouseholdSize__c != oldIntake.HouseholdSize__c ||
                               newIntake.County__c != oldIntake.County__c ||
                               newIntake.Town__c != oldIntake.Town__c) {
                                   String townCountyZipKey = 
                                       (String.isBlank(newIntake.Town__c) ? '' : newIntake.Town__c) + '-' + 
                                       (String.isBlank(newIntake.County__c) ? '' : newIntake.County__c) + '-' + 
                                       (String.isBlank(newIntake.Address__PostalCode__s) ? '' : newIntake.Address__PostalCode__s);
                                   townCountyZipKeys.add(townCountyZipKey);
                                   validZipIntakeList.add(newIntake);  
                               }
                    if(newIntake.MonthlyIncome__c != oldIntake.MonthlyIncome__c )
                    {
                        changedMonthlyIncomeIntakelist.add(newIntake);
                    }
                }
            }
            if (!changedMonthlyIncomeIntakelist.isEmpty()) {
                RecalculateIncome(changedMonthlyIncomeIntakelist, false);
            }
        }

        List<HUDAMIData__c> hudamiRecordsByZip = new List<HUDAMIData__c>();
        List<HUDAMIData__c> hudamiRecordsByTownCountyZip = new List<HUDAMIData__c>();
        
        if (!zipCodes.isEmpty()) {
            hudamiRecordsByZip = Utility.getHUDAMIData(zipCodes, new Set<String>());
        }
        
        if (!townCountyZipKeys.isEmpty()) {
            hudamiRecordsByTownCountyZip = Utility.getHUDAMIData(new Set<String>(), townCountyZipKeys);
        }

        addToHudamiDataMap(hudamiDataMap, hudamiRecordsByZip);
        addToHudamiDataMap(hudamiDataMap, hudamiRecordsByTownCountyZip);

        if (!validZipIntakeList.isEmpty()) {         
            newIntakeList = validZipIntakeList;      
        } else {                                     
            newIntakeList = new List<Intake__c>();   
        }                                            
        
        for (Intake__c intake : newIntakeList) {
            if (!hudamiDataMap.isEmpty()) {
                processIntakeRecord(intake, hudamiDataMap);
            }                                                
            else {                                           
                intake.isInvalidZip__c = true;               
                // intake.EvaluateHUDAMI__c = false;            
                intake.County__c = null;                
                intake.Town__c = null;                  
                intake.MetropolitanStatisticalArea__c = null;  
                intake.AreaMedianIncome__c = null;            
                intake.DateAMILastCalculated__c = null;      
                intake.HouseholdOfAMI__c = null;             
                System.debug('IntakeTriggerHandler: Invalid Zip Code Entered');    
            }                                                
        }
    }
    
    /**
* @desc: Adds HUDAMI data records to the HUDAMI data map.
* @param hudamiDataMap: Map of HUDAMI data grouped by keys.
* @param records: List of HUDAMI data records to add to the map.
*/
    private static void addToHudamiDataMap(Map<String, List<HUDAMIData__c>> hudamiDataMap, List<HUDAMIData__c> records) {
        for (HUDAMIData__c hud : records) {
            String zipKey = hud.Zipcode__c;
            
            if (!hudamiDataMap.containsKey(zipKey)) {
                hudamiDataMap.put(zipKey, new List<HUDAMIData__c>());
            }
            hudamiDataMap.get(zipKey).add(hud);
            
            if (!hudamiDataMap.containsKey(hud.UniqueKey__c)) {
                hudamiDataMap.put(hud.UniqueKey__c, new List<HUDAMIData__c>());
            }
            hudamiDataMap.get(hud.UniqueKey__c).add(hud);
        }
    }
    
    /**
* @desc: Processes an Intake__c record to populate fields based on HUDAMI data.
* @param intake: The Intake__c record to process.
* @param hudamiDataMap: Map of HUDAMI data grouped by keys.
*/
    private static void processIntakeRecord(Intake__c intake, Map<String, List<HUDAMIData__c>> hudamiDataMap) {
        String zipKey = intake.Address__PostalCode__s;
        String townCountyZipKey = (String.isBlank(intake.Town__c) ? '' : intake.Town__c) + '-' + 
            (String.isBlank(intake.County__c) ? '' : intake.County__c) + '-' + 
            (String.isBlank(intake.Address__PostalCode__s) ? '' : intake.Address__PostalCode__s);

        if (hudamiDataMap.containsKey(zipKey) && hudamiDataMap.get(zipKey).size() > 1) {
            intake.EvaluateHUDAMI__c = true;
            intake.isInvalidZip__c = false;           
            intake.County__c = null;
            intake.Town__c = null;
            intake.MetropolitanStatisticalArea__c = null;
            intake.AreaMedianIncome__c = null;
            intake.DateAMILastCalculated__c = null;
            intake.HouseholdOfAMI__c = null;
        } else if (hudamiDataMap.containsKey(zipKey) && hudamiDataMap.get(zipKey).size() == 1) {
            HUDAMIData__c hudRec = hudamiDataMap.get(zipKey)[0];
            updateIntakeRecord(intake, hudRec);
            intake.EvaluateHUDAMI__c = false;
            intake.isInvalidZip__c = false;        
        } else if (hudamiDataMap.containsKey(townCountyZipKey)) {
            HUDAMIData__c hudRec = hudamiDataMap.get(townCountyZipKey)[0];
            updateIntakeRecord(intake, hudRec);
            intake.EvaluateHUDAMI__c = false;
            intake.isInvalidZip__c = false;         
        } 
        else {                                      
            intake.isInvalidZip__c = true;          
            // intake.EvaluateHUDAMI__c = false;       
        }                                           
    }
    
    /**
* @desc: Updates an Intake__c record with data from a HUDAMIData__c record.
* @param intake: The Intake__c record to update.
* @param hudRec: The HUDAMIData__c record containing the data.
*/
    private static void updateIntakeRecord(Intake__c intake, HUDAMIData__c hudRec) {
        Decimal annualHouseholdIncome = (intake.HouseholdMonthlyIncome__c != null) ? (intake.HouseholdMonthlyIncome__c  * 12): 0;
        Integer householdSize = (intake.HouseholdSize__c != null) ? intake.HouseholdSize__c.intValue() : 0;
        if(!intake.ChoseNottoProvideIncome__c){
            HUDAMICalculationService.HUDAMIServiceWrapper wrapper =
                HUDAMICalculationService.getHudAmiCalculatedWrapper(hudRec, householdSize, annualHouseholdIncome);
            
            if (String.isBlank(wrapper.error)) {
                intake.County__c = wrapper.countyName != null ? wrapper.countyName : '';
                intake.MetropolitanStatisticalArea__c = wrapper.metropolitanStatisticalArea != null ? wrapper.metropolitanStatisticalArea : '';
                intake.AreaMedianIncome__c = wrapper.areaMedianIncome != null ? wrapper.areaMedianIncome : '';
                //intake.AreaName__c = wrapper.areaname != null ? wrapper.areaname : ''; // Field needs to be created if required
                intake.Town__c = wrapper.townName != null ? wrapper.townName : '';
                //intake.Address__PostalCode__s = wrapper.zipcode != null ? wrapper.zipcode : '';
                //intake.Address__StateCode__s = wrapper.stateCode != null ? wrapper.stateCode : '';
                intake.DateAMILastCalculated__c = System.now();
                intake.HouseholdOfAMI__c = wrapper.householdOfAMI != null ? wrapper.householdOfAMI : 0.0;
            } else {
                System.debug('IntakeTriggerHandler: Error in wrapper: ' + wrapper.error);
            }
        }
    } 
    
    
/**
* @desc: Recalculate Household Monthly Income on intake
*/
    
    public static void RecalculateIncome(List<Intake__c> intakes, Boolean isFromContact) {

        List<CoApplicant__c> coApplicants = [
            SELECT Id, IntakeRequest__c, Contact__r.TotalMonthlyIncome__c 
            FROM CoApplicant__c 
            WHERE IntakeRequest__c IN :intakes
        ];
        
        Map<Id, Decimal> intakeToCoApplicantIncomeMap = new Map<Id, Decimal>();
        for (CoApplicant__c coApplicant : coApplicants) {
            if (coApplicant.IntakeRequest__c != null && coApplicant.Contact__r.TotalMonthlyIncome__c != null) {
                if (!intakeToCoApplicantIncomeMap.containsKey(coApplicant.IntakeRequest__c)) {
                    intakeToCoApplicantIncomeMap.put(coApplicant.IntakeRequest__c, 0);
                }
                intakeToCoApplicantIncomeMap.put(coApplicant.IntakeRequest__c, 
                                                 intakeToCoApplicantIncomeMap.get(coApplicant.IntakeRequest__c) + coApplicant.Contact__r.TotalMonthlyIncome__c);
            } else {
                System.debug('IntakeTriggerHandler: CoApplicant or Monthly Income is null for Id: ' + coApplicant.Id);
            }
        }
        
        for (Intake__c intake : intakes) {
            if(!intake.ChoseNottoProvideIncome__c){
                Decimal totalIncome = 0;
                
                if (intake.MonthlyIncome__c != null) {
                    totalIncome += intake.MonthlyIncome__c;
                }
                
                if (intakeToCoApplicantIncomeMap.containsKey(intake.Id)) {
                    totalIncome += intakeToCoApplicantIncomeMap.get(intake.Id);
                }
                intake.HouseholdMonthlyIncome__c = (totalIncome > 0 ? totalIncome : null);
            }
        }
        if (isFromContact == true) {
            update intakes;
        }
    }
    
}