objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ActiveMilitary__c</fullName>
        <description>Yes, No, Not Applicable</description>
        <label>Active Military</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ActiveMilitary</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Besttimetocontact__c</fullName>
        <description>Contact’s preferred time to be contacted</description>
        <label>Best Time to Contact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Morning</fullName>
                </value>
                <value>
                    <fullName>Afternoon</fullName>
                </value>
                <value>
                    <fullName>Evening</fullName>
                </value>
                <value>
                    <fullName>Weekend</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClientHUDAssistance__c</fullName>
        <label>Client HUD Assistance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Rental Voucher</fullName>
                </value>
                <value>
                    <fullName>Place Based Rental Assistance</fullName>
                </value>
                <value>
                    <fullName>Home Ownership Voucher</fullName>
                </value>
                <value>
                    <fullName>Purchase REO Property</fullName>
                </value>
                <value>
                    <fullName>Down Payment Assistance</fullName>
                </value>
                <value>
                    <fullName>Other HUD Program</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ColoniasResidence__c</fullName>
        <label>Colonias Residence</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CreditScore__c</fullName>
        <label>Credit Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CurrentResidence__c</fullName>
        <description>Own, Rent, Others</description>
        <label>Current Residence</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CurrentResidenceContact</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DisabledStatus__c</fullName>
        <label>Disabled Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <description>Pre-defined list</description>
        <label>Education</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Education</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EmploymentStatus__c</fullName>
        <label>Employment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Employed Full-Time</fullName>
                </value>
                <value>
                    <fullName>Employed Part-Time</fullName>
                </value>
                <value>
                    <fullName>Unemployed AND Looking for Work</fullName>
                </value>
                <value>
                    <fullName>Unable to Work Due to Disability</fullName>
                </value>
                <value>
                    <fullName>Stay-at-Home Caregiver OR Parent</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Employed Full-Time AND Student</fullName>
                </value>
                <value>
                    <fullName>Employed Part-Time AND Student</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EnglishProficiency__c</fullName>
        <description>Reflects overall level of English proficiency within the same household as the contact.</description>
        <inlineHelpText>English Proficiency of the primary client</inlineHelpText>
        <label>English Proficiency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Limited_English_Proficiency_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <description>Client’s self-identified ethnicity, used in 9902 reporting</description>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>FarmWorker__c</fullName>
        <label>Farm Worker</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Male, Female, Other/Non-Conforming</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>Number of people in the household</description>
        <inlineHelpText>Total number of people living in the same household</inlineHelpText>
        <label>Household Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HouseholdType__c</fullName>
        <label>Household Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MaritalStatus__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>HouseholdTypeHeadofHousehold</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MailingAddressLine2__c</fullName>
        <label>Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaritalStatus__c</fullName>
        <description>Pre-defined  list</description>
        <label>Marital Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MaritalStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MonthlyCreditorsDebt__c</fullName>
        <label>Monthly Creditor’s Debt</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NumberOfDependents__c</fullName>
        <label>Number of Dependents</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OccupationStartDate__c</fullName>
        <label>Occupation Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Occupation__c</fullName>
        <label>Occupation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreferredLanguage__c</fullName>
        <description>Client’s preferred language</description>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English (US)</label>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>ASL</fullName>
                </value>
                <value>
                    <fullName>Cambodian</fullName>
                </value>
                <value>
                    <fullName>Cantonese</fullName>
                </value>
                <value>
                    <fullName>Chinese Mandarin</fullName>
                </value>
                <value>
                    <fullName>Creole</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Goboligok</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hmong</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latin</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
                <value>
                    <fullName>Portuuguese</fullName>
                </value>
                <value>
                    <fullName>Russian</fullName>
                </value>
                <value>
                    <fullName>Swahili</fullName>
                </value>
                <value>
                    <fullName>Turkish</fullName>
                </value>
                <value>
                    <fullName>Ukrainian</fullName>
                </value>
                <value>
                    <fullName>Urdu</fullName>
                </value>
                <value>
                    <fullName>Vietnamese</fullName>
                </value>
                <value>
                    <fullName>Yiddish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <description>Which HUD 9902-recognized race category the contact belongs to.</description>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RelationshipToPrimaryApplicant__c</fullName>
        <description>contact relationship to primary contact</description>
        <inlineHelpText>If applicable</inlineHelpText>
        <label>Relationship to Primary Applicant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Brother</fullName>
                </value>
                <value>
                    <fullName>Employer</fullName>
                </value>
                <value>
                    <fullName>Father</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Husband</fullName>
                </value>
                <value>
                    <fullName>Mother</fullName>
                </value>
                <value>
                    <fullName>Other Relative</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Sister</fullName>
                </value>
                <value>
                    <fullName>Step-Daughter</fullName>
                </value>
                <value>
                    <fullName>Wife</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <description>Client Social Security Number</description>
        <label>SSN</label>
        <length>11</length>
        <maskChar>X</maskChar>
        <maskType>ssn</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>TotalMonthlyIncome__c</fullName>
        <label>Total Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Veteran__c</fullName>
        <description>Yes, No, Not Applicable</description>
        <label>Veteran</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Veteran</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>X1stTimeHomeBuyer__c</fullName>
        <description>Yes, No</description>
        <inlineHelpText>Must not have owned a home within the last 3 years.</inlineHelpText>
        <label>1st Time Home Buyer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>X1stTimeHomeBuyer</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>PrimaryClient</fullName>
        <active>true</active>
        <label>Primary Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <label>Prospect</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/ActiveMilitary.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>Not available</fullName>
    </customValue>
    <masterLabel>Active Military?</masterLabel>
</GlobalValueSet>

globalValueSets/CurrentResidenceContact.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Own</fullName>
    </customValue>
    <customValue>
        <fullName>Rent</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>Current Residence Contact</masterLabel>
</GlobalValueSet>

globalValueSets/Education.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Elementary/Primary</fullName>
    </customValue>
    <customValue>
        <fullName>Junior High School</fullName>
    </customValue>
    <customValue>
        <fullName>High School/GED</fullName>
    </customValue>
    <customValue>
        <fullName>Junior College</fullName>
    </customValue>
    <customValue>
        <fullName>University</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate School</fullName>
    </customValue>
    <customValue>
        <fullName>Vocational</fullName>
    </customValue>
    <customValue>
        <fullName>College</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>High School</fullName>
        <isActive>false</isActive>
        <label>High School</label>
    </customValue>
    <customValue>
        <fullName>Elementary</fullName>
        <isActive>false</isActive>
        <label>Elementary</label>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
        <isActive>false</isActive>
        <label>Unknown</label>
    </customValue>
    <description>Education</description>
    <masterLabel>Education</masterLabel>
</GlobalValueSet>

globalValueSets/Ethnicity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Not Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Ethnicity</description>
    <masterLabel>Ethnicity</masterLabel>
</GlobalValueSet>

globalValueSets/Gender.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <customValue>
        <fullName>Other/Non-conforming</fullName>
    </customValue>
    <description>Gender</description>
    <masterLabel>Gender</masterLabel>
</GlobalValueSet>

globalValueSets/HouseholdTypeHeadofHousehold.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Single adult</fullName>
    </customValue>
    <customValue>
        <fullName>Female-headed single parent household</fullName>
    </customValue>
    <customValue>
        <fullName>Male-headed single parent household</fullName>
    </customValue>
    <customValue>
        <fullName>Married without dependents</fullName>
    </customValue>
    <customValue>
        <fullName>Married with dependents</fullName>
    </customValue>
    <customValue>
        <fullName>Two or more unrelated Adults</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Married with children</fullName>
        <isActive>false</isActive>
        <label>Married with children</label>
    </customValue>
    <customValue>
        <fullName>Male-headed single parent household/Head of Household</fullName>
        <isActive>false</isActive>
        <label>Male-headed single parent household/Head of Household</label>
    </customValue>
    <customValue>
        <fullName>Female-headed single parent household/Head of Household</fullName>
        <isActive>false</isActive>
        <label>Female-headed single parent household/Head of Household</label>
    </customValue>
    <customValue>
        <fullName>Domestic partnership</fullName>
        <isActive>false</isActive>
        <label>Domestic partnership</label>
    </customValue>
    <customValue>
        <fullName>Married without children</fullName>
        <isActive>false</isActive>
        <label>Married without children</label>
    </customValue>
    <masterLabel>Household Type/Head of Household</masterLabel>
</GlobalValueSet>

globalValueSets/Limited_English_Proficiency_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Limited English Proficient</fullName>
    </customValue>
    <customValue>
        <fullName>Not Limited English Proficient</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Limited English Proficiency Status</description>
    <masterLabel>Limited English Proficiency Status</masterLabel>
</GlobalValueSet>

globalValueSets/MaritalStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Married</fullName>
    </customValue>
    <customValue>
        <fullName>Single</fullName>
    </customValue>
    <customValue>
        <fullName>Divorced</fullName>
    </customValue>
    <customValue>
        <fullName>Separated</fullName>
    </customValue>
    <customValue>
        <fullName>Widowed</fullName>
    </customValue>
    <customValue>
        <fullName>Choose not to respond</fullName>
    </customValue>
    <customValue>
        <fullName>Legally Separated</fullName>
        <isActive>false</isActive>
        <label>Legally Separated</label>
    </customValue>
    <masterLabel>Marital Status</masterLabel>
</GlobalValueSet>

globalValueSets/Race.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>American Indian/Alaskan Native</fullName>
    </customValue>
    <customValue>
        <fullName>Asian</fullName>
    </customValue>
    <customValue>
        <fullName>Black or African American</fullName>
    </customValue>
    <customValue>
        <fullName>Native Hawaiian or Other Pacific Islander</fullName>
    </customValue>
    <customValue>
        <fullName>White</fullName>
    </customValue>
    <customValue>
        <fullName>More than one race</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Race</description>
    <masterLabel>Race</masterLabel>
</GlobalValueSet>

globalValueSets/Veteran.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>Not available</fullName>
    </customValue>
    <masterLabel>Veteran?</masterLabel>
</GlobalValueSet>

globalValueSets/X1stTimeHomeBuyer.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>Not available</fullName>
    </customValue>
    <masterLabel>1st Time Home Buyer?</masterLabel>
</GlobalValueSet>

classes/EducationalIntakeController.cls
public with sharing class EducationalIntakeController {
    
    
    
    public class EducationalIntakeWrapper {
        @AuraEnabled
        public Contact contact{get;set;}
        
        @AuraEnabled
        public List<Contact> contacts{get;set;}
        
        @AuraEnabled
        public Map<String, List<String>> zipcodeData{get;set;}
    }
    
    /**
     * @description : stores the respective records for education form
    */

    @AuraENabled
    public static Contact storeEducationIntake(EducationalIntakeWrapper requestWrapper) {
        Savepoint sp = Database.setSavepoint();
        try{
            Contact contact = requestWrapper.contact;
            RecordType prospectRecordType = [SELECT Id, Name, DeveloperName FROM RecordType where SobjectType='Contact' AND NAme='Prospect' WITH SECURITY_ENFORCED];
            if(contact!=null && Schema.sObjectType.Contact.isCreateable()) {
                //contact.RecordTypeId = prospectRecordType.Id;
                Id prospectRTId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Prospect').getRecordTypeId();
                Id primaryClientRTId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('PrimaryClient').getRecordTypeId();
                Contact con;
                if(contact.Id != null ){
                    con = [SELECT Id, RecordTypeId FROM Contact WHERE Id = :contact.Id WITH SECURITY_ENFORCED];
                    if(con.RecordTypeId != primaryClientRTId){
                        contact.RecordTypeId = prospectRTId;
                    }
                }else{
                    contact.RecordTypeId = prospectRTId;
                }
                Database.UpsertResult result = Database.upsert(contact,true,AccessLevel.USER_MODE);
                if(!result.isSuccess()) {
                    System.debug('Errors : '+ result.getErrors());
                }
                
                System.debug('Contact Inserted : '+contact);
            }
            
            Id accountID = [Select id,AccountID from Contact where id=:contact.Id WITH SECURITY_ENFORCED]?.AccountID;
            
            List<Contact> coapplicants = requestWrapper.contacts;
            if(coapplicants!=null && !coapplicants.isEmpty() && Schema.sObjectType.Contact.isCreateable()) {
                RecordType recType = [SELECT Id, Name, DeveloperName FROM RecordType where SobjectType='Contact' AND NAme='Co-Applicant' WITH SECURITY_ENFORCED];
                for(Contact con : coapplicants) {
                    con.AccountId=accountId;
                    con.RecordTypeId=recType.Id;
                    con.isActive__c = true;
                    if(String.isNotEmpty(con.MailingAddressLine2__c)){
                        con.MailingStreet = con.MailingStreet + '\n' + con.MailingAddressLine2__c;
                    }
                }
                for(Database.UpsertResult result: Database.upsert(coapplicants,false, AccessLevel.USER_MODE)) {
                    if(!result.isSuccess()) {
                        System.debug('Errors : '+result.getErrors());
                        System.debug('Error Occured for Id : '+result.getId());
                        for(Database.Error err : result.getErrors()) {
                            System.debug('The following error has occurred.');                    
                            System.debug(err.getStatusCode() + ': ' + err.getMessage());
                            System.debug('Co Applicant fields that affected this error: ' + err.getFields());
                        }
                        throw new AuraHandledException('Error Occurred while Updating co applicants');
                        
                    }
                }
                System.debug('Co Applicants Inserted : '+coapplicants);
                
            }
            return contact;
        }catch(Exception e) {
            System.debug('Exception Occurred : at line '+e.getLineNumber());
            System.debug('Exception Message : '+ e.getMessage());
            System.debug('Stack Traced : '+ e.getStackTraceString()) ;
            LoggerClass.log(e,'educationFormSubmit');
            Database.rollback(sp);
            
            throw new AuraHandledException(e.getMessage());
        }
        
        //return null;
        
    }
    
    
    /**
     * @description : retrieves the respective records for education form
    */
    @AuraEnabled
    public static EducationalIntakeWrapper getIntakeDetails(Id contactId) {
        EducationalIntakeWrapper response = new EducationalIntakeWrapper();
        Id accountID = [Select id,AccountID from Contact where id=:contactId WITH SECURITY_ENFORCED]?.AccountID;
        List<Contact> contacts = [Select 
                                  id,FirstName,MiddleName,Suffix,Besttimetocontact__c,LastName,SSN__c,Email,Phone,PreferredLanguage__c,Birthdate,MailingStreet,HouseholdType__c,MailingAddressLine2__c,MailingCity,MailingStateCode,MailingPostalCode,Race__c,Ethnicity__c,Gender__c,Education__c,MaritalStatus__c, EnglishProficiency__c,ActiveMilitary__c,Veteran__c,X1stTimeHomeBuyer__c,RecordType.DeveloperName,RelationshipToPrimaryApplicant__c,
                                  FarmWorker__c,ColoniasResidence__c,DisabledStatus__c,TotalMonthlyIncome__c,NumberOfDependents__c,ClientHUDAssistance__c,Occupation__c,OccupationStartDate__c,MonthlyCreditorsDebt__c,CreditScore__c,EmploymentStatus__c,CurrentResidence__c,HouseholdSize__c,RuralAreaStatus__c,County__c,Town__c,MarketingCommunicationsOptOut__c FROM Contact where AccountId=:accountID];
        List<Contact> coApplicants = new List<Contact>();
        for(Contact con: contacts) {
            if(con.RecordType.DeveloperName=='PrimaryClient' || con.RecordType.DeveloperName=='Lead' || con.RecordType.DeveloperName=='Prospect'){
                response.contact = con;
                response.zipcodeData=HUDAMICalculationService.getCountyNamesBasedOnZip(con.MailingPostalCode);
            } else {
                 coApplicants.add(con);
            }
        }
        response.contacts = coApplicants;
        return response;
    }
    
    
    
}