objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AreaMedianIncome__c</fullName>
        <label>Area Median Income</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Below 30% of AMI</fullName>
                </value>
                <value>
                    <fullName>30 - 49% of AMI</fullName>
                </value>
                <value>
                    <fullName>50 - 79% of AMI</fullName>
                </value>
                <value>
                    <fullName>80 - 100% of AMI</fullName>
                </value>
                <value>
                    <fullName>101% - 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Above 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Chose not to respond</fullName>
                </value>
                <value>
                    <fullName>Above 100% AMI</fullName>
                    <isActive>false</isActive>
                    <label>Above 100% AMI</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EnglishProficiency__c</fullName>
        <description>Reflects overall level of English proficiency within the same household as the contact.</description>
        <inlineHelpText>English Proficiency of the primary client</inlineHelpText>
        <label>English Proficiency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Limited_English_Proficiency_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <description>Client’s self-identified ethnicity, used in 9902 reporting</description>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HouseholdOfAMI__c</fullName>
        <label>Household % Of AMI</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <description>Which HUD 9902-recognized race category the contact belongs to.</description>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReferralSource__c</fullName>
        <label>Referral Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ReferralSource</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RuralAreaStatus__c</fullName>
        <description>Whether or not this contact resides in a rural area as defined by HUD.</description>
        <label>Rural Area Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Rural_Area_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>X1stTimeHomeBuyer__c</fullName>
        <description>Yes, No</description>
        <inlineHelpText>Must not have owned a home within the last 3 years.</inlineHelpText>
        <label>1st Time Home Buyer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>X1stTimeHomeBuyer</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>PrimaryClient</fullName>
        <active>true</active>
        <label>Primary Client</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>sumoapp__Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Child Events</relationshipLabel>
        <relationshipName>ChildEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BOOKED</fullName>
                    <default>true</default>
                    <label>Booked</label>
                </value>
                <value>
                    <fullName>CANCELED</fullName>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>RESCHEDULED</fullName>
                    <label>Rescheduled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__Attendee__c.object
<CustomObject>
    <fields>
        <fullName>AreaMedianIncome__c</fullName>
        <label>Area Median Income</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Below 30% of AMI</fullName>
                </value>
                <value>
                    <fullName>30 - 49% of AMI</fullName>
                </value>
                <value>
                    <fullName>50 - 79% of AMI</fullName>
                </value>
                <value>
                    <fullName>80 - 100% of AMI</fullName>
                </value>
                <value>
                    <fullName>101% - 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Above 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Chose not to respond</fullName>
                </value>
                <value>
                    <fullName>Above 100% AMI</fullName>
                    <isActive>false</isActive>
                    <label>Above 100% AMI</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Attendance_Status__c</fullName>
        <label>Attendee Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Attended - Complete</fullName>
                </value>
                <value>
                    <fullName>Attended - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Course Complete</fullName>
                </value>
                <value>
                    <fullName>Course Incomplete</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EnglishProficiency__c</fullName>
        <label>English Proficiency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Limited_English_Proficiency_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HouseholdofAMI__c</fullName>
        <label>Household % Of AMI</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReferralSource__c</fullName>
        <label>Referral Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ReferralSource</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RuralAreaStatus__c</fullName>
        <label>Rural Area Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Rural_Area_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>X1stTimeHomeBuyer__c</fullName>
        <label>1st Time Home Buyer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>X1stTimeHomeBuyer</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>sumoapp__ContactRelation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Relation</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Event Attendees</relationshipLabel>
        <relationshipName>ContactEventAttendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__IsNotArrived__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It shows whether the attendee has arrived at the event or not</description>
        <inlineHelpText>Set this value if the attendee did not arrive at the event</inlineHelpText>
        <label>No-Show</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sumoapp__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>CANCELED</fullName>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>COMPLIMENTARY</fullName>
                    <label>Complimentary</label>
                </value>
                <value>
                    <fullName>DECLINED</fullName>
                    <label>Declined</label>
                </value>
                <value>
                    <fullName>DRAFT</fullName>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>REFUNDED</fullName>
                    <label>Fully Refunded</label>
                </value>
                <value>
                    <fullName>PAID_MANUAL</fullName>
                    <label>Paid - Manual</label>
                </value>
                <value>
                    <fullName>PAID</fullName>
                    <label>Paid - Online</label>
                </value>
                <value>
                    <fullName>PARTIALLY_REFUNDED</fullName>
                    <label>Partially Refunded</label>
                </value>
                <value>
                    <fullName>BOOKED</fullName>
                    <default>true</default>
                    <label>Registered</label>
                </value>
                <value>
                    <fullName>WAITLISTED</fullName>
                    <label>Waitlisted</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sumoapp__SumoEvent__c</fullName>
        <label>SUMO Event</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SUMO Attendee</label>
    <nameField>
        <displayFormat>ATD-{000000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Ethnicity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Not Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Ethnicity</description>
    <masterLabel>Ethnicity</masterLabel>
</GlobalValueSet>

globalValueSets/Limited_English_Proficiency_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Limited English Proficient</fullName>
    </customValue>
    <customValue>
        <fullName>Not Limited English Proficient</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Limited English Proficiency Status</description>
    <masterLabel>Limited English Proficiency Status</masterLabel>
</GlobalValueSet>

globalValueSets/Race.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>American Indian/Alaskan Native</fullName>
    </customValue>
    <customValue>
        <fullName>Asian</fullName>
    </customValue>
    <customValue>
        <fullName>Black or African American</fullName>
    </customValue>
    <customValue>
        <fullName>Native Hawaiian or Other Pacific Islander</fullName>
    </customValue>
    <customValue>
        <fullName>White</fullName>
    </customValue>
    <customValue>
        <fullName>More than one race</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Race</description>
    <masterLabel>Race</masterLabel>
</GlobalValueSet>

globalValueSets/ReferralSource.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Advertisement</fullName>
    </customValue>
    <customValue>
        <fullName>Employer</fullName>
    </customValue>
    <customValue>
        <fullName>Event</fullName>
    </customValue>
    <customValue>
        <fullName>Lender</fullName>
    </customValue>
    <customValue>
        <fullName>Mailer</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Partner Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Project Own App</fullName>
    </customValue>
    <customValue>
        <fullName>Realtor</fullName>
    </customValue>
    <customValue>
        <fullName>Walk-in</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <customValue>
        <fullName>Word of Mouth</fullName>
    </customValue>
    <customValue>
        <fullName>Referral</fullName>
        <isActive>false</isActive>
        <label>Referral</label>
    </customValue>
    <masterLabel>Referral Source</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/Rural_Area_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Lives in a rural area</fullName>
    </customValue>
    <customValue>
        <fullName>Does not live in a rural area</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Rural Area Status</description>
    <masterLabel>Rural Area Status</masterLabel>
</GlobalValueSet>

globalValueSets/X1stTimeHomeBuyer.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>Not available</fullName>
    </customValue>
    <masterLabel>1st Time Home Buyer?</masterLabel>
</GlobalValueSet>

classes/AttendeeController.cls
public with sharing class AttendeeController {

    public static Id primaryclientRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('PrimaryClient').getRecordTypeId();
    /*
    * @description : To get Attendee records
    */ 
    @AuraEnabled(cacheable=true)
    public static List<sumoapp__Attendee__c> getAttendees(String additionalInfoId) {
        return [SELECT Id, sumoapp__ContactRelation__r.Name ,sumoapp__ContactRelation__r.Account.Name, sumoapp__Status__c, Notes__c,sumoapp__IsNotArrived__c, Attendance_Status__c, sumoapp__ContactRelation__r.RecordTypeId, sumoapp__ContactRelation__r.RecordType.Name 
                FROM sumoapp__Attendee__c where sumoapp__ContactRelation__r.Name != null AND sumoapp__ContactRelation__r.AccountId != null AND sumoapp__ContactRelation__r.RecordTypeId!=null AND sumoapp__SumoEvent__c=:additionalInfoId WITH SECURITY_ENFORCED Order BY sumoapp__ContactRelation__r.AccountId];
    }
    
    /*
    * @description : To get Attendee records and metrics
    */ 
    @AuraEnabled
    public static AttendeeWrapper getCourseSeries(String additionalInfoId) {
        AttendeeWrapper wrapper = new AttendeeWrapper();
        Map<Id, sumoapp__AdditionalInfo__c> sessions = new Map<Id, sumoapp__AdditionalInfo__c>([Select Id from sumoapp__AdditionalInfo__c where sumoapp__Parent__c=:additionalInfoId]);
        wrapper.attendees = [SELECT Id, sumoapp__ContactRelation__r.Name ,sumoapp__ContactRelation__r.Account.Name, sumoapp__Status__c, Notes__c,sumoapp__IsNotArrived__c, Attendance_Status__c, sumoapp__ContactRelation__r.RecordTypeId, sumoapp__ContactRelation__r.RecordType.Name 
                            FROM sumoapp__Attendee__c where sumoapp__ContactRelation__r.Name != null AND sumoapp__ContactRelation__r.AccountId != null AND sumoapp__ContactRelation__r.RecordTypeId!=null AND sumoapp__SumoEvent__c In:sessions.keyset() WITH SECURITY_ENFORCED Order BY sumoapp__ContactRelation__r.AccountId];
        wrapper.totalCourseComplete = [Select count() from sumoapp__Attendee__c where Attendance_Status__c='Course Complete' AND sumoapp__SumoEvent__c In:sessions.keyset() WITH SECURITY_ENFORCED];
        wrapper.totalCourseIncomplete = [Select count() from sumoapp__Attendee__c where Attendance_Status__c='Course Incomplete' AND sumoapp__SumoEvent__c In:sessions.keyset() WITH SECURITY_ENFORCED];
        return wrapper;
    }

    @AuraEnabled
    public static void updateAttendeeAttendance(List<Id> attendeeIds, String status, boolean convertProspect, List<Id> prospectContactIds, 
                                                List<Id> prospectAndPrimaryClientContactIds) {
        Map<Id,Contact> conMap = new Map<Id,Contact>();
        if(convertProspect != null && convertProspect == true && prospectContactIds != null ){
            List<Contact> conToUpdate = new List<Contact>();
            for (Id conId : prospectContactIds) {
                conToUpdate.add(new Contact(
                    Id = conId, RecordTypeId = primaryclientRecordTypeId
                ));
            }
            update conToUpdate;
        }
        if(prospectAndPrimaryClientContactIds != null){
            conMap = new Map<Id,Contact>([Select id, RuralAreaStatus__c, HouseholdofAMI__c, AreaMedianIncome__c, ReferralSource__c, MailingCity, MailingState, MailingStateCode, MailingCountryCode, MailingPostalCode, X1stTimeHomeBuyer__c, EnglishProficiency__c, Race__c, Ethnicity__c from Contact where Id in : prospectAndPrimaryClientContactIds]);
        }
        if(attendeeIds.size() > 0){
            List<sumoapp__Attendee__c> attendeesToUpdate = new List<sumoapp__Attendee__c>();
            Map<Id,sumoapp__Attendee__c> attMap = new Map<Id,sumoapp__Attendee__c>([Select id, sumoapp__ContactRelation__c from sumoapp__Attendee__c where id in : attendeeIds]);
            for (Id attendeeId : attendeeIds) {
                sumoapp__Attendee__c att = new sumoapp__Attendee__c();
                att.Id = attendeeId;
                att.Attendance_Status__c = status;
                att.RuralAreaStatus__c = conMap.containskey(attMap.get(attendeeId).sumoapp__ContactRelation__c) ? conMap.get(attMap.get(attendeeId).sumoapp__ContactRelation__c).RuralAreaStatus__c : '';
                att.HouseholdofAMI__c = conMap.containskey(attMap.get(attendeeId).sumoapp__ContactRelation__c) ? conMap.get(attMap.get(attendeeId).sumoapp__ContactRelation__c).HouseholdofAMI__c : 0;
                att.AreaMedianIncome__c = conMap.containskey(attMap.get(attendeeId).sumoapp__ContactRelation__c) ? conMap.get(attMap.get(attendeeId).sumoapp__ContactRelation__c).AreaMedianIncome__c : '';
                
                if(status == 'Course Complete'){
                    att.ReferralSource__c = conMap.containskey(attMap.get(attendeeId).sumoapp__ContactRelation__c) ? conMap.get(attMap.get(attendeeId).sumoapp__ContactRelation__c).ReferralSource__c : '';
                    att.MailingAddress__City__s = conMap.containskey(attMap.get(attendeeId).sumoapp__ContactRelation__c) ? conMap.get(attMap.get(attendeeId).sumoapp__ContactRelation__c).MailingCity : '';
                    att.MailingAddress__StateCode__s = conMap.containskey(attMap.get(attendeeId).sumoapp__ContactRelation__c) ? conMap.get(attMap.get(attendeeId).sumoapp__ContactRelation__c).MailingStateCode : '';
                    att.MailingAddress__CountryCode__s = conMap.containskey(attMap.get(attendeeId).sumoapp__ContactRelation__c) ? conMap.get(attMap.get(attendeeId).sumoapp__ContactRelation__c).MailingCountryCode : '';
                    att.MailingAddress__PostalCode__s = conMap.containskey(attMap.get(attendeeId).sumoapp__ContactRelation__c) ? conMap.get(attMap.get(attendeeId).sumoapp__ContactRelation__c).MailingPostalCode : '';
                    att.X1stTimeHomeBuyer__c = conMap.containskey(attMap.get(attendeeId).sumoapp__ContactRelation__c) ? conMap.get(attMap.get(attendeeId).sumoapp__ContactRelation__c).X1stTimeHomeBuyer__c : '';
                    att.EnglishProficiency__c = conMap.containskey(attMap.get(attendeeId).sumoapp__ContactRelation__c) ? conMap.get(attMap.get(attendeeId).sumoapp__ContactRelation__c).EnglishProficiency__c : '';
                    att.Race__c = conMap.containskey(attMap.get(attendeeId).sumoapp__ContactRelation__c) ? conMap.get(attMap.get(attendeeId).sumoapp__ContactRelation__c).Race__c : '';
                    att.Ethnicity__c = conMap.containskey(attMap.get(attendeeId).sumoapp__ContactRelation__c) ? conMap.get(attMap.get(attendeeId).sumoapp__ContactRelation__c).Ethnicity__c : '';
                }
                
                attendeesToUpdate.add(att);
            }
            update attendeesToUpdate;
        }
    }

    public class AttendeeWrapper{
        @AuraEnabled
        public List<sumoapp__Attendee__c> attendees{get;set;}
        @AuraEnabled
        public Integer totalCourseComplete{get;set;}
        @AuraEnabled
        public Integer totalCourseIncomplete{get;set;}
        
    }
}