objects/Contact.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>Number of people in the household</description>
        <inlineHelpText>Total number of people living in the same household</inlineHelpText>
        <label>Household Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <description>Client Social Security Number</description>
        <label>SSN</label>
        <length>11</length>
        <maskChar>X</maskChar>
        <maskType>ssn</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>TotalMonthlyIncome__c</fullName>
        <label>Total Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>CoApplicant</fullName>
        <active>true</active>
        <label>Co-Applicant</label>
    </recordTypes>
    <recordTypes>
        <fullName>PrimaryClient</fullName>
        <active>true</active>
        <label>Primary Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <label>Prospect</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/HUDAMIData__c.object
<CustomObject>
    <description>To store data related to Area Median Income (AMI) for various regions, including details such as area names, county names, FIPS codes, and HUD-specific identifiers for HUD AMI calculations.</description>
    <fields>
        <fullName>CountyName__c</fullName>
        <description>HUD Income Limit - Official County Name</description>
        <label>County Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MedianFamilyIncome__c</fullName>
        <description>Median Family Income (MFI) for area</description>
        <label>Median Family Income</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TownName__c</fullName>
        <description>Town Name for Income Limit purposes</description>
        <label>Town Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zipcode__c</fullName>
        <label>Zipcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p1__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 1 Persons in Household</description>
        <label>il30 p1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p2__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 2 Persons in Household</description>
        <label>il30 p2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p3__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 3 Persons in Household</description>
        <label>il30 p3</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p4__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 4 Persons in Household</description>
        <label>il30 p4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p1__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 1 Persons in Household</description>
        <label>il50 p1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p2__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 2 Persons in Household</description>
        <label>il50 p2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p3__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 3 Persons in Household</description>
        <label>il50 p3</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p4__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 4 Persons in Household</description>
        <label>il50 p4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p1__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 1 Persons in Household</description>
        <label>il80 p1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p2__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 2 Persons in Household</description>
        <label>il80 p2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p3__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 3 Persons in Household</description>
        <label>il80 p3</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p4__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 4 Persons in Household</description>
        <label>il80 p4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>HUD AMI Data</label>
    <nameField>
        <label>HUD AMI Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HUD AMI Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContactTriggerHandlerTest.cls
@isTest
private class ContactTriggerHandlerTest {
    static Id coappRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName()
        .get('CoApplicant')
        .getRecordTypeId();
    static Id primaryClientRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName()
        .get('PrimaryClient')
        .getRecordTypeId();
    static Id prospectRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName()
        .get('Prospect')
        .getRecordTypeId();
    
    @testSetup
    static void setupTestData() {
        List<HUDAMIData__c> hudamiDataList = new List<HUDAMIData__c>{
            new HUDAMIData__c(CountyName__c = 'County1', TownName__c = 'Town1', 
                              Zipcode__c = '12345', MedianFamilyIncome__c = '50000', il30p1__c = '20000', il30p2__c = '25000', il30p3__c = '30000', il50p1__c = '40000', il50p2__c = '45000', il50p3__c = '50000', il80p1__c = '60000', il80p2__c = '65000', il80p3__c = '70000', il30p4__c = '50000', il50p4__c = '60000', il80p4__c = '70000'),
            new HUDAMIData__c(CountyName__c = 'County2', TownName__c = 'Town2', 
                              Zipcode__c = '67890', MedianFamilyIncome__c = '60000', il30p2__c = '25000', il30p3__c = '30000', il50p1__c = '40000', il50p2__c = '45000', il50p3__c = '50000', il80p1__c = '60000', il80p2__c = '65000', il80p3__c = '70000', il30p4__c = '50000', il50p4__c = '60000', il80p4__c = '70000')
        };
        insert hudamiDataList;
    }
    
    @isTest
    static void Test1() {
        
        Account acc = TestDataFactory.createAccounts(1, true)[0];
        Contact coappContact = TestDataFactory.createContacts(acc.id,1, false)[0];
        coappContact.FirstName = 'Jhon';
        coappContact.LastName = 'Jordan';
        coappContact.Email = 'Jhon@Jordan.com';
        coappContact.AccountId = acc.Id;
        coappContact.TotalMonthlyIncome__c = 5555;
        coappContact.RecordTypeId = coappRecTypeId;
        coappContact.MailingPostalCode = '12345';
        coappContact.isActive__c = true;  
        insert coappContact;

        coappContact.FirstName = 'Updaed';
        coappContact.isActive__c = true;
        coappContact.TotalMonthlyIncome__c = 55345;
        update coappContact;
    }

@isTest
    static void Test10() {
        Account acc = TestDataFactory.createAccounts(1, true)[0];
        Contact coappContact = TestDataFactory.createContacts(acc.id,1, false)[0];
        coappContact.AccountId = acc.Id;
        coappContact.TotalMonthlyIncome__c = 5555;
        coappContact.RecordTypeId = coappRecTypeId;
        coappContact.MailingPostalCode = '12345';
        coappContact.isActive__c = true;  
        insert coappContact;
        
        coappContact.MailingPostalCode = '5525';
        update coappContact;
    }    
    @isTest
    static void Test2() {
        Account acc = TestDataFactory.createAccounts(1, true)[0];
        Contact coappContact = TestDataFactory.createContacts(acc.id,1, false)[0];
        coappContact.AccountId = acc.Id;
        coappContact.TotalMonthlyIncome__c = 5555;
        coappContact.RecordTypeId = coappRecTypeId;
        coappContact.MailingPostalCode = '12345';
        coappContact.isActive__c = true;
        coappContact.County__c = 'County1';
        coappContact.Town__c = 'Town1';
        coappContact.HouseholdSize__c = 3;
        insert coappContact;
        
        Contact primaryClientContact = TestDataFactory.createContacts(acc.id,1, false)[0];
        primaryClientContact.FirstName = 'Asad';
        primaryClientContact.LastName = 'Ali';
        primaryClientContact.Email = 'Asad.hr@Ali.com';
        primaryClientContact.AccountId = acc.Id;
        primaryClientContact.TotalMonthlyIncome__c = 5555;
        primaryClientContact.RecordTypeId = primaryClientRecTypeId;
        primaryClientContact.MailingPostalCode = '12345';
        primaryClientContact.isActive__c = true;
        primaryClientContact.County__c = 'County1';
        primaryClientContact.Town__c = 'Town1';
        primaryClientContact.HouseholdSize__c = 3;
        primaryClientContact.SSN__c = '999999999';
        
        Test.startTest();  
        insert primaryClientContact;
        primaryClientContact.MailingPostalCode = '67890';
        primaryClientContact.County__c = 'County2';
        primaryClientContact.Town__c = 'Town2';
        primaryClientContact.HouseholdSize__c = 4;
        primaryClientContact.TotalMonthlyIncome__c = 5555;
        primaryClientContact.SSN__c = '888888888';
        update primaryClientContact;
        Test.stopTest();
    }
    
    @isTest
    static void Test3() {
        
        Account acc = TestDataFactory.createAccounts(1, true)[0];
        Contact primaryClientContact = TestDataFactory.createContacts(acc.id,1, false)[0];
        primaryClientContact.FirstName = 'Asad';
        primaryClientContact.LastName = 'Ali';
        primaryClientContact.Email = 'Asad.hr@Ali.com';
        primaryClientContact.AccountId = acc.Id;
        primaryClientContact.TotalMonthlyIncome__c = 5555;
        primaryClientContact.RecordTypeId = prospectRecTypeId;
        primaryClientContact.MailingPostalCode = '12345';
        primaryClientContact.isActive__c = true;
        primaryClientContact.County__c = 'County';
        primaryClientContact.Town__c = 'Town';
        primaryClientContact.HouseholdSize__c = 3;
        
        Test.startTest();  
        insert primaryClientContact;
        primaryClientContact.isActive__c = False;
        primaryClientContact.MailingPostalCode = '6782290';
        update primaryClientContact;
        Test.stopTest();
    }
}