objects/Contact.object
<CustomObject>
    <fields>
        <fullName>HouseholdType__c</fullName>
        <label>Household Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MaritalStatus__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>HouseholdTypeHeadofHousehold</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MaritalStatus__c</fullName>
        <description>Pre-defined  list</description>
        <label>Marital Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MaritalStatus</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/HouseholdTypeHeadofHousehold.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Single adult</fullName>
    </customValue>
    <customValue>
        <fullName>Female-headed single parent household</fullName>
    </customValue>
    <customValue>
        <fullName>Male-headed single parent household</fullName>
    </customValue>
    <customValue>
        <fullName>Married without dependents</fullName>
    </customValue>
    <customValue>
        <fullName>Married with dependents</fullName>
    </customValue>
    <customValue>
        <fullName>Two or more unrelated Adults</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Married with children</fullName>
        <isActive>false</isActive>
        <label>Married with children</label>
    </customValue>
    <customValue>
        <fullName>Male-headed single parent household/Head of Household</fullName>
        <isActive>false</isActive>
        <label>Male-headed single parent household/Head of Household</label>
    </customValue>
    <customValue>
        <fullName>Female-headed single parent household/Head of Household</fullName>
        <isActive>false</isActive>
        <label>Female-headed single parent household/Head of Household</label>
    </customValue>
    <customValue>
        <fullName>Domestic partnership</fullName>
        <isActive>false</isActive>
        <label>Domestic partnership</label>
    </customValue>
    <customValue>
        <fullName>Married without children</fullName>
        <isActive>false</isActive>
        <label>Married without children</label>
    </customValue>
    <masterLabel>Household Type/Head of Household</masterLabel>
</GlobalValueSet>

globalValueSets/MaritalStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Married</fullName>
    </customValue>
    <customValue>
        <fullName>Single</fullName>
    </customValue>
    <customValue>
        <fullName>Divorced</fullName>
    </customValue>
    <customValue>
        <fullName>Separated</fullName>
    </customValue>
    <customValue>
        <fullName>Widowed</fullName>
    </customValue>
    <customValue>
        <fullName>Choose not to respond</fullName>
    </customValue>
    <customValue>
        <fullName>Legally Separated</fullName>
        <isActive>false</isActive>
        <label>Legally Separated</label>
    </customValue>
    <masterLabel>Marital Status</masterLabel>
</GlobalValueSet>

classes/DependencyMatrixGenerator.cls
public class DependencyMatrixGenerator {

    //DependencyMatrixGenerator.getFieldDependencies('Contact', 'MaritalStatus__c' ,'HouseholdType__c')
    
    @AuraENabled(Cacheable=true)
    public static Map<String,List<PickListInfo>> getDependencyMatrix(String objectName, String controllingField, String dependentField) {
        
        Schema.SObjectType objType = Schema.getGlobalDescribe().get(objectName);
        Schema.DescribeSObjectResult describeResult = objType.getDescribe();
        Schema.DescribeFieldResult controllingFieldInfo = describeResult.fields.getMap().get(controllingField).getDescribe();
        Schema.DescribeFieldResult dependentFieldInfo = describeResult.fields.getMap().get(dependentField).getDescribe();
        
        List<Schema.PicklistEntry> controllingValues = controllingFieldInfo.getPicklistValues();
        List<Schema.PicklistEntry> dependentValues = dependentFieldInfo.getPicklistValues();
        
         Map<String, List<PickListInfo>> dependencyMatrix = new Map<String, List<PickListInfo>>();
        
        Integer index=0;
        for(Schema.PicklistEntry controllingValue : controllingValues) {
            System.debug('Index :: '+(index++)+' Value :: '+controllingValue.getValue());
            dependencyMatrix.put(controllingValue.getValue(), new List<PickListInfo>());
        }
        
       
        
        for(Schema.PicklistEntry currDependentValue : dependentValues) {
            PickListInfo picklist = (PickListInfo)JSON.deserialize(JSON.serialize(currDependentValue), PickListInfo.class);
            //System.debug(picklist);
			String hexString = EncodingUtil.convertToHex(EncodingUtil.base64Decode(picklist.validFor)).toUpperCase();
            

            System.debug('Picklist Values :: '+picklist+'Hex Code :: '+hexString);
            Integer baseCount=0;
            //if(picklist.value=='Other') {
                //System.debug('Understanding Hex :: for :: '+hexString);
                //We are getting first 4 in each index
                for(Integer curr : hexString.getChars()) {
                    Integer hexVal;
                    if(curr>=65) {
                        hexVal=(curr-65)+10;
                    } else {
                        hexVal=curr+48;
                    }
                    
                    if((hexVal & 8)==8) {
                        dependencyMatrix.get(controllingValues.get(baseCount+0).getValue()).add(picklist);
                    }
                    
                    if((hexVal & 4)==4) {
                        dependencyMatrix.get(controllingValues.get(baseCount+1).getValue()).add(picklist);
                    }
                    
                    if((hexVal & 2)==2) {
                        dependencyMatrix.get(controllingValues.get(baseCount+2).getValue()).add(picklist);
                    }
                    
                    if((hexVal & 1)==1) {
                        dependencyMatrix.get(controllingValues.get(baseCount+3).getValue()).add(picklist);
                    }
                    
                    baseCount += 4;
                    
                    
                }
            //}
        }
        
        System.debug('If it works ::');
        
        for(String key : dependencyMatrix.keyset()) {
            System.debug('Key ::: '+ key);
            System.debug('Value ::: '+dependencyMatrix.get(key));
        }
        return dependencyMatrix;
    }
    
    public class PickListInfo
    {
        @AuraEnabled 
        public String validFor{get;set;}
        @AuraEnabled
        public String label{get;set;}
        @AuraEnabled
        public String value{get;set;}
    }
}