objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AreaMedianIncome__c</fullName>
        <label>Area Median Income</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Below 30% of AMI</fullName>
                </value>
                <value>
                    <fullName>30 - 49% of AMI</fullName>
                </value>
                <value>
                    <fullName>50 - 79% of AMI</fullName>
                </value>
                <value>
                    <fullName>80 - 100% of AMI</fullName>
                </value>
                <value>
                    <fullName>101% - 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Above 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Chose not to respond</fullName>
                </value>
                <value>
                    <fullName>Above 100% AMI</fullName>
                    <isActive>false</isActive>
                    <label>Above 100% AMI</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <description>Client’s self-identified ethnicity, used in 9902 reporting</description>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HouseholdOfAMI__c</fullName>
        <label>Household % Of AMI</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <description>Which HUD 9902-recognized race category the contact belongs to.</description>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RuralAreaStatus__c</fullName>
        <description>Whether or not this contact resides in a rural area as defined by HUD.</description>
        <label>Rural Area Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Rural_Area_Status</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>CoApplicant</fullName>
        <active>true</active>
        <label>Co-Applicant</label>
    </recordTypes>
    <recordTypes>
        <fullName>PrimaryClient</fullName>
        <active>true</active>
        <label>Primary Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <label>Prospect</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>Facilitator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facilitator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Open_Seats__c</fullName>
        <formula>IF( NOT( ISNULL(sumoapp__Capacity__c)) , IF((sumoapp__Capacity__c - TotalEnrolled__c)&gt;=0,TEXT(sumoapp__Capacity__c - TotalEnrolled__c),&apos;0&apos;), &apos;Unlimited&apos;)</formula>
        <label>Open Seats</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalEnrolled__c</fullName>
        <label>Total Enrolled</label>
        <summaryForeignKey>sumoapp__Attendee__c.sumoapp__SumoEvent__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Duration_In_Minutes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Duration In Minutes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sumoapp__Capacity__c</fullName>
        <inlineHelpText>The total # of seats or people allowed to register for this event, once met, the event is considered SOLD OUT.  If blank, then capacity is unlimited.</inlineHelpText>
        <label>Capacity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sumoapp__Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If you would like people to self-register for this Event, you must choose a category to effectively tie this Event to the Online Scheduler.</inlineHelpText>
        <label>Category</label>
        <referenceTo>sumoapp__Category__c</referenceTo>
        <relationshipLabel>Category Activities</relationshipLabel>
        <relationshipName>CategoryActivities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__DurationInMinutes__c</fullName>
        <formula>( sumoapp__EndDatetime__c -  sumoapp__StartDatetime__c )*1440</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duration In Minutes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sumoapp__EndDatetime__c</fullName>
        <label>End Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__EventName__c</fullName>
        <label>Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__LocationType__c</fullName>
        <label>Location Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__Organizer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organizer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Organizer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Child Events</relationshipLabel>
        <relationshipName>ChildEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__PricePerSeat__c</fullName>
        <label>Price per Seat</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>sumoapp__Price__c</fullName>
        <label>Price</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>sumoapp__RecurringCount__c</fullName>
        <label>Recurring Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BOOKED</fullName>
                    <default>true</default>
                    <label>Booked</label>
                </value>
                <value>
                    <fullName>CANCELED</fullName>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>RESCHEDULED</fullName>
                    <label>Rescheduled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sumoapp__TotalRegisteredAttendee__c</fullName>
        <label>Total Registered Attendee</label>
        <summarizedField>sumoapp__Attendee__c.sumoapp__NumberOfSeats__c</summarizedField>
        <summaryFilterItems>
            <field>sumoapp__Attendee__c.sumoapp__IsRegisteredSeats__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>sumoapp__Attendee__c.sumoapp__SumoEvent__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>sumoapp__VirtualEventType__c</fullName>
        <label>Virtual Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>sumoapp__WebConferenceTypes</valueSetName>
        </valueSet>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__Attendee__c.object
<CustomObject>
    <fields>
        <fullName>AreaMedianIncome__c</fullName>
        <label>Area Median Income</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Below 30% of AMI</fullName>
                </value>
                <value>
                    <fullName>30 - 49% of AMI</fullName>
                </value>
                <value>
                    <fullName>50 - 79% of AMI</fullName>
                </value>
                <value>
                    <fullName>80 - 100% of AMI</fullName>
                </value>
                <value>
                    <fullName>101% - 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Above 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Chose not to respond</fullName>
                </value>
                <value>
                    <fullName>Above 100% AMI</fullName>
                    <isActive>false</isActive>
                    <label>Above 100% AMI</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HouseholdofAMI__c</fullName>
        <label>Household % Of AMI</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RuralAreaStatus__c</fullName>
        <label>Rural Area Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Rural_Area_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>sumoapp__ContactRelation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Relation</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Event Attendees</relationshipLabel>
        <relationshipName>ContactEventAttendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__EndDatetime__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__EndDatetime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__EventName__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__EventName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__StartDatetime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>CANCELED</fullName>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>COMPLIMENTARY</fullName>
                    <label>Complimentary</label>
                </value>
                <value>
                    <fullName>DECLINED</fullName>
                    <label>Declined</label>
                </value>
                <value>
                    <fullName>DRAFT</fullName>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>REFUNDED</fullName>
                    <label>Fully Refunded</label>
                </value>
                <value>
                    <fullName>PAID_MANUAL</fullName>
                    <label>Paid - Manual</label>
                </value>
                <value>
                    <fullName>PAID</fullName>
                    <label>Paid - Online</label>
                </value>
                <value>
                    <fullName>PARTIALLY_REFUNDED</fullName>
                    <label>Partially Refunded</label>
                </value>
                <value>
                    <fullName>BOOKED</fullName>
                    <default>true</default>
                    <label>Registered</label>
                </value>
                <value>
                    <fullName>WAITLISTED</fullName>
                    <label>Waitlisted</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sumoapp__SumoEvent__c</fullName>
        <label>SUMO Event</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SUMO Attendee</label>
    <nameField>
        <displayFormat>ATD-{000000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/sumoapp__Category__c.object
<CustomObject>
    <fields>
        <fullName>sumoapp__Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SUMO Category</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Ethnicity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Not Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Ethnicity</description>
    <masterLabel>Ethnicity</masterLabel>
</GlobalValueSet>

globalValueSets/Race.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>American Indian/Alaskan Native</fullName>
    </customValue>
    <customValue>
        <fullName>Asian</fullName>
    </customValue>
    <customValue>
        <fullName>Black or African American</fullName>
    </customValue>
    <customValue>
        <fullName>Native Hawaiian or Other Pacific Islander</fullName>
    </customValue>
    <customValue>
        <fullName>White</fullName>
    </customValue>
    <customValue>
        <fullName>More than one race</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Race</description>
    <masterLabel>Race</masterLabel>
</GlobalValueSet>

globalValueSets/Rural_Area_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Lives in a rural area</fullName>
    </customValue>
    <customValue>
        <fullName>Does not live in a rural area</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Rural Area Status</description>
    <masterLabel>Rural Area Status</masterLabel>
</GlobalValueSet>

globalValueSets/sumoapp__WebConferenceTypes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>USERS_LINK</fullName>
        <label>User&apos;s Link</label>
    </customValue>
    <customValue>
        <fullName>ZOOM</fullName>
        <label>Zoom</label>
    </customValue>
    <customValue>
        <fullName>MICROSOFT_TEAMS</fullName>
        <label>Microsoft Teams</label>
    </customValue>
    <masterLabel>Web Conference Types</masterLabel>
</GlobalValueSet>

classes/CourseManagementController.cls
/*
* @author         Mahesh Panda
* @description    Controller class containing methods for Course Management
* @date           2024-04-12
* @group          Course Management
*/
public with sharing class CourseManagementController {
    
    /*
* @description    This method is used to get the courses on load of the course management screen
*/
    @AuraEnabled(cacheable=true)
    public static List<sumoapp__AdditionalInfo__c> getCourses() {
        if(Schema.sObjectType.sumoapp__AdditionalInfo__c.isAccessible()){
            return [Select Id,RecordType.DeveloperName,sumoapp__EventName__c, sumoapp__StartDatetime__c, sumoapp__EndDatetime__c, sumoapp__VirtualEventType__c,  
                     sumoapp__DurationInMinutes__c,sumoapp__Price__c, sumoapp__TotalRegisteredAttendee__c, sumoapp__Capacity__c, sumoapp__LocationType__c, Total_Duration_In_Minutes__c, sumoapp__Status__c,
                     Open_Seats__c, TotalEnrolled__c, sumoapp__Category__r.sumoapp__Label__c, Facilitator__c, Facilitator__r.Name, sumoapp__Organizer__r.Name, sumoapp__PricePerSeat__c,  
                    (Select Id,sumoapp__EventName__c, sumoapp__StartDatetime__c, sumoapp__EndDatetime__c, sumoapp__VirtualEventType__c, 
                     sumoapp__DurationInMinutes__c,sumoapp__Price__c, sumoapp__TotalRegisteredAttendee__c, sumoapp__Capacity__c, sumoapp__LocationType__c, sumoapp__Status__c,
                     Open_Seats__c, TotalEnrolled__c, sumoapp__Category__r.sumoapp__Label__c, Facilitator__c, Facilitator__r.Name, sumoapp__Organizer__r.Name, sumoapp__PricePerSeat__c    
                     from sumoapp__ChildEvents__r order by sumoapp__StartDatetime__c DESC) 
                    FROM sumoapp__AdditionalInfo__c 
                    where (sumoapp__StartDatetime__c = THIS_YEAR OR sumoapp__EndDatetime__c = THIS_YEAR) 
                    AND (RecordType.DeveloperName = 'Course' or RecordType.DeveloperName = 'Event') 
                    and sumoapp__Parent__c=null WITH SECURITY_ENFORCED order by sumoapp__StartDatetime__c DESC];
        }
        return null;
    }
    
    /*
* @description    This method is used to get the contact related to enrollment related functionality
*/
    @AuraEnabled(cacheable=true)
    public static List<Contact> getContacts(Id eventId) {
        Set<Id> contactIds = new Set<Id>();

        for(sumoapp__Attendee__c attendee:[SELECT Id, sumoapp__ContactRelation__c from sumoapp__Attendee__c where sumoapp__SumoEvent__c=:eventId]){
            contactIds.add(attendee.sumoapp__ContactRelation__c);
        }
        if(Schema.sObjectType.Contact.isAccessible()){
            return [Select id, LastName, FirstName, Phone, RecordType.Name, Email FROM Contact where Id Not In:contactIds and RecordType.DeveloperName IN ('CoApplicant', 'PrimaryClient', 'Prospect') WITH SECURITY_ENFORCED order by createddate desc];
        }
        return null;
    }
    
    /*
* @description    This method is used to filter courses based on start date and end date
*/
    @AuraEnabled(cacheable=true)
    public static List<sumoapp__AdditionalInfo__c> filterRows(String searchKeyword, Date startDate, Date endDate) {
        searchKeyword = String.escapeSingleQuotes(searchKeyword);
        searchKeyword = '%'+searchKeyword+'%';
        if(Schema.sObjectType.sumoapp__AdditionalInfo__c.isAccessible()){
            List<sumoapp__AdditionalInfo__c> recList = [Select id,RecordType.DeveloperName,sumoapp__Price__c, sumoapp__EndDatetime__c, sumoapp__EventName__c, sumoapp__RecurringCount__c, sumoapp__StartDatetime__c, sumoapp__LocationType__c,
                                                         sumoapp__DurationInMinutes__c, sumoapp__TotalRegisteredAttendee__c, sumoapp__Capacity__c, sumoapp__VirtualEventType__c,Total_Duration_In_Minutes__c, sumoapp__Status__c,
                                                         Open_Seats__c, TotalEnrolled__c, sumoapp__Category__r.sumoapp__Label__c, Facilitator__c, Facilitator__r.Name, sumoapp__Organizer__r.Name, sumoapp__PricePerSeat__c , 
                                                        (Select Id,sumoapp__EventName__c,sumoapp__Price__c, sumoapp__StartDatetime__c, sumoapp__EndDatetime__c, sumoapp__LocationType__c, sumoapp__Status__c,
                                                         sumoapp__DurationInMinutes__c,Total_Duration_In_Minutes__c, sumoapp__TotalRegisteredAttendee__c, sumoapp__Capacity__c, sumoapp__VirtualEventType__c,
                                                         Open_Seats__c, TotalEnrolled__c, sumoapp__Category__r.sumoapp__Label__c, Facilitator__c, Facilitator__r.Name, sumoapp__Organizer__r.Name, sumoapp__PricePerSeat__c
                                                         FROM sumoapp__ChildEvents__r WHERE (sumoapp__EventName__c like :searchKeyword or 
                                                                                             sumoapp__Organizer__r.Name like :searchKeyword or 
                                                                                             sumoapp__Category__r.sumoapp__Label__c like :searchKeyword or 
                                                                                             sumoapp__LocationType__c like :searchKeyword)) 
                                                        FROM sumoapp__AdditionalInfo__c 
                                                        WHERE (RecordType.DeveloperName = 'Course' or RecordType.DeveloperName = 'Event') 
                                                        AND sumoapp__Parent__c = null
                                                        AND ((sumoapp__StartDatetime__c >= :startDate AND sumoapp__StartDatetime__c <= :endDate) 
                                                             OR (sumoapp__EndDatetime__c >= :startDate AND sumoapp__EndDatetime__c <= :endDate))
                                                        WITH SECURITY_ENFORCED
                                                        ORDER BY sumoapp__StartDatetime__c DESC];
            List<sumoapp__AdditionalInfo__c> finalRecList = new List<sumoapp__AdditionalInfo__c>();
            searchKeyword = searchKeyword.remove('%');
            for(sumoapp__AdditionalInfo__c rec : recList){
                if(rec.sumoapp__ChildEvents__r.size() > 0 || (string.isNotBlank(rec.sumoapp__EventName__c) && rec.sumoapp__EventName__c.containsIgnoreCase(searchKeyword))){
                    finalRecList.add(rec);
                }
            }
            return finalRecList;
        }
        return null;
    }

    @AuraEnabled
      public static void createAttendees(List<Id> contactIds, Id eventId, boolean isParent) {
          Set<Id> existingAttendeeIds = new Set<Id>();
          List<sumoapp__Attendee__c> attendees = new List<sumoapp__Attendee__c>();
          Map<Id, sumoapp__AdditionalInfo__c> eventMap = isParent?new Map<Id, sumoapp__AdditionalInfo__c>([Select Id, sumoapp__Parent__c, RecordType.DeveloperName from sumoapp__AdditionalInfo__c where sumoapp__Parent__c=:eventId ]):new Map<Id, sumoapp__AdditionalInfo__c>([Select Id, sumoapp__Parent__c,RecordType.DeveloperName from sumoapp__AdditionalInfo__c where Id=:eventId ]);
          Map<Id,Contact> conMap = new Map<Id,Contact>([Select id, HouseholdofAMI__c, AreaMedianIncome__c, RuralAreaStatus__c, Race__c, Ethnicity__c, EnglishProficiency__c, X1stTimeHomeBuyer__c,
                                                        MailingStreet, MailingCity, MailingStateCode, MailingCountryCode, MailingPostalCode, ChoseNottoProvideIncome__c from Contact where id in:contactIds WITH SECURITY_ENFORCED]);
          Map<Id, sumoapp__Attendee__c> attendeeMap = new Map<Id, sumoapp__Attendee__c>([Select Id, sumoapp__SumoEvent__c, sumoapp__ContactRelation__c from sumoapp__Attendee__c where sumoapp__SumoEvent__c IN: eventMap.keyset()]);
          for(sumoapp__Attendee__c attendee: attendeeMap.values()){
                if(contactIds.contains(attendee.sumoapp__ContactRelation__c)){

                 existingAttendeeIds.add(attendee.sumoapp__ContactRelation__c);
                }
          }
          
          for (Id contactId : contactIds) {
            if(!existingAttendeeIds.contains(contactId)){
            boolean isParentCreated = false;
            for(sumoapp__AdditionalInfo__c event:eventMap.values()){
                if(!isParentCreated && event.RecordType.DeveloperName!='Event'){
                    sumoapp__Attendee__c attendee = new sumoapp__Attendee__c();
                    attendee.sumoapp__ContactRelation__c = contactId;
                    attendee.sumoapp__SumoEvent__c = event.sumoapp__Parent__c;
                    attendee.HouseholdofAMI__c = conMap.get(contactId).HouseholdofAMI__c;
                    attendee.AreaMedianIncome__c = conMap.get(contactId).AreaMedianIncome__c;
                    attendee.RuralAreaStatus__c = conMap.get(contactId).RuralAreaStatus__c;
                    attendee.Race__c = conMap.get(contactId).Race__c;
                    attendee.Ethnicity__c = conMap.get(contactId).Ethnicity__c;
                    attendee.X1stTimeHomeBuyer__c = conMap.get(contactId).X1stTimeHomeBuyer__c;
                    attendee.EnglishProficiency__c = conMap.get(contactId).EnglishProficiency__c;
                    attendee.MailingAddress__Street__s = conMap.get(contactId).MailingStreet;
                    attendee.MailingAddress__City__s = conMap.get(contactId).MailingCity;
                    attendee.MailingAddress__StateCode__s = conMap.get(contactId).MailingStateCode;
                    attendee.MailingAddress__CountryCode__s = conMap.get(contactId).MailingCountryCode;
                    attendee.MailingAddress__PostalCode__s = conMap.get(contactId).MailingPostalCode;
                    attendee.ChoseNottoProvideIncome__c = conMap.get(contactId).ChoseNottoProvideIncome__c;
                    attendee.sumoapp__NumberOfSeats__c = 1;
                    attendees.add(attendee);
                    isParentCreated = true;
                }
                sumoapp__Attendee__c attendee = new sumoapp__Attendee__c();
                attendee.sumoapp__ContactRelation__c = contactId;
                attendee.sumoapp__SumoEvent__c = event.Id;
                attendee.HouseholdofAMI__c = conMap.get(contactId).HouseholdofAMI__c;
                attendee.AreaMedianIncome__c = conMap.get(contactId).AreaMedianIncome__c;
                attendee.RuralAreaStatus__c = conMap.get(contactId).RuralAreaStatus__c;
                attendee.Race__c = conMap.get(contactId).Race__c;
                attendee.Ethnicity__c = conMap.get(contactId).Ethnicity__c;
                attendee.X1stTimeHomeBuyer__c = conMap.get(contactId).X1stTimeHomeBuyer__c;
                attendee.EnglishProficiency__c = conMap.get(contactId).EnglishProficiency__c;
                attendee.MailingAddress__Street__s = conMap.get(contactId).MailingStreet;
                attendee.MailingAddress__City__s = conMap.get(contactId).MailingCity;
                attendee.MailingAddress__StateCode__s = conMap.get(contactId).MailingStateCode;
                attendee.MailingAddress__CountryCode__s = conMap.get(contactId).MailingCountryCode;
                attendee.MailingAddress__PostalCode__s = conMap.get(contactId).MailingPostalCode;
                attendee.ChoseNottoProvideIncome__c = conMap.get(contactId).ChoseNottoProvideIncome__c;
                attendee.sumoapp__NumberOfSeats__c = 1;
                attendees.add(attendee);
            }
          }
        }
          system.debug('attendees '+attendees);
        if(!attendees.isempty()){
          insert attendees;
        }
      }
}