objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <formula>YEAR(TODAY()) - YEAR(Birthdate) - IF(MONTH(TODAY()) * 100 + DAY(TODAY()) &lt; MONTH(Birthdate) * 100 + DAY(Birthdate), 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AreaMedianIncome__c</fullName>
        <label>Area Median Income</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Below 30% of AMI</fullName>
                </value>
                <value>
                    <fullName>30 - 49% of AMI</fullName>
                </value>
                <value>
                    <fullName>50 - 79% of AMI</fullName>
                </value>
                <value>
                    <fullName>80 - 100% of AMI</fullName>
                </value>
                <value>
                    <fullName>101% - 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Above 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Chose not to respond</fullName>
                </value>
                <value>
                    <fullName>Above 100% AMI</fullName>
                    <isActive>false</isActive>
                    <label>Above 100% AMI</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <formula>Account.ClientNumber__c</formula>
        <label>Client #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DisabledStatus__c</fullName>
        <label>Disabled Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <description>Client’s self-identified ethnicity, used in 9902 reporting</description>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Male, Female, Other/Non-Conforming</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HouseholdMonthlyIncome1__c</fullName>
        <label>Household Monthly Income</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>Number of people in the household</description>
        <inlineHelpText>Total number of people living in the same household</inlineHelpText>
        <label>Household Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HouseholdType__c</fullName>
        <label>Household Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MaritalStatus__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>HouseholdTypeHeadofHousehold</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MailingAddressLine2__c</fullName>
        <label>Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreferredLanguage__c</fullName>
        <description>Client’s preferred language</description>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English (US)</label>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>ASL</fullName>
                </value>
                <value>
                    <fullName>Cambodian</fullName>
                </value>
                <value>
                    <fullName>Cantonese</fullName>
                </value>
                <value>
                    <fullName>Chinese Mandarin</fullName>
                </value>
                <value>
                    <fullName>Creole</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Goboligok</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hmong</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latin</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
                <value>
                    <fullName>Portuuguese</fullName>
                </value>
                <value>
                    <fullName>Russian</fullName>
                </value>
                <value>
                    <fullName>Swahili</fullName>
                </value>
                <value>
                    <fullName>Turkish</fullName>
                </value>
                <value>
                    <fullName>Ukrainian</fullName>
                </value>
                <value>
                    <fullName>Urdu</fullName>
                </value>
                <value>
                    <fullName>Vietnamese</fullName>
                </value>
                <value>
                    <fullName>Yiddish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <description>Which HUD 9902-recognized race category the contact belongs to.</description>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RuralAreaStatus__c</fullName>
        <description>Whether or not this contact resides in a rural area as defined by HUD.</description>
        <label>Rural Area Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Rural_Area_Status</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>ExcludeCourseFromHUD9902__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude Course From HUD 9902</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsParent__c</fullName>
        <formula>IsBlank(sumoapp__Parent__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sumoapp__EndDatetime__c</fullName>
        <label>End Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BOOKED</fullName>
                    <default>true</default>
                    <label>Booked</label>
                </value>
                <value>
                    <fullName>CANCELED</fullName>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>RESCHEDULED</fullName>
                    <label>Rescheduled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__Attendee__c.object
<CustomObject>
    <fields>
        <fullName>AreaMedianIncome__c</fullName>
        <label>Area Median Income</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Below 30% of AMI</fullName>
                </value>
                <value>
                    <fullName>30 - 49% of AMI</fullName>
                </value>
                <value>
                    <fullName>50 - 79% of AMI</fullName>
                </value>
                <value>
                    <fullName>80 - 100% of AMI</fullName>
                </value>
                <value>
                    <fullName>101% - 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Above 120% of AMI</fullName>
                </value>
                <value>
                    <fullName>Chose not to respond</fullName>
                </value>
                <value>
                    <fullName>Above 100% AMI</fullName>
                    <isActive>false</isActive>
                    <label>Above 100% AMI</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Attendance_Status__c</fullName>
        <label>Attendee Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Attended - Complete</fullName>
                </value>
                <value>
                    <fullName>Attended - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Course Complete</fullName>
                </value>
                <value>
                    <fullName>Course Incomplete</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <formula>sumoapp__ContactRelation__r.HouseholdSize__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Household Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <formula>TEXT( sumoapp__SumoEvent__r.HUD_Purpose__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outcome</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RuralAreaStatus__c</fullName>
        <label>Rural Area Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Rural_Area_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>sumoapp__ContactRelation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Relation</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Event Attendees</relationshipLabel>
        <relationshipName>ContactEventAttendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__EndDatetime__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__EndDatetime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__SumoEvent__c</fullName>
        <label>SUMO Event</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SUMO Attendee</label>
    <nameField>
        <displayFormat>ATD-{000000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Ethnicity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Not Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Ethnicity</description>
    <masterLabel>Ethnicity</masterLabel>
</GlobalValueSet>

globalValueSets/Gender.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <customValue>
        <fullName>Other/Non-conforming</fullName>
    </customValue>
    <description>Gender</description>
    <masterLabel>Gender</masterLabel>
</GlobalValueSet>

globalValueSets/HouseholdTypeHeadofHousehold.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Single adult</fullName>
    </customValue>
    <customValue>
        <fullName>Female-headed single parent household</fullName>
    </customValue>
    <customValue>
        <fullName>Male-headed single parent household</fullName>
    </customValue>
    <customValue>
        <fullName>Married without dependents</fullName>
    </customValue>
    <customValue>
        <fullName>Married with dependents</fullName>
    </customValue>
    <customValue>
        <fullName>Two or more unrelated Adults</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Married with children</fullName>
        <isActive>false</isActive>
        <label>Married with children</label>
    </customValue>
    <customValue>
        <fullName>Male-headed single parent household/Head of Household</fullName>
        <isActive>false</isActive>
        <label>Male-headed single parent household/Head of Household</label>
    </customValue>
    <customValue>
        <fullName>Female-headed single parent household/Head of Household</fullName>
        <isActive>false</isActive>
        <label>Female-headed single parent household/Head of Household</label>
    </customValue>
    <customValue>
        <fullName>Domestic partnership</fullName>
        <isActive>false</isActive>
        <label>Domestic partnership</label>
    </customValue>
    <customValue>
        <fullName>Married without children</fullName>
        <isActive>false</isActive>
        <label>Married without children</label>
    </customValue>
    <masterLabel>Household Type/Head of Household</masterLabel>
</GlobalValueSet>

globalValueSets/Race.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>American Indian/Alaskan Native</fullName>
    </customValue>
    <customValue>
        <fullName>Asian</fullName>
    </customValue>
    <customValue>
        <fullName>Black or African American</fullName>
    </customValue>
    <customValue>
        <fullName>Native Hawaiian or Other Pacific Islander</fullName>
    </customValue>
    <customValue>
        <fullName>White</fullName>
    </customValue>
    <customValue>
        <fullName>More than one race</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Race</description>
    <masterLabel>Race</masterLabel>
</GlobalValueSet>

globalValueSets/Rural_Area_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Lives in a rural area</fullName>
    </customValue>
    <customValue>
        <fullName>Does not live in a rural area</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Rural Area Status</description>
    <masterLabel>Rural Area Status</masterLabel>
</GlobalValueSet>

classes/NWQREducationReportController.cls
/**
 * @description       : Controller of HudOrsEducationReport lwc for NWQR reporting
 * @group             : 
**/
public with sharing class NWQREducationReportController {
    
    public static DateTime GMTStartDate;
    public static DateTime GMTEndDate;
    
    public static void setUTCStartEndDateTime(Date qtrStartDate,Date qtrEndDate){
        DateTime qtrStartDateTime = DateTime.newInstance(qtrStartDate.year(), qtrStartDate.month(), qtrStartDate.day());
        DateTime qtrEndDateTime = DateTime.newInstance(qtrEndDate.year(), qtrEndDate.month(), qtrEndDate.day(),23,59,59);
    	GMTStartDate = qtrStartDateTime.addHours(-UserInfo.getTimeZone().getOffset(qtrStartDateTime) / 3600000);
        GMTEndDate = qtrEndDateTime.addHours(-UserInfo.getTimeZone().getOffset(qtrEndDateTime) / 3600000);
    }
    
    /*
    * @description : method to fetch Education records
    */
    @AuraEnabled
    public static List<OrsReportWrapper> fetchOrsEducationRecords(Date qtrStartDate,Date qtrEndDate){
        setUTCStartEndDateTime(qtrStartDate, qtrEndDate);
        String currentUserTimeZone = [select id,TimeZoneSidKey from user where id =: UserInfo.getUserId()].TimeZoneSidKey;
        system.debug('GMTStartDate = '+GMTStartDate);
        system.debug('GMTEndDate = '+GMTEndDate);
        
        List<OrsReportWrapper> orsWrapperList = new List<OrsReportWrapper>();
        String recordTypeIDEvent = Schema.getGlobalDescribe().get('sumoapp__AdditionalInfo__c').getDescribe().getRecordTypeInfosByName().get('Event').getRecordTypeId();
        String recordTypeIDCourse = Schema.getGlobalDescribe().get('sumoapp__AdditionalInfo__c').getDescribe().getRecordTypeInfosByName().get('Course').getRecordTypeId();
        String recordTypeIDPrimaryClient = Schema.getGlobalDescribe().get('Contact').getDescribe().getRecordTypeInfosByName().get('Primary Client').getRecordTypeId();

        List<sumoapp__Attendee__c> attendeeList = [select sumoapp__ContactRelation__r.Client__c, sumoapp__ContactRelation__r.Age__c, sumoapp__ContactRelation__r.Gender__c, sumoapp__ContactRelation__r.Race__c, sumoapp__ContactRelation__r.Ethnicity__c,
                                                   sumoapp__ContactRelation__r.DisabledStatus__c, sumoapp__ContactRelation__r.HouseholdType__c, sumoapp__ContactRelation__r.HouseholdSize__c, sumoapp__ContactRelation__r.HouseholdMonthlyIncome1__c, sumoapp__ContactRelation__r.AreaMedianIncome__c,
                                                   sumoapp__ContactRelation__r.PreferredLanguage__c, sumoapp__ContactRelation__r.MailingStreet, sumoapp__ContactRelation__r.MailingAddressLine2__c, sumoapp__ContactRelation__r.MailingCity, sumoapp__ContactRelation__r.MailingStateCode,
                                                   sumoapp__ContactRelation__r.MailingPostalCode, sumoapp__ContactRelation__r.RuralAreaStatus__c, sumoapp__SumoEvent__r.sumoapp__EndDatetime__c, Outcome__c
                                                   from sumoapp__Attendee__c
                                                   where sumoapp__SumoEvent__r.sumoapp__EndDatetime__c <=: GMTEndDate and sumoapp__SumoEvent__r.sumoapp__EndDatetime__c >=: GMTStartDate
                                                   and ((Attendance_Status__c = 'Course Complete' and sumoapp__SumoEvent__r.recordTypeId =: recordTypeIDCourse) or 
                                                        (Attendance_Status__c = 'Attended - Complete' and sumoapp__SumoEvent__r.recordTypeId =: recordTypeIDEvent))
                                                   and sumoapp__SumoEvent__r.IsParent__c = true and sumoapp__ContactRelation__r.recordTypeId =: recordTypeIDPrimaryClient 
                                                   and sumoapp__SumoEvent__r.ExcludeCourseFromHUD9902__c != true and Outcome__c != null
                                                   and sumoapp__SumoEvent__r.sumoapp__Status__c != 'CANCELED' WITH SECURITY_ENFORCED limit 49999];
        
        List<NWQR_Picklist_Mapping__mdt> pickListAdj = [select id, Label__c, Value__c from NWQR_Picklist_Mapping__mdt where (ObjectApiName__c = 'Contact' OR ObjectApiName__c = 'sumoapp__Attendee__c') And (FieldApiName__c = 'AreaMedianIncome__c' OR FieldApiName__c = 'Gender__c' OR FieldApiName__c = 'Outcome__c' OR FieldApiName__c = 'Race__c')];
        
        Map<String,String> labelValueMap = new Map<String,String>();
        for(NWQR_Picklist_Mapping__mdt mdt : pickListAdj){
            if(mdt.Value__c != null && mdt.Label__c != null){
                labelValueMap.put(mdt.Value__c,mdt.Label__c);
            }
        }
        system.debug('labelValueMap = '+labelValueMap);
        for(sumoapp__Attendee__c attendee : attendeeList){
            OrsReportWrapper orswrap = new OrsReportWrapper();
            orswrap.Client_ID = attendee.sumoapp__ContactRelation__r.Client__c;
            orswrap.Age = attendee.sumoapp__ContactRelation__r.Age__c;
            
            if(labelValueMap.containsKey(attendee.sumoapp__ContactRelation__r.Gender__c)){
                orswrap.Gender = labelValueMap.get(attendee.sumoapp__ContactRelation__r.Gender__c);
            }else{
                orswrap.Gender = attendee.sumoapp__ContactRelation__r.Gender__c;
            }

            if(labelValueMap.containsKey(attendee.sumoapp__ContactRelation__r.Race__c)){
                orswrap.Race = labelValueMap.get(attendee.sumoapp__ContactRelation__r.Race__c);
            }else{
                orswrap.Race = attendee.sumoapp__ContactRelation__r.Race__c;
            }
            orswrap.Ethnicity = attendee.sumoapp__ContactRelation__r.Ethnicity__c;
            if(attendee.sumoapp__ContactRelation__r.DisabledStatus__c == 'Yes'){
                orswrap.Disability = 'Disabled';
            }else if(attendee.sumoapp__ContactRelation__r.DisabledStatus__c == 'No'){
                orswrap.Disability = 'Not disabled';
            }
            orswrap.Household_Type = attendee.sumoapp__ContactRelation__r.HouseholdType__c;
            orswrap.Household_Size = attendee.sumoapp__ContactRelation__r.HouseholdSize__c;
            orswrap.Monthly_Household_Income = attendee.sumoapp__ContactRelation__r.HouseholdMonthlyIncome1__c;
            if(labelValueMap.containsKey(attendee.sumoapp__ContactRelation__r.AreaMedianIncome__c)){
                orswrap.Household_Income_Band = labelValueMap.get(attendee.sumoapp__ContactRelation__r.AreaMedianIncome__c);
            }else{
                orswrap.Household_Income_Band = attendee.sumoapp__ContactRelation__r.AreaMedianIncome__c;
            }
            orswrap.Primary_Language_Spoken = attendee.sumoapp__ContactRelation__r.PreferredLanguage__c;
            orswrap.House_Number_and_Street_Name = attendee.sumoapp__ContactRelation__r.MailingStreet;
            orswrap.Apartment_or_Unit_Number = attendee.sumoapp__ContactRelation__r.MailingAddressLine2__c;
            orswrap.City = attendee.sumoapp__ContactRelation__r.MailingCity;
            orswrap.State = attendee.sumoapp__ContactRelation__r.MailingStateCode;
            orswrap.Zip_Code = attendee.sumoapp__ContactRelation__r.MailingPostalCode;
            orswrap.Rural_Area_Status = attendee.sumoapp__ContactRelation__r.RuralAreaStatus__c;
            if(labelValueMap.containsKey(attendee.Outcome__c)){
                orswrap.Group_Education_Service_Completed = labelValueMap.get(attendee.Outcome__c);
            }else{
                orswrap.Group_Education_Service_Completed = attendee.Outcome__c;
            }
            orswrap.Series_End_date =  attendee.sumoapp__SumoEvent__r.sumoapp__EndDatetime__c.format('MM/dd/yyyy',currentUserTimeZone);
            orsWrapperList.add(orswrap);
        }
        
        
        return orsWrapperList;
        
    }
    
    public class OrsReportWrapper{
        @AuraEnabled
        public String Client_ID;
        @AuraEnabled
        public Decimal Age;
        @AuraEnabled
        public String Gender;
        @AuraEnabled
        public String Race;
        @AuraEnabled
        public String Ethnicity;
        @AuraEnabled
        public String Disability;
        @AuraEnabled
        public String Household_Type;
        @AuraEnabled
        public Decimal Household_Size;
        @AuraEnabled
        public Decimal Monthly_Household_Income;
        @AuraEnabled
        public String Household_Income_Band;
        @AuraEnabled
        public String Primary_Language_Spoken;
        @AuraEnabled
        public String House_Number_and_Street_Name;
        @AuraEnabled
        public String Apartment_or_Unit_Number;
        @AuraEnabled
        public String City;
        @AuraEnabled
        public String State;
        @AuraEnabled
        public String Zip_Code;
        @AuraEnabled
        public String Rural_Area_Status;
        @AuraEnabled
        public String Group_Education_Service_Completed;
        @AuraEnabled
        public String Series_End_date;
    }
    
    
}