objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ActiveMilitary__c</fullName>
        <description>Yes, No, Not Applicable</description>
        <label>Active Military</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ActiveMilitary</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Besttimetocontact__c</fullName>
        <description>Contact’s preferred time to be contacted</description>
        <label>Best Time to Contact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Morning</fullName>
                </value>
                <value>
                    <fullName>Afternoon</fullName>
                </value>
                <value>
                    <fullName>Evening</fullName>
                </value>
                <value>
                    <fullName>Weekend</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CreditScore__c</fullName>
        <label>Credit Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Disabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if disabled</description>
        <label>Disabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <description>Pre-defined list</description>
        <label>Education</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Education</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EmploymentStatus__c</fullName>
        <label>Employment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Employed Full-Time</fullName>
                </value>
                <value>
                    <fullName>Employed Part-Time</fullName>
                </value>
                <value>
                    <fullName>Unemployed AND Looking for Work</fullName>
                </value>
                <value>
                    <fullName>Unable to Work Due to Disability</fullName>
                </value>
                <value>
                    <fullName>Stay-at-Home Caregiver OR Parent</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Employed Full-Time AND Student</fullName>
                </value>
                <value>
                    <fullName>Employed Part-Time AND Student</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EnglishProficiency__c</fullName>
        <description>Reflects overall level of English proficiency within the same household as the contact.</description>
        <inlineHelpText>English Proficiency of the primary client</inlineHelpText>
        <label>English Proficiency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Limited_English_Proficiency_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <description>Client’s self-identified ethnicity, used in 9902 reporting</description>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Male, Female, Other/Non-Conforming</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HouseholdMonthlyIncome1__c</fullName>
        <label>Household Monthly Income</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>Number of people in the household</description>
        <inlineHelpText>Total number of people living in the same household</inlineHelpText>
        <label>Household Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HouseholdType__c</fullName>
        <label>Household Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MaritalStatus__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>HouseholdTypeHeadofHousehold</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MailingAddressLine2__c</fullName>
        <label>Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaritalStatus__c</fullName>
        <description>Pre-defined  list</description>
        <label>Marital Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MaritalStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>NumberOfDependents__c</fullName>
        <label>Number of Dependents</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PreferredLanguage__c</fullName>
        <description>Client’s preferred language</description>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English (US)</label>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>ASL</fullName>
                </value>
                <value>
                    <fullName>Cambodian</fullName>
                </value>
                <value>
                    <fullName>Cantonese</fullName>
                </value>
                <value>
                    <fullName>Chinese Mandarin</fullName>
                </value>
                <value>
                    <fullName>Creole</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Goboligok</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hmong</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latin</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
                <value>
                    <fullName>Portuuguese</fullName>
                </value>
                <value>
                    <fullName>Russian</fullName>
                </value>
                <value>
                    <fullName>Swahili</fullName>
                </value>
                <value>
                    <fullName>Turkish</fullName>
                </value>
                <value>
                    <fullName>Ukrainian</fullName>
                </value>
                <value>
                    <fullName>Urdu</fullName>
                </value>
                <value>
                    <fullName>Vietnamese</fullName>
                </value>
                <value>
                    <fullName>Yiddish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <description>Which HUD 9902-recognized race category the contact belongs to.</description>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Race</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RelationshipToPrimaryApplicant__c</fullName>
        <description>contact relationship to primary contact</description>
        <inlineHelpText>If applicable</inlineHelpText>
        <label>Relationship to Primary Applicant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Brother</fullName>
                </value>
                <value>
                    <fullName>Employer</fullName>
                </value>
                <value>
                    <fullName>Father</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Husband</fullName>
                </value>
                <value>
                    <fullName>Mother</fullName>
                </value>
                <value>
                    <fullName>Other Relative</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Sister</fullName>
                </value>
                <value>
                    <fullName>Step-Daughter</fullName>
                </value>
                <value>
                    <fullName>Wife</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RuralAreaStatus__c</fullName>
        <description>Whether or not this contact resides in a rural area as defined by HUD.</description>
        <label>Rural Area Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Rural_Area_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TotalMonthlyIncome__c</fullName>
        <label>Total Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X1stTimeHomeBuyer__c</fullName>
        <description>Yes, No</description>
        <inlineHelpText>Must not have owned a home within the last 3 years.</inlineHelpText>
        <label>1st Time Home Buyer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>X1stTimeHomeBuyer</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>CoApplicant</fullName>
        <active>true</active>
        <label>Co-Applicant</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/ActiveMilitary.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>Not available</fullName>
    </customValue>
    <masterLabel>Active Military?</masterLabel>
</GlobalValueSet>

globalValueSets/Education.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Elementary/Primary</fullName>
    </customValue>
    <customValue>
        <fullName>Junior High School</fullName>
    </customValue>
    <customValue>
        <fullName>High School/GED</fullName>
    </customValue>
    <customValue>
        <fullName>Junior College</fullName>
    </customValue>
    <customValue>
        <fullName>University</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate School</fullName>
    </customValue>
    <customValue>
        <fullName>Vocational</fullName>
    </customValue>
    <customValue>
        <fullName>College</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>High School</fullName>
        <isActive>false</isActive>
        <label>High School</label>
    </customValue>
    <customValue>
        <fullName>Elementary</fullName>
        <isActive>false</isActive>
        <label>Elementary</label>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
        <isActive>false</isActive>
        <label>Unknown</label>
    </customValue>
    <description>Education</description>
    <masterLabel>Education</masterLabel>
</GlobalValueSet>

globalValueSets/Ethnicity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Not Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Ethnicity</description>
    <masterLabel>Ethnicity</masterLabel>
</GlobalValueSet>

globalValueSets/Gender.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <customValue>
        <fullName>Other/Non-conforming</fullName>
    </customValue>
    <description>Gender</description>
    <masterLabel>Gender</masterLabel>
</GlobalValueSet>

globalValueSets/HouseholdTypeHeadofHousehold.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Single adult</fullName>
    </customValue>
    <customValue>
        <fullName>Female-headed single parent household</fullName>
    </customValue>
    <customValue>
        <fullName>Male-headed single parent household</fullName>
    </customValue>
    <customValue>
        <fullName>Married without dependents</fullName>
    </customValue>
    <customValue>
        <fullName>Married with dependents</fullName>
    </customValue>
    <customValue>
        <fullName>Two or more unrelated Adults</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Married with children</fullName>
        <isActive>false</isActive>
        <label>Married with children</label>
    </customValue>
    <customValue>
        <fullName>Male-headed single parent household/Head of Household</fullName>
        <isActive>false</isActive>
        <label>Male-headed single parent household/Head of Household</label>
    </customValue>
    <customValue>
        <fullName>Female-headed single parent household/Head of Household</fullName>
        <isActive>false</isActive>
        <label>Female-headed single parent household/Head of Household</label>
    </customValue>
    <customValue>
        <fullName>Domestic partnership</fullName>
        <isActive>false</isActive>
        <label>Domestic partnership</label>
    </customValue>
    <customValue>
        <fullName>Married without children</fullName>
        <isActive>false</isActive>
        <label>Married without children</label>
    </customValue>
    <masterLabel>Household Type/Head of Household</masterLabel>
</GlobalValueSet>

globalValueSets/Limited_English_Proficiency_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Limited English Proficient</fullName>
    </customValue>
    <customValue>
        <fullName>Not Limited English Proficient</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Limited English Proficiency Status</description>
    <masterLabel>Limited English Proficiency Status</masterLabel>
</GlobalValueSet>

globalValueSets/MaritalStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Married</fullName>
    </customValue>
    <customValue>
        <fullName>Single</fullName>
    </customValue>
    <customValue>
        <fullName>Divorced</fullName>
    </customValue>
    <customValue>
        <fullName>Separated</fullName>
    </customValue>
    <customValue>
        <fullName>Widowed</fullName>
    </customValue>
    <customValue>
        <fullName>Choose not to respond</fullName>
    </customValue>
    <customValue>
        <fullName>Legally Separated</fullName>
        <isActive>false</isActive>
        <label>Legally Separated</label>
    </customValue>
    <masterLabel>Marital Status</masterLabel>
</GlobalValueSet>

globalValueSets/Race.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>American Indian/Alaskan Native</fullName>
    </customValue>
    <customValue>
        <fullName>Asian</fullName>
    </customValue>
    <customValue>
        <fullName>Black or African American</fullName>
    </customValue>
    <customValue>
        <fullName>Native Hawaiian or Other Pacific Islander</fullName>
    </customValue>
    <customValue>
        <fullName>White</fullName>
    </customValue>
    <customValue>
        <fullName>More than one race</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Race</description>
    <masterLabel>Race</masterLabel>
</GlobalValueSet>

globalValueSets/Rural_Area_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Lives in a rural area</fullName>
    </customValue>
    <customValue>
        <fullName>Does not live in a rural area</fullName>
    </customValue>
    <customValue>
        <fullName>Chose not to respond</fullName>
    </customValue>
    <description>Rural Area Status</description>
    <masterLabel>Rural Area Status</masterLabel>
</GlobalValueSet>

globalValueSets/X1stTimeHomeBuyer.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>Not available</fullName>
    </customValue>
    <masterLabel>1st Time Home Buyer?</masterLabel>
</GlobalValueSet>

classes/ProfileDetailsController.cls
/*
@description    this is controller class for profileDetails lwc
*/
public class ProfileDetailsController {
    /*
    @description    this method is used to return contact details and its co-applicant details
    */
    @AuraEnabled(cacheable=true)
    public static ResultWrapper getProfileDetails(){
        ResultWrapper result = new ResultWrapper();
        try{
            List<Contact> conRec = [Select Id, Name, Suffix, Email, Phone, Besttimetocontact__c, PreferredLanguage__c, RelationshipToPrimaryApplicant__c,
                                 MailingStreet, MailingAddressLine2__c, MailingCity, MailingState, MailingStateCode, MailingPostalCode,
                                 Birthdate, Gender__c, Race__c, Ethnicity__c, RuralAreaStatus__c, EnglishProficiency__c, X1stTimeHomeBuyer__c, HouseholdSize__c, HouseholdType__c, MaritalStatus__c, Education__c, ActiveMilitary__c, Disabled__c,
                                 TotalMonthlyIncome__c, NumberOfDependents__c, EmploymentStatus__c, CreditScore__c, AccountId, HouseholdMonthlyIncome1__c from Contact where Id IN (Select ContactId from User where Id =: UserInfo.getUserId()) WITH USER_MODE Limit 1];
            
            if(conRec.size() > 0){
                result.primaryContact = new ContactDetailWrapper(conRec[0], 1);
            }
            
            if(conRec.size() > 0 && String.isNotBlank(conRec[0].AccountId)){
                List<Contact> coApplicants = [Select Id, Name, Suffix, Email, Phone, Besttimetocontact__c, PreferredLanguage__c, RelationshipToPrimaryApplicant__c,
                                              MailingStreet, MailingAddressLine2__c, MailingCity, MailingState, MailingStateCode, MailingPostalCode,
                                              Birthdate, Gender__c, Race__c, Ethnicity__c, RuralAreaStatus__c, EnglishProficiency__c, X1stTimeHomeBuyer__c, HouseholdSize__c, HouseholdType__c, MaritalStatus__c, Education__c, ActiveMilitary__c, Disabled__c,
                                              TotalMonthlyIncome__c, NumberOfDependents__c, EmploymentStatus__c, CreditScore__c, AccountId, HouseholdMonthlyIncome1__c from Contact where AccountId =: conRec[0].AccountId AND Id != :conRec[0].Id AND RecordType.DeveloperName = 'CoApplicant'
                                              AND isActive__c  = true WITH USER_MODE
                                            ];
                
                List<ContactDetailWrapper> coAppList = new List<ContactDetailWrapper>();
                
                Integer counter = 1;
                for(Contact con : coApplicants){
                    coAppList.add(new ContactDetailWrapper(con, counter++));
                }
                
                result.coApplicants = coAppList;
                
            }
            return result;
            
        } catch(Exception exe){
            throw new AuraHandledException(exe.getMessage());
        }
    }
    
    /*
    @description   wrapper class to return contact details and its co-applicant details
    */
    public class ResultWrapper{
        @AuraEnabled
        public ContactDetailWrapper primaryContact{get;set;}
        @AuraEnabled
        public List<ContactDetailWrapper> coApplicants{get;set;}
    }
    
    /*
    @description   wrapper class to Contact Details
    */
    public class ContactDetailWrapper{
        @AuraEnabled
        public Integer SeqNo{get;set;}
        @AuraEnabled
        public String FullName{get;set;}
        @AuraEnabled
        public String Suffix{get;set;}
        @AuraEnabled
        public String EmailAddress{get;set;}
        @AuraEnabled
        public String FormattedPhoneNumber{get;set;}
        @AuraEnabled
        public String BestTimeToCall{get;set;}
        @AuraEnabled
        public String PreferredLanguage{get;set;}
        @AuraEnabled
        public String RelationshipToClient{get;set;}
        @AuraEnabled
        public String Street{get;set;}
        @AuraEnabled
        public String AddressLine2{get;set;}
        @AuraEnabled
        public String City{get;set;}
        @AuraEnabled
        public String State{get;set;}
        @AuraEnabled
        public String PostaCode{get;set;}
        @AuraEnabled
        public String Address{get;set;}
        @AuraEnabled
        public String Birthdate{get;set;}
        @AuraEnabled
        public String Gender{get;set;}
        @AuraEnabled
        public String Race{get;set;}
        @AuraEnabled
        public String Ethnicity{get;set;}
        @AuraEnabled
        public String Community{get;set;}
        @AuraEnabled
        public String FirstTimeHomeBuyer{get;set;}
        @AuraEnabled
        public String FluencyInEnglish{get;set;}
        @AuraEnabled
        public Integer HouseholdSize{get;set;}
        @AuraEnabled
        public String HouseholdTypeHeadOfHousehold{get;set;}
        @AuraEnabled
        public String MaritalStatus{get;set;}
        @AuraEnabled
        public String Education{get;set;}
        @AuraEnabled
        public String ActiveMilitary{get;set;}
        @AuraEnabled
        public String LegallyDisabled{get;set;}
        @AuraEnabled
        public Decimal TotalMonthlyIncome{get;set;}
        @AuraEnabled
        public Decimal HouseholdIncome{get;set;}
        @AuraEnabled
        public Integer NoOfDependents{get;set;}
        @AuraEnabled
        public String EmploymentStatus{get;set;}
        @AuraEnabled
        public Integer CreditScore{get;set;}
        
        public ContactDetailWrapper(Contact con, Integer SeqNo){
            this.SeqNo = SeqNo;
            this.FullName = con.Name;
            this.Suffix = con.Suffix;
            this.EmailAddress = con.Email;
            this.FormattedPhoneNumber = con.Phone;
            this.BestTimeToCall = con.Besttimetocontact__c;
            this.PreferredLanguage = con.PreferredLanguage__c;
            this.RelationshipToClient = con.RelationshipToPrimaryApplicant__c;
            this.Street = con.MailingStreet;
            this.AddressLine2 = con.MailingAddressLine2__c;
            
            String add = '';
            add += String.isNotBlank(con.MailingStreet) ? con.MailingStreet : '';
            add += String.isNotBlank(con.MailingAddressLine2__c) ? ('<br>' + con.MailingAddressLine2__c) : '';
            add += String.isNotBlank(con.MailingCity) ? ('<br>' + con.MailingCity + ' ') : '';
            add += String.isNotBlank(con.MailingStateCode) ? con.MailingStateCode : '';
            add += String.isNotBlank(con.MailingPostalCode) ? (', ' + con.MailingPostalCode) : '';
            
            this.Address = add;
            
            this.City = con.MailingCity;
            this.State = con.MailingStateCode;
            this.PostaCode = con.MailingPostalCode;
            this.Birthdate = String.valueof(con.Birthdate);
            this.Gender = con.Gender__c;
            this.Race = con.Race__c;
            this.Ethnicity = con.Ethnicity__c;
            this.Community = con.RuralAreaStatus__c;
            this.FirstTimeHomeBuyer = con.X1stTimeHomeBuyer__c;
            this.FluencyInEnglish = con.EnglishProficiency__c;
            this.HouseholdSize = Integer.valueOf(con.HouseholdSize__c);
            this.HouseholdTypeHeadOfHousehold = con.HouseholdType__c;
            this.MaritalStatus = con.MaritalStatus__c;
            this.Education = con.Education__c;
            this.ActiveMilitary = con.ActiveMilitary__c;
            this.LegallyDisabled = con.Disabled__c ? 'Yes' : 'No';
            this.TotalMonthlyIncome = con.TotalMonthlyIncome__c;
            this.HouseholdIncome = con.HouseholdMonthlyIncome1__c;
            this.NoOfDependents = Integer.valueOf(con.NumberOfDependents__c);
            this.EmploymentStatus = con.EmploymentStatus__c;
            this.CreditScore = Integer.valueOf(con.CreditScore__c);
        }
    }
}