objects/CounselorTraining__c.object
<CustomObject>
    <description>To store information about counselor training, including completed courses, certifications, and relevant training activities.</description>
    <label>Counselor Training</label>
    <nameField>
        <displayFormat>Training {000000}</displayFormat>
        <label>Counselor Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counselor Training</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>Facilitator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facilitator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HUD_Purpose__c</fullName>
        <label>HUD Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completed financial literacy workshop, including home affordability, budgeting and understanding use of credit</fullName>
                </value>
                <value>
                    <fullName>Completed predatory lending, loan scam or other fraud prevention workshop</fullName>
                </value>
                <value>
                    <fullName>Completed fair housing workshop</fullName>
                </value>
                <value>
                    <fullName>Completed homelessness prevention workshop</fullName>
                </value>
                <value>
                    <fullName>Completed rental workshop</fullName>
                </value>
                <value>
                    <fullName>Completed pre-purchase homebuyer education workshop</fullName>
                </value>
                <value>
                    <fullName>Completed non-delinquency post-purchase workshop, including home maintenance and/or financial management for homeowners</fullName>
                </value>
                <value>
                    <fullName>Completed resolving or preventing mortgage delinquency workshop</fullName>
                </value>
                <value>
                    <fullName>Completed disaster preparedness assistance workshop</fullName>
                </value>
                <value>
                    <fullName>Completed disaster recovery assistance workshop</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sumoapp__EndDatetime__c</fullName>
        <label>End Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>CMSCounselorID__c</fullName>
        <description>Represents the unique identifier or code assigned to the counselor</description>
        <inlineHelpText>If this field is blank the user will not be reported to HUD as a counselor.</inlineHelpText>
        <label>CMS Counselor ID</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CounselorHUDID__c</fullName>
        <description>The unique identifier or code assigned to the counselor by HUD</description>
        <inlineHelpText>The 6-digit number found on the counselor&apos;s HUD certificate. If the counselor works for agency but does not conduct one-on-one counseling sessions, they may not have a HUD Counselor ID. Enter NA</inlineHelpText>
        <label>Counselor HUD ID</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmploymentEndDate__c</fullName>
        <description>The date on which the counselor&apos;s employment with the organization ends.</description>
        <inlineHelpText>Enter the date on which the counselor&apos;s employment with the organization ends</inlineHelpText>
        <label>Employment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EmploymentStartDate__c</fullName>
        <description>The date on which the counselor&apos;s employment with the organization began.</description>
        <inlineHelpText>Enter the date on which the counselor&apos;s employment with the organization began</inlineHelpText>
        <label>Employment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsCounselor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Counselor</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/X9902__c.object
<CustomObject>
    <description>To store data and information related to HUD 9902 reporting, including fields for Generation and Submission statuses, and serves as the parent object for the 9902 Agency, 9902 Client, 9902 Counselor, and 9902 Summary objects.</description>
    <label>9902</label>
    <nameField>
        <displayFormat>HUD-{000000}</displayFormat>
        <label>9902</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>9902</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/X9902Counselor__c.object
<CustomObject>
    <description>To store detailed information about counselors who work with clients within the Agency.</description>
    <fields>
        <fullName>CMSCounselorID__c</fullName>
        <label>CMS Counselor ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CounselorHUDID__c</fullName>
        <description>Unique identifier assigned to the counselor by the Department of Housing and Urban Development (HUD).</description>
        <inlineHelpText>Enter the HUD ID assigned to the counselor by the Department of Housing and Urban Development.</inlineHelpText>
        <label>Counselor HUD ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X9902__c</fullName>
        <label>9902</label>
        <referenceTo>X9902__c</referenceTo>
        <relationshipLabel>9902 Counselor</relationshipLabel>
        <relationshipName>X9902_Counselor</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>9902 Counselor</label>
    <nameField>
        <displayFormat>99-{00000}</displayFormat>
        <label>9902 Counselor ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>9902 Counselor</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/HUD9902CounselorReportGenerateBatchTest.cls
@isTest(SeeAllData=false)
public class HUD9902CounselorReportGenerateBatchTest {
    
    @testSetup
    static void setupData() {
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        List<User> adminUser = new List<User>();
        adminUser = TestDataFactory.createUsers(adminProfile.Id, '', 2, false);
        
        // Generate unique CMSCounselorID__c dynamically with leading zeros
        adminUser[0].isActive = true;
        adminUser[0].IsCounselor__c = true;
        adminUser[0].CounselorHUDID__c = '123401';
        adminUser[0].CMSCounselorID__c = String.valueOf(Math.round(Math.random() * 99999));  
        if (adminUser[0].CMSCounselorID__c.length() < 5) {
            adminUser[0].CMSCounselorID__c = '0'.repeat(5 - adminUser[0].CMSCounselorID__c.length()) + adminUser[0].CMSCounselorID__c;
        }
        adminUser[0].EmploymentEndDate__c = Date.today();
        adminUser[0].EmploymentStartDate__c = Date.today().addYears(-1);
        
        adminUser[1].isActive = true;
        adminUser[1].IsCounselor__c = true;
        adminUser[1].CounselorHUDID__c = '123402';
        adminUser[1].CMSCounselorID__c = String.valueOf(Math.round(Math.random() * 99999)); 
        if (adminUser[1].CMSCounselorID__c.length() < 5) {
            adminUser[1].CMSCounselorID__c = '0'.repeat(5 - adminUser[1].CMSCounselorID__c.length()) + adminUser[1].CMSCounselorID__c;
        }
        adminUser[1].EmploymentEndDate__c = Date.today();
        adminUser[1].EmploymentStartDate__c = Date.today().addYears(-1);
        
        insert adminUser;
    }
    
    @isTest
    static void testBatch() {
        // Use the CMSCounselorID__c values generated in the test setup
        List<User> adminUser = [Select Id from User where CounselorHUDID__c in ('123401', '123402') limit 2];
        
        // Create Counselor Training records associated with Users
        List<CounselorTraining__c> trainingRecords = new List<CounselorTraining__c>();
        for (User u : adminUser) {
            List<CounselorTraining__c> rec = TestDataFactory.createCounselorTraining(1, false, u.Id);
            trainingRecords.add(rec[0]);
        }
        insert trainingRecords;
        
        List<X9902__c> x9902recs = TestDataFactory.createX9902(1, true);
        sumoapp__AdditionalInfo__c AdditionalInfo = TestDataFactory.createSumoEvent(1, false)[0];
        
        AdditionalInfo.RecordTypeId = Schema.SObjectType.sumoapp__AdditionalInfo__c.getRecordTypeInfosByName().get('Course').getRecordTypeId();
        AdditionalInfo.sumoapp__EndDatetime__c = DateTime.newInstance(2024, 1, 15).addDays(5);
        AdditionalInfo.Facilitator__c = adminUser[0].Id;
        AdditionalInfo.sumoapp__StartDatetime__c =  Date.Today();
        AdditionalInfo.sumoapp__EndDatetime__c =  Date.Today() + 3;
        AdditionalInfo.HUD_Purpose__c = 'Completed rental workshop';
        insert AdditionalInfo;

        
        // Initialize the batch class
        HUD9902CounselorReportGenerateBatch batch = new HUD9902CounselorReportGenerateBatch(x9902recs[0].Id);
        
        // Execute the batch
        Test.startTest();
        Database.executeBatch(batch);
        Test.stopTest();
        
        // Assert that X9902Counselor__c records were created
        Integer counselorCount = [SELECT COUNT() FROM X9902Counselor__c WHERE X9902__c = :x9902recs[0].Id];
        System.assertNotEquals(0, counselorCount);  // Ensure records are created
    }
}