objects/HUD9902FiscalYear__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>FiscalYearID__c</fullName>
        <label>Fiscal Year ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>HUD 9902 Fiscal Year</label>
</CustomObject>

objects/IntegrationSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Integration Parameters and Settings</description>
    <label>Integration Settings</label>
</CustomObject>

objects/X9902__c.object
<CustomObject>
    <description>To store data and information related to HUD 9902 reporting, including fields for Generation and Submission statuses, and serves as the parent object for the 9902 Agency, 9902 Client, 9902 Counselor, and 9902 Summary objects.</description>
    <fields>
        <fullName>PeriodStartDate__c</fullName>
        <description>Start date of the reporting period.</description>
        <label>Period Start Date</label>
        <type>Date</type>
    </fields>
    <label>9902</label>
    <nameField>
        <displayFormat>HUD-{000000}</displayFormat>
        <label>9902</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>9902</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/X9902Agency__c.object
<CustomObject>
    <description>To store unique identifier for each agency.</description>
    <fields>
        <fullName>ElementType__c</fullName>
        <label>Element Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Profile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X9902__c</fullName>
        <label>9902</label>
        <referenceTo>X9902__c</referenceTo>
        <relationshipLabel>9902 Agency</relationshipLabel>
        <relationshipName>X9902_Agency</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>9902 Agency</label>
    <nameField>
        <displayFormat>99-{00000}</displayFormat>
        <label>9902 Agency ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>9902 Agency</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/X9902Summary__c.object
<CustomObject>
    <description>To capture and summarize demographic and activity data related to the HUD 9902 report.</description>
    <fields>
        <fullName>ElementType__c</fullName>
        <label>Element Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>9902</fullName>
                </value>
                <value>
                    <fullName>Attendee</fullName>
                </value>
                <value>
                    <fullName>Group Session Attendee</fullName>
                </value>
                <value>
                    <fullName>Group Session</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GroupSessionAttendeeFeeAmount__c</fullName>
        <description>The amount of fee charged for attending the group session by each attendee.</description>
        <inlineHelpText>Enter the fee amount charged for each attendee to participate in the group session.</inlineHelpText>
        <label>Group Session Attendee Fee Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GroupSessionAttendeeID__c</fullName>
        <label>Group Session Attendee ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GroupSessionCounselorHUDId__c</fullName>
        <label>Group Session Counselor HUD ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GroupSessionDate__c</fullName>
        <label>Group Session Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GroupSessionID__c</fullName>
        <label>Group Session ID </label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X9902__c</fullName>
        <label>9902</label>
        <referenceTo>X9902__c</referenceTo>
        <relationshipLabel>9902 Summary</relationshipLabel>
        <relationshipName>X9902_Summary</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>9902 Summary</label>
    <nameField>
        <displayFormat>99-{00000}</displayFormat>
        <label>9902 Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>9902 Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/HUD9902SummaryReportControllerTest.cls
@IsTest
public class HUD9902SummaryReportControllerTest {
    
    @testSetup 
    static void testSetup() {
        // Create test data for X9902__c
        X9902__c x9902Rec = TestDataFactory.createX9902(1,false)[0];
        x9902Rec.PeriodStartDate__c = System.today().addDays(-10);
        insert x9902Rec;
                
        List<X9902Agency__c> x9902Agency1 = TestDataFactory.createX9902Agency(1, false, x9902Rec.Id, 'Profile');
        
        insert x9902Agency1;

        // Create test data for IntegrationSettings__c
        IntegrationSettings__c settings = TestDataFactory.createIntegrationSettings(true);
        
        // Create test data for HUD9902FiscalYear__c
        HUD9902FiscalYear__c fiscalYear = new HUD9902FiscalYear__c(
            Name = '2028',
            FiscalYearId__c = '28'
        );
        insert fiscalYear;
        
         X9902Summary__c summary = new X9902Summary__c(
            ElementType__c = '9902',
            X9902__c = x9902Rec.Id,
            GroupSessionID__c = 'GSID001',
            GroupSessionDate__c = Date.today(),
            GroupSessionAttendeeID__c = 'GSAID001',
            GroupSessionCounselorHUDId__c = 'HUD001',
            GroupSessionAttendeeFeeAmount__c = 100
        );
        insert summary;
	}
    
    @isTest
    static void get9902SummaryDetailsTest() {
        X9902__c x9902Rec = [Select Id from X9902__c limit 1];
        Test.startTest();
            PageReference pageRef = Page.HUD9902Summary;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('recId', x9902Rec.Id);
            HUD9902SummaryReportController objCtrl = new HUD9902SummaryReportController();
        Test.stopTest();
    }

}