objects/HUD9902ErrorLog__c.object
<CustomObject>
    <fields>
        <fullName>RecordID__c</fullName>
        <label>Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType__c</fullName>
        <label>Record Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>HUD 9902 Error Log</label>
    <nameField>
        <displayFormat>HEL-{000000}</displayFormat>
        <label>HUD 9902 Error Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HUD 9902 Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Hud9902ErrorLogTriggerHandler.cls
public with sharing class Hud9902ErrorLogTriggerHandler {
    public static void handleTrigger(List<HUD9902ErrorLog__c> newRecords, List<HUD9902ErrorLog__c> oldRecords, TriggerOperation operationType) {
        switch on operationType {
            when BEFORE_INSERT {
                handleBeforeInsert(newRecords);
            }
            when BEFORE_UPDATE {
                handleBeforeUpdate(newRecords, oldRecords);
            }
        }
    }

    private static void handleBeforeInsert(List<HUD9902ErrorLog__c> newRecords) {
        for (HUD9902ErrorLog__c errLog: newRecords) {
            if (String.isNotBlank(errLog.RecordID__c)) {
                errLog.RecordType__c = getSObjectLabelById(errLog.RecordID__c);
            }
        }
    }

    private static void handleBeforeUpdate(List<HUD9902ErrorLog__c> newRecords, List<HUD9902ErrorLog__c> oldRecords) {
        for (HUD9902ErrorLog__c errLog: newRecords) {
            if (String.isNotBlank(errLog.RecordID__c)) {
                errLog.RecordType__c = getSObjectLabelById(errLog.RecordID__c);
            }
        }
    }

    public static String getSObjectLabelById(String sObjectId) {
        if (String.isBlank(sObjectId)) {
            return '';
        }
        return Id.valueOf(sObjectId).getSObjectType().getDescribe().getLabel();
    }
}