objects/HUD9902FiscalYear__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>FiscalYearID__c</fullName>
        <label>Fiscal Year ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>HUD 9902 Fiscal Year</label>
</CustomObject>

objects/IntegrationSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Integration Parameters and Settings</description>
    <fields>
        <fullName>AgencyID__c</fullName>
        <description>Agency ID</description>
        <label>Agency ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AgencyName__c</fullName>
        <description>Agency Name</description>
        <label>CMS Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMSPassword__c</fullName>
        <description>CMS Password</description>
        <label>CMS Password</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndpointURL__c</fullName>
        <description>Endpoint URL</description>
        <label>Endpoint URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <description>Password</description>
        <label>Password</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>Username</description>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VendorID__c</fullName>
        <description>Vendor ID</description>
        <label>Vendor ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Integration Settings</label>
</CustomObject>

objects/X9902__c.object
<CustomObject>
    <description>To store data and information related to HUD 9902 reporting, including fields for Generation and Submission statuses, and serves as the parent object for the 9902 Agency, 9902 Client, 9902 Counselor, and 9902 Summary objects.</description>
    <fields>
        <fullName>PeriodEndDate__c</fullName>
        <description>End date of the reporting period.</description>
        <label>Period End Date</label>
        <type>Date</type>
    </fields>
    <label>9902</label>
    <nameField>
        <displayFormat>HUD-{000000}</displayFormat>
        <label>9902</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>9902</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/X9902Client__c.object
<CustomObject>
    <description>To store detailed information about clients served by the Agency.</description>
    <fields>
        <fullName>ClientIDNumber__c</fullName>
        <label>Client ID Number </label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X9902__c</fullName>
        <label>9902</label>
        <referenceTo>X9902__c</referenceTo>
        <relationshipLabel>9902 Client</relationshipLabel>
        <relationshipName>X9902_Client</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>9902 Client</label>
    <nameField>
        <displayFormat>99-{00000}</displayFormat>
        <label>9902 Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>9902 Client</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/HUD9902ClientSubmissionBatchTest.cls
@isTest
public class HUD9902ClientSubmissionBatchTest {
    
    @testSetup static void setup() {
        
        /*IntegrationSettings__c settings = new IntegrationSettings__c(
            Name = 'HUD Settings',
            EndpointURL__c = 'https://example.com/endpoint',
            AgencyID__c = '12345',
            AgencyName__c = 'Test Agency',
            VendorID__c = '67890',
            CMSPassword__c = 'password',
            Username__c = 'testuser',
            Password__c = 'testpassword'
        );
        insert settings;
        IntegrationSettings__c mc = new IntegrationSettings__c(
            Name = 'HUD Settings',
            AgencyID__c = '12345',
            AgencyName__c = 'Test Agency',
            VendorID__c = '67890',
            CMSPassword__c = 'password'
        );
        insert mc;*/
        IntegrationSettings__c settings = TestDataFactory.createIntegrationSettings(true);
        X9902__c x9902 = new X9902__c(
            PeriodEndDate__c = Date.newInstance(2028, 8, 1)
        );
        insert x9902;
        
        X9902Client__c x9902Client = new X9902Client__c(
            X9902__c = x9902.Id,
            ClientIDNumber__c = 'Client123'
        );
        insert x9902Client;
        
        HUD9902FiscalYear__c fiscalYear = new HUD9902FiscalYear__c(
            FiscalYearID__c = '28',
            Name = '2028'
        );
        insert fiscalYear;
        
    }
    @isTest
    static void testBatch() {
        X9902__c x9902 = [SELECT id FROM X9902__c Limit 1];
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        HUD9902ClientSubmissionBatch batch = new HUD9902ClientSubmissionBatch(x9902.Id);
        Database.executeBatch(batch);
        Test.stopTest();
    }
}