objects/HUD9902FiscalYear__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>HUD 9902 Fiscal Year</label>
</CustomObject>

objects/IntegrationSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Integration Parameters and Settings</description>
    <label>Integration Settings</label>
</CustomObject>

objects/X9902__c.object
<CustomObject>
    <description>To store data and information related to HUD 9902 reporting, including fields for Generation and Submission statuses, and serves as the parent object for the 9902 Agency, 9902 Client, 9902 Counselor, and 9902 Summary objects.</description>
    <label>9902</label>
    <nameField>
        <displayFormat>HUD-{000000}</displayFormat>
        <label>9902</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>9902</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/X9902Agency__c.object
<CustomObject>
    <description>To store unique identifier for each agency.</description>
    <fields>
        <fullName>X9902__c</fullName>
        <label>9902</label>
        <referenceTo>X9902__c</referenceTo>
        <relationshipLabel>9902 Agency</relationshipLabel>
        <relationshipName>X9902_Agency</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>9902 Agency</label>
    <nameField>
        <displayFormat>99-{00000}</displayFormat>
        <label>9902 Agency ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>9902 Agency</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/HUD9902AgencySubmitBatchTest.cls
@IsTest
public class HUD9902AgencySubmitBatchTest {
    
    @testSetup 
    static void setup() {
        
        IntegrationSettings__c settings = TestDataFactory.createIntegrationSettings(true);
        List<X9902__c> x9902recs = TestDataFactory.createX9902(1, true);
        String currentYear = String.valueOf(Date.today().adddays(365).year());
        List<HUD9902FiscalYear__c> fiscalYear = TestDataFactory.createHUD9902FiscalYear(currentYear.subString(2), currentYear, 1, true);
        
        List<X9902Agency__c> agencyRecs = new List<X9902Agency__c>();
        
        List<X9902Agency__c> x9902Agency1 = TestDataFactory.createX9902Agency(1, false, x9902recs[0].Id, 'Profile');
        List<X9902Agency__c> x9902Agency2 = TestDataFactory.createX9902Agency(1, false, x9902recs[0].Id, 'Contact');
        
        agencyRecs.add(x9902Agency1[0]);
        agencyRecs.add(x9902Agency2[0]);
        
        insert agencyRecs;
        
        
    }
    
    @isTest
    static void testBatch() {
        X9902__c x9902 = [SELECT id FROM X9902__c Limit 1];
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        HUD9902AgencySubmitBatch batch = new HUD9902AgencySubmitBatch(x9902.Id);
        Database.executeBatch(batch);
        Test.stopTest();
    }

}