objects/HUD9902FiscalYear__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>HUD 9902 Fiscal Year</label>
</CustomObject>

objects/IntegrationSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Integration Parameters and Settings</description>
    <label>Integration Settings</label>
</CustomObject>

objects/X9902__c.object
<CustomObject>
    <description>To store data and information related to HUD 9902 reporting, including fields for Generation and Submission statuses, and serves as the parent object for the 9902 Agency, 9902 Client, 9902 Counselor, and 9902 Summary objects.</description>
    <label>9902</label>
    <nameField>
        <displayFormat>HUD-{000000}</displayFormat>
        <label>9902</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>9902</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/X9902Counselor__c.object
<CustomObject>
    <description>To store detailed information about counselors who work with clients within the Agency.</description>
    <fields>
        <fullName>X9902__c</fullName>
        <label>9902</label>
        <referenceTo>X9902__c</referenceTo>
        <relationshipLabel>9902 Counselor</relationshipLabel>
        <relationshipName>X9902_Counselor</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>9902 Counselor</label>
    <nameField>
        <displayFormat>99-{00000}</displayFormat>
        <label>9902 Counselor ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>9902 Counselor</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/HUD9902CounselorSubmitBatchTest.cls
@IsTest
public class HUD9902CounselorSubmitBatchTest {
	@testSetup 
    static void setup() {
        IntegrationSettings__c settings = TestDataFactory.createIntegrationSettings(true);
        List<X9902__c> x9902recs = TestDataFactory.createX9902(1, true);
        
        List<X9902Counselor__c> counselorRecs = new List<X9902Counselor__c>();
        
        List<X9902Counselor__c> counselor1 = TestDataFactory.createX9902Counselor(1, false, x9902recs[0].Id, 'Profile');
        List<X9902Counselor__c> counselor2 = TestDataFactory.createX9902Counselor(1, false, x9902recs[0].Id, 'Training Course');
        List<X9902Counselor__c> counselor3 = TestDataFactory.createX9902Counselor(1, false, x9902recs[0].Id, 'Training');
        
        counselorRecs.add(counselor1[0]);
        counselorRecs.add(counselor2[0]);
        counselorRecs.add(counselor3[0]);
        
        insert counselorRecs;
        
        String currentYear = String.valueOf(System.now().year());
        List<HUD9902FiscalYear__c> fiscalYear = TestDataFactory.createHUD9902FiscalYear(currentYear.subString(2), currentYear, 1, true);
    }
    
    @isTest
    static void testBatch() {
        X9902__c x9902 = [SELECT id FROM X9902__c Limit 1];
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        HUD9902CounselorSubmitBatch batch = new HUD9902CounselorSubmitBatch(x9902.Id);
        Database.executeBatch(batch);
        Test.stopTest();
    }
}