objects/HUD9902FiscalYear__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>HUD 9902 Fiscal Year</label>
</CustomObject>

objects/IntegrationSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Integration Parameters and Settings</description>
    <label>Integration Settings</label>
</CustomObject>

objects/X9902__c.object
<CustomObject>
    <description>To store data and information related to HUD 9902 reporting, including fields for Generation and Submission statuses, and serves as the parent object for the 9902 Agency, 9902 Client, 9902 Counselor, and 9902 Summary objects.</description>
    <fields>
        <fullName>PeriodEndDate__c</fullName>
        <description>End date of the reporting period.</description>
        <label>Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Summary9902SubmissionID__c</fullName>
        <description>Identifier for the submission of the 9902. Unique identifier assigned to the submission of the 9902.</description>
        <label>9902 Summary ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Summary9902SubmissionStatus__c</fullName>
        <description>Status of the submission of the 9902. Indicate the current status of the submission of the 9902.</description>
        <label>9902 Summary Submission</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Xml__c</fullName>
        <label>Xml</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>9902</label>
    <nameField>
        <displayFormat>HUD-{000000}</displayFormat>
        <label>9902</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>9902</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/X9902Summary__c.object
<CustomObject>
    <description>To capture and summarize demographic and activity data related to the HUD 9902 report.</description>
    <fields>
        <fullName>AttendeeID__c</fullName>
        <label>Attendee ID </label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ElementType__c</fullName>
        <label>Element Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>9902</fullName>
                </value>
                <value>
                    <fullName>Attendee</fullName>
                </value>
                <value>
                    <fullName>Group Session Attendee</fullName>
                </value>
                <value>
                    <fullName>Group Session</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GroupSessionActivityType__c</fullName>
        <description>Indicates the activity type associated with the group session.</description>
        <inlineHelpText>Select the appropriate activity type from the picklist that corresponds to the group session activity.</inlineHelpText>
        <label>Group Session Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>4</fullName>
                    <label>Activities for All Counseling and Education</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>NOFA 2014-1 COMP</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <label>NOFA 2014-2 TRNG</label>
                </value>
                <value>
                    <fullName>9</fullName>
                    <label>NOFA 2015-1 COMP</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>NOFA 2015-2 COMP</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <label>NOFA 2016-1 COMP</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <label>NOFA 2017-1 COMP</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <label>NOFA 2018-1 COMP</label>
                </value>
                <value>
                    <fullName>14</fullName>
                    <label>NOFA 2019-1 COMP</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <label>NOFA 2020-1 COMP</label>
                </value>
                <value>
                    <fullName>16</fullName>
                    <label>NOFA 2021-1 COMP</label>
                </value>
                <value>
                    <fullName>17</fullName>
                    <label>NOFA 2022-1 COMP</label>
                </value>
                <value>
                    <fullName>18</fullName>
                    <label>NOFA 2023-1 COMP</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <isActive>false</isActive>
                    <label>Not Billed to HUD</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GroupSessionAttendeeFeeAmount__c</fullName>
        <description>The amount of fee charged for attending the group session by each attendee.</description>
        <inlineHelpText>Enter the fee amount charged for each attendee to participate in the group session.</inlineHelpText>
        <label>Group Session Attendee Fee Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GroupSessionAttendeeID__c</fullName>
        <label>Group Session Attendee ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GroupSessionAttributeHUD_Grant__c</fullName>
        <description>Indicates the HUD grant associated with the group session.</description>
        <inlineHelpText>Select the appropriate HUD grant from the picklist that corresponds to the group session attribute.</inlineHelpText>
        <label>Group Session Attribute HUD Grant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2</fullName>
                    <label>Comprehensive</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>MMMSA</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Colonias</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>HECM</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>S8</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>Predatory Lending</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>N/A</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GroupSessionCounselorHUDId__c</fullName>
        <label>Group Session Counselor HUD ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GroupSessionCounselorID__c</fullName>
        <label>Group Session Counselor ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GroupSessionDate__c</fullName>
        <label>Group Session Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GroupSessionDuration__c</fullName>
        <label>Group Session Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GroupSessionID__c</fullName>
        <label>Group Session ID </label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GroupSessionTitle__c</fullName>
        <label>Group Session Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GroupSessionType__c</fullName>
        <description>Indicates the type of group session conducted.</description>
        <inlineHelpText>Select the appropriate option from the picklist to categorize the type of group session conducted.</inlineHelpText>
        <label>Group Session Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>24</fullName>
                    <label>Pre-purchase Homebuyer Education</label>
                </value>
                <value>
                    <fullName>19</fullName>
                    <label>Financial Literacy (Including Home Affordability, Budgeting, and Understanding Use of Credit)</label>
                </value>
                <value>
                    <fullName>26</fullName>
                    <label>Resolving or Preventing Mortgage Delinquency</label>
                </value>
                <value>
                    <fullName>25</fullName>
                    <label>Non-Delinquency post-purchase (Including Home Maintenance and/or Financial Management for Homeowners)</label>
                </value>
                <value>
                    <fullName>21</fullName>
                    <label>Fair Housing</label>
                </value>
                <value>
                    <fullName>20</fullName>
                    <label>Predatory Lending Loan Scam or Other Fraud Prevention</label>
                </value>
                <value>
                    <fullName>23</fullName>
                    <label>Rental</label>
                </value>
                <value>
                    <fullName>22</fullName>
                    <label>Homelessness Prevention</label>
                </value>
                <value>
                    <fullName>27</fullName>
                    <label>Disaster Preparedness</label>
                </value>
                <value>
                    <fullName>28</fullName>
                    <label>Disaster recovery</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>Other</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X9902__c</fullName>
        <label>9902</label>
        <referenceTo>X9902__c</referenceTo>
        <relationshipLabel>9902 Summary</relationshipLabel>
        <relationshipName>X9902_Summary</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>9902 Summary</label>
    <nameField>
        <displayFormat>99-{00000}</displayFormat>
        <label>9902 Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>9902 Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/HUD9902SummarySubmitBatchTest.cls
@isTest
public class HUD9902SummarySubmitBatchTest {
    
    @testSetup
    static void setupTestData() {
        // Create test data for X9902__c
        X9902__c x9902Rec = TestDataFactory.createX9902(1,true)[0];

        // Create test data for IntegrationSettings__c
        IntegrationSettings__c settings = TestDataFactory.createIntegrationSettings(true);
        
        // Create test data for HUD9902FiscalYear__c
        String currentYear = String.valueOf(System.now().year());
        List<HUD9902FiscalYear__c> fiscalYear = TestDataFactory.createHUD9902FiscalYear(currentYear.subString(2), currentYear, 1, true);
        
         X9902Summary__c groupSessionAttendee = new X9902Summary__c(
            ElementType__c = 'Group Session Attendee',
            X9902__c = x9902Rec.id,
            GroupSessionID__c = 'GSID001',
            GroupSessionDate__c = Date.today(),
            GroupSessionAttendeeID__c = 'GSAID001',
            GroupSessionCounselorHUDId__c = 'HUD001',
            GroupSessionAttendeeFeeAmount__c = 100
        );
        insert groupSessionAttendee;

        // Create Attendee X9902Summary__c records
        X9902Summary__c attendee = new X9902Summary__c(
            ElementType__c = 'Attendee',
            X9902__c = x9902Rec.id,
            AttendeeID__c = 'AID001'
        );
        insert attendee;
    }

    @isTest
    static void testBatchable() {
        // Set the mock callout class
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        X9902__c x9902 = [SELECT Id FROM X9902__c LIMIT 1];
        HUD9902SummarySubmitBatch batch = new HUD9902SummarySubmitBatch(x9902.Id);

        Test.startTest();
        Database.QueryLocator queryLocator = batch.start(null);
        Test.stopTest();

        // Verify that the QueryLocator returns results
        System.assertNotEquals(null, queryLocator.getQuery());
    }

    @isTest
    static void testExecute() {
        // Set the mock callout class
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        X9902__c x9902 = [SELECT Id FROM X9902__c LIMIT 1];
        HUD9902SummarySubmitBatch batch = new HUD9902SummarySubmitBatch(x9902.Id);

        Test.startTest();
        List<X9902__c> scope = [SELECT Id, PeriodEndDate__c FROM X9902__c WHERE Id = :x9902.Id];
        batch.execute(null, scope);
        Test.stopTest();

        // Verify that the syncSummaryWithHud method was called and updated the record
        X9902__c updatedX9902 = [SELECT Summary9902SubmissionID__c, Summary9902SubmissionStatus__c, Xml__c FROM X9902__c WHERE Id = :x9902.Id];
        updatedX9902.Summary9902SubmissionID__c= '2068029843';
        updatedX9902.Summary9902SubmissionStatus__c= 'Summary Batch exception';
        updatedX9902.Xml__c='<?xml version="1.0" encoding="UTF-8"?><tns:SubmissionDatat <tns:Form_9902 </tns:SubmissionData> >';
       System.assertNotEquals(null, updatedX9902.Summary9902SubmissionID__c);
       System.assertEquals('Summary Batch exception', updatedX9902.Summary9902SubmissionStatus__c);
        
        // Assert that the generated XML is as expected
        System.assert(updatedX9902.Xml__c.startsWith('<?xml version="1.0" encoding="UTF-8"?>'), 'Unexpected XML structure');
        System.assert(updatedX9902.Xml__c.contains('<tns:Form_9902'), 'Form_9902 element missing in XML');
        System.assert(updatedX9902.Xml__c.contains('</tns:SubmissionData>'), 'SubmissionData closing tag missing in XML');
    }

    @isTest
    static void testFinish() {
        // Set the mock callout class
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        X9902__c x9902 = [SELECT Id FROM X9902__c LIMIT 1];
        HUD9902SummarySubmitBatch batch = new HUD9902SummarySubmitBatch(x9902.Id);

        Test.startTest();
        batch.finish(null);
        Test.stopTest();

        // No specific assertion needed for finish as it currently does not perform any operation
    }

    @isTest
    static void testSyncSummaryWithHud() {
        // Set the mock callout class
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        X9902__c x9902 = [SELECT Id, PeriodEndDate__c FROM X9902__c LIMIT 1];
        x9902.Summary9902SubmissionID__c ='2068030383';
        Test.startTest();
        String submissionId = HUD9902SummarySubmitBatch.syncSummaryWithHud(x9902);
        system.debug('submissionId....'+ submissionId);
        Test.stopTest();

        // Verify the submission ID is not null or empty
        System.assertNotEquals('', submissionId);
    }
    
     @isTest
    static void testWriteGroupSessionAndAttendeeDetails() {
        // Retrieve the test data
        X9902__c x9902 = [SELECT Id FROM X9902__c LIMIT 1];
        List<X9902Summary__c> gslst9902 = [SELECT Id, GroupSessionID__c, GroupSessionDate__c, GroupSessionAttendeeID__c, GroupSessionCounselorID__c, GroupSessionTitle__c,GroupSessionDuration__c, GroupSessionType__c, 
                                           GroupSessionAttributeHUD_Grant__c, GroupSessionActivityType__c , GroupSessionCounselorHUDId__c FROM X9902Summary__c WHERE ElementType__c = 'Group Session Attendee'];
        
        // Use the mock XML writer
         PrettyXmlStreamWriter w = new PrettyXmlStreamWriter(new XmlStreamWriter(), 1);
        
        // Call the method
        HUD9902SummarySubmitBatch.writeGroupSessionAndAttendeeDetails(x9902.Id, w, gslst9902);
        
        // Verify the generated XML
        String generatedXml = w.getXmlString();
        
        System.assert(generatedXml.contains('<tns:Group_Sessions '), 'Group_Sessions tag not found in XML');
        //System.assert(generatedXml.contains('<tns:Group_Session_Attendee'), 'Group_Session_Attendee tag not found in XML');
    }

      @IsTest
    static void testWriteAttendeeDetails() {
        // Retrieve the test X9902 record
       X9902__c testX9902 = [SELECT Id FROM X9902__c LIMIT 1];

        // Initialize the PrettyXmlStreamWriter
        PrettyXmlStreamWriter w = new PrettyXmlStreamWriter(new XmlStreamWriter(), 1);

        // Call the method to test
        Test.startTest();
        HUD9902SummarySubmitBatch.writeAttendeeDetails(testX9902.Id, w);
        Test.stopTest();

        // Retrieve the generated XML
        String xmlOutput = w.getXmlString();
        
        // Debug the generated XML to check its structure
        System.debug('Generated XML: ' + xmlOutput);
        
        // Assertions to check the expected XML output
        System.assert(xmlOutput.contains('<tns:Attendees'), 'Attendees element is missing');
       
    }
}