objects/HUDAMIData__c.object
<CustomObject>
    <description>To store data related to Area Median Income (AMI) for various regions, including details such as area names, county names, FIPS codes, and HUD-specific identifiers for HUD AMI calculations.</description>
    <fields>
        <fullName>Areaname__c</fullName>
        <description>HUD Income Limit Area Name</description>
        <label>Area name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CountyName__c</fullName>
        <description>HUD Income Limit - Official County Name</description>
        <label>County Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MedianFamilyIncome__c</fullName>
        <description>Median Family Income (MFI) for area</description>
        <label>Median Family Income</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StateCode__c</fullName>
        <label>State code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StateName__c</fullName>
        <description>Name of US State or Territory Client Case is taking place in</description>
        <label>State Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TownName__c</fullName>
        <description>Town Name for Income Limit purposes</description>
        <label>Town Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UniqueKey__c</fullName>
        <formula>TownName__c+&apos;-&apos;+CountyName__c+&apos;-&apos;+Zipcode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unique Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zipcode__c</fullName>
        <label>Zipcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p1__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 1 Persons in Household</description>
        <label>il30 p1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p2__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 2 Persons in Household</description>
        <label>il30 p2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p3__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 3 Persons in Household</description>
        <label>il30 p3</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p4__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 4 Persons in Household</description>
        <label>il30 p4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p5__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 5 Persons in Household</description>
        <label>il30 p5</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p6__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 6 Persons in Household</description>
        <label>il30 p6</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p7__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 7 Persons in Household</description>
        <label>il30 p7</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p8__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 8 Persons in Household</description>
        <label>il30 p8</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p1__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 1 Persons in Household</description>
        <label>il50 p1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p2__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 2 Persons in Household</description>
        <label>il50 p2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p3__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 3 Persons in Household</description>
        <label>il50 p3</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p4__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 4 Persons in Household</description>
        <label>il50 p4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p5__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 5 Persons in Household</description>
        <label>il50 p5</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p6__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 6 Persons in Household</description>
        <label>il50 p6</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p7__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 7 Persons in Household</description>
        <label>il50 p7</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p8__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 8 Persons in Household</description>
        <label>il50 p8</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p1__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 1 Persons in Household</description>
        <label>il80 p1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p2__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 2 Persons in Household</description>
        <label>il80 p2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p3__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 3 Persons in Household</description>
        <label>il80 p3</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p4__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 4 Persons in Household</description>
        <label>il80 p4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p5__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 5 Persons in Household</description>
        <label>il80 p5</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p6__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 6 Persons in Household</description>
        <label>il80 p6</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p7__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 7 Persons in Household</description>
        <label>il80 p7</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p8__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 8 Persons in Household</description>
        <label>il80 p8</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il_metro_name__c</fullName>
        <label>Metro Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>HUD AMI Data</label>
    <nameField>
        <label>HUD AMI Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HUD AMI Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Utility.cls
/*
@description    Utility class for common utility methods and common wrapper classes
*/
public class Utility {

    /*
    @description    Wrapper class for picklist options
    */
    public class PicklistOption {
        @AuraEnabled
        public string label{get;set;}
        @AuraEnabled
        public string value{get;set;}
        
        public PicklistOption(String label, String value){
            this.label = label;
            this.value = value;
        }
    }

    public static List<HUDAMIData__c> getHUDAMIData(Set<String> zipCodes, Set<String> townCountyZipKeys) {
        List<HUDAMIData__c> hudamiData = new List<HUDAMIData__c>();
        if (!zipCodes.isEmpty()) {
            hudamiData = [SELECT Id, CountyName__c, TownName__c, MedianFamilyIncome__c, il_metro_name__c, Areaname__c,
            Zipcode__c, StateCode__c, StateName__c, UniqueKey__c, il30p1__c, il30p2__c, il30p3__c, il30p4__c, il30p5__c,
            il30p6__c, il30p7__c, il30p8__c, il50p1__c, il50p2__c, il50p3__c, il50p4__c, il50p5__c, il50p6__c,
            il50p7__c, il50p8__c, il80p1__c, il80p2__c, il80p3__c, il80p4__c, il80p5__c, il80p6__c, il80p7__c,
            il80p8__c FROM HUDAMIData__c WHERE Zipcode__c IN :zipCodes WITH SECURITY_ENFORCED ];
        } else if (!townCountyZipKeys.isEmpty()) {
            hudamiData = [
                SELECT Id, CountyName__c, TownName__c, MedianFamilyIncome__c, il_metro_name__c, Areaname__c,
                Zipcode__c, StateCode__c, StateName__c, UniqueKey__c, il30p1__c, il30p2__c, il30p3__c, il30p4__c, il30p5__c,
                il30p6__c, il30p7__c, il30p8__c, il50p1__c, il50p2__c, il50p3__c, il50p4__c, il50p5__c, il50p6__c,
                il50p7__c, il50p8__c, il80p1__c, il80p2__c, il80p3__c, il80p4__c, il80p5__c, il80p6__c, il80p7__c,
                il80p8__c
                FROM HUDAMIData__c
                WHERE UniqueKey__c IN :townCountyZipKeys WITH SECURITY_ENFORCED
            ];
        }

        return hudamiData;
    }
    
    /*
    @description    Get NWC2 NameSpace
    */
     public static string getNwc2NameSpace(){
         string NWC2NameSpace = string.valueOf(System.Label.NWC2NameSpace).replace('unmanaged','').trim();
         return NWC2NameSpace;
     }

     /*
    @description    Generate 10 digit unique
    */
    public static String getNewUniqueId(){
		Long timestamp = System.currentTimeMillis();
		Integer randomNum = Math.abs(Crypto.getRandomInteger());
		randomNum = randomNum - (randomNum / 100000) * 100000;
		Long uniqueLong = randomNum + timestamp;
		String uniqueNumber = String.valueOf(uniqueLong).substring(Math.max(String.valueOf(uniqueLong).length() - 10, 0));
		while(uniqueNumber.length() < 10) {
			double MIN = Math.pow(10,0);
			double MAX = Math.pow(10,1) - 1;
			String aleaNumberN = String.valueOf(Math.Round(Math.Random() * (MAX-MIN) + MIN));
			if(aleaNumberN == '0'){
				uniqueNumber = '8' + uniqueNumber;
			} else {
				uniqueNumber = aleaNumberN + uniqueNumber;
			}
		}
        
        if (uniqueNumber.substring(0, 1) == '0') {
            // Replace the leading zero with a random digit between 1 and 9
            Integer leadingDigit = (Integer)(Math.random() * 9) + 1; // Random number between 1 and 9
            uniqueNumber = leadingDigit + uniqueNumber.substring(1); // Replace the first character
            
        }
		return uniqueNumber;
	}
    
}