objects/HUDAMIData__c.object
<CustomObject>
    <description>To store data related to Area Median Income (AMI) for various regions, including details such as area names, county names, FIPS codes, and HUD-specific identifiers for HUD AMI calculations.</description>
    <fields>
        <fullName>Areaname__c</fullName>
        <description>HUD Income Limit Area Name</description>
        <label>Area name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CountyName__c</fullName>
        <description>HUD Income Limit - Official County Name</description>
        <label>County Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FIPScode__c</fullName>
        <description>Federal Information Processing System Code</description>
        <label>FIPS code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MSA__c</fullName>
        <description>HUD Income Limit Metropolitan Statistical Area</description>
        <label>MSA</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MedianFamilyIncome__c</fullName>
        <description>Median Family Income (MFI) for area</description>
        <label>Median Family Income</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StateCode__c</fullName>
        <label>State code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StateName__c</fullName>
        <description>Name of US State or Territory Client Case is taking place in</description>
        <label>State Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TownName__c</fullName>
        <description>Town Name for Income Limit purposes</description>
        <label>Town Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>Fiscal Year of current AMI data</description>
        <label>Year</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zipcode__c</fullName>
        <label>Zipcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p1__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 1 Persons in Household</description>
        <label>il30 p1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p2__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 2 Persons in Household</description>
        <label>il30 p2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p3__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 3 Persons in Household</description>
        <label>il30 p3</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p4__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 4 Persons in Household</description>
        <label>il30 p4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p5__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 5 Persons in Household</description>
        <label>il30 p5</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p6__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 6 Persons in Household</description>
        <label>il30 p6</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p7__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 7 Persons in Household</description>
        <label>il30 p7</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il30p8__c</fullName>
        <description>Income Limit for Extremely Low Income (30% AMI), 8 Persons in Household</description>
        <label>il30 p8</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p1__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 1 Persons in Household</description>
        <label>il50 p1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p2__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 2 Persons in Household</description>
        <label>il50 p2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p3__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 3 Persons in Household</description>
        <label>il50 p3</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p4__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 4 Persons in Household</description>
        <label>il50 p4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p5__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 5 Persons in Household</description>
        <label>il50 p5</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p6__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 6 Persons in Household</description>
        <label>il50 p6</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p7__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 7 Persons in Household</description>
        <label>il50 p7</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il50p8__c</fullName>
        <description>Income Limit for Very Low Income (50% AMI), 8 Persons in Household</description>
        <label>il50 p8</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p1__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 1 Persons in Household</description>
        <label>il80 p1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p2__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 2 Persons in Household</description>
        <label>il80 p2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p3__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 3 Persons in Household</description>
        <label>il80 p3</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p4__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 4 Persons in Household</description>
        <label>il80 p4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p5__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 5 Persons in Household</description>
        <label>il80 p5</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p6__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 6 Persons in Household</description>
        <label>il80 p6</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p7__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 7 Persons in Household</description>
        <label>il80 p7</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il80p8__c</fullName>
        <description>Income Limit for Low Income (80% AMI), 8 Persons in Household</description>
        <label>il80 p8</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>il_metro_name__c</fullName>
        <label>Metro Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>HUD AMI Data</label>
    <nameField>
        <label>HUD AMI Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HUD AMI Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/IntegrationSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Integration Parameters and Settings</description>
    <fields>
        <fullName>AgencyID__c</fullName>
        <description>Agency ID</description>
        <label>Agency ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AgencyName__c</fullName>
        <description>Agency Name</description>
        <label>CMS Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HUD_AMI_Data_Token_1__c</fullName>
        <label>HUD AMI Data Token 1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HUD_AMI_Data_Token_2__c</fullName>
        <label>HUD AMI Data Token 2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HUD_AMI_Data_Token_3__c</fullName>
        <label>HUD AMI Data Token 3</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HUD_AMI_End_Point_URL__c</fullName>
        <label>HUD AMI End Point URL</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <description>Password</description>
        <label>Password</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>Username</description>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Settings</label>
</CustomObject>

objects/Log__c.object
<CustomObject>
    <description>To captures detailed information about exceptions and errors encountered in the system.</description>
    <fields>
        <fullName>ClassName__c</fullName>
        <label>ClassName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExceptionMessage__c</fullName>
        <label>Exception Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LineNumber__c</fullName>
        <label>Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MethodName__c</fullName>
        <label>MethodName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StackTrace__c</fullName>
        <label>StackTrace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{0000000}</displayFormat>
        <label>Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HudIntegrationSettingsCtrl.cls
/*
* @description    Controller class containing methods for Hud Integration Settings Component
* @group          HUD AMI Integration
*/
public class HudIntegrationSettingsCtrl {
    /*
    * @description : To get Hud Integration Settings
    */ 
    @AuraEnabled
    public static IntegrationSettings__c getHudIntegrationSettings(){
        IntegrationSettings__c rec = [Select Id, Name, AgencyID__c, AgencyName__c, Username__c, Password__c, HUD_AMI_End_Point_URL__c, HUD_AMI_Data_Token_1__c, HUD_AMI_Data_Token_2__c, HUD_AMI_Data_Token_3__c from IntegrationSettings__c limit 1];
        return rec;
    }
    /*
    * @description : To upsert Hud Integration Settings
    */ 
    @AuraEnabled
    public static boolean upsertHudIntegRecord(String recId, String agencyId, String userName, String password, String endpointUrl, String amiToken1, String amiToken2, String amiToken3){
        IntegrationSettings__c rec = new IntegrationSettings__c();
        rec.Id = String.isNotEmpty(recId) ? recId : '';
        rec.Name = 'HUD Settings';
        rec.AgencyID__c = agencyId;
        rec.Username__c = userName;
        rec.Password__c = password;
        rec.HUD_AMI_End_Point_URL__c = endpointUrl;
        rec.HUD_AMI_Data_Token_1__c = amiToken1;
        rec.HUD_AMI_Data_Token_2__c = amiToken2;
        rec.HUD_AMI_Data_Token_3__c = amiToken3;
        System.debug('@@@ rec : '+rec);
        upsert rec;
        return true;
    }
    /*
    * @description : To trigger Hud Integration Callouts
    */ 
    @AuraEnabled
    public static Boolean triggerHudCallout(){
        System.debug('triggerHudCallout');
        
        if(!validFieldAccess()){
            return false;
        }
        
        IntegrationSettings__c integSettRec = IntegrationSettings__c.getValues('HUD Settings');
        String amitoken = HudAmiCalloutService.getamiToken();
        
        HudAmiCalloutService.CalloutParamsWrapper paramWrap = new HudAmiCalloutService.CalloutParamsWrapper();
        paramWrap.endpointPostfix = HudAmiCalloutService.STATELIST_ENDPOINT;
        paramWrap.calltype = HudAmiCalloutService.GET_STATE_INFO;
        
		HudAmiCalloutService.CalloutResponseWrapper respWrap = HudAmiCalloutService.performCallout(paramWrap);
        if(respWrap.statusCode == 200){
            System.debug('@@@@ respWrap.stateRespList : '+respWrap.stateRespList);
            if (!Test.isRunningTest()) {
                HudAmiCountyProcessBatch batchObject = new HudAmiCountyProcessBatch(respWrap.stateRespList);
        	    Database.executeBatch(batchObject,1);
            }
        } else {
            Log__c logRec = new Log__c();
            logRec.ClassName__c = 'HudAmiCountyProcessBatch';
            logRec.MethodName__c = 'HudIntegrationSettingsCtrl.triggerHudCallout';
            logRec.LineNumber__c = 51;
            logRec.ExceptionMessage__c = respWrap.errorMsg;
            logRec.StackTrace__c = 'HudIntegrationSettingsCtrl.triggerHudCallout';
            insert logRec;
        }
        
        System.debug('@@@@ respWrap : '+respWrap);
        return true;
    }
    /*
    * @description : To check valid field access
    */ 
    private static boolean validFieldAccess(){
        if(Schema.sObjectType.HUDAMIData__c.Fields.Areaname__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.Areaname__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.MSA__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.MSA__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.CountyName__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.CountyName__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il30p1__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il30p1__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il30p2__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il30p2__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il30p3__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il30p3__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il30p4__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il30p4__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il30p5__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il30p5__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il30p6__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il30p6__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il30p7__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il30p7__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il30p8__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il30p8__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il50p1__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il50p1__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il50p2__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il50p2__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il50p3__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il50p3__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il50p4__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il50p4__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il50p5__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il50p5__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il50p6__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il50p6__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il50p7__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il50p7__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il50p8__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il50p8__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il80p1__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il80p1__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il80p2__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il80p2__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il80p3__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il80p3__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il80p4__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il80p4__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il80p5__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il80p5__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il80p6__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il80p6__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il80p7__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il80p7__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il80p8__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il80p8__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.TownName__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.TownName__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.MedianFamilyIncome__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.MedianFamilyIncome__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.il_metro_name__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.il_metro_name__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.Year__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.Year__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.StateCode__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.StateCode__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.StateName__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.StateName__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.FIPScode__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.StateCode__c.isUpdateable() &&
           Schema.sObjectType.HUDAMIData__c.Fields.zipcode__c.isCreateable() && Schema.sObjectType.HUDAMIData__c.Fields.StateName__c.isUpdateable()){
            return true;
    	}
        return false;
    }
}