objects/IntegrationSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Integration Parameters and Settings</description>
    <fields>
        <fullName>AgencyID__c</fullName>
        <description>Agency ID</description>
        <label>Agency ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AgencyName__c</fullName>
        <description>Agency Name</description>
        <label>CMS Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMSPassword__c</fullName>
        <description>CMS Password</description>
        <label>CMS Password</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndpointURL__c</fullName>
        <description>Endpoint URL</description>
        <label>Endpoint URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <description>Password</description>
        <label>Password</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>Username</description>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VendorID__c</fullName>
        <description>Vendor ID</description>
        <label>Vendor ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Integration Settings</label>
</CustomObject>

classes/HTTPCalloutServiceTest.cls
@IsTest
public class HTTPCalloutServiceTest {
    
    @TestSetup
    static void setupTestData() {
        IntegrationSettings__c settings = new IntegrationSettings__c(
            Name = 'HUD Settings',
            EndpointURL__c = 'https://example.com/endpoint',
            AgencyID__c = '12345',
            AgencyName__c = 'Test Agency',
            VendorID__c = '67890',
            CMSPassword__c = 'password',
            Username__c = 'testuser',
            Password__c = 'testpassword'
        );
        insert settings;
    }
    
    @IsTest
    static void testPostHUDReport() {
        Test.startTest();
        String reqBody = '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><submissionId>12345</submissionId></soapenv:Body></soapenv:Envelope>';
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        String submissionId = HTTPCalloutService.postHUDReport(reqBody);
        Test.stopTest();
    }

    @IsTest
    static void testGetSubmissionInfo() {
        Test.startTest();
        String submissionID = '12345'; 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        String submissionStatus = HTTPCalloutService.getSubmissionInfo(submissionID);
        Test.stopTest();
        
        System.debug('Submission Status: ' + submissionStatus);
    }
    

    @IsTest
    static void testGetHttprequest() {
        HttpRequest req = HTTPCalloutService.getHttprequest();
    }
    
    @IsTest
    static void testThreadSleep() {
        HTTPCalloutService.threadSleep(1000);
    }
}