objects/IntegrationSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Integration Parameters and Settings</description>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <description>Fiscal Year</description>
        <label>Fiscal Year</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Integration Settings</label>
</CustomObject>

objects/X9902__c.object
<CustomObject>
    <description>To store data and information related to HUD 9902 reporting, including fields for Generation and Submission statuses, and serves as the parent object for the 9902 Agency, 9902 Client, 9902 Counselor, and 9902 Summary objects.</description>
    <fields>
        <fullName>CounselorProfile__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Profile information for the counselor.</description>
        <inlineHelpText>Provide details if is a Counselor profile</inlineHelpText>
        <label>Counselor Profile</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <inlineHelpText>Indicate the year of the reporting period.</inlineHelpText>
        <label>Fiscal Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
                <value>
                    <fullName>2031</fullName>
                </value>
                <value>
                    <fullName>2032</fullName>
                </value>
                <value>
                    <fullName>2033</fullName>
                </value>
                <value>
                    <fullName>2034</fullName>
                </value>
                <value>
                    <fullName>2035</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>9902</label>
    <nameField>
        <displayFormat>HUD-{000000}</displayFormat>
        <label>9902</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>9902</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/X9902Counselor__c.object
<CustomObject>
    <description>To store detailed information about counselors who work with clients within the Agency.</description>
    <fields>
        <fullName>CMSCounselorID__c</fullName>
        <label>CMS Counselor ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CounselorBillingMethod__c</fullName>
        <label>Counselor Billing Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hourly</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CounselorEmailAddress__c</fullName>
        <label>Counselor Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CounselorEmpEndDate__c</fullName>
        <description>Indicates the date when the counselor&apos;s employment or contract ends.</description>
        <inlineHelpText>Enter the date when the counselor&apos;s employment or contract officially ends.</inlineHelpText>
        <label>Counselor Employment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CounselorEmpStartDate__c</fullName>
        <description>Indicates the date when the counselor&apos;s employment or contract begins.</description>
        <inlineHelpText>Enter the date when the counselor&apos;s employment or contract officially starts.</inlineHelpText>
        <label>Counselor Employment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CounselorFirstName__c</fullName>
        <label>Counselor First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CounselorHUDID__c</fullName>
        <description>Unique identifier assigned to the counselor by the Department of Housing and Urban Development (HUD).</description>
        <inlineHelpText>Enter the HUD ID assigned to the counselor by the Department of Housing and Urban Development.</inlineHelpText>
        <label>Counselor HUD ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CounselorLanguages__c</fullName>
        <label>Counselor Languages</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Cambodian</fullName>
                </value>
                <value>
                    <fullName>Cantonese</fullName>
                </value>
                <value>
                    <fullName>Chinese Mandarin</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
                <value>
                    <fullName>Portuguese</fullName>
                </value>
                <value>
                    <fullName>Russian</fullName>
                </value>
                <value>
                    <fullName>Swahili</fullName>
                </value>
                <value>
                    <fullName>Turkish</fullName>
                </value>
                <value>
                    <fullName>Vietnamese</fullName>
                </value>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>Ukrainian</fullName>
                </value>
                <value>
                    <fullName>ASL</fullName>
                </value>
                <value>
                    <fullName>Hmong</fullName>
                </value>
                <value>
                    <fullName>Creole</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CounselorLastName__c</fullName>
        <label>Counselor Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CounselorMiddleName__c</fullName>
        <label>Counselor Middle Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CounselorPhone__c</fullName>
        <label>Counselor Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CounselorRate__c</fullName>
        <description>The rate at which the counselor&apos;s services are billed or charged, typically per hour or per session.</description>
        <inlineHelpText>Enter the billing rate at which the counselor&apos;s services are charged.</inlineHelpText>
        <label>Counselor Billing Rate</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CounselorServiceTypes__c</fullName>
        <description>Indicates the types of counseling services provided by the counselor.</description>
        <inlineHelpText>Select one or more options from the picklist to specify the types of counseling services offered by the counselor.</inlineHelpText>
        <label>Counselor Service Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mortgage Delinquency and Default Resolution Counseling</fullName>
                </value>
                <value>
                    <fullName>Reverse Mortgage Counseling</fullName>
                </value>
                <value>
                    <fullName>Home Improvement and Rehabilitation Counseling</fullName>
                </value>
                <value>
                    <fullName>Services for Homeless Counseling</fullName>
                </value>
                <value>
                    <fullName>Financial Management/Budget Counseling</fullName>
                </value>
                <value>
                    <fullName>Pre-purchase Counseling</fullName>
                </value>
                <value>
                    <fullName>Rental Housing Counseling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CounselorTrainingCourseID__c</fullName>
        <label>Counselor Training Course ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CounselorTrainingDate__c</fullName>
        <label>Counselor Training Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CounselorTrainingOrganizationOther__c</fullName>
        <description>Indicates the name of the training organization if &quot;Other&quot; is selected in the &quot;Counselor Training Organization&quot; field.</description>
        <inlineHelpText>If &quot;Other&quot; is selected in the &quot;Counselor Training Organization&quot; field, specify the name of the training organization in this field.</inlineHelpText>
        <label>Counselor Training Organization Other</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CounselorTrainingOrganization__c</fullName>
        <description>Indicates the organization or entity from which the counselor received training.</description>
        <inlineHelpText>Select the organization from which the counselor received training.</inlineHelpText>
        <label>Counselor Training Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>NeighborWorks America</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>La Raza</fullName>
                </value>
                <value>
                    <fullName>NCRC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CounselorTrainingSponsor__c</fullName>
        <description>Indicates the entity sponsoring the counselor&apos;s training program.</description>
        <inlineHelpText>Enter the name of the entity sponsoring the counselor&apos;s training program.</inlineHelpText>
        <label>Counselor Training Sponsor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>HUD</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CounselorTrainingTitle__c</fullName>
        <label>Counselor Training Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ElementType__c</fullName>
        <label>Element Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Profile</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Training Course</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>X9902_Counselor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X9902__c</fullName>
        <label>9902</label>
        <referenceTo>X9902__c</referenceTo>
        <relationshipLabel>9902 Counselor</relationshipLabel>
        <relationshipName>X9902_Counselor</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>9902 Counselor</label>
    <nameField>
        <displayFormat>99-{00000}</displayFormat>
        <label>9902 Counselor ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>9902 Counselor</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/HUD9902CounselorSubmitBatch.cls
public with sharing class HUD9902CounselorSubmitBatch  implements Database.Batchable<SObject>, Database.Stateful, Database.AllowsCallouts {
    private String queryString = 'SELECT Id, User__c, X9902__c FROM X9902Counselor__c';
    Id reportId;
    public String submissionId;
    private string NWC2NameSpace = '';
    
    public HUD9902CounselorSubmitBatch(String reportRecordId){
        reportId = (Id)reportRecordId;
        NWC2NameSpace = Utility.getNwc2NameSpace();
        
        queryString = 'SELECT Id, '+NWC2NameSpace+'CounselorProfile__c, '+NWC2NameSpace+'FiscalYear__c FROM '+NWC2NameSpace+'X9902__c WHERE Id = \''+reportRecordId+'\'';
        
        
    }
    
    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator(queryString);
    }
    public void execute(Database.BatchableContext context, List<X9902__c> scope) {
        if(scope.size() > 0){
            X9902__c masterObj = scope[0];
            Boolean chkStatus = true;
            String submissionStatus;
            
            XmlStreamWriter writer = new XmlStreamWriter();
        	PrettyXmlStreamWriter w = new PrettyXmlStreamWriter(writer, 4);
            
            w.writeStartDocument('UTF-8','1.0');
            w.writeStartElement('tns','SubmissionData ','tns');
            w.writeAttribute('','','xsi:schemaLocation','http://gov.hud.arm/counselor_profile_databag_6_0 counselor_profile_databag_6_0.xsd');
            w.writeAttribute('','','xmlns:tns','http://gov.hud.arm/counselor_profile_databag_6_0');
            w.writeAttribute('','','xmlns:xsi','http://www.w3.org/2001/XMLSchema-instance');

            
            List<X9902Counselor__c> counselorProfileRec = [select Id, CMSCounselorID__c, CounselorFirstName__c, CounselorLastName__c, CounselorMiddleName__c, CounselorEmpStartDate__c, 
                                           CounselorEmpEndDate__c, CounselorHUDID__c, CounselorRate__c, CounselorBillingMethod__c, CounselorEmailAddress__c, 
                                           CounselorPhone__c, CounselorLanguages__c, CounselorServiceTypes__c from X9902Counselor__c where X9902__c = :reportId AND ElementType__c = 'Profile'];
            
            w.writeStartElement('tns','Counselor_Profiles','tns'); 
            
            for(X9902Counselor__c objAP : counselorProfileRec){
                
                w.writeStartElementNoIndentNewLine('tns','Counselor_Profile','tns');
                
                w.writeElementNoIndent('tns', 'CMS_Counselor_Id', 'tns', String.isNotBlank(objAp.CMSCounselorID__c) ? objAp.CMSCounselorID__c : '');
                w.writeElementNoIndent('tns', 'Counselor_Fname', 'tns', String.isNotBlank(objAp.CounselorFirstName__c) ? objAp.CounselorFirstName__c : '');
                w.writeElementNoIndent('tns', 'Counselor_Lname', 'tns', String.isNotBlank(objAp.CounselorLastName__c) ? objAp.CounselorLastName__c : '');
                if(String.isNotBlank(objAp.CounselorMiddleName__c)){
                    w.writeElementNoIndent('tns', 'Counselor_Mname', 'tns', String.isNotBlank(objAp.CounselorMiddleName__c) ? objAp.CounselorMiddleName__c : '');
                }
                w.writeElementNoIndent('tns', 'Counselor_Emp_Start_Date', 'tns', objAp.CounselorEmpStartDate__c != NULL ? HUD9902Helper.formatDate(objAp.CounselorEmpStartDate__c) : '');
                w.writeElementNoIndent('tns', 'Counselor_Emp_End_Date', 'tns', objAp.CounselorEmpEndDate__c != NULL ? HUD9902Helper.formatDate(objAp.CounselorEmpEndDate__c) : '');
                w.writeElementNoIndent('tns', 'Counselor_HUD_Id', 'tns', String.isNotBlank(objAp.CounselorHUDID__c) ? objAp.CounselorHUDID__c : '');
                w.writeElementNoIndent('tns', 'Counselor_Rate', 'tns', objAp.CounselorRate__c != NULL ? String.valueOf(objAp.CounselorRate__c) : '');
                w.writeElementNoIndent('tns', 'Counselor_Billing_Method', 'tns', String.isNotBlank(objAp.CounselorBillingMethod__c) ? objAp.CounselorBillingMethod__c : '');
                w.writeElementNoIndent('tns', 'Counselor_Email', 'tns', String.isNotBlank(objAp.CounselorEmailAddress__c) ? objAp.CounselorEmailAddress__c : '');
                if(objAp.CounselorPhone__c != null){
                    w.writeElementNoIndent('tns', 'Counselor_Phone', 'tns', objAp.CounselorPhone__c != NULL ? HUD9902Helper.formatPhone(objAp.CounselorPhone__c) : '');
                }
                String language = HUD9902Helper.generateHUDSbiArrayCode('Languages', objAP.CounselorLanguages__c);
            	String serviceTypes =  HUD9902Helper.generateHUDSbiArrayCode('Counselor Service Types', objAp.CounselorServiceTypes__c);
                
                w.writeStartElementNoIndent('tns','Counselor_Service_Types','tns');
                //w.writeElement('tns', 'Service_Type', 'tns', '8');
                if(String.isNotBlank(serviceTypes)){
                    for(string service : serviceTypes.split(';')){
                        //writeElement(w, 'Service_Type', service);
						w.writeElementNoIndent('tns', 'Service_Type', 'tns', service);
                    }
                }
                w.writeEndElementNoIndent();
                
                w.writeStartElementNoIndent('tns','Counselor_Languages','tns');
                if (String.isNotBlank(language)){
                    For(string lang : language.split(';')){
                        w.writeElementNoIndent('tns', 'Language', 'tns', lang);
                    }
                }
                w.writeEndElementNoIndent();
                
                w.writeEndElementNoIndent();
            }
            
            w.writeEndElement();
            
            List<X9902Counselor__c> counselorTrainingCourseRec = [select Id, CounselorTrainingTitle__c, CounselorTrainingDate__c, CounselorTrainingCourseID__c,
                                                            CounselorTrainingOrganization__c, CounselorTrainingOrganizationOther__c, CounselorTrainingSponsor__c, 
                                                            CounselorTrainingSponsorOther__c, CounselorTrainingDuration__c from X9902Counselor__c where X9902__c = :reportId 
                                                            AND ElementType__c = 'Training Course'];
            
            w.writeStartElement('tns','Counselor_Training_Courses','tns');
            
            for(X9902Counselor__c objAP : counselorTrainingCourseRec){
                w.writeStartElementNoIndentNewLine('tns','Counselor_Training_Course','tns');
                
                w.writeElementNoIndent('tns', 'Counselor_Training_Course_Id', 'tns', String.isNotBlank(objAp.CounselorTrainingCourseID__c) ? objAp.CounselorTrainingCourseID__c : '');
                w.writeElementNoIndent('tns', 'Counselor_Training_Title', 'tns', String.isNotBlank(objAp.CounselorTrainingTitle__c) ? objAp.CounselorTrainingTitle__c : '');
                w.writeElementNoIndent('tns', 'Counselor_Training_Date', 'tns', objAp.CounselorTrainingDate__c != NULL ? HUD9902Helper.formatDate(objAp.CounselorTrainingDate__c) : '');
                w.writeElementNoIndent('tns', 'Counselor_Training_Org', 'tns', String.isNotBlank(objAp.CounselorTrainingOrganization__c) ? HUD9902Helper.getHUDSbiCode('Training Organizations', objAp.CounselorTrainingOrganization__c) : '');
                w.writeElementNoIndent('tns', 'Counselor_Training_Org_Other', 'tns', String.isNotBlank(objAp.CounselorTrainingOrganizationOther__c) ? objAp.CounselorTrainingOrganizationOther__c : '');
                w.writeElementNoIndent('tns', 'Counselor_Training_Sponsor', 'tns', String.isNotBlank(objAp.CounselorTrainingSponsor__c) ? HUD9902Helper.getHUDSbiCode('Training Sponsors', objAp.CounselorTrainingSponsor__c) : '');
                w.writeElementNoIndent('tns', 'Counselor_Training_Sponsor_Other', 'tns', String.isNotBlank(objAp.CounselorTrainingSponsorOther__c) ? objAp.CounselorTrainingSponsorOther__c : '');
                w.writeElementNoIndent('tns', 'Counselor_Training_Duration', 'tns', objAp.CounselorTrainingDuration__c != NULL ? String.valueOf(objAp.CounselorTrainingDuration__c) : '');
                
                w.writeEndElementNoIndent();
            }
            
            w.writeEndElement();
            
            List<X9902Counselor__c> counselorTrainingRec = [select Id, CMSCounselorID__c, CounselorTrainingCertificate__c, CounselorTrainingCourseID__c,
                                                            CounselorTrainingTitle__c, CounselorTrainingDate__c, 
                                                            CounselorTrainingOrganization__c, CounselorTrainingOrganizationOther__c, CounselorTrainingSponsor__c, 
                                                            CounselorTrainingSponsorOther__c, CounselorTrainingDuration__c
                                                            from X9902Counselor__c where X9902__c = :reportId 
                                                            AND ElementType__c = 'Training'];
            
            w.writeStartElement('tns','Counselor_Trainings','tns');
            
            for(X9902Counselor__c objAP : counselorTrainingRec){
                
                w.writeStartElementNoIndentNewLine('tns','Counselor_Training','tns');
                
                w.writeElementNoIndent('tns', 'CMS_Counselor_Id', 'tns', String.isNotBlank(objAp.CMSCounselorID__c) ? objAp.CMSCounselorID__c : '');
                w.writeElementNoIndent('tns', 'Counselor_Training_Cert', 'tns', objAp.CounselorTrainingCertificate__c != NULL ? objAp.CounselorTrainingCertificate__c : '');
                w.writeElementNoIndent('tns', 'Counselor_Training_Course_Id', 'tns', String.isNotBlank(objAp.CounselorTrainingCourseID__c) ? objAp.CounselorTrainingCourseID__c : '');
                

                w.writeEndElementNoIndent();
            }
            
            w.writeEndElement();
            w.writeEndElement();
            w.writeEndDocument();
            
            String xml = w.getXmlString();
            w.close();
            
            String strFileEncode = EncodingUtil.base64Encode(blob.valueOf(xml));
            
            Map<String, HUD9902FiscalYear__c > fiscalYearCodeMap = HUD9902FiscalYear__c.getAll();
            
            IntegrationSettings__c mc = IntegrationSettings__c.getValues('HUD Settings');
            String endpoint = mc.EndpointURL__c; 
            Integer agencyid = Integer.valueOf(mc.AgencyID__c);
            String agencyName = mc.AgencyName__c;
            Integer FiscalYear = Integer.valueOf(fiscalYearCodeMap.get(String.valueOf(masterObj.FiscalYear__c)).FiscalYearID__c);
            String vendorid = mc.VendorID__c;
            String pw = mc.CMSPassword__c;

            String soapXML ='<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://service.arm.hud.gov/"><soapenv:Header></soapenv:Header><soapenv:Body><ser:postCounselorData><ser:submissionHeader6.0><ser:agcHcsId>'+agencyID+'</ser:agcHcsId><ser:agcName>'+agencyName+'</ser:agcName><ser:fiscalYearId>'+FiscalYear+'</ser:fiscalYearId><ser:cmsVendorId>'+vendorid+'</ser:cmsVendorId><ser:cmsPassword>'+pw+'</ser:cmsPassword></ser:submissionHeader6.0>';
            String subXML1='<ser:submissionData>';
            String subXML2='</ser:submissionData>';
            String strEncodedSubxml=subXML1+strFileEncode+subXML2;
            
            String strsubEncode='<ser:submissionDataEncoding>TEXT/XML</ser:submissionDataEncoding>';
            String strEnv='</ser:postCounselorData></soapenv:Body></soapenv:Envelope>';
            String reqBody = soapXML+strsubEncode+strEncodedSubxml+strEnv;
            
            String submissionId = HTTPCalloutService.postHUDReport(reqBody);
            System.debug('submissionId: ' + submissionId);
            /*if (submissionId.substring(0,5) != 'Error'){
                while (chkStatus){
                    submissionStatus = HTTPCalloutService.getSubmissionInfo(submissionId);
                    if (submissionStatus == 'DONE' || submissionStatus.substring(0,5) == 'Error'){
                        chkStatus = false;
                    }
                    else{
                        HTTPCalloutService.threadSleep(1000);
                    }
                }
            }*/
            masterObj = new X9902__c();
            masterObj.Id = reportId;
            masterObj.CounselorSubmissionID__c = submissionId;
            //masterObj.CounselorSubmissionStatus__c = submissionStatus;
            //masterObj.CounselorXML__c = xml;
            update masterObj;
            ID jobID1 = System.enqueueJob(new HudSubmissionStatusCheck(blob.valueOf(xml), submissionId, reportId, '9902_Counselor'));
        }
            
    }

    public void finish(Database.BatchableContext context) {
    }
    
    public static void writeElement(XmlStreamWriter w, String node, String fieldValue){
        w.writeStartElement('tns', node,'tns');
        w.writeCharacters(fieldValue);
        w.writeEndElement();        
    }
}