objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>sumoapp__EndDatetime__c</fullName>
        <label>End Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Child Events</relationshipLabel>
        <relationshipName>ChildEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CourseTriggerHandlerTest.cls
@isTest
public class CourseTriggerHandlerTest {
    
    @isTest
    static void testAfterInsert() {
        // Create a new sumoapp__AdditionalInfo__c record
        Test.startTest();
        sumoapp__AdditionalInfo__c parent = new sumoapp__AdditionalInfo__c(sumoapp__StartDatetime__c=datetime.now());
        insert parent;
        sumoapp__AdditionalInfo__c child = new sumoapp__AdditionalInfo__c(sumoapp__Parent__c = parent.Id, sumoapp__StartDatetime__c=datetime.now(), sumoapp__EndDatetime__c=dateTime.now() + 1);
        insert child;
        sumoapp__AdditionalInfo__c child2 = new sumoapp__AdditionalInfo__c(sumoapp__Parent__c = parent.Id, sumoapp__StartDatetime__c=datetime.now(), sumoapp__EndDatetime__c=dateTime.now() + 1);
        insert child2;
        Test.stopTest();

    }
    
    @isTest
    static void testAfterUpdate() {
        sumoapp__AdditionalInfo__c parent = new sumoapp__AdditionalInfo__c(sumoapp__StartDatetime__c=datetime.now());
        insert parent;
        sumoapp__AdditionalInfo__c child = new sumoapp__AdditionalInfo__c(sumoapp__Parent__c = parent.Id, sumoapp__StartDatetime__c=datetime.now(), sumoapp__EndDatetime__c=dateTime.now() + 1);
        insert child;
        
        Test.startTest();
        child.sumoapp__EndDatetime__c = dateTime.now() + 2;
        update child;
        Test.stopTest();
    }
    
   
}