objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>Public__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Public</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sumoapp__EndDatetime__c</fullName>
        <label>End Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__EventName__c</fullName>
        <label>Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BOOKED</fullName>
                    <default>true</default>
                    <label>Booked</label>
                </value>
                <value>
                    <fullName>CANCELED</fullName>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>RESCHEDULED</fullName>
                    <label>Rescheduled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__Attendee__c.object
<CustomObject>
    <fields>
        <fullName>sumoapp__ContactRelation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Relation</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Event Attendees</relationshipLabel>
        <relationshipName>ContactEventAttendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__EndDatetime__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__EndDatetime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__EventName__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__EventName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__StartDatetime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>CANCELED</fullName>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>COMPLIMENTARY</fullName>
                    <label>Complimentary</label>
                </value>
                <value>
                    <fullName>DECLINED</fullName>
                    <label>Declined</label>
                </value>
                <value>
                    <fullName>DRAFT</fullName>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>REFUNDED</fullName>
                    <label>Fully Refunded</label>
                </value>
                <value>
                    <fullName>PAID_MANUAL</fullName>
                    <label>Paid - Manual</label>
                </value>
                <value>
                    <fullName>PAID</fullName>
                    <label>Paid - Online</label>
                </value>
                <value>
                    <fullName>PARTIALLY_REFUNDED</fullName>
                    <label>Partially Refunded</label>
                </value>
                <value>
                    <fullName>BOOKED</fullName>
                    <default>true</default>
                    <label>Registered</label>
                </value>
                <value>
                    <fullName>WAITLISTED</fullName>
                    <label>Waitlisted</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sumoapp__SumoEvent__c</fullName>
        <label>SUMO Event</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SUMO Attendee</label>
    <nameField>
        <displayFormat>ATD-{000000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UserClassesController.cls
public without sharing class UserClassesController {
    
    /*
     * @desc: Method for home page classes tiles
     */ 
    @AuraEnabled(cacheable=true)
    public static List<sumoapp__Attendee__c> getUserClasses() {
        List<sumoapp__Attendee__c> classes = new List<sumoapp__Attendee__c>();
        try {
            List<User> users = [SELECT Id, ContactId FROM User WHERE Id = :UserInfo.getUserId()];
            if (users.isEmpty() || users[0].ContactId == null) return classes;
            classes = [ SELECT Id,
                        sumoapp__SumoEvent__r.Id,
                        sumoapp__SumoEvent__r.sumoapp__EventName__c,
                        sumoapp__SumoEvent__r.sumoapp__StartDatetime__c,
                        sumoapp__Status__c
                        FROM sumoapp__Attendee__c
                        WHERE sumoapp__ContactRelation__c = :users[0].ContactId 
                       	AND sumoapp__SumoEvent__r.sumoapp__EndDatetime__c > Today
                        AND sumoapp__SumoEvent__r.Public__c  = TRUE
                      ];
            return classes;
            // // For Testing
            // return [ SELECT Id, 
            //                    sumoapp__SumoEvent__r.sumoapp__EventName__c,
            //                    sumoapp__SumoEvent__r.sumoapp__StartDatetime__c,
            //                    sumoapp__Status__c
            //                    FROM sumoapp__Attendee__c LIMIT 8
            //                ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}