objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>CourseLanguage__c</fullName>
        <label>Course Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English (US)</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>ASL</fullName>
                </value>
                <value>
                    <fullName>Cambodian</fullName>
                </value>
                <value>
                    <fullName>Cantonese</fullName>
                </value>
                <value>
                    <fullName>Chinese Mandarin</fullName>
                </value>
                <value>
                    <fullName>Creole</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Goboligok</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hmong</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latin</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
                <value>
                    <fullName>Portuuguese</fullName>
                </value>
                <value>
                    <fullName>Russian</fullName>
                </value>
                <value>
                    <fullName>Swahili</fullName>
                </value>
                <value>
                    <fullName>Turkish</fullName>
                </value>
                <value>
                    <fullName>Ukrainian</fullName>
                </value>
                <value>
                    <fullName>Urdu</fullName>
                </value>
                <value>
                    <fullName>Vietnamese</fullName>
                </value>
                <value>
                    <fullName>Yiddish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CourseNumber__c</fullName>
        <label>Course Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Facilitator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facilitator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Presenter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Presenter</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select Presenter of type Affiliate !</errorMessage>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Affiliate</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__Capacity__c</fullName>
        <inlineHelpText>The total # of seats or people allowed to register for this event, once met, the event is considered SOLD OUT.  If blank, then capacity is unlimited.</inlineHelpText>
        <label>Capacity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sumoapp__EndDatetime__c</fullName>
        <label>End Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__EventName__c</fullName>
        <label>Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__LocationDetails__c</fullName>
        <label>Location Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>sumoapp__Location__c</referenceTo>
        <relationshipLabel>Location Infos</relationshipLabel>
        <relationshipName>LocationInfos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__RegisteredAttendeeCount__c</fullName>
        <label>Registered Attendee Count</label>
        <summaryFilterItems>
            <field>sumoapp__Attendee__c.sumoapp__Status__c</field>
            <operation>notEqual</operation>
            <value>CANCELED, WAITLISTED, DRAFT, DECLINED</value>
        </summaryFilterItems>
        <summaryForeignKey>sumoapp__Attendee__c.sumoapp__SumoEvent__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Attendance_Status__c</fullName>
        <label>Attendee Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Attended - Complete</fullName>
                </value>
                <value>
                    <fullName>Attended - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Course Complete</fullName>
                </value>
                <value>
                    <fullName>Course Incomplete</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sumoapp__ContactRelation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Relation</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Event Attendees</relationshipLabel>
        <relationshipName>ContactEventAttendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__EndDatetime__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__EndDatetime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__EventName__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__EventName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__IsNotArrived__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It shows whether the attendee has arrived at the event or not</description>
        <inlineHelpText>Set this value if the attendee did not arrive at the event</inlineHelpText>
        <label>No-Show</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sumoapp__Location__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__Location__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__StartDatetime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__SumoEvent__c</fullName>
        <label>SUMO Event</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SUMO Attendee</label>
    <nameField>
        <displayFormat>ATD-{000000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/sumoapp__Location__c.object
<CustomObject>
    <label>SUMO Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SUMO Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PrintRosterController.cls
public class PrintRosterController {
    public sumoapp__AdditionalInfo__c courseDetails {get;set;}
    public integer noOfClasses {get;set;}
    public list<Course> courses {get;set;}
    
    public list<Integer> blankRowsExtraPage {get; set;}
    public map<string,list<Integer>> classtoBlankrowsMap {get; set;} 
    public map<string,Boolean> classtoExtraRowsMap {get; set;}
    
    public PrintRosterController(){
        
        Id recId        = ApexPages.currentPage().getParameters().get('Id');
        courses     = new list<Course>();
        
        blankRowsExtraPage = new list<Integer>{1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24};
            classtoBlankrowsMap = new map<string, list<integer>>();
        classtoExtraRowsMap = new map<string,Boolean>();
        courseDetails = [SELECT Name, sumoapp__EventName__c, sumoapp__Location__c, sumoapp__Location__r.Name, sumoapp__LocationDetails__c, Facilitator__c, Facilitator__r.Name, sumoapp__StartDatetime__c, sumoapp__EndDatetime__c, Presenter__c, Presenter__r.Name,
                         CourseLanguage__c, sumoapp__Capacity__c, sumoapp__RegisteredAttendeeCount__c, CourseNumber__c,
                         (Select Id, sumoapp__ContactRelation__r.Name, sumoapp__IsNotArrived__c, Attendance_Status__c, sumoapp__ContactRelation__r.RecordType.Name from sumoapp__EventAttendees__r where sumoapp__ContactRelation__c != NULL AND sumoapp__ContactRelation__r.Name != null AND sumoapp__ContactRelation__r.AccountId != null AND sumoapp__ContactRelation__r.RecordTypeId!=null order by sumoapp__ContactRelation__r.AccountId,  sumoapp__ContactRelation__r.RecordType.DeveloperName desc)
                         FROM sumoapp__AdditionalInfo__c
                         WHERE Id =: recId WITH User_Mode ];
        
        Course attn = new Course();
        attn.courseName = courseDetails.sumoapp__EventName__c != NULL ? (courseDetails.sumoapp__EventName__c).toUpperCase() : '';
        attn.courseNumber = courseDetails.CourseNumber__c;
        attn.classId = courseDetails.Id;
        attn.locationName = courseDetails.sumoapp__Location__c != null ? courseDetails.sumoapp__Location__r.Name : '';
        attn.counselorName = courseDetails.Facilitator__c != null ? courseDetails.Facilitator__r.Name : '';
        attn.counselorPresentator = courseDetails.Presenter__c != null ? courseDetails.Presenter__r.Name : '';
        attn.counselorFecilator = courseDetails.Facilitator__c != null ? courseDetails.Facilitator__r.Name : '';
        String dt = courseDetails.sumoapp__StartDatetime__c != null ? courseDetails.sumoapp__StartDatetime__c.format() : '';
        
        dt = (String.isNotBlank(dt) && courseDetails.sumoapp__EndDatetime__c != null ) ? (dt + ' - ' + courseDetails.sumoapp__EndDatetime__c.format().subString(10)) : dt;
        
        attn.apptDate = dt;
        attn.capacity = Integer.valueOf(courseDetails.sumoapp__Capacity__c);
        attn.language = courseDetails.CourseLanguage__c;
        attn.totalEnrolled = Integer.valueOf(courseDetails.sumoapp__RegisteredAttendeeCount__c);
        
        List<Attendee> attendees = new List<Attendee>();
        for(sumoapp__Attendee__c rec : courseDetails.sumoapp__EventAttendees__r){
            if(String.isNotBlank(rec.sumoapp__ContactRelation__c)){
                attendees.add(new Attendee(rec));
            }
        }
        
        attn.students = attendees;
        
        courses.add(attn);
        noOfClasses = 0;
    }
    
    public class Course{
        public string courseName {get; set;}
        public string courseNumber {get; set;}
        public string classId {get; set;}
        public string locationName {get; set;}
        public string counselorName {get; set;}
        public string counselorPresentator {get; set;}
        public string counselorFecilator {get; set;}
        public string apptDate {get; set;}
        public Integer capacity {get; set;}
        public Integer totalEnrolled {get; set;}
        public String language {get; set;}
        public List<Attendee> students {get; set;}
        
    }
    
    public class Attendee{
        public string attendeeName {get; set;}
        public Boolean isCoApp {get; set;}
        public Boolean noShow {get; set;}
        public Boolean attended {get; set;}
        public String attendance {get; set;}
        
        public Attendee(sumoapp__Attendee__c rec){
            String name = rec.sumoapp__ContactRelation__r.Name;
            
            if(String.isNotBlank(rec.sumoapp__ContactRelation__r.RecordTypeId) && rec.sumoapp__ContactRelation__r.RecordType.Name == 'Co-Applicant'){
                name = '**' + name;
                this.isCoApp = true;
            } else{
                this.isCoApp = false;
            }
            
            this.attendeeName = name;
            if(String.isNotBlank(rec.Attendance_Status__c) && rec.Attendance_Status__c == 'Attended - Complete'){
                this.attendance = 'Complete';
            } else if(String.isNotBlank(rec.Attendance_Status__c) && rec.Attendance_Status__c == 'Course Incomplete'){
                this.attendance = 'Incomplete';
            } else if(String.isNotBlank(rec.Attendance_Status__c) && rec.Attendance_Status__c == 'No Show'){
                this.attendance = 'No Show';
            }
            
        }
    }
    
    
}