objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>Attendee_Status__c</fullName>
        <label>Attendee Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FrequentlyAskedQuestionsSpanish__c</fullName>
        <label>Frequently Asked Questions Spanish</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>FrequentlyAskedQuestions__c</fullName>
        <label>Frequently Asked Questions</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>FullDescriptionSpanish__c</fullName>
        <label>Full Description Spanish</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>FullDescription__c</fullName>
        <label>Full Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>HighlightsSpanish__c</fullName>
        <label>Highlights Spanish</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Highlights__c</fullName>
        <label>Highlights</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsParent__c</fullName>
        <formula>IsBlank(sumoapp__Parent__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Open_Seats__c</fullName>
        <formula>IF( NOT( ISNULL(sumoapp__Capacity__c)) , IF((sumoapp__Capacity__c - TotalEnrolled__c)&gt;=0,TEXT(sumoapp__Capacity__c - TotalEnrolled__c),&apos;0&apos;), &apos;Unlimited&apos;)</formula>
        <label>Open Seats</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Public__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Public</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShortDescriptionSpanish__c</fullName>
        <label>Short Description Spanish</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ShortDescription__c</fullName>
        <label>Short Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>sumoapp__EndDatetime__c</fullName>
        <label>End Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__EventName__c</fullName>
        <label>Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__GenerateVirtualDetails__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Generate Virtual Details</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sumoapp__LocationType__c</fullName>
        <label>Location Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>sumoapp__Location__c</referenceTo>
        <relationshipLabel>Location Infos</relationshipLabel>
        <relationshipName>LocationInfos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Child Events</relationshipLabel>
        <relationshipName>ChildEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__PricePerSeat__c</fullName>
        <label>Price per Seat</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BOOKED</fullName>
                    <default>true</default>
                    <label>Booked</label>
                </value>
                <value>
                    <fullName>CANCELED</fullName>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>RESCHEDULED</fullName>
                    <label>Rescheduled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Attendance_Status__c</fullName>
        <label>Attendee Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Attended - Complete</fullName>
                </value>
                <value>
                    <fullName>Attended - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Course Complete</fullName>
                </value>
                <value>
                    <fullName>Course Incomplete</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sumoapp__ContactRelation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Relation</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Event Attendees</relationshipLabel>
        <relationshipName>ContactEventAttendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__EndDatetime__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__EndDatetime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__EventName__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__EventName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__Location__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__Location__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <formula>sumoapp__SumoEvent__r.sumoapp__StartDatetime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>CANCELED</fullName>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>COMPLIMENTARY</fullName>
                    <label>Complimentary</label>
                </value>
                <value>
                    <fullName>DECLINED</fullName>
                    <label>Declined</label>
                </value>
                <value>
                    <fullName>DRAFT</fullName>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>REFUNDED</fullName>
                    <label>Fully Refunded</label>
                </value>
                <value>
                    <fullName>PAID_MANUAL</fullName>
                    <label>Paid - Manual</label>
                </value>
                <value>
                    <fullName>PAID</fullName>
                    <label>Paid - Online</label>
                </value>
                <value>
                    <fullName>PARTIALLY_REFUNDED</fullName>
                    <label>Partially Refunded</label>
                </value>
                <value>
                    <fullName>BOOKED</fullName>
                    <default>true</default>
                    <label>Registered</label>
                </value>
                <value>
                    <fullName>WAITLISTED</fullName>
                    <label>Waitlisted</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sumoapp__SumoEvent__c</fullName>
        <label>SUMO Event</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SUMO Attendee</label>
    <nameField>
        <displayFormat>ATD-{000000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/sumoapp__Location__c.object
<CustomObject>
    <label>SUMO Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SUMO Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ClassesController.cls
/*
 * @description    Class providing methods to get data related to Course or Classes which we are showing over Classes and Class Details Page.
 */
public without sharing class ClassesController {
    /*
     * @desc: Method returns Parent Course Session or Course Series records.
     */
    @AuraEnabled(cacheable=true)
    public static List<ClassWrapper> getAllParentClasses(String language) {
        List<ClassWrapper> parentClasses = new List<ClassWrapper>();
        if(language != null) {
            Map<String, String> languageFieldMappings = getParentFieldMappings(language);
            Map<String, String> keyValFieldMappings = getParentKeyValueFieldMappings(language);
            if(languageFieldMappings.isEmpty() && keyValFieldMappings.isEmpty()) return parentClasses;
            String fields = String.join(languageFieldMappings.values(), ', ');
            // Key Value pairs
            if(!keyValFieldMappings.isEmpty()) {
                fields += ', ' + String.join(keyValFieldMappings.values(), ', ');
            }
            String query = 'SELECT ' + fields + ' FROM sumoapp__AdditionalInfo__c ' + 
                                                ' WHERE IsParent__c = true ' + 
                                                ' AND sumoapp__Parent__c = null ' +
                                                ' AND  RecordType.DeveloperName IN (\'Course\', \'Event\', \'EventClass\')'+
                								' AND Public__c = true';
            System.debug('ClassesController.getAllParentClasses() - query::' + query);

            List<sumoapp__AdditionalInfo__c> parentRecords = Database.query(query);
            for(sumoapp__AdditionalInfo__c parent: parentRecords) {
                Map<String,Object> clsMap =  (Map<String,Object>) JSON.deserializeUntyped(JSON.serialize(new ClassWrapper()));
                for(String key: languageFieldMappings.keySet()) {
                    clsMap.put(key, parent.get(languageFieldMappings.get(key)));
                }
                if(!keyValFieldMappings.isEmpty()) {
                    List<Map<String, String>> keyValPairs = new List<Map<String, String>>();
                    for(String key: keyValFieldMappings.keySet()) {
                        String value = SObjectUtility.getSobjectFieldValue(parent, keyValFieldMappings.get(key));
                        keyValPairs.add(new Map<String, String>{ 'key' => key, 'value' => SObjectUtility.getSobjectFieldValue(parent, keyValFieldMappings.get(key)) });
                    	if(key == 'availableSeats'){
                             clsMap.put('seatsNotAvailable', (value != null && value == 'Unlimited')? false: Integer.valueOf(value) < 1 ? true : false);
                        } else if(key == 'startDate'){
                            clsMap.put('courseExpire', Datetime.valueOf(value) < System.today() ? true : false);                        }
                    }
                    clsMap.put('keyValPairs', keyValPairs);
                }
                
                parentClasses.add((ClassWrapper) JSON.deserialize(JSON.serialize(clsMap), ClassWrapper.class));
            }
        }
        return parentClasses;
    }

    /*
     * @desc: Method returns Parent Course Session or Course Series records for logged In Users
     */
    @AuraEnabled(cacheable=true)
    public static List<ClassWrapper> getClassesForLoggedInUser(String language) {
        List<ClassWrapper> finalClassesContent = new List<ClassWrapper>();
        if(language != null) {
            List<ClassWrapper> allParentClasses = getAllParentClasses(language);
            List<ClassWrapper> optedClasses = getOptedClasses(language);
            Map<String, ClassWrapper> idToOptedClassWrap = new Map<String, ClassWrapper>();
            for(ClassWrapper optedCls: optedClasses) {
                //idToOptedClassWrap.put(optedCls.courseId, optedCls);
                if(!idToOptedClassWrap.containsKey(optedCls.Id)){
                    idToOptedClassWrap.put(optedCls.Id, optedCls);
                }
            }
            for(ClassWrapper cls: allParentClasses) {
                if(idToOptedClassWrap.containsKey(cls.id)) {
                    finalClassesContent.add(idToOptedClassWrap.get(cls.id));
                } else {
                    finalClassesContent.add(cls);
                }
            }
        }
        return finalClassesContent;
    }

    /*
     * @desc: Method returns opted course or attendee records.
     */
    @AuraEnabled(cacheable=true)
    public static List<ClassWrapper> getOptedClasses(String language) {
        List<ClassWrapper> allOptedClasses = new List<ClassWrapper>();
        List<User> currUser = [SELECT Id, ContactId FROM User WHERE Id = :UserInfo.getUserId()];
        if(Auth.CommunitiesUtil.isGuestUser() || currUser.isEmpty() || currUser[0].ContactId == null) {
            return allOptedClasses;
        }
        if(language != null) {
            Map<String, String> languageFieldMappings = getAttendeeFieldMappings(language);
            Map<String, String> keyValFieldMappings = getAttendeeKeyValueFieldMappings(language);
            if(languageFieldMappings.isEmpty() && keyValFieldMappings.isEmpty()) return allOptedClasses;
            String fields = String.join(languageFieldMappings.values(), ', ');
            // Key Value pairs
            if(!keyValFieldMappings.isEmpty()) {
                fields += ', ' + String.join(keyValFieldMappings.values(), ', ');
            }
            Id userContactId = currUser[0].ContactId;
            String query = 'SELECT ' + fields + ' FROM sumoapp__Attendee__c ' +
                                                ' WHERE sumoapp__ContactRelation__c = :userContactId' +
                								' AND sumoapp__SumoEvent__r.Public__c = true';
                								/*' AND sumoapp__SumoEvent__r.IsParent__c = true'+
                								' AND sumoapp__SumoEvent__r.sumoapp__Parent__c = null';*/
			System.debug('languageFieldMappings  ===:'+languageFieldMappings);
            List<sumoapp__Attendee__c> optedClasses = Database.query(query);
            for(sumoapp__Attendee__c optedCls: optedClasses) {
                Map<String,Object> clsMap =  (Map<String,Object>) JSON.deserializeUntyped(JSON.serialize(new ClassWrapper()));
                for(String key: languageFieldMappings.keySet()) {
                    //clsMap.put(key, SObjectUtility.getSobjectFieldValue(optedCls, languageFieldMappings.get(key)));
                    Object value;
                    
                    if(key == 'isVirtualEvent'){
                        value = SObjectUtility.getSobjectFieldValue(optedCls, languageFieldMappings.get(key)) != NULL ? 
                            	Boolean.valueOf(SObjectUtility.getSobjectFieldValue(optedCls, languageFieldMappings.get(key))) : false;
                    } else{
                        value = SObjectUtility.getSobjectFieldValue(optedCls, languageFieldMappings.get(key));
                    }
                    
                    clsMap.put(key, value);
                }
                if(!keyValFieldMappings.isEmpty()) {
                    List<Map<String, String>> keyValPairs = new List<Map<String, String>>();
                    for(String key: keyValFieldMappings.keySet()) {
                        String value = SObjectUtility.getSobjectFieldValue(optedCls, keyValFieldMappings.get(key));
                        keyValPairs.add(new Map<String, String>{ 'key' => key, 'value' => value });
                        if(key == 'availableSeats'){
                             clsMap.put('seatsNotAvailable', (value != null && value == 'Unlimited')? false: Integer.valueOf(value) < 1 ? true : false);
                        } else if(key == 'startDate'){
                            clsMap.put('courseExpire', Datetime.valueOf(value) < System.today() ? true : false);
                        }
                    }
                    clsMap.put('keyValPairs', keyValPairs);
                }
				/*
                clsMap.put('seatsNotAvailable', Integer.valueOf(clsMap.get('availableSeats')) < 1 ? true : false);*/
                allOptedClasses.add((ClassWrapper) JSON.deserialize(JSON.serialize(clsMap), ClassWrapper.class));
            }
        }
        return allOptedClasses;
    }

    /*
     * @desc: Method returns course details.
     */
    @AuraEnabled(cacheable=true)
    public static ClassDetails getClassDetails(String language, String recordId) {
        ClassDetails classDetails = new ClassDetails();
        if(language != null) {
            List<User> currUser = [SELECT Id, ContactId FROM User WHERE Id = :UserInfo.getUserId()];
            Id userContactId = currUser[0]?.ContactId;
            Map<String, String> languageFieldMappings = getParentFieldMappings(language);
            Map<String, String> keyValFieldMappings = getParentKeyValueFieldMappings(language);
            if(languageFieldMappings.isEmpty() && keyValFieldMappings.isEmpty()) return classDetails;
            String fields = String.join(languageFieldMappings.values(), ', ');
            // Key Value pairs
            if(!keyValFieldMappings.isEmpty()) {
                fields += ', ' + String.join(keyValFieldMappings.values(), ', ');
            }
            String query = 'SELECT ' + fields + ' FROM sumoapp__AdditionalInfo__c WHERE Id = \'' + recordId + '\'';
            System.debug('ClassesController.getClassDetails() - query::' + query);
            List<sumoapp__AdditionalInfo__c> parentRecords = Database.query(query);
            for(sumoapp__AdditionalInfo__c parent: parentRecords) {
                Map<String,Object> clsMap =  (Map<String,Object>) JSON.deserializeUntyped(JSON.serialize(new ClassDetails()));
                for(String key: languageFieldMappings.keySet()) {
                    clsMap.put(key, parent.get(languageFieldMappings.get(key)));
                }
                if(!keyValFieldMappings.isEmpty()) {
                    List<Map<String, String>> keyValPairs = new List<Map<String, String>>();
                    for(String key: keyValFieldMappings.keySet()) {
                        String value = SObjectUtility.getSobjectFieldValue(parent, keyValFieldMappings.get(key));
                        keyValPairs.add(new Map<String, String>{ 'key' => key, 'value' => value});
                        if(key == 'availableSeats'){
                            clsMap.put('seatsNotAvailable', (value != null && value == 'Unlimited')? false: Integer.valueOf(value) < 1 ? true : false);
                       } else if(key == 'startDate'){
                           clsMap.put('courseExpire', Datetime.valueOf(value) < System.today() ? true : false);
                       }
                    }
                    clsMap.put('keyValPairs', keyValPairs);
                }
                classDetails = (ClassDetails) JSON.deserialize(JSON.serialize(clsMap), ClassDetails.class);
            }

            List<ClassWrapper> childClasses = new List<ClassWrapper>();
            ClassWrapper child;
            languageFieldMappings = getChildFieldMappings(language);
            if(languageFieldMappings.size() == 0) return classDetails;
            String childFields = String.join(languageFieldMappings.values(), ', ');
            query = 'SELECT ' + childFields + ' FROM sumoapp__AdditionalInfo__c WHERE sumoapp__Parent__c = \'' + recordId + '\'';
            List<sumoapp__AdditionalInfo__c> classSeries = Database.query(query);
            for(sumoapp__AdditionalInfo__c clss: classSeries) {
                Map<String,Object> clsMap =  (Map<String,Object>) JSON.deserializeUntyped(JSON.serialize(new ClassWrapper()));
                for(String key: languageFieldMappings.keySet()) {
                    clsMap.put(key, clss.get(languageFieldMappings.get(key)));
                }
                childClasses.add((ClassWrapper) JSON.deserialize(JSON.serialize(clsMap), ClassWrapper.class));
            }

            // Status Logic
            List<sumoapp__Attendee__c> parentAttendeeRec = [ SELECT 
                                                                Id,
                                                                sumoapp__Status__c,
                                                                Attendance_Status__c
                                                                FROM sumoapp__Attendee__c
                                                                WHERE sumoapp__SumoEvent__c = :recordId
                                                                AND sumoapp__ContactRelation__c = :userContactId
                                                            ];
            if (parentAttendeeRec != null && parentAttendeeRec.size() > 0) {
                classDetails.status = parentAttendeeRec[0].sumoapp__Status__c;
                classDetails.attendeeStatus = parentAttendeeRec[0].Attendance_Status__c;
            }
            classDetails.childClasses = childClasses;
        }
        return classDetails;
    }

    /*
     * @desc: Method returns language-specific field mappings.
     */
    public static Map<String, String> getParentFieldMappings(String language) {
        switch on language {
            when 'en-US' {
                return new Map<String, String> { 
                    'id' => 'Id',
                    'eventName' => 'sumoapp__EventName__c',
                    'shortDescription' => 'ShortDescription__c',
                    'description' => 'FullDescription__c',
                    'highlights' => 'Highlights__c',
                    'isVirtualEvent' => 'sumoapp__GenerateVirtualDetails__c',
                    'frequentlyAskedQuestions' => 'FrequentlyAskedQuestions__c'
                    // 'status' => 'sumoapp__Status__c',
                    // 'attendeeStatus' => 'Attendee_Status__c'
                };
            }
            when 'es' {
                return new Map<String, String> { 
                    'id' => 'Id',
                    'eventName' => 'sumoapp__EventName__c',
                    'shortDescription' => 'ShortDescriptionSpanish__c',
                    'description' => 'FullDescriptionSpanish__c',
                    'highlights' => 'HighlightsSpanish__c',
                    'isVirtualEvent' => 'sumoapp__GenerateVirtualDetails__c',
                    'frequentlyAskedQuestions' => 'FrequentlyAskedQuestionsSpanish__c'
                    // 'status' => 'sumoapp__Status__c',
                    // 'attendeeStatus' => 'Attendee_Status__c'
                };
            } when else {
                return new Map<String, String>();
            }
        }
    }

    /*
     * @desc: Method returns language-specific key value pair fields which we're showing over the UI.
     */
    public static Map<String, String> getParentKeyValueFieldMappings(String language) {
        switch on language {
            when 'en-US' {
                return new Map<String, String> { 
                    'type' => 'sumoapp__LocationType__c',
                    'startDate' => 'sumoapp__StartDatetime__c',
                    'endDate' => 'sumoapp__EndDatetime__c',
                    'availableSeats' => 'Open_Seats__c',
                    'cost' => 'sumoapp__PricePerSeat__c',
                    'location' => 'sumoapp__Location__r.Name'
                };
            } when 'es' {
                return new Map<String, String> { 
                    'type' => 'sumoapp__LocationType__c',
                    'startDate' => 'sumoapp__StartDatetime__c',
                    'endDate' => 'sumoapp__EndDatetime__c',
                    'availableSeats' => 'Open_Seats__c',
                    'cost' => 'sumoapp__PricePerSeat__c',
                    'location' => 'sumoapp__Location__r.Name'
                };
            } when else {
                return new Map<String, String>();
            }
        }
    }

    /*
     * @desc: Method returns language-specific key value pair fields which we're showing over the UI.
     */
    public static Map<String, String> getChildFieldMappings(String language) {
        switch on language {
            when 'en-US' {
                return new Map<String, String> {
                    'id' => 'Id',
                    'eventName' => 'sumoapp__EventName__c',
                    'startDate' => 'sumoapp__StartDatetime__c',
                    'endDate' => 'sumoapp__EndDatetime__c',
                    'shortDescription' => 'ShortDescription__c'
                };
            }
            when 'es' {
                return new Map<String, String> {
                    'id' => 'Id',
                    'eventName' => 'sumoapp__EventName__c',
                    'startDate' => 'sumoapp__StartDatetime__c',
                    'endDate' => 'sumoapp__EndDatetime__c',
                    'shortDescription' => 'ShortDescriptionSpanish__c'
                };
            } when else {
                return new Map<String, String>();
            }
        }
    }

    /*
     * @desc: Method returns language-specific key value pair fields which we're showing over the UI.
     */
    public static Map<String, String> getAttendeeFieldMappings(String language) {
        switch on language {
            when 'en-US' {
                return new Map<String, String> {
                    // 'id' => 'Id',
                    // 'courseId' => 'sumoapp__SumoEvent__r.Id',
                    // 'startDate' => 'sumoapp__SumoEvent__r.sumoapp__StartDatetime__c',
                    // 'endDate' => 'sumoapp__SumoEvent__r.sumoapp__EndDatetime__c',
                    'id' => 'sumoapp__SumoEvent__r.Id',
                    'eventName' => 'sumoapp__SumoEvent__r.sumoapp__EventName__c',
                    'shortDescription' => 'sumoapp__SumoEvent__r.ShortDescription__c',
                    'description' => 'sumoapp__SumoEvent__r.FullDescription__c',
                    'highlights' => 'sumoapp__SumoEvent__r.Highlights__c',
                    'isVirtualEvent' => 'sumoapp__SumoEvent__r.sumoapp__GenerateVirtualDetails__c',
                    'frequentlyAskedQuestions' => 'sumoapp__SumoEvent__r.FrequentlyAskedQuestions__c',
                    'status' => 'sumoapp__Status__c',
                    'attendeeStatus' => 'Attendance_Status__c'
                };
            }
            when 'es' {
                return new Map<String, String> {
                    // 'id' => 'Id',
                    // 'courseId' => 'sumoapp__SumoEvent__r.Id',
                    // 'startDate' => 'sumoapp__SumoEvent__r.sumoapp__StartDatetime__c',
                    // 'endDate' => 'sumoapp__SumoEvent__r.sumoapp__EndDatetime__c',
                    'id' => 'sumoapp__SumoEvent__r.Id',
                    'eventName' => 'sumoapp__SumoEvent__r.sumoapp__EventName__c',
                    'shortDescription' => 'sumoapp__SumoEvent__r.ShortDescriptionSpanish__c',
                    'description' => 'sumoapp__SumoEvent__r.FullDescriptionSpanish__c',
                    'highlights' => 'sumoapp__SumoEvent__r.HighlightsSpanish__c',
                    'isVirtualEvent' => 'sumoapp__SumoEvent__r.sumoapp__GenerateVirtualDetails__c',
                    'frequentlyAskedQuestions' => 'sumoapp__SumoEvent__r.FrequentlyAskedQuestionsSpanish__c',
                    'status' => 'sumoapp__Status__c',
                    'attendeeStatus' => 'Attendance_Status__c'
                };
            } when else {
                return new Map<String, String>();
            }
        }
    }

    /*
     * @desc: Method returns language-specific key value pair fields which we're showing over the UI.
     */
    public static Map<String, String> getAttendeeKeyValueFieldMappings(String language) {
        switch on language {
            when 'en-US' {
                return new Map<String, String> { 
                    'type' => 'sumoapp__SumoEvent__r.sumoapp__LocationType__c',
                    'startDate' => 'sumoapp__SumoEvent__r.sumoapp__StartDatetime__c',
                    'endDate' => 'sumoapp__SumoEvent__r.sumoapp__EndDatetime__c',
                    'availableSeats' => 'sumoapp__SumoEvent__r.Open_Seats__c',
                    'cost' => 'sumoapp__SumoEvent__r.sumoapp__PricePerSeat__c',
                    'location' => 'sumoapp__SumoEvent__r.sumoapp__Location__r.Name'
                };
            } when 'es' {
                return new Map<String, String> { 
                    'type' => 'sumoapp__SumoEvent__r.sumoapp__LocationType__c',
                    'startDate' => 'sumoapp__SumoEvent__r.sumoapp__StartDatetime__c',
                    'endDate' => 'sumoapp__SumoEvent__r.sumoapp__EndDatetime__c',
                    'availableSeats' => 'sumoapp__SumoEvent__r.Open_Seats__c',
                    'cost' => 'sumoapp__SumoEvent__r.sumoapp__PricePerSeat__c',
                    'location' => 'sumoapp__SumoEvent__r.sumoapp__Location__r.Name'
                };
            } when else {
                return new Map<String, String>();
            }
        }
    }

    /******* Wrappers *******/
    public virtual class ClassWrapper {
        @AuraEnabled
        public String id;

        @AuraEnabled
        public String courseId;

        @AuraEnabled
        public String eventName;

        @AuraEnabled
        public String startDate;

        @AuraEnabled
        public String endDate;

        @AuraEnabled
        public String shortDescription;

        @AuraEnabled
        public String description;

        @AuraEnabled
        public String highlights;

        @AuraEnabled
        public String attendeeStatus;

        @AuraEnabled
        public String status;

        @AuraEnabled
        public Boolean isVirtualEvent;

        @AuraEnabled
        public List<KeyValPairs> keyValPairs;
        
        @AuraEnabled
        public Boolean seatsNotAvailable;
        
        @AuraEnabled
        public Boolean courseExpire;
    }

    public class ClassDetails extends ClassWrapper {
        @AuraEnabled
        public String frequentlyAskedQuestions;
        @AuraEnabled
        public List<ClassWrapper> childClasses;
    }

    public class KeyValPairs {
        @AuraEnabled
        public String key;

        @AuraEnabled
        public String value;
    }
}