objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>sumoapp__Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Child Events</relationshipLabel>
        <relationshipName>ChildEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BOOKED</fullName>
                    <default>true</default>
                    <label>Booked</label>
                </value>
                <value>
                    <fullName>CANCELED</fullName>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>RESCHEDULED</fullName>
                    <label>Rescheduled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sumoapp__Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Attendance_Status__c</fullName>
        <label>Attendee Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Attended - Complete</fullName>
                </value>
                <value>
                    <fullName>Attended - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Course Complete</fullName>
                </value>
                <value>
                    <fullName>Course Incomplete</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>sumoapp__ContactRelation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Relation</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Event Attendees</relationshipLabel>
        <relationshipName>ContactEventAttendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__IsNotArrived__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It shows whether the attendee has arrived at the event or not</description>
        <inlineHelpText>Set this value if the attendee did not arrive at the event</inlineHelpText>
        <label>No-Show</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sumoapp__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>CANCELED</fullName>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>COMPLIMENTARY</fullName>
                    <label>Complimentary</label>
                </value>
                <value>
                    <fullName>DECLINED</fullName>
                    <label>Declined</label>
                </value>
                <value>
                    <fullName>DRAFT</fullName>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>REFUNDED</fullName>
                    <label>Fully Refunded</label>
                </value>
                <value>
                    <fullName>PAID_MANUAL</fullName>
                    <label>Paid - Manual</label>
                </value>
                <value>
                    <fullName>PAID</fullName>
                    <label>Paid - Online</label>
                </value>
                <value>
                    <fullName>PARTIALLY_REFUNDED</fullName>
                    <label>Partially Refunded</label>
                </value>
                <value>
                    <fullName>BOOKED</fullName>
                    <default>true</default>
                    <label>Registered</label>
                </value>
                <value>
                    <fullName>WAITLISTED</fullName>
                    <label>Waitlisted</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sumoapp__SumoEvent__c</fullName>
        <label>SUMO Event</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SUMO Attendee</label>
    <nameField>
        <displayFormat>ATD-{000000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MassAttendanceComponentController.cls
public with sharing class MassAttendanceComponentController {
    /*
    * @description : To get Attendee records
    */ 
    @AuraEnabled(cacheable=true)
    public static List<sumoapp__Attendee__c> getAttendees(String additionalInfoId) {
        String eventId = String.escapeSingleQuotes(additionalInfoId);
        return [SELECT Id, sumoapp__ContactRelation__r.Name ,sumoapp__ContactRelation__r.Account.Name, sumoapp__Status__c, Notes__c,sumoapp__IsNotArrived__c, Attendance_Status__c, sumoapp__ContactRelation__r.RecordTypeId, sumoapp__ContactRelation__r.RecordType.Name 
                FROM sumoapp__Attendee__c where sumoapp__ContactRelation__r.Name != null AND sumoapp__ContactRelation__r.AccountId != null AND sumoapp__ContactRelation__r.RecordTypeId!=null AND sumoapp__SumoEvent__c=:eventId WITH SECURITY_ENFORCED Order BY sumoapp__ContactRelation__r.AccountId, sumoapp__ContactRelation__r.RecordType.DeveloperName desc];
    }
    
    /*
    * @description : To get Attendee records and metrics
    */ 
    @AuraEnabled
    public static AttendeeWrapper getCourseSeries(String additionalInfoId) {
        String eventId = String.escapeSingleQuotes(additionalInfoId);
        AttendeeWrapper wrapper = new AttendeeWrapper();
        Map<Id, sumoapp__AdditionalInfo__c> sessions = new Map<Id, sumoapp__AdditionalInfo__c>([Select Id from sumoapp__AdditionalInfo__c where sumoapp__Parent__c=:eventId]);
        wrapper.attendees = [SELECT Id, sumoapp__ContactRelation__r.Name ,sumoapp__ContactRelation__r.AccountId, sumoapp__ContactRelation__r.Account.Name, sumoapp__Status__c, Notes__c,sumoapp__IsNotArrived__c, Attendance_Status__c, sumoapp__ContactRelation__r.RecordTypeId, sumoapp__ContactRelation__r.RecordType.Name 
                            FROM sumoapp__Attendee__c where sumoapp__ContactRelation__r.Name != null AND sumoapp__ContactRelation__r.AccountId != null AND sumoapp__ContactRelation__r.RecordTypeId!=null AND sumoapp__SumoEvent__c In:sessions.keyset() WITH SECURITY_ENFORCED Order BY sumoapp__ContactRelation__r.AccountId];
        wrapper.totalCourseComplete = [Select count() from sumoapp__Attendee__c where Attendance_Status__c='Course Complete' AND sumoapp__SumoEvent__c =:eventId WITH SECURITY_ENFORCED];
        wrapper.totalCourseIncomplete = [Select count() from sumoapp__Attendee__c where Attendance_Status__c='Course Incomplete' AND sumoapp__SumoEvent__c =:eventId WITH SECURITY_ENFORCED];
        return wrapper;
    }

    @AuraEnabled(cacheable=true)
    public static Contact getContactDetail(String contactId) {
        return [SELECT Id, Name, Email, Account.Name FROM COntact WHERE Id =:  contactId LIMIT 1];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<sumoapp__Attendee__c> getAttendeeRecords(String contactId) {
        if(String.isBlank(contactId)){
            return new List<sumoapp__Attendee__c>();
        }
        return [SELECT Id, Name, sumoapp__SumoEvent__c FROM sumoapp__Attendee__c WHERE sumoapp__ContactRelation__c =: contactId ];
    }
    
    public class AttendeeWrapper{
        @AuraEnabled
        public List<sumoapp__Attendee__c> attendees{get;set;}
        @AuraEnabled
        public Integer totalCourseComplete{get;set;}
        @AuraEnabled
        public Integer totalCourseIncomplete{get;set;}
        
    }
}