objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>sumoapp__Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Child Events</relationshipLabel>
        <relationshipName>ChildEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/courseProgressBarControllerTest.cls
@istest
private class courseProgressBarControllerTest {

    @istest
    static void getParentAndChildRecordsTest() {

        sumoapp__AdditionalInfo__c parent = new sumoapp__AdditionalInfo__c(sumoapp__StartDatetime__c=datetime.now());
        insert parent;
        sumoapp__AdditionalInfo__c child = new sumoapp__AdditionalInfo__c(sumoapp__Parent__c = parent.Id, sumoapp__StartDatetime__c=datetime.now());
        insert child;
        Test.startTest();
        List<courseProgressBarController.courseWrapper> course =  courseProgressBarController.getParentAndChildRecords(child.Id);
        
    }
}