objects/sumoapp__AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>sumoapp__EndDatetime__c</fullName>
        <label>End Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sumoapp__EventName__c</fullName>
        <label>Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sumoapp__Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>sumoapp__AdditionalInfo__c</referenceTo>
        <relationshipLabel>Child Events</relationshipLabel>
        <relationshipName>ChildEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sumoapp__StartDatetime__c</fullName>
        <label>Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <label>SUMO Additional Info</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>SUMO Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUMO Additional Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CourseManagementControllerTest.cls
/**
* @desc: Test Class for CourseManagementController.
*/
@isTest
public class CourseManagementControllerTest {
    /**
* @desc: Test Data Setup.
*/
    @testSetup 
    static void testSetup() {
        Account acc = TestDataFactory.createAccounts(1, true)[0];
        Contact con = TestDataFactory.createContacts(acc.Id, 1, true)[0];
        List<sumoapp__AdditionalInfo__c> courses = TestDataFactory.createSumoEventInfo(5, true);
        TestDataFactory.createAttendee(con, courses[0].id, 5, true);
    }
    
    /**
* @desc: Test Method to test getCourses method of the controller.
*/
    @isTest
    public static void testGetCourses() {
        Test.startTest();
        List<sumoapp__AdditionalInfo__c> courses = CourseManagementController.getCourses();
        Test.stopTest();
    }
    
    /**
* @desc: Test Method to test getContacts method of the controller.
*/
    @isTest
    public static void testGetContacts() {
        sumoapp__AdditionalInfo__c event = [SELECT Id FROM sumoapp__AdditionalInfo__c LIMIT 1];
        Test.startTest();
        List<Contact> contacts = CourseManagementController.getContacts(event.Id);
        Test.stopTest();
    }
    
    /**
* @desc: Test Method to test filterRows method of the controller.
*/
    @isTest
    public static void testFilterRows() {
        Test.startTest();
        List<sumoapp__AdditionalInfo__c> filteredCourses = CourseManagementController.filterRows('Test', Date.today(), Date.today().addDays(1));
        Test.stopTest();
    }
    
    /*
* @desc: Test Method to test createAttendees method of the controller.
*/
    
    @isTest
    public static void testCreateAttendees() {
        sumoapp__AdditionalInfo__c parentEvent = [SELECT Id FROM sumoapp__AdditionalInfo__c LIMIT 1];
        sumoapp__AdditionalInfo__c childEvent = new sumoapp__AdditionalInfo__c(
            sumoapp__EventName__c = 'Test Child Event',
            sumoapp__StartDatetime__c = Date.today(),
            sumoapp__EndDatetime__c = Date.today().addDays(1),
            sumoapp__Parent__c = parentEvent.Id
        );
        insert childEvent;
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        Test.startTest();
        CourseManagementController.createAttendees(new List<Id>{con.Id}, parentEvent.Id, true);
        Test.stopTest();
    }
}