objects/X9902__c.object
<CustomObject>
    <description>To store data and information related to HUD 9902 reporting, including fields for Generation and Submission statuses, and serves as the parent object for the 9902 Agency, 9902 Client, 9902 Counselor, and 9902 Summary objects.</description>
    <fields>
        <fullName>Summary9902SubmissionID__c</fullName>
        <description>Identifier for the submission of the 9902. Unique identifier assigned to the submission of the 9902.</description>
        <label>9902 Summary ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Summary9902SubmissionStatus__c</fullName>
        <description>Status of the submission of the 9902. Indicate the current status of the submission of the 9902.</description>
        <label>9902 Summary Submission</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>9902</label>
    <nameField>
        <displayFormat>HUD-{000000}</displayFormat>
        <label>9902</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>9902</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HudSubmissionStatusCheckTest.cls
@IsTest
public with sharing class HudSubmissionStatusCheckTest {
    @TestSetup
    static void makeData(){
        TestDataFactory.createIntegrationSettings(true);
        List<X9902__c> x9902Recs = TestDataFactory.createX9902(1, false);
        x9902Recs[0].Summary9902SubmissionID__c = '2068030345';
        insert x9902Recs;
    }
 
    @IsTest
    static void verifyStatusCheck() {
        MockHttpResponseGenerator mock = new MockHttpResponseGenerator();
        HttpRequest request = new HttpRequest();
        mock.respond(request);
        Test.setMock(HttpCalloutMock.class, mock);
        X9902__c x9902 = [SELECT Id FROM X9902__c LIMIT 1];
        Test.startTest();
        System.enqueueJob(new HudSubmissionStatusCheck(blob.valueOf(TestDataFactory.getSampleXmlString()), '2068030345', x9902.Id, '9902_Summary'));
        Test.stopTest();
        x9902 = [SELECT Id, Summary9902SubmissionStatus__c FROM X9902__c WHERE Id =:x9902.Id];
        System.assertEquals('DONE', x9902.Summary9902SubmissionStatus__c);
    }
}